;;;; tests/pbt/codec-conformance.lisp -- SPEC-VK VK-5 differential acceptance.
;;;;
;;;; Pins the certified EOL codec (verified/codec.lisp, loaded through
;;;; verified/shim.lisp) against the REAL production read/write path
;;;; (src/buffer/file.lisp %encoding-read / %write-region-to-file), closing the
;;;; gap left by the book's documented scoping deviation (the book models the EOL
;;;; layer over DECODED codepoints; this suite feeds actual UTF-8 byte files
;;;; through production and compares).
;;;;
;;;; For each generated byte file (random EOL mixes -- lone CR, CRLF, LF,
;;;; no-trailing-newline -- interleaved with multibyte/emoji codepoints, UTF-8
;;;; encoded), opened via the production FIND-FILE-BUFFER machinery exactly as
;;;; tests/eol-roundtrip.lisp does:
;;;;
;;;;   READ  : the buffer's line list must EQUAL `decode-eol' applied to the same
;;;;           decoded codepoints under the buffer's detected end-of-line, and the
;;;;           mixed-EOL notification must fire iff `decode-eol' reports mixed.
;;;;   WRITE : saving the buffer must produce bytes EQUAL to the UTF-8 encoding of
;;;;           `encode-eol' applied to the buffer's line list -- the uniform-EOL
;;;;           emission of %write-region-to-file.
;;;;
;;;; The reference decoded codepoints are read back through the buffer's OWN
;;;; external format (so the comparison is independent of encoding-detection
;;;; quirks and isolates the EOL layer this kernel actually models). Production is
;;;; the spec: any divergence is a codec transcription bug.
;;;;
;;;; The tests/eol-roundtrip.lisp corpus is included as a fixed regression subset
;;;; against the kernel (SPEC-VK VK-5 acceptance). Codepoint conversion
;;;; (char-code / code-char) happens here, never inside a book.

(defpackage :lem-tests/pbt/codec-conformance
  (:use :cl
        :rove
        :lem-tests/pbt/harness)
  (:import-from :lem-fake-interface
                :with-fake-interface))
(in-package :lem-tests/pbt/codec-conformance)

;;; ------------------------------------------------------------------
;;; Kernel loading (shim + certified codec book)
;;; ------------------------------------------------------------------

(defun repo-root ()
  (asdf:system-source-directory :lem-tests))

(defun ensure-kernel-loaded ()
  "Load the dual-load shim and the VK-5 codec book into this image once."
  (handler-bind ((warning #'muffle-warning))
    (unless (find-package "LEM/KERNEL")
      (load (merge-pathnames "verified/shim.lisp" (repo-root))))
    (let ((d (find-symbol "DECODE-EOL" "LEM/KERNEL")))
      (when (or (null d) (not (fboundp d)))
        (funcall (find-symbol "LOAD-VERIFIED-BOOK" "LEM/KERNEL") "codec")))))

(defun k-decode-eol (codepoints eol)
  "Kernel decode: (values lines-as-codepoint-lists mixed-p)."
  (funcall (find-symbol "DECODE-EOL" "LEM/KERNEL") codepoints eol))

(defun k-encode-eol (lines eol)
  "Kernel encode: lines -> codepoint list with uniform EOL."
  (funcall (find-symbol "ENCODE-EOL" "LEM/KERNEL") lines eol))

;;; ------------------------------------------------------------------
;;; Byte / codepoint plumbing
;;; ------------------------------------------------------------------

(defun codepoints->utf8 (codepoints)
  "UTF-8 encode a list of CODEPOINTS to an (unsigned-byte 8) vector."
  (sb-ext:string-to-octets (map 'string #'code-char codepoints)
                           :external-format :utf-8))

(defun write-octets (path octets)
  (with-open-file (stream path :direction :output
                               :element-type '(unsigned-byte 8)
                               :if-exists :supersede
                               :if-does-not-exist :create)
    (write-sequence octets stream)))

(defun read-octets (path)
  (with-open-file (stream path :direction :input
                               :element-type '(unsigned-byte 8))
    (let ((octets (make-array (file-length stream) :element-type '(unsigned-byte 8))))
      (read-sequence octets stream)
      octets)))

(defun read-decoded-codepoints (path external-format)
  "Read PATH as a character stream under EXTERNAL-FORMAT (no EOL translation),
returning the decoded codepoints as a list -- exactly the sequence
%encoding-read's READ-LINE consumes."
  (with-open-file (stream path :direction :input :external-format external-format)
    (loop :for ch := (read-char stream nil nil)
          :while ch
          :collect (char-code ch))))

(defun production-lines (buffer)
  "BUFFER content as a list of codepoint lists, in line order."
  (loop :for line := (lem/buffer/internal:point-line
                      (lem/buffer/internal:buffer-start-point buffer))
          :then (lem/buffer/line:line-next line)
        :while line
        :collect (map 'list #'char-code (lem/buffer/line:line-string line))))

;;; ------------------------------------------------------------------
;;; The differential check: one generated file, both directions
;;; ------------------------------------------------------------------

(defun check-file-conforms (input-codepoints)
  "Write INPUT-CODEPOINTS as a UTF-8 file, open it through the production read
path, and assert both the read-side (buffer == decode-eol prediction, mixed
notification == kernel mixed flag) and the write-side (saved bytes == UTF-8 of
encode-eol) conformance. Return T on full agreement, NIL otherwise. Must run
inside WITH-FAKE-INTERFACE."
  (let ((path (namestring
               (uiop:tmpize-pathname
                (merge-pathnames "lem-vk5-codec" (uiop:temporary-directory)))))
        (path2 (namestring
                (uiop:tmpize-pathname
                 (merge-pathnames "lem-vk5-codec-out" (uiop:temporary-directory)))))
        (notified nil))
    (unwind-protect
         (let ((lem/buffer/file:*mixed-eol-notification-function*
                 (lambda (fn) (declare (ignore fn)) (setf notified t))))
           (write-octets path (codepoints->utf8 input-codepoints))
           (let ((buffer (lem:find-file-buffer path :temporary t)))
             (unwind-protect
                  (let* ((encoding (lem:buffer-encoding buffer))
                         (eol (lem/buffer/encodings:encoding-end-of-line encoding))
                         (xf (lem/buffer/encodings:encoding-external-format encoding))
                         (ref-codepoints (read-decoded-codepoints path xf))
                         (prod-lines (production-lines buffer)))
                    (multiple-value-bind (klines kmixed) (k-decode-eol ref-codepoints eol)
                      ;; READ side: buffer lines == kernel decode.
                      (and (equal prod-lines klines)
                           ;; mixed notification == kernel mixed flag (and the
                           ;; kernel only ever flags :crlf, matching production).
                           (eq (and notified t) (and kmixed t))
                           (or (eq eol :crlf) (null kmixed))
                           ;; WRITE side: saved bytes == UTF-8 of encode-eol.
                           (progn
                             (lem:write-to-file buffer path2)
                             (equalp (read-octets path2)
                                     (codepoints->utf8 (k-encode-eol prod-lines eol)))))))
               (lem:delete-buffer buffer))))
      (uiop:delete-file-if-exists path)
      (uiop:delete-file-if-exists path2))))

;;; ------------------------------------------------------------------
;;; Generators
;;; ------------------------------------------------------------------

;; Content codepoints: ASCII, Latin-1, CJK and emoji, all valid UTF-8 and none
;; equal to CR(13)/LF(10) -- EOLs are injected as explicit tokens below.
(defparameter *content-codepoints*
  (coerce
   (append (loop :for c :from 65 :to 90 :collect c)      ; A-Z
           (list #xE9 #xF1 #xFC #xDF)                    ; accented latin-1
           (list #x3042 #x4E2D #xAC00)                   ; CJK / Hangul
           (list #x1F600 #x1F308 #x200D #x2764 #xFE0F))  ; emoji + ZWJ/VS
   'vector)
  "Non-EOL content codepoints for generated files (multibyte on purpose).")

(defun gen-codepoints (&key (max-tokens 40))
  "Generate a codepoint list interleaving content codepoints with LF, CRLF and
lone-CR tokens; a run may end without a trailing EOL."
  (make-generator
   :sample (lambda (rng)
             (let ((n (rng-below rng (1+ max-tokens)))
                   (acc '()))
               (dotimes (i n)
                 (case (rng-below rng 10)
                   ((0 1 2 3 4) (push (rng-element rng *content-codepoints*) acc))
                   ((5 6) (push 10 acc))                     ; LF
                   (7 (push 13 acc) (push 10 acc))           ; CRLF (in order)
                   (8 (push 13 acc))                         ; lone CR
                   (t (push (rng-element rng *content-codepoints*) acc))))
               (nreverse acc)))
   :shrink (lambda (l) (shrink-list l (constantly nil)))))

;;; ------------------------------------------------------------------
;;; Tests
;;; ------------------------------------------------------------------

(defparameter *codec-num-files* 300
  "Random generated files per differential run (file I/O per case, kept CI-sane).")

(deftest codec-conformance-smoke
  (ensure-kernel-loaded)
  (with-fake-interface ()
    ;; Deterministic cases covering every EOL family and boundary.
    (ok (check-file-conforms '())                                  "empty")
    (ok (check-file-conforms (map 'list #'char-code "one two"))    "no EOL at all")
    (ok (check-file-conforms (list 97 10 98 10 99 10))             "pure LF, trailing")
    (ok (check-file-conforms (list 97 10 98 10 99))               "pure LF, no trailing")
    (ok (check-file-conforms (list 97 13 10 98 13 10))             "pure CRLF, trailing")
    (ok (check-file-conforms (list 97 13 10 98))                  "pure CRLF, no trailing")
    (ok (check-file-conforms (list 97 13 98 13 99 13))            "pure CR")
    (ok (check-file-conforms (list 97 13 10 98 10 99 13 10))       "mixed: CRLF with a bare LF")
    (ok (check-file-conforms (list #x3042 10 #x1F600 13 10 #xE9))  "multibyte around EOLs")))

;;; VK-5 acceptance: random UTF-8 files, read AND write differential vs production.
(deftest codec-conformance-differential
  (ensure-kernel-loaded)
  (with-fake-interface ()
    (let ((*num-tests* *codec-num-files*))
      (for-all ((codepoints (gen-codepoints)))
        (check-file-conforms codepoints)))))

;;; Fixed regression subset: the tests/eol-roundtrip.lisp corpus, pinned against
;;; the kernel through the same differential pipeline.
(deftest codec-conformance-eol-roundtrip-corpus
  (ensure-kernel-loaded)
  (with-fake-interface ()
    (flet ((cps (string) (map 'list #'char-code string)))
      (ok (check-file-conforms (cps (format nil "one~Ctwo~Cthree~C" #\Lf #\Lf #\Lf)))
          "corpus LF")
      (ok (check-file-conforms (cps (format nil "one~C~Ctwo~C~Cthree~C~C"
                                            #\Cr #\Lf #\Cr #\Lf #\Cr #\Lf)))
          "corpus CRLF")
      (ok (check-file-conforms (cps (format nil "one~Ctwo~Cthree~C" #\Cr #\Cr #\Cr)))
          "corpus CR")
      (ok (check-file-conforms (cps (format nil "one~Ctwo~Cthree" #\Lf #\Lf)))
          "corpus LF no trailing")
      (ok (check-file-conforms (cps (format nil "one~C~Ctwo~C~Cthree" #\Cr #\Lf #\Cr #\Lf)))
          "corpus CRLF no trailing")
      (ok (check-file-conforms (cps (format nil "one~C~Ctwo~Cthree~C~C"
                                            #\Cr #\Lf #\Lf #\Cr #\Lf)))
          "corpus mixed CRLF-first")
      (ok (check-file-conforms (cps (format nil "one~Ctwo~C~Cthree~C" #\Lf #\Cr #\Lf #\Lf)))
          "corpus mixed LF-first"))))
