(asdf:defsystem "lem-structured-notes"
  :description "Format-neutral semantic core for Org, LSM, and CalDAV data."
  :author "Lem Project"
  :license "MIT"
  :version "0.1.0"
  :depends-on ("alexandria")
  :serial t
  :pathname "src/"
  :components ((:file "package")
               (:file "model")
               (:file "caldav-resource-name")
               (:file "icalendar-uid")
               (:file "source-protocol")
               (:file "lsm-cst")
               (:file "icalendar-cst")
               (:file "icalendar-octets")
               (:file "icalendar-uri")
               (:file "icalendar-value")
               (:file "icalendar-recur")
               (:file "icalendar-codec")
               (:file "icalendar-property")
               (:file "icalendar-extensions")
               (:file "icalendar-projection")
               (:file "icalendar-refresh")
               (:file "icalendar-availability")
               (:file "icalendar-timezone")
               (:file "icalendar-writer")
               (:file "icalendar-edit")
               (:file "caldav-write")
               (:file "http-prefer")
               (:file "caldav-read")
               (:file "caldav-uri")
               (:file "caldav-write-prefer")
               (:file "icalendar-recurrence")
               (:file "icalendar-timezone-recurrence")
               (:file "icalendar-series")
               (:file "icalendar-availability-expansion")
               (:file "icalendar-semantic")
               (:file "inline")
               (:file "block")
               (:file "org-cst")
               (:file "lsm-parser")
               (:file "legacy-markdown")
               (:file "lsm-writer")
               (:file "migration")
               (:file "notes-workflow"))
  :in-order-to ((test-op (test-op "lem-structured-notes/tests"))))

(asdf:defsystem "lem-structured-notes/tests"
  :description "Local semantic and source-preservation fixtures; no calendar transport."
  :depends-on ("lem-structured-notes")
  :serial t
  :pathname "tests/"
  :components ((:file "package")
               (:file "fixtures")
               (:file "model-test")
               (:file "caldav-resource-name-test")
               (:file "icalendar-uid-test")
               (:file "icalendar-cst-test")
               (:file "icalendar-octets-test")
               (:file "icalendar-value-test")
               (:file "icalendar-property-test")
               (:file "icalendar-projection-test")
               (:file "icalendar-extensions-test")
               (:file "icalendar-refresh-test")
               (:file "icalendar-availability-test")
               (:file "icalendar-writer-test")
               (:file "icalendar-edit-test")
               (:file "caldav-write-test")
               (:file "http-prefer-test")
               (:file "caldav-read-test")
               (:file "icalendar-recurrence-test")
               (:file "icalendar-timezone-test")
               (:file "icalendar-series-test")
               (:file "icalendar-availability-expansion-test")
               (:file "icalendar-semantic-test")
               (:file "inline-test")
               (:file "block-test")
               (:file "source-protocol-test")
               (:file "org-cst-test")
               (:file "lsm-parser-test")
               (:file "lsm-writer-test")
               (:file "migration-test")
               (:file "notes-workflow-test")
               (:file "caldav-uri-test")
               (:static-file "../spec/leap-second-snapshot.tsv"))
  :perform (test-op (operation component)
             (declare (ignore operation component))
             (uiop:symbol-call :lem-structured-notes/tests :run-tests)))

(asdf:defsystem "lem-structured-notes/lem-notes-adapter"
  :description "Explicit unsaved notes commands with live revision provenance."
  :depends-on ("lem-structured-notes" "lem/core" "lem-buffer-proposals")
  :serial t
  :pathname "lem/"
  :components ((:file "package") (:file "notes-workflow"))
  :in-order-to ((test-op (test-op "lem-structured-notes/lem-notes-adapter-tests"))))

(asdf:defsystem "lem-structured-notes/lem-notes-adapter-tests"
  :depends-on ("lem-structured-notes/lem-notes-adapter" "lem-fake-interface" "lem-daemon/recovery" "rove")
  :components ((:file "tests/adapter"))
  :perform (test-op (operation component)
             (declare (ignore operation)) (uiop:symbol-call :rove :run component)))
