(defpackage :lem-tests/mode
  (:use :cl :rove)
  (:local-nicknames (:core :lem-core)))
(in-package :lem-tests/mode)

(defvar *visited-identifiers* :disabled)

(defclass probe-mode (core:mode)
  ((identifier :initarg :identifier :reader probe-identifier)))

;; Exercise identifier dispatch independently of registration names/class names.
(defmethod core::mode-identifier-name ((mode probe-mode))
  (unless (eq *visited-identifiers* :disabled)
    (push (probe-identifier mode) *visited-identifiers*))
  (probe-identifier mode))

(deftest active-mode-query-preserves-lookup-semantics
  (lem:with-current-buffers ()
    (let* ((core::*mode-objects* nil)
           (core::*active-global-minor-modes* nil)
           (core::*current-global-mode* nil)
           (buffer (lem:make-buffer "mode-query"))
           (identifiers #(:local-a :local-b :major :global-minor :global))
           (objects (map 'vector (lambda (id) (make-instance 'probe-mode :identifier id))
                         identifiers))
           (names (map 'vector (lambda (id) (gensym (symbol-name id))) identifiers)))
      (loop :for name :across names
            :for object :across objects
            :do (core::register-mode name object))
      (let ((failure nil))
        (dotimes (mask 32)
          (flet ((active (index)
                   (aref (if (logbitp index mask) objects names) index)))
            (setf (lem:buffer-minor-modes buffer) (list (active 0) (active 1))
                  (lem:buffer-major-mode buffer) (active 2)
                  core::*active-global-minor-modes* (list (active 3))
                  core::*current-global-mode* (active 4)))
          (dolist (query (append (coerce identifiers 'list) (coerce names 'list)
                                (list :missing nil)))
            ;; Frozen query from before the allocation optimization.
            (let ((expected (not (null (find query (core:all-active-modes buffer)
                                            :key #'core::mode-identifier-name)))))
              (unless (eq expected (core:mode-active-p buffer query))
                (setf failure (list mask query)))))
          (let ((*visited-identifiers* nil))
            (core:mode-active-p buffer :major)
            (unless (equal '(:major :local-b :local-a) *visited-identifiers*)
              (setf failure (list mask :lookup-order)))))
        (ok (null failure)
            (format nil "384 mixed-storage queries and lookup order; mismatch: ~s" failure)))
      (setf (lem:buffer-minor-modes buffer) (list (aref names 0)))
      (ok (eq t (core:mode-active-p buffer :local-a)))
      (core::register-mode (aref names 0)
                           (make-instance 'probe-mode :identifier :replacement))
      (ok (null (core:mode-active-p buffer :local-a)))
      (ok (eq t (core:mode-active-p buffer :replacement))
          "queries resolve the current registration without stale cached results")
      (setf (lem:buffer-minor-modes buffer) (list (aref objects 0)))
      (ok (eq t (core:mode-active-p buffer :local-a))
          "object-valued active modes keep their identity after re-registration")
      (setf (lem:buffer-minor-modes buffer) nil)
      (ok (null (core:mode-active-p buffer :local-a)))
      (let ((core::*active-global-minor-modes* nil)
            (core::*current-global-mode*
              (make-instance 'probe-mode :identifier :new-global)))
        (ok (null (core:mode-active-p buffer :global-minor)))
        (ok (null (core:mode-active-p buffer :global)))
        (ok (eq t (core:mode-active-p buffer :new-global)))))))
