(defpackage :lem-tests/visible-lines
  (:use :cl :rove)
  (:local-nicknames (:core :lem-core)))
(in-package :lem-tests/visible-lines)

;; Frozen traversal from 62989222c, with direction as an explicit parameter.
(defun reference-move (point n direction)
  (lem:with-point ((candidate point))
    (dotimes (i n)
      (loop
        (unless (lem:line-offset candidate direction)
          (return-from reference-move nil))
        (unless (core::line-hidden-p candidate) (return))))
    (lem:move-point point candidate)))

(deftest visible-line-movement-matches-reference
  (lem:with-current-buffers ()
    (let* ((buffer (lem:make-buffer "visible-lines"))
           (failure nil)
           (cases 0))
      (lem:insert-string (lem:buffer-point buffer) (format nil "abc~%def~%ghi~%jkl~%mno"))
      (block compare
        (dolist (mask (cons nil (loop :for mask :below 32 :collect mask)))
          (setf (lem:variable-value 'core::line-hidden-function :buffer buffer)
                (when mask
                  (lambda (point) (logbitp (1- (lem:line-number-at-point point)) mask))))
          (dolist (kind '(:temporary :left-inserting :right-inserting))
            (lem:with-point ((expected (lem:buffer-start-point buffer) kind)
                             (actual (lem:buffer-start-point buffer) kind))
              (dotimes (start 5)
                (dolist (column '(0 2))
                  (dotimes (n 7)
                    (dolist (direction '(-1 1))
                      (dolist (point (list expected actual))
                        (lem:buffer-start point)
                        (lem:line-offset point start column))
                      (let ((want (reference-move expected n direction))
                            (got (funcall (if (plusp direction)
                                              #'core::move-to-next-visible-line
                                              #'core::move-to-previous-visible-line)
                                          actual n)))
                        (incf cases)
                        (unless (and (eq (not (null want)) (not (null got)))
                                     (or (null got) (eq got actual))
                                     (lem:point= expected actual)
                                     (eq kind (lem:point-kind actual)))
                          (setf failure (list mask kind start column n direction))
                          (return-from compare)))))))))))
      (ok (null failure) (format nil "~D movement cases; first mismatch: ~S" cases failure)))))

(deftest visible-line-predicate-remains-live-and-transactional
  (lem:with-current-buffers ()
    (let ((buffer (lem:make-buffer "live-visible-lines")))
      (lem:insert-string (lem:buffer-point buffer) (format nil "abc~%def~%ghi~%jkl"))
      (lem:with-point ((point (lem:buffer-start-point buffer)))
        (core::move-to-next-visible-line point)
        (setf (lem:variable-value 'core::line-hidden-function :buffer buffer)
              (lambda (candidate) (= 3 (lem:line-number-at-point candidate))))
        (core::move-to-next-visible-line point)
        (ok (= 4 (lem:line-number-at-point point)))
        (setf (lem:variable-value 'core::line-hidden-function :buffer buffer) nil)
        (core::move-to-previous-visible-line point)
        (ok (= 3 (lem:line-number-at-point point)))
        (lem:buffer-start point)
        (let ((calls 0))
          (setf (lem:variable-value 'core::line-hidden-function :buffer buffer)
                (lambda (candidate)
                  (declare (ignore candidate))
                  (incf calls)
                  (setf (lem:variable-value 'core::line-hidden-function :buffer buffer) nil)
                  t))
          (core::move-to-next-visible-line point)
          (ok (= 1 calls))
          (ok (= 3 (lem:line-number-at-point point))
              "predicate removal during a traversal affects the next line"))
        (setf (lem:variable-value 'core::line-hidden-function :buffer buffer)
              (lambda (candidate) (declare (ignore candidate)) (error "visibility failure")))
        (ok (signals (core::move-to-previous-visible-line point) 'error))
        (ok (= 3 (lem:line-number-at-point point))
            "a failed predicate leaves the original point in place")
        (dolist (n '(-1 1/2))
          (ok (signals (core::move-to-next-visible-line point n) 'type-error))
          (ok (signals (core::move-to-previous-visible-line point n) 'type-error)))))))
