(defpackage #:lem-structured-notes
  (:use #:cl)
  (:export
   ;; Model conditions and validation.
   #:semantic-model-error
   #:semantic-model-error-code
   #:semantic-model-error-value
   #:semantic-model-error-message
   #:validate-document

   ;; Opaque CalDAV resource names.
   #:generate-caldav-opaque-resource-name

   ;; Privacy-preserving iCalendar identities.
   #:generate-icalendar-uid

   ;; Source positions and diagnostics.
   #:source-span
   #:make-source-span
   #:source-span-source-id
   #:source-span-character-start
   #:source-span-character-end
   #:source-span-byte-start
   #:source-span-byte-end
   #:diagnostic
   #:make-diagnostic
   #:diagnostic-severity
   #:diagnostic-code
   #:diagnostic-message
   #:diagnostic-span
   #:diagnostic-remediation
   #:diagnostic-loss-risk

   ;; Source-preserving iCalendar syntax.
   #:ical-parameter-value
   #:ical-parameter-value-p
   #:ical-parameter-value-raw
   #:ical-parameter-value-text
   #:ical-parameter-value-decoded-text
   #:ical-parameter-value-quoted-p
   #:decode-ical-parameter-text
   #:encode-ical-parameter-text
   #:fold-ical-content-line
   #:generate-ical-content-line
   #:plan-ical-content-line-replacement
   #:plan-ical-content-line-deletion
   #:plan-ical-content-line-insertion
   #:apply-ical-source-edits
   #:replace-ical-content-line
   #:ical-source-edit
   #:ical-source-edit-p
   #:ical-source-edit-kind
   #:ical-source-edit-source-id
   #:ical-source-edit-character-start
   #:ical-source-edit-character-end
   #:ical-source-edit-byte-start
   #:ical-source-edit-byte-end
   #:ical-source-edit-expected-source
   #:ical-source-edit-replacement
   #:ical-parameter
   #:ical-parameter-p
   #:ical-parameter-raw
   #:ical-parameter-name
   #:ical-parameter-normalized-name
   #:ical-parameter-values
   #:ical-content-line
   #:ical-content-line-p
   #:ical-content-line-raw
   #:ical-content-line-unfolded
   #:ical-content-line-span
   #:ical-content-line-group
   #:ical-content-line-normalized-group
   #:ical-content-line-name
   #:ical-content-line-normalized-name
   #:ical-content-line-parameters
   #:ical-content-line-value
   #:ical-content-line-valid-p
   #:ical-component
   #:ical-component-p
   #:ical-component-name
   #:ical-component-normalized-name
   #:ical-component-begin-line
   #:ical-component-end-line
   #:ical-component-items
   #:ical-component-span
   #:ical-component-closed-p
   #:ical-component-properties
   #:ical-component-children
   #:ical-document
   #:ical-document-p
   #:ical-document-source
   #:ical-document-source-id
   #:ical-document-newline
   #:ical-document-content-lines
   #:ical-document-components
   #:ical-document-diagnostics
   #:parse-icalendar-cst
   #:normalize-icalendar-line-endings-to-crlf
   #:serialize-icalendar-cst

   ;; Source-preserving iCalendar octet ingress.
   #:ical-octet-input
   #:ical-octet-input-p
   #:ical-octet-input-octets
   #:ical-octet-input-decoded-source
   #:ical-octet-input-document
   #:ical-octet-input-diagnostics
   #:ical-octet-input-utf8-valid-p
   #:parse-icalendar-octets
   #:serialize-icalendar-octets

   ;; Typed iCalendar scalar values.
   #:ical-time-value
   #:ical-time-value-p
   #:ical-time-value-hour
   #:ical-time-value-minute
   #:ical-time-value-second
   #:ical-time-value-utc-p
   #:ical-time-value-timezone-id
   #:ical-time-value-original-lexeme
   #:make-ical-time-value
   #:ical-positive-leap-second-utc-dates
   #:ical-positive-leap-second-utc-date-p
   #:validate-ical-time-value-date-context
   #:ical-value
   #:ical-value-p
   #:ical-value-kind
   #:ical-value-raw
   #:ical-value-decoded
   #:ical-value-valid-p
   #:ical-value-diagnostics
   #:ical-uri-value
   #:ical-uri-value-p
   #:ical-uri-value-original-lexeme
   #:ical-uri-value-scheme
   #:ical-uri-value-authority
   #:ical-uri-value-userinfo
   #:ical-uri-value-host
   #:ical-uri-value-host-kind
   #:ical-uri-value-port
   #:ical-uri-value-path
   #:ical-uri-value-query
   #:ical-uri-value-fragment
   #:ical-recur-weekday
   #:ical-recur-weekday-p
   #:ical-recur-weekday-ordinal
   #:ical-recur-weekday-weekday
   #:ical-recur-value
   #:ical-recur-value-p
   #:ical-recur-value-original-lexeme
   #:ical-recur-value-frequency
   #:ical-recur-value-until
   #:ical-recur-value-count
   #:ical-recur-value-interval
   #:ical-recur-value-by-second
   #:ical-recur-value-by-minute
   #:ical-recur-value-by-hour
   #:ical-recur-value-by-day
   #:ical-recur-value-by-month-day
   #:ical-recur-value-by-year-day
   #:ical-recur-value-by-week-number
   #:ical-recur-value-by-month
   #:ical-recur-value-by-set-position
   #:ical-recur-value-week-start
   #:ical-recur-value-recurrence-scale
   #:ical-recur-value-skip
   #:encode-ical-recur
   #:ical-duration-value
   #:ical-duration-value-p
   #:ical-duration-value-sign
   #:ical-duration-value-weeks
   #:ical-duration-value-days
   #:ical-duration-value-hours
   #:ical-duration-value-minutes
   #:ical-duration-value-seconds
   #:ical-duration-value-original-lexeme
   #:make-ical-duration-value
   #:ical-period-value
   #:ical-period-value-p
   #:ical-period-value-start
   #:ical-period-value-end
   #:ical-period-value-duration
   #:ical-period-value-original-lexeme
   #:ical-request-status-value
   #:ical-request-status-value-p
   #:make-ical-request-status-value
   #:ical-request-status-value-code
   #:ical-request-status-value-components
   #:ical-request-status-value-class
   #:ical-request-status-value-description
   #:ical-request-status-value-exception-data
   #:ical-request-status-value-original-lexeme
   #:decode-ical-request-status
   #:encode-ical-request-status
   #:decode-ical-value
   #:encode-ical-value
   #:encode-ical-binary
   #:encode-ical-duration
   #:decode-ical-text
   #:encode-ical-text

   ;; Property-aware iCalendar decoding.
   #:ical-property-profile
   #:ical-property-profile-p
   #:ical-property-profile-name
   #:ical-property-profile-default-type
   #:ical-property-profile-allowed-types
   #:ical-property-profile-list-p
   #:find-ical-property-profile
   #:ical-property-value
   #:ical-property-value-p
   #:ical-property-value-line
   #:ical-property-value-value-type
   #:ical-property-value-values
   #:ical-property-value-language
   #:ical-property-value-media-type
   #:ical-property-value-typed-p
   #:ical-property-value-valid-p
   #:ical-property-value-diagnostics
   #:ical-property-effective-calendar-user-type
   #:ical-property-effective-free-busy-type
   #:ical-property-effective-participation-status
   #:ical-property-effective-relationship-type
   #:ical-property-effective-role
   #:ical-property-effective-rsvp-p
   #:ical-property-effective-media-type
   #:ical-property-effective-image-displays
   #:ical-property-effective-conference-features
   #:ical-property-conference-label
   #:ical-property-calendar-user-email
   #:ical-well-formed-language-tag-p
   ;; RFC 9073/9074/9253 typed, inert extension projection.
   #:ical-publishing-component
   #:ical-publishing-component-p
   #:ical-publishing-component-kind
   #:ical-publishing-component-component
   #:ical-publishing-component-uid
   #:ical-publishing-component-type
   #:ical-publishing-component-calendar-address
   #:ical-publishing-component-url
   #:ical-publishing-component-properties
   #:ical-publishing-component-children
   #:ical-publishing-component-schedulable-p
   #:ical-publishing-component-diagnostics
   #:ical-publishing-component-valid-p
   #:ical-styled-description
   #:ical-styled-description-p
   #:ical-styled-description-property
   #:ical-styled-description-value-type
   #:ical-styled-description-value
   #:ical-styled-description-media-type
   #:ical-styled-description-language
   #:ical-styled-description-derived-p
   #:ical-styled-description-order
   #:ical-styled-description-diagnostics
   #:ical-styled-description-valid-p
   #:ical-structured-data
   #:ical-structured-data-p
   #:ical-structured-data-property
   #:ical-structured-data-value-type
   #:ical-structured-data-value
   #:ical-structured-data-media-type
   #:ical-structured-data-schema
   #:ical-structured-data-order
   #:ical-structured-data-retrieval-safe-p
   #:ical-structured-data-diagnostics
   #:ical-structured-data-valid-p
   #:ical-calendar-relationship
   #:ical-calendar-relationship-p
   #:ical-calendar-relationship-property
   #:ical-calendar-relationship-type
   #:ical-calendar-relationship-raw-type
   #:ical-calendar-relationship-resolution
   #:ical-calendar-relationship-value-type
   #:ical-calendar-relationship-target
   #:ical-calendar-relationship-gap
   #:ical-calendar-relationship-diagnostics
   #:ical-calendar-relationship-valid-p
   #:ical-calendar-link
   #:ical-calendar-link-p
   #:ical-calendar-link-property
   #:ical-calendar-link-value-type
   #:ical-calendar-link-target
   #:ical-calendar-link-link-relations
   #:ical-calendar-link-media-type
   #:ical-calendar-link-label
   #:ical-calendar-link-language
   #:ical-calendar-link-retrieval-safe-p
   #:ical-calendar-link-diagnostics
   #:ical-calendar-link-valid-p
   #:ical-rfc-extension-set
   #:ical-rfc-extension-set-p
   #:ical-rfc-extension-set-component
   #:ical-rfc-extension-set-publishing-components
   #:ical-rfc-extension-set-styled-descriptions
   #:ical-rfc-extension-set-structured-data
   #:ical-rfc-extension-set-relationships
   #:ical-rfc-extension-set-concepts
   #:ical-rfc-extension-set-links
   #:ical-rfc-extension-set-refids
   #:ical-rfc-extension-set-diagnostics
   #:ical-rfc-extension-set-valid-p
   #:project-ical-publishing-component
   #:project-ical-styled-description
   #:project-ical-structured-data
   #:project-ical-calendar-relationship
   #:project-ical-calendar-link
   #:project-ical-rfc-extensions
   #:ical-property-presentation
   #:ical-property-presentation-p
   #:ical-property-presentation-ordinal
   #:ical-property-presentation-property
   #:ical-property-presentation-value
   #:ical-property-presentation-language
   #:ical-property-presentation-set
   #:ical-property-presentation-set-p
   #:ical-property-presentation-set-component
   #:ical-property-presentation-set-values
   #:ical-property-presentation-set-diagnostics
   #:ical-property-presentation-set-valid-p
   #:project-ical-property-presentations
   #:ical-managed-attachment
   #:ical-managed-attachment-p
   #:ical-managed-attachment-kind
   #:ical-managed-attachment-property
   #:ical-managed-attachment-uri
   #:ical-managed-attachment-managed-id
   #:ical-managed-attachment-media-type
   #:ical-managed-attachment-filename
   #:ical-managed-attachment-size
   #:ical-managed-attachment-retrieval-safe-p
   #:ical-managed-attachment-diagnostics
   #:ical-managed-attachment-valid-p
   #:project-ical-managed-attachment
   #:ical-image
   #:ical-image-p
   #:ical-image-property
   #:ical-image-kind
   #:ical-image-uri
   #:ical-image-binary
   #:ical-image-media-type
   #:ical-image-displays
   #:ical-image-raw-displays
   #:ical-image-display-resolution
   #:ical-image-alternate-uri
   #:ical-image-retrieval-safe-p
   #:ical-image-diagnostics
   #:ical-image-valid-p
   #:project-ical-image
   #:ical-conference
   #:ical-conference-p
   #:ical-conference-property
   #:ical-conference-uri
   #:ical-conference-features
   #:ical-conference-feature-resolution
   #:ical-conference-label
   #:ical-conference-language
   #:ical-conference-moderator-p
   #:ical-conference-retrieval-safe-p
   #:ical-conference-diagnostics
   #:ical-conference-valid-p
   #:project-ical-conference
   #:decode-ical-content-line-value
   #:generate-ical-property-line

   ;; Verified canonical iCalendar generation.
   #:ical-property-output
   #:ical-property-output-p
   #:make-ical-property-output
   #:ical-property-output-name
   #:ical-property-output-value
   #:ical-property-output-value-type
   #:ical-property-output-group
   #:ical-property-output-parameters
   #:ical-component-output
   #:ical-component-output-p
   #:make-ical-component-output
   #:ical-component-output-name
   #:ical-component-output-properties
   #:ical-component-output-children
   #:generate-icalendar-document

   ;; Verified semantic iCalendar source edits.
   #:ical-property-change
   #:ical-property-change-p
   #:make-ical-property-change
   #:ical-property-change-name
   #:ical-property-change-operation
   #:ical-property-change-property
   #:ical-property-change-metadata-policy
   #:ical-semantic-edit-plan
   #:ical-semantic-edit-plan-p
   #:ical-semantic-edit-plan-source-id
   #:ical-semantic-edit-plan-base-source
   #:ical-semantic-edit-plan-component-path
   #:ical-semantic-edit-plan-changes
   #:ical-semantic-edit-plan-source-edits
   #:ical-semantic-edit-plan-proposed-source
   #:plan-ical-semantic-property-changes
   #:apply-ical-semantic-edit-plan

   ;; Conditional CalDAV write intents.
   #:http-entity-tag
   #:http-entity-tag-p
   #:parse-http-entity-tag
   #:http-entity-tag-raw
   #:http-entity-tag-opaque
   #:http-entity-tag-weak-p
   #:strong-http-entity-tag-p
   #:caldav-write-intent
   #:caldav-write-intent-p
   #:make-caldav-write-intent
   #:make-caldav-update-intent-from-plan
   #:caldav-write-intent-operation
   #:caldav-write-intent-method
   #:caldav-write-intent-href
   #:caldav-write-intent-entity-tag
   #:caldav-write-intent-schedule-tag
   #:caldav-write-intent-schedule-reply
   #:caldav-write-intent-return-preference
   #:caldav-write-intent-validation-profile
   #:caldav-write-intent-body
   #:caldav-write-intent-headers
   #:caldav-write-intent-rscale-write-proof
   #:caldav-write-intent-timezone-reference-write-proof
   #:caldav-timezone-reference-write-proof
   #:caldav-timezone-reference-write-proof-p
   #:make-caldav-timezone-reference-write-proof
   #:caldav-timezone-reference-write-proof-service-uri
   #:caldav-timezone-reference-write-proof-cache-sha256
   #:caldav-timezone-reference-write-proof-admitted-at
   #:caldav-timezone-reference-write-proof-expires-at
   #:caldav-timezone-reference-write-proof-timezone-ids
   #:caldav-timezone-reference-write-proof-timezone-sources
   #:caldav-rscale-write-proof
   #:caldav-rscale-write-proof-p
   #:make-caldav-rscale-write-proof
   #:caldav-rscale-write-proof-collection-href
   #:caldav-rscale-write-proof-kind
   #:caldav-rscale-write-proof-supported-rscales
   #:caldav-rscale-write-proof-property-status
   #:caldav-write-conflict
   #:caldav-write-conflict-p
   #:caldav-write-conflict-operation
   #:caldav-write-conflict-href
   #:caldav-write-conflict-status
   #:caldav-write-conflict-base-entity-tag
   #:caldav-write-conflict-reason
   #:caldav-write-outcome
   #:caldav-write-outcome-p
   #:classify-caldav-write-response
   #:caldav-write-outcome-kind
   #:caldav-write-outcome-status
   #:caldav-write-outcome-entity-tag
   #:caldav-write-outcome-schedule-tag
   #:caldav-write-outcome-location
   #:caldav-write-outcome-refetch-required-p
   #:caldav-write-outcome-conflict

   ;; RFC 7240 return preferences and exact application evidence.
   #:http-applied-preference
   #:http-applied-preference-p
   #:http-applied-preference-token
   #:http-applied-preference-value
   #:http-applied-preference-raw
   #:http-preference-parameter
   #:http-preference-parameter-p
   #:http-preference-parameter-name
   #:http-preference-parameter-value
   #:http-preference-parameter-raw
   #:http-request-preference
   #:http-request-preference-p
   #:http-request-preference-token
   #:http-request-preference-value
   #:http-request-preference-parameters
   #:http-request-preference-raw
   #:caldav-return-preference-evidence
   #:caldav-return-preference-evidence-p
   #:caldav-return-preference-evidence-kind
   #:caldav-return-preference-evidence-requested
   #:caldav-return-preference-evidence-applied
   #:caldav-return-preference-evidence-applied-preferences
   #:normalize-caldav-return-preference
   #:caldav-return-preference-header
   #:parse-http-prefer-field
   #:parse-http-prefer-headers
   #:parse-http-applied-preference-field
   #:parse-http-preference-applied-headers
   #:caldav-return-preference-from-request-headers
   #:caldav-depth-noroot-from-request-headers
   #:classify-caldav-return-preference
   #:caldav-write-representation-evidence
   #:caldav-write-representation-evidence-p
   #:caldav-write-representation-evidence-kind
   #:caldav-write-representation-evidence-preference-evidence
   #:caldav-write-representation-evidence-read-outcome
   #:caldav-write-representation-evidence-diagnostics
   #:classify-caldav-write-representation

   ;; Bounded CalDAV calendar-resource reads.
   #:http-media-type
   #:http-media-type-p
   #:parse-http-media-type
   #:http-media-type-raw
   #:http-media-type-type
   #:http-media-type-subtype
   #:http-media-type-parameters
   #:http-media-type-parameter
   #:caldav-read-intent
   #:caldav-read-intent-p
   #:make-caldav-get-intent
   #:caldav-read-intent-method
   #:caldav-read-intent-href
   #:caldav-read-intent-entity-tag
   #:caldav-read-intent-headers
   #:caldav-read-outcome
   #:caldav-read-outcome-p
   #:classify-caldav-get-response
   #:caldav-read-outcome-kind
   #:caldav-read-outcome-status
   #:caldav-read-outcome-href
   #:caldav-read-outcome-entity-tag
   #:caldav-read-outcome-schedule-tag
   #:caldav-read-outcome-media-type
   #:caldav-read-outcome-location
   #:caldav-read-outcome-body-octets
   #:caldav-read-outcome-calendar-input
   #:caldav-read-outcome-diagnostics

   ;; Pure DAV URI resolution and identity evidence.
   #:dav-resolved-href
   #:dav-resolved-href-p
   #:resolve-dav-href
   #:dav-resolved-href-original
   #:dav-resolved-href-absolute-uri
   #:dav-resolved-href-reference-kind
   #:dav-resolved-href-same-origin-p
   #:dav-resolved-href-fetchable-p
   #:dav-resolved-href-diagnostics

   ;; Bounded HTTPS URI-reference resolution.
   #:caldav-https-origin
   #:caldav-https-origin-p
   #:caldav-https-origin-host
   #:caldav-https-origin-port
   #:resolve-caldav-discovery-location

   ;; Opaque scheduling entity tags.
   #:caldav-schedule-tag
   #:caldav-schedule-tag-p
   #:caldav-schedule-tag-raw
   #:caldav-schedule-tag-opaque
   #:parse-caldav-schedule-tag

   ;; Conservative VEVENT/VTODO/VJOURNAL projection.
   #:ical-calendar-item
   #:ical-calendar-item-p
   #:ical-calendar-item-kind
   #:ical-calendar-item-component
   #:ical-calendar-item-uid
   #:ical-calendar-item-dtstamp
   #:ical-calendar-item-summary
   #:ical-calendar-item-description
   #:ical-calendar-item-descriptions
   #:ical-calendar-item-request-statuses
   #:ical-calendar-item-status
   #:ical-calendar-item-location
   #:ical-calendar-item-url
   #:ical-calendar-item-transparency
   #:ical-calendar-item-categories
   #:ical-calendar-item-color
   #:ical-calendar-item-images
   #:ical-calendar-item-conferences
   #:ical-calendar-item-start
   #:ical-calendar-item-end
   #:ical-calendar-item-due
   #:ical-calendar-item-duration
   #:ical-calendar-item-completed
   #:ical-calendar-item-percent-complete
   #:ical-calendar-item-priority
   #:ical-calendar-item-sequence
   #:ical-calendar-item-recurrence-id
   #:ical-calendar-item-recurrence-range
   #:ical-calendar-item-recurrence-rule
   #:ical-calendar-item-recurrence-dates
   #:ical-calendar-item-recurrence-exception-dates
   #:ical-calendar-item-alarms
   #:ical-calendar-item-properties
   #:ical-calendar-item-diagnostics
   #:ical-calendar-item-valid-p
   #:ical-calendar-item-extensions
   #:assert-ical-conference-egress-safe
   #:ical-freebusy-period-entry
   #:ical-freebusy-period-entry-p
   #:ical-freebusy-period-entry-property
   #:ical-freebusy-period-entry-period
   #:ical-freebusy-period-entry-type
   #:ical-freebusy-period-entry-raw-type
   #:ical-freebusy-period-entry-resolution
   #:ical-freebusy
   #:ical-freebusy-p
   #:ical-freebusy-component
   #:ical-freebusy-uid
   #:ical-freebusy-dtstamp
   #:ical-freebusy-contact
   #:ical-freebusy-start
   #:ical-freebusy-end
   #:ical-freebusy-organizer
   #:ical-freebusy-url
   #:ical-freebusy-attendees
   #:ical-freebusy-comments
   #:ical-freebusy-periods
   #:ical-freebusy-request-statuses
   #:ical-freebusy-properties
   #:ical-freebusy-diagnostics
   #:ical-freebusy-valid-p
   #:ical-freebusy-extensions
   #:ical-available
   #:ical-available-p
   #:ical-available-component
   #:ical-available-uid
   #:ical-available-dtstamp
   #:ical-available-start
   #:ical-available-end
   #:ical-available-duration
   #:ical-available-recurrence-id
   #:ical-available-recurrence-range
   #:ical-available-recurrence-rule
   #:ical-available-recurrence-dates
   #:ical-available-recurrence-exception-dates
   #:ical-available-summary
   #:ical-available-description
   #:ical-available-location
   #:ical-available-categories
   #:ical-available-properties
   #:ical-available-diagnostics
   #:ical-available-valid-p
   #:ical-availability
   #:ical-availability-p
   #:ical-availability-component
   #:ical-availability-uid
   #:ical-availability-dtstamp
   #:ical-availability-busy-type
   #:ical-availability-start
   #:ical-availability-end
   #:ical-availability-duration
   #:ical-availability-priority
   #:ical-availability-available
   #:ical-availability-properties
   #:ical-availability-diagnostics
   #:ical-availability-valid-p
   #:project-ical-available-component
   #:project-ical-availability-component
   #:ical-availability-priority-rank
   #:ical-availability-busy-type-rank
   #:ical-availability-sensitive-property-p
   #:plan-ical-availability-redaction
   #:ical-availability-period
   #:ical-availability-period-p
   #:ical-availability-period-type
   #:ical-availability-period-start
   #:ical-availability-period-end
   #:ical-availability-expansion
   #:ical-availability-expansion-p
   #:ical-availability-expansion-window-start
   #:ical-availability-expansion-window-end
   #:ical-availability-expansion-periods
   #:ical-availability-expansion-components-examined
   #:ical-availability-expansion-boundaries-examined
   #:calculate-ical-availability
   #:ical-availability-overlaps-window-p
   #:ical-calendar-envelope
   #:ical-calendar-envelope-p
   #:ical-calendar-envelope-component
   #:ical-calendar-envelope-prodid
   #:ical-calendar-envelope-version
   #:ical-calendar-envelope-calscale
   #:ical-calendar-envelope-method
   #:ical-calendar-envelope-names
   #:ical-calendar-envelope-descriptions
   #:ical-calendar-envelope-uid
   #:ical-calendar-envelope-last-modified
   #:ical-calendar-envelope-url
   #:ical-calendar-envelope-categories
   #:ical-calendar-envelope-refresh-interval
   #:ical-calendar-envelope-source
   #:ical-calendar-envelope-color
   #:ical-calendar-envelope-images
   #:ical-calendar-envelope-components
   #:ical-calendar-envelope-properties
   #:ical-calendar-envelope-diagnostics
   #:ical-calendar-envelope-valid-p
   #:project-ical-calendar-envelope
   #:+ical-refresh-default-minimum-seconds+
   #:ical-refresh-consent
   #:ical-refresh-consent-p
   #:ical-refresh-consent-source
   #:ical-refresh-consent-approved-at
   #:ical-refresh-consent-expires-at
   #:ical-refresh-consent-minimum-seconds
   #:make-ical-refresh-consent
   #:ical-refresh-plan
   #:ical-refresh-plan-p
   #:ical-refresh-plan-kind
   #:ical-refresh-plan-source
   #:ical-refresh-plan-requested-seconds
   #:ical-refresh-plan-effective-seconds
   #:ical-refresh-plan-next-at
   #:ical-refresh-plan-warning-p
   #:ical-refresh-plan-retrieval-safe-p
   #:ical-refresh-plan-consent
   #:plan-ical-calendar-refresh
   #:ical-alarm
   #:ical-alarm-p
   #:ical-alarm-component
   #:ical-alarm-action
   #:ical-alarm-supported-p
   #:ical-alarm-trigger
   #:ical-alarm-trigger-related
   #:ical-alarm-repeat
   #:ical-alarm-duration
   #:ical-alarm-description
   #:ical-alarm-summary
   #:ical-alarm-attendees
   #:ical-alarm-attachments
   #:ical-alarm-properties
   #:ical-alarm-diagnostics
   #:ical-alarm-valid-p
   #:ical-alarm-extensions
   #:project-ical-alarm
   #:project-ical-component
   #:project-ical-freebusy-component
   #:project-ical-item-to-semantic-node

   ;; Bounded Gregorian recurrence-set expansion.
   #:ical-recurrence-limits
   #:ical-recurrence-limits-p
   #:make-ical-recurrence-limits
   #:ical-recurrence-limits-max-periods
   #:ical-recurrence-limits-max-candidates
   #:ical-recurrence-limits-max-instances
   #:ical-recurrence-expansion
   #:ical-recurrence-expansion-p
   #:ical-recurrence-expansion-instances
   #:ical-recurrence-expansion-periods-examined
   #:ical-recurrence-expansion-candidates-examined
   #:expand-ical-recurrence-set
   #:expand-ical-calendar-item-recurrence

   ;; Detached recurrence-instance assembly.
   #:ical-effective-duration
   #:ical-effective-duration-p
   #:ical-effective-duration-kind
   #:ical-effective-duration-seconds
   #:ical-effective-duration-nominal-days
   #:ical-effective-duration-nominal-subday-seconds
   #:ical-recurrence-instance
   #:ical-recurrence-instance-p
   #:ical-recurrence-instance-recurrence-id
   #:ical-recurrence-instance-actual-start
   #:ical-recurrence-instance-actual-finish
   #:ical-recurrence-instance-effective-duration
   #:ical-recurrence-instance-status
   #:ical-recurrence-instance-item
   #:ical-recurrence-series-expansion
   #:ical-recurrence-series-expansion-p
   #:ical-recurrence-series-expansion-uid
   #:ical-recurrence-series-expansion-kind
   #:ical-recurrence-series-expansion-master
   #:ical-recurrence-series-expansion-instances
   #:ical-rscale-family-rejection
   #:ical-rscale-family-rejection-p
   #:ical-rscale-family-rejection-uid
   #:ical-rscale-family-rejection-kind
   #:ical-rscale-family-rejection-recurrence-scale
   #:ical-rscale-family-rejection-items
   #:classify-ical-rscale-component-families
   #:select-ical-calendar-item-revisions
   #:expand-ical-recurrence-series

   ;; VTIMEZONE projection and explicit resolution.
   #:ical-timezone-observance
   #:ical-timezone-observance-p
   #:ical-timezone-observance-kind
   #:ical-timezone-observance-component
   #:ical-timezone-observance-start
   #:ical-timezone-observance-offset-from
   #:ical-timezone-observance-offset-to
   #:ical-timezone-observance-names
   #:ical-timezone-observance-recurrence-rule
   #:ical-timezone-observance-recurrence-dates
   #:ical-timezone-observance-comments
   #:ical-timezone-observance-properties
   #:ical-timezone-observance-diagnostics
   #:ical-timezone-observance-valid-p
   #:ical-timezone-definition
   #:ical-timezone-definition-p
   #:ical-timezone-definition-component
   #:ical-timezone-definition-timezone-id
   #:ical-timezone-definition-last-modified
   #:ical-timezone-definition-url
   #:ical-timezone-definition-observances
   #:ical-timezone-definition-properties
   #:ical-timezone-definition-diagnostics
   #:ical-timezone-definition-valid-p
   #:project-ical-timezone-component
   #:timezone-provider
   #:timezone-provider-version
   #:find-timezone-definition
   #:resolve-zoned-local-time
   #:project-utc-time-to-zoned-local-time
   #:validate-ical-time-value-timezone-context
   #:validate-ical-date-time-leap-second-context
   #:embedded-timezone-provider
   #:make-embedded-timezone-provider
   #:embedded-timezone-max-transition-periods
   #:embedded-timezone-max-transition-candidates
   #:embedded-timezone-max-transitions
   #:timezone-resolution-candidate
   #:timezone-resolution-candidate-p
   #:timezone-resolution-candidate-utc-seconds
   #:timezone-resolution-candidate-offset-seconds
   #:timezone-resolution-candidate-fold
   #:timezone-local-resolution
   #:timezone-local-resolution-p
   #:timezone-local-resolution-status
   #:timezone-local-resolution-timezone-id
   #:timezone-local-resolution-local
   #:timezone-local-resolution-candidates
   #:select-timezone-resolution

   ;; Temporal and recurrence semantics.
   #:temporal-value
   #:temporal-value-p
   #:make-temporal-value
   #:temporal-value-kind
   #:temporal-value-local-value
   #:temporal-value-timezone-id
   #:temporal-value-fold
   #:temporal-value-gap-policy
   #:temporal-value-precision
   #:temporal-value-original-lexeme
   #:recurrence-period
   #:recurrence-period-p
   #:make-recurrence-period
   #:recurrence-period-start
   #:recurrence-period-end
   #:recurrence-period-duration
   #:recurrence-period-original-lexeme
   #:recurrence
   #:make-recurrence
   #:recurrence-rules
   #:recurrence-dates
   #:recurrence-exception-dates
   #:recurrence-policy
   #:recurrence-original-lexeme

   ;; Extensibility and calendar projection.
   #:opaque-extension
   #:make-opaque-extension
   #:opaque-extension-namespace
   #:opaque-extension-media-type
   #:opaque-extension-owner-id
   #:opaque-extension-raw-value
   #:opaque-extension-ordering-anchor
   #:opaque-extension-provenance
   #:calendar-binding
   #:make-calendar-binding
   #:calendar-binding-id
   #:calendar-binding-node-id
   #:calendar-binding-projection-kind
   #:calendar-binding-account-id
   #:calendar-binding-calendar-id
   #:calendar-binding-uid
   #:calendar-binding-recurrence-id
   #:calendar-binding-ownership
   #:calendar-binding-write-policy

   ;; Format-neutral event semantics.
   #:event-facet
   #:event-facet-p
   #:make-event-facet
   #:event-facet-start
   #:event-facet-end
   #:event-facet-duration
   #:event-facet-status
   #:event-facet-location
   #:event-facet-url
   #:event-facet-transparency
   #:event-facet-recurrence

   ;; Format-neutral task clocks.
   #:task-clock
   #:task-clock-p
   #:make-task-clock
   #:task-clock-start
   #:task-clock-end

   ;; Documents, nodes, and tasks.
   #:task-facet
   #:task-effort-duration-p
   #:make-task-facet
   #:task-facet-workflow-id
   #:task-facet-state
   #:task-facet-done-p
   #:task-facet-priority
   #:task-facet-progress
   #:task-facet-effort
   #:task-facet-scheduled
   #:task-facet-scheduled-delay
   #:task-facet-deadline
   #:task-facet-closed
   #:task-facet-deadline-warning
   #:task-facet-recurrence
   #:task-facet-dependencies
   #:task-facet-logs
   #:inline-node
   #:inline-node-p
   #:make-inline-node
   #:inline-node-kind
   #:inline-node-source-format
   #:inline-node-raw
   #:inline-node-span
   #:inline-node-text
   #:inline-node-destination
   #:inline-node-children
   #:inline-node-attributes
   #:inline-nodes-equivalent-p
   #:parse-org-paragraph-inlines
   #:parse-commonmark-paragraph-inlines
   #:render-commonmark-inlines
   #:list-item
   #:list-item-p
   #:make-list-item
   #:list-item-source-format
   #:list-item-raw
   #:list-item-span
   #:list-item-ordered-p
   #:list-item-ordinal
   #:list-item-checkbox
   #:list-item-inlines
   #:list-item-attributes
   #:list-items-equivalent-p
   #:parse-org-list-items
   #:parse-commonmark-list-items
   #:render-commonmark-list-lines
   #:table-cell
   #:table-cell-p
   #:make-table-cell
   #:table-cell-source-format
   #:table-cell-raw
   #:table-cell-span
   #:table-cell-inlines
   #:table-cell-attributes
   #:table-row
   #:table-row-p
   #:make-table-row
   #:table-row-source-format
   #:table-row-raw
   #:table-row-span
   #:table-row-cells
   #:table-row-attributes
   #:table-data
   #:table-data-p
   #:make-table-data
   #:table-data-alignments
   #:table-data-rows
   #:table-data-attributes
   #:table-data-equivalent-p
   #:parse-org-table-data
   #:parse-gfm-table-data
   #:render-gfm-table-lines
   #:code-block-data
   #:code-block-data-p
   #:make-code-block-data
   #:code-block-data-source-format
   #:code-block-data-raw
   #:code-block-data-span
   #:code-block-data-language
   #:code-block-data-code
   #:code-block-data-attributes
   #:code-block-data-equivalent-p
   #:parse-org-source-block-data
   #:parse-commonmark-fenced-code-data
   #:render-commonmark-fenced-code-lines
   #:parse-myst-code-cell-data
   #:render-myst-code-cell-lines
   #:parse-org-quote-inlines
   #:parse-commonmark-quote-inlines
   #:render-commonmark-quote-line
   #:quote-inlines-canonical-commonmark-p
   #:content-node
   #:content-node-p
   #:make-content-node
   #:content-node-kind
   #:content-node-source-format
   #:content-node-raw
   #:content-node-span
   #:content-node-name
   #:content-node-attributes
   #:content-node-text
   #:content-node-inlines
   #:content-node-items
   #:content-node-table
   #:content-node-code-block
   #:content-node-native-commonmark-paragraph-p
   #:content-node-native-commonmark-list-p
   #:content-node-native-gfm-table-p
   #:content-node-native-fenced-code-p
   #:content-node-native-myst-code-cell-p
   #:content-node-native-code-block-p
   #:content-node-native-commonmark-quote-p
   #:parse-org-drawer-inlines
   #:parse-myst-drawer-inlines
   #:render-myst-drawer-lines
   #:drawer-inlines-canonical-myst-p
   #:content-node-native-myst-drawer-p
   #:content-node-native-myst-comment-p
   #:node-reference
   #:node-reference-p
   #:make-node-reference
   #:node-reference-kind
   #:node-reference-value
   #:semantic-node
   #:make-semantic-node
   #:semantic-node-id
   #:semantic-node-level
   #:semantic-node-title
   #:semantic-node-body
   #:semantic-node-parent-id
   #:semantic-node-child-ids
   #:semantic-node-aliases
   #:semantic-node-references
   #:semantic-node-tags
   #:semantic-node-properties
   #:semantic-node-event
   #:semantic-node-task
   #:semantic-node-inactive-dates
   #:semantic-node-calendar-bindings
   #:semantic-node-span
   #:semantic-node-extensions
   #:semantic-document
   #:make-semantic-document
   #:semantic-document-id
   #:semantic-document-source-uri
   #:semantic-document-format
   #:semantic-document-profile
   #:semantic-document-preamble
   #:semantic-document-metadata
   #:semantic-document-nodes
   #:semantic-document-root-ids
   #:semantic-document-newline
   #:semantic-document-encoding
   #:semantic-document-source-revision
   #:semantic-document-diagnostics
   #:semantic-document-extensions
   #:find-semantic-node
   #:semantic-node-subtree-character-range
   #:semantic-node-subtree-nodes
   #:rewrite-semantic-subtree-heading-levels
   #:minimal-source-replacement
   #:move-semantic-subtree-source

   ;; Source adapter protocol.
   #:source-provider
   #:source-provider-format
   #:source-provider-profile
   #:parse-source
   #:enumerate-nodes
   #:enumerate-tasks
   #:resolve-node
   #:plan-source-edit
   #:apply-source-edit
   #:render-source-node
   #:source-content-fingerprint
   #:source-metadata-fingerprint
   #:source-snapshot
   #:make-source-snapshot
   #:source-snapshot-provider
   #:source-snapshot-source-id
   #:source-snapshot-revision
   #:source-snapshot-document
   #:source-snapshot-syntax-tree
   #:source-snapshot-content-fingerprint
   #:source-snapshot-metadata-fingerprint
   #:plan-lsm-calendar-projection-edits
   #:source-snapshot-diagnostics
   #:source-location
   #:make-source-location
   #:source-location-source-id
   #:source-location-node-id
   #:source-location-revision
   #:source-location-span
   #:edit-operation
   #:make-edit-operation
   #:edit-operation-kind
   #:edit-operation-target-id
   #:edit-operation-payload
   #:archive-context
   #:archive-context-p
   #:make-archive-context
   #:archive-context-timestamp
   #:archive-context-source-id
   #:archive-context-outline-path
   #:archive-context-category
   #:archive-context-task-state
   #:archive-context-inherited-tags
   #:edit-plan
   #:edit-plan-p
   #:make-edit-plan
   #:edit-plan-provider
   #:edit-plan-source-id
   #:edit-plan-base-revision
   #:edit-plan-base-content-fingerprint
   #:edit-plan-base-metadata-fingerprint
   #:edit-plan-operations
   #:edit-plan-metadata
   #:source-archive-plan
   #:source-archive-plan-p
   #:make-source-archive-plan
   #:source-archive-plan-provider
   #:source-archive-plan-source-node-id
   #:source-archive-plan-context
   #:source-archive-plan-source-plan
   #:source-archive-plan-destination-plan
   #:source-archive-plan-destination-created-p
   #:make-archive-destination-plan
   #:make-provider-source-archive-plan
   #:archived-node-shape-present-p
   #:plan-source-archive
   #:apply-source-archive
   #:assert-edit-plan-current
   #:source-adapter-error
   #:source-adapter-error-provider
   #:source-adapter-error-message
   #:unsupported-source-operation
   #:unsupported-source-operation-operation
   #:stale-source
   #:stale-source-expected-revision
   #:stale-source-actual-revision
   #:stale-source-expected-fingerprint
   #:stale-source-actual-fingerprint
   #:stale-source-expected-metadata-fingerprint
   #:stale-source-actual-metadata-fingerprint

   ;; LSM concrete syntax and provider.
   #:cst-node
   #:cst-node-kind
   #:cst-node-character-start
   #:cst-node-character-end
   #:cst-node-byte-start
   #:cst-node-byte-end
   #:cst-node-raw
   #:cst-node-name
   #:cst-node-fields
   #:lsm-syntax-document
   #:lsm-syntax-document-p
   #:lsm-syntax-document-source
   #:lsm-syntax-document-newline
   #:lsm-syntax-document-nodes
   #:lsm-syntax-document-profile
   #:lsm-syntax-document-document-id
   #:lsm-syntax-document-diagnostics
   #:serialize-lsm-syntax
   #:render-lsm-document
   #:render-lsm-node
   #:lsm-provider
   #:legacy-markdown-provider
   #:plan-lsm-node-id
   #:plan-lsm-node-id-batch
   #:plan-lsm-task-state-batch
   #:plan-lsm-task-planning-batch

   ;; Verified, stale-safe migration planning and application.
   #:semantic-document-equivalent-p
   #:migration-error
   #:migration-error-message
   #:migration-equivalence-error
   #:migration-target-exists
   #:migration-target-exists-target-id
   #:migration-report
   #:migration-report-p
   #:migration-report-status
   #:migration-report-disposition
   #:migration-report-source-id
   #:migration-report-target-id
   #:migration-report-node-count
   #:migration-report-task-count
   #:migration-report-opaque-content-count
   #:migration-report-diagnostics
   #:migration-report-loss-risk-counts
   #:migration-plan
   #:migration-plan-p
   #:migration-plan-source-snapshot
   #:migration-plan-target-id
   #:migration-plan-target-source
   #:migration-plan-preview-snapshot
   #:migration-plan-report
   #:plan-lsm-migration
   #:assert-migration-plan-current
   #:apply-migration-plan-to-stream
   #:write-migration-plan-file
   #:resume-migration-plan-file
   #:rollback-migration-plan-file

   ;; Provider-neutral native notes workflows.
   #:notes-workflow-error
   #:notes-workflow-error-code
   #:notes-workflow-error-value
   #:notes-workflow-error-message
   #:generate-lsm-node-id
   #:notes-workspace
   #:notes-workspace-p
   #:notes-workspace-root
   #:notes-workspace-roam-root
   #:notes-workspace-journal-root
   #:resolve-notes-workspace
   #:notes-capture-origin
   #:notes-capture-origin-p
   #:notes-capture-origin-provider
   #:notes-capture-origin-scope
   #:notes-capture-origin-path
   #:notes-capture-origin-node-id
   #:notes-capture-origin-date
   #:make-notes-capture-origin
   #:valid-notes-iso-date-p
   #:notes-workspace-daily-path
   #:notes-workspace-journal-path
   #:notes-workspace-capture-path
   #:notes-document-plan
   #:notes-document-plan-p
   #:notes-document-plan-kind
   #:notes-document-plan-target-path
   #:notes-document-plan-base-source
   #:notes-document-plan-output-source
   #:notes-document-plan-document-id
   #:notes-document-plan-focus-node-id
   #:notes-document-plan-created-p
   #:plan-lsm-daily-note
   #:plan-lsm-journal-entry
   #:plan-lsm-capture
   #:apply-notes-document-plan

   ;; Source-preserving Org concrete syntax.
   #:org-cst-element
   #:org-cst-element-kind
   #:org-cst-element-character-start
   #:org-cst-element-character-end
   #:org-cst-element-byte-start
   #:org-cst-element-byte-end
   #:org-cst-element-raw
   #:org-cst-element-name
   #:org-cst-element-closed-p
   #:org-cst-document
   #:org-cst-document-source-id
   #:org-cst-document-newline
   #:org-cst-document-elements
   #:org-cst-document-diagnostics
   #:parse-org-cst
   #:serialize-org-cst
   #:org-cst-content-nodes-in-range))
