(defpackage :lem-agent/process-tools-tests
  (:use :cl :rove)
  (:local-nicknames (:agent :lem-agent) (:jobs :lem-toolkit/jobs)
                    (:process :lem-agent/process-tools) (:store :lem-daemon/recovery-store)))
(in-package :lem-agent/process-tools-tests)

(defun field (object key) (gethash key object))
(defun await (receipt)
  (multiple-value-bind (value done) (agent:await-request receipt :timeout 10)
    (unless done (error "Agent request timed out")) value))
(defun wait-for (predicate)
  (loop repeat 1000 when (funcall predicate) return t do (sleep 0.01)
        finally (error "Expected process tool state did not arrive")))
(defun state (session) (field (agent:session-snapshot session) "status"))
(defun idle (session)
  (wait-for (lambda ()
              (let ((snapshot (agent:session-snapshot session)))
                (and (equal "idle" (field snapshot "status"))
                     (null (field snapshot "active_turn"))
                     (plusp (length (field snapshot "turns")))
                     (zerop (length (field snapshot "queue"))))))))
(defun decision (session)
  (let ((pending nil))
    (wait-for (lambda ()
                (setf pending (find "pending" (field (agent:session-snapshot session) "decisions")
                                    :key (lambda (entry) (field entry "status")) :test #'equal))))
    pending))
(defun result (session)
  (let* ((turn (aref (field (agent:session-snapshot session) "turns") 0))
         (message (find "tool" (field turn "messages")
                        :key (lambda (entry) (field entry "role")) :test #'equal)))
    (field message "content")))
(defun tool-provider (arguments)
  (lambda (request emit context)
    (declare (ignore emit context))
    (if (find "tool" (field request "messages") :key (lambda (entry) (field entry "role")) :test #'equal)
        (agent:json-object "content" "Process result inspected")
        (agent:json-object "tool_calls"
                           (vector (agent:json-object "id" "process-call" "name" "run_process"
                                                       "arguments" arguments))))))
(defun new-session (manager root arguments)
  (agent:register-provider manager "fake" (tool-provider arguments))
  (let ((session (agent:create-session manager :provider "fake" :model "fixture" :root root)))
    (await (agent:session-ready session)) (await (agent:submit-message session "Run the reviewed tool"))
    session))
(defun allow (session)
  (await (agent:resolve-decision session (field (decision session) "id") "allow")))
(defun arguments (script &rest options)
  (apply #'agent:json-object "argv" (vector "/run/current-system/sw/bin/bash" "-c" script) options))
(defmacro with-managers ((manager jobs root base) &body body)
  `(let* ((,base (merge-pathnames (format nil "lem-process-tools-~a/" (store:new-id))
                                (uiop:temporary-directory)))
          (,root (merge-pathnames "project/" ,base))
          (,manager (agent:make-manager :directory (merge-pathnames "agents/" ,base)))
          (,jobs (jobs:open-job-manager :directory (merge-pathnames "jobs/" ,base))))
     (ensure-directories-exist ,root)
     (process:install-process-tools ,manager :job-manager ,jobs)
     (unwind-protect (progn ,@body)
       (agent:close-manager ,manager :wait t)
       (jobs:close-job-manager ,jobs)
       (uiop:delete-directory-tree ,base :validate t))))

(deftest approval-denial-and-literal-arguments
  (with-managers (manager registry root base)
    (let* ((effect (merge-pathnames "effect" root))
           (session (new-session manager root (arguments "printf allowed > effect"))))
      (decision session)
      (ok (null (jobs:list-jobs registry)) "no job exists before permission")
      (ok (not (probe-file effect)))
      (await (agent:resolve-decision session (field (decision session) "id") "deny"))
      (idle session)
      (ok (null (jobs:list-jobs registry)))
      (ok (not (probe-file effect))))
    (let ((session (new-session manager root (arguments "printf allowed > effect"))))
      (decision session)
      (ok (not (probe-file (merge-pathnames "effect" root))))
      (allow session) (idle session)
      (ok (equal "allowed" (uiop:read-file-string (merge-pathnames "effect" root)))))
    (let* ((literal "$(touch must-not-exist); literal")
           (session (new-session manager root
                                 (agent:json-object "argv" (vector "/run/current-system/sw/bin/printf" "%s" literal)))))
      (allow session) (idle session)
      (ok (equal literal (field (result session) "stdout")))
      (ok (eq t (field (result session) "success")))
      (ok (not (probe-file (merge-pathnames "must-not-exist" root))))
      (ok (search (agent:session-id session)
                  (jobs:job-owner (jobs:find-job (field (result session) "job_id") registry))))
      (ok (null (find-package :lem-core)) "process tools have no editor dependency"))))

(deftest validation-and-root-contained-working-directories
  (with-managers (manager registry root base)
    (dolist (extra (list (agent:json-object "argv" #("true") "environment" (agent:json-object))
                        (agent:json-object "argv" #("true") "api_key" "not-accepted")
                        (agent:json-object "argv" #("true") "timeout_ms" 0)
                        (agent:json-object "argv" #("true") "output_limit" 2049)
                        (agent:json-object "argv" #("true") "input" (make-string 4097 :initial-element #\a))))
      (let ((session (new-session manager root extra)))
        (idle session)
        (ok (field (result session) "error"))
        (ok (zerop (length (field (agent:session-snapshot session) "decisions"))))))
    (ok (null (jobs:list-jobs registry)) "pure argument rejection cannot submit processes")
    (sb-posix:symlink (namestring base) (namestring (merge-pathnames "escape" root)))
    (dolist (cwd '("/" ".." "escape" "missing"))
      (let ((session (new-session manager root (arguments "printf forbidden" "cwd" cwd))))
        (allow session) (idle session)
        (ok (equal "rejected" (field (result session) "state")))
        (ok (equal "not-started" (field (result session) "outcome")))))
    (ok (null (jobs:list-jobs registry)) "outside and symlink-escape working directories never submit jobs")
    (let ((path (concatenate 'string (namestring root) "literal[*]?")))
      (sb-posix:mkdir path #o700)
      (let ((session (new-session manager root (arguments "pwd" "cwd" "literal[*]?"))))
        (allow session) (idle session)
        (ok (eq t (field (result session) "success")))
        (ok (equal path (string-right-trim '(#\Newline) (field (result session) "stdout"))))))))

(deftest nonzero-private-runtime-environment-and-bounded-binary-output
  (with-managers (manager registry root base)
    (let ((session (new-session manager root (arguments "printf failure >&2; exit 7"))))
      (allow session) (idle session)
      (ok (eq yason:false (field (result session) "success")))
      (ok (eql 7 (field (result session) "exit_code")))
      (ok (equal "completed" (field (result session) "outcome"))))
    (let ((session (new-session manager root
                                (arguments "cat; head -c 100000 /dev/zero; head -c 100000 /dev/zero >&2"
                                           "input" "public fixture stdin"))))
      (allow session) (idle session)
      (let ((result (result session)))
        (ok (eq t (field result "success")))
        (ok (> (field result "stdout_observed_bytes") 100000))
        (ok (= 100000 (field result "stderr_observed_bytes")))
        (ok (= 2048 (field result "stdout_retained_bytes")))
        (ok (eq t (field result "stdout_truncated")))
        (ok (eq t (field result "stderr_truncated")))
        (ok (< (lem-agent::encoded-size result) 32768)
            "worst-case NUL escaping remains a useful result inside the core budget")))
    (let ((saved (uiop:getenv "LEM_TEST_PROVIDER_API_KEY")))
      (unwind-protect
           (progn
             (sb-posix:setenv "LEM_TEST_PROVIDER_API_KEY" "fixture-never-inherit-provider-secret" 1)
             (let ((session (new-session manager root
                                         (arguments "printf '%s' \"${LEM_TEST_PROVIDER_API_KEY-unset}\""))))
               (allow session) (idle session)
               (ok (equal "unset" (field (result session) "stdout")))))
        (if saved (sb-posix:setenv "LEM_TEST_PROVIDER_API_KEY" saved 1)
            (sb-posix:unsetenv "LEM_TEST_PROVIDER_API_KEY"))))))

(defun running-p (pid)
  (let ((path (format nil "/proc/~d/stat" pid)))
    (when (probe-file path)
      (let* ((text (uiop:read-file-string path)) (end (position #\) text :from-end t)))
        (not (find (char text (+ end 2)) "ZX"))))))

(deftest timeout-kills-descendants-and-closing-a-view-preserves-jobs
  (with-managers (manager registry root base)
    (let* ((path (merge-pathnames "child.pid" root))
           (session (new-session manager root
                                 (arguments "sleep 30 & printf '%s' $! > child.pid; wait" "timeout_ms" 350))))
      (allow session) (idle session)
      (ok (equal "timed-out" (field (result session) "state")))
      (ok (equal "interrupted" (field (result session) "outcome")))
      (let ((pid (parse-integer (uiop:read-file-string path))))
        (ok (wait-for (lambda () (not (running-p pid)))))))
    (let* ((session (new-session manager root (arguments "sleep 0.4; printf view-survived")))
           (view (agent:subscribe-session session (lambda (event) (declare (ignore event))))))
      (allow session)
      (wait-for (lambda () (find "running" (jobs:list-jobs registry)
                                 :key (lambda (job) (field (jobs:job-snapshot job) "state")) :test #'equal)))
      (agent:unsubscribe-session session view)
      (ok (equal "running" (state session)))
      (idle session)
      (ok (equal "view-survived" (field (result session) "stdout")))
      (ok (eq t (field (result session) "success"))))))

(defstruct gate (lock (bt2:make-lock)) (condition (bt2:make-condition-variable)) open)
(defun open-gate (gate)
  (bt2:with-lock-held ((gate-lock gate))
    (setf (gate-open gate) t) (bt2:condition-broadcast (gate-condition gate))))
(defun wait-gate (gate)
  (bt2:with-lock-held ((gate-lock gate))
    (loop until (gate-open gate)
          do (unless (bt2:condition-wait (gate-condition gate) (gate-lock gate) :timeout 8)
               (error "Process launch gate timed out")))))

(deftest interruption-between-launch-and-cancellation-registration
  (with-managers (manager registry root base)
    (let ((original (symbol-function 'jobs:start-job)) (gate (make-gate)) (created nil))
      (unwind-protect
           (progn
             (setf (symbol-function 'jobs:start-job)
                   (lambda (&rest arguments)
                     (setf created (apply original arguments))
                     (wait-gate gate)
                     created))
             (let ((session (new-session manager root (arguments "sleep 30"))))
               (allow session)
               (wait-for (lambda () (and created (equal "running" (field (jobs:job-snapshot created) "state")))))
               (await (agent:interrupt-session session))
               (open-gate gate)
               (let ((result (jobs:wait-job created :timeout 10)))
                 (ok (equal "cancelled" (field result "state"))
                     "late cancellation registration cleans the already-created process"))
               (ok (equal "interrupted" (state session)))
               (ok (equal "unknown" (field (result session) "outcome")))
               (ok (not (field (result session) "success")) "late successful results cannot overwrite interruption")))
        (open-gate gate)
        (setf (symbol-function 'jobs:start-job) original)))))

(deftest failed-supervisor-reports-unknown-and-diagnostics-fit-the-budget
  (with-managers (manager registry root base)
    (let ((saved jobs:*guardian-path*))
      (unwind-protect
           (progn
             (setf jobs:*guardian-path* #p"/definitely/no/such/guardian.lisp")
             (let ((session (new-session manager root (arguments "printf never-launched"))))
               (allow session) (idle session)
               (ok (equal "failed" (field (result session) "state")))
               (ok (equal "unknown" (field (result session) "outcome")))
               (ok (eq yason:false (field (result session) "success")))
               (let* ((job (jobs:find-job (field (result session) "job_id") registry))
                      (snapshot (jobs:job-snapshot job)))
                 ;; Combine the maximum diagnostic fields with the stream's
                 ;; worst JSON expansion, not merely its ordinary printable form.
                 (setf (gethash "reason" snapshot) (make-string 4096 :initial-element #\Null)
                       (gethash "journal-error" snapshot) (make-string 4096 :initial-element #\Null)
                       (gethash "stdout" snapshot) (make-string 2048 :initial-element #\Null)
                       (gethash "stderr" snapshot) (make-string 2048 :initial-element #\Null))
                 (ok (< (lem-agent::encoded-size (process::process-result job snapshot)) 32768)))))
        (setf jobs:*guardian-path* saved)))
    (jobs:close-job-manager registry)
    (let ((session (new-session manager root (arguments "printf unavailable"))))
      (allow session) (idle session)
      (ok (equal "rejected" (field (result session) "state")))
      (ok (equal "not-started" (field (result session) "outcome"))))))
