(defpackage :lem-toolkit/jobs-ui
  (:use :cl :lem)
  (:local-nicknames (:jobs :lem-toolkit/jobs) (:store :lem-daemon/recovery-store))
  (:export :show-job :jobs-list :job-open :job-cancel :job-refresh))
(in-package :lem-toolkit/jobs-ui)

(defvar *job-buffers* (make-hash-table :test #'eq))
(defvar *refresh-timer* nil)

(define-major-mode managed-job-mode () (:name "Managed Job" :keymap *managed-job-keymap*))
(define-key *managed-job-keymap* "g" 'job-refresh)
(define-key *managed-job-keymap* "c" 'job-cancel)

(defun refresh-job-buffer (buffer job)
  (let ((snapshot (jobs:job-snapshot job)))
    (unless (equalp snapshot (buffer-value buffer 'last-job-snapshot))
      (let ((position (position-at-point (buffer-point buffer))))
        (with-buffer-read-only buffer nil
          (erase-buffer buffer)
          (insert-string
           (buffer-point buffer)
           (with-output-to-string (out)
             (format out "Job ~a~%State: ~a  Owner: ~a~%Directory: ~a~%Argv: ~s~%"
                     (store:field snapshot "id") (store:field snapshot "state")
                     (store:field snapshot "owner") (store:field snapshot "directory")
                     (store:field snapshot "argv"))
             (when (store:field snapshot "reason") (format out "Reason: ~a~%" (store:field snapshot "reason")))
             (when (store:field snapshot "journal-error")
               (format out "Journal failure: ~a~%" (store:field snapshot "journal-error")))
             (format out "Closing this buffer leaves the job running. Press c to cancel; g to refresh.~%")
             (dolist (channel '("stdout" "stderr"))
               (format out "~%~a (retained ~d of ~d bytes):~%~a"
                       channel (store:field snapshot (concatenate 'string channel "-retained-bytes"))
                       (store:field snapshot (concatenate 'string channel "-bytes"))
                       (store:field snapshot channel)))))
          (move-to-position (buffer-point buffer) (min position (position-at-point (buffer-end-point buffer))))
          (buffer-mark-saved buffer)))
      (setf (buffer-value buffer 'last-job-snapshot) snapshot))))

(defun refresh-visible-jobs ()
  (maphash (lambda (buffer job)
             (if (eq buffer (get-buffer (buffer-name buffer)))
                 (refresh-job-buffer buffer job)
                 (remhash buffer *job-buffers*)))
           *job-buffers*)
  (when (zerop (hash-table-count *job-buffers*))
    (stop-timer *refresh-timer*) (setf *refresh-timer* nil)))

(defun show-job (job)
  (let ((buffer (make-buffer (format nil "*Job ~a*" (jobs:job-id job)))))
    (setf (buffer-value buffer 'managed-job) job
          (buffer-directory buffer) (uiop:ensure-directory-pathname (jobs:job-directory job))
          (buffer-value buffer 'lem-daemon/recovery::recovery-exclude) t
          (gethash buffer *job-buffers*) job)
    (change-buffer-mode buffer 'managed-job-mode)
    (refresh-job-buffer buffer job)
    (setf (buffer-read-only-p buffer) t)
    (unless *refresh-timer*
      (setf *refresh-timer* (start-timer (make-idle-timer 'refresh-visible-jobs :name "managed job views")
                                        500 :repeat t)))
    (pop-to-buffer buffer)
    buffer))

(define-command job-refresh () ()
  (let ((job (buffer-value (current-buffer) 'managed-job)))
    (when job (refresh-job-buffer (current-buffer) job))))
(define-command job-cancel () ()
  (let ((job (buffer-value (current-buffer) 'managed-job)))
    (unless job (editor-error "This buffer does not display a managed job"))
    (jobs:cancel-job job)
    (message "Cancellation requested")))
(define-command job-open (id) ((:string "Job ID: "))
  (let ((job (jobs:find-job id)))
    (unless job (editor-error "Unknown job ID"))
    (show-job job)))
(define-command jobs-list () ()
  (let ((buffer (make-buffer "*Managed Jobs*")))
    (with-buffer-read-only buffer nil
      (erase-buffer buffer)
      (insert-string (buffer-point buffer)
                     (with-output-to-string (out)
                       (format out "Managed jobs. Use job-open with an ID.~%~%")
                       (dolist (job (jobs:list-jobs))
                         (let ((snapshot (jobs:job-snapshot job)))
                           (format out "~a  ~a  ~a~%  ~s~%"
                                   (store:field snapshot "id") (store:field snapshot "state")
                                   (store:field snapshot "owner") (store:field snapshot "argv"))))))
      (buffer-start (buffer-point buffer)) (buffer-mark-saved buffer))
    (setf (buffer-read-only-p buffer) t)
    (pop-to-buffer buffer)))
