;;;; Small bounded binary protocol shared by the controller and standalone SBCL guardian.
(defpackage :lem-toolkit/jobs-wire
  (:use :cl)
  (:export :read-frame :write-frame :encode-launch :decode-launch :utf8 :text))
(in-package :lem-toolkit/jobs-wire)

(defconstant +maximum-frame+ (* 4 1024 1024))
(defun utf8 (string) (sb-ext:string-to-octets string :external-format :utf-8))
(defun text (bytes) (sb-ext:octets-to-string bytes :external-format :utf-8))

(defun write-u32 (integer stream)
  (unless (typep integer '(unsigned-byte 32)) (error "Invalid jobs wire integer"))
  (loop for shift from 24 downto 0 by 8 do (write-byte (ldb (byte 8 shift) integer) stream)))
(defun read-u32 (stream)
  (loop repeat 4 for byte = (read-byte stream) for value = byte then (+ (ash value 8) byte)
        finally (return value)))

(defun write-frame (tag payload stream)
  (when (> (length payload) +maximum-frame+) (error "Jobs frame too large"))
  (write-byte (char-code tag) stream)
  (write-u32 (length payload) stream)
  (write-sequence payload stream)
  (finish-output stream))

(defun read-frame (stream)
  (let ((tag (read-byte stream nil)))
    (when tag
      (let ((size (read-u32 stream)))
        (when (> size +maximum-frame+) (error "Jobs frame too large"))
        (let ((bytes (make-array size :element-type '(unsigned-byte 8))))
          (unless (= size (read-sequence bytes stream)) (error "Truncated jobs frame"))
          (values (code-char tag) bytes))))))

(defun encode-launch (argv directory timeout-ms &optional (input #()) environment)
  (let ((bytes (make-array 128 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (labels ((u32 (n) (loop for shift from 24 downto 0 by 8 do (vector-push-extend (ldb (byte 8 shift) n) bytes)))
             (string-value (string)
               (let ((encoded (utf8 string)))
                 (u32 (length encoded))
                 (loop for byte across encoded do (vector-push-extend byte bytes)))))
      (u32 timeout-ms)
      (u32 (length argv))
      (dolist (argument argv) (string-value argument))
      (string-value directory)
      (u32 (length input))
      (loop for byte across input do (vector-push-extend byte bytes))
      (u32 (length environment))
      (dolist (entry environment) (string-value entry)))
    (when (> (length bytes) +maximum-frame+) (error "Job launch frame too large"))
    bytes))

(defun decode-launch (bytes)
  (let ((offset 0))
    (labels ((u32 ()
               (when (> (+ offset 4) (length bytes)) (error "Truncated launch frame"))
               (loop repeat 4 for n = (aref bytes offset)
                     for value = n then (+ (ash value 8) n)
                     do (incf offset) finally (return value)))
             (string-value ()
               (let ((size (u32)))
                 (unless (and (<= size 65536) (<= (+ offset size) (length bytes)))
                   (error "Invalid launch string length"))
                 (prog1 (text (subseq bytes offset (+ offset size))) (incf offset size)))))
      (let* ((timeout (u32)) (count (u32)))
        (unless (and (<= 1 count 128) (<= 1 timeout 86400000)) (error "Invalid launch limits"))
        (let* ((argv (loop repeat count collect (string-value))) (directory (string-value))
               (input-size (u32)))
          (unless (and (<= input-size (* 1024 1024)) (<= (+ offset input-size) (length bytes))
                       (plusp (length directory)) (char= (char directory 0) #\/)
                       (plusp (length (first argv)))
                       (notany (lambda (string) (find #\Null string)) (cons directory argv)))
            (error "Invalid launch values"))
          (let ((input (subseq bytes offset (+ offset input-size))))
            (incf offset input-size)
            (let ((count (u32)))
              (unless (<= count 4096) (error "Too many target environment entries"))
              (let ((environment (loop repeat count collect (string-value))))
                (unless (and (= offset (length bytes))
                             (<= (reduce #'+ environment :key (lambda (entry) (length (utf8 entry))) :initial-value 0)
                                 (* 1024 1024))
                             (every (lambda (entry) (let ((equal (position #\= entry)))
                                                     (and equal (plusp equal) (not (find #\Null entry))))) environment))
                  (error "Invalid target environment"))
                (values argv directory timeout input environment)))))))))
