(defpackage :lem-toolkit/tests/ui
  (:use :cl :rove)
  (:local-nicknames (:jobs :lem-toolkit/jobs) (:ui :lem-toolkit/jobs-ui)
                    (:store :lem-daemon/recovery-store)))
(in-package :lem-toolkit/tests/ui)

(defun wait-for (predicate &key (pump t))
  (loop repeat 1000 do (when pump (lem-core::receive-event 0))
        when (funcall predicate) return t do (sleep 0.005)
        finally (error "Job UI fixture timed out")))
(defun ready (buffer)
  (wait-for (lambda () (null (lem:buffer-value buffer 'ui::maintenance-request)))))
(defmacro with-ui ((manager directory job) &body body)
  `(let ((lem-core::*frames* nil) (lem-core::*display-frame-map* (make-hash-table)))
     (lem:with-current-buffers ()
       (let ((lem/buffer/internal::*current-buffer* (lem:primordial-buffer)))
         (lem-fake-interface:with-fake-interface ()
           (let* ((,directory (merge-pathnames (format nil "job-ui-~a/" (store:new-id)) (uiop:temporary-directory)))
                  (,manager (jobs:open-job-manager :directory ,directory))
                  (,job (jobs:start-job '("/run/current-system/sw/bin/printf" "reviewed") :manager ,manager)))
             (unwind-protect
                  (progn (jobs:wait-job ,job :timeout 10)
                         (wait-for (lambda () (jobs::job-settled-p ,job))) ,@body)
               (jobs:close-job-manager ,manager)
               (wait-for (lambda () (zerop ui::*maintenance-requests*)))
               (uiop:delete-directory-tree ,directory :validate t))))))))

(deftest journal-view-is-asynchronous-and-never-focuses-on-completion
  (with-ui (manager directory job)
    (let* ((original (lem:current-buffer)) (buffer (ui::show-journal manager (jobs:job-id job))))
      (ok (eq original (lem:current-buffer))) (ready buffer)
      (ok (search "reviewed" (lem:buffer-text buffer)))
      (ok (eq original (lem:current-buffer)) "I/O completion leaves the current view alone")
      (let ((inventory (lem:make-buffer "job inventory fixture")))
        (setf (lem:buffer-value inventory 'ui::journal-manager) manager)
        (ui::refresh-inventory inventory nil) (ready inventory)
        (ok (search "1 / 256 retained slots" (lem:buffer-text inventory)))
        (ok (search (jobs:job-id job) (lem:buffer-text inventory)))))))

(deftest explicit-discard-denial-and-exact-confirmed-cleanup
  (with-ui (manager directory job)
    (let ((buffer (ui::show-journal manager (jobs:job-id job))) (prompts nil))
      (ready buffer)
      (let ((ui::*confirm-journal-discard* (lambda (text) (push text prompts) nil)))
        (ui::discard-displayed-journal buffer))
      (ok (jobs:find-job (jobs:job-id job) manager))
      (ok (search "fingerprint" (first prompts)))
      (let ((ui::*confirm-journal-discard* (lambda (text) (declare (ignore text)) t)))
        (ui::discard-displayed-journal buffer))
      (ready buffer)
      (ok (not (jobs:find-job (jobs:job-id job) manager)))
      (ok (search "discarded" (lem:buffer-text buffer))))))

(deftest uncertain-history-requires-second-consent-and-stale-review-refuses
  (with-ui (manager directory job)
    (let* ((id (jobs:job-id job)) (record (store:read-private-json directory id)) (prompts 0))
      (setf (gethash "state" record) "interrupted") (store:write-private-json directory id record)
      (let ((buffer (ui::show-journal manager id)))
        (ready buffer)
        (let ((ui::*confirm-journal-discard* (lambda (text) (declare (ignore text)) (= 1 (incf prompts)))))
          (ui::discard-displayed-journal buffer))
        (ok (= 2 prompts)) (ok (jobs:find-job id manager))
        (setf prompts 0)
        (let ((ui::*confirm-journal-discard*
                (lambda (text)
                  (declare (ignore text))
                  (when (= 1 (incf prompts))
                    (setf (gethash "reason" record) "changed after human review")
                    (store:write-private-json directory id record))
                  t)))
          (ui::discard-displayed-journal buffer))
        (ready buffer)
        (ok (jobs:find-job id manager))
        (ok (search "changed" (lem:buffer-value buffer 'ui::maintenance-error)))))))

(deftest killed-view-and-enqueued-dispatch-failure-are-inert
  (with-ui (manager directory job)
    (let ((callback nil) (published nil) (buffer (lem:make-buffer "disposable job history")))
      (let ((ui::*maintenance-dispatch* (lambda (function) (setf callback function))))
        (ui::async-maintenance buffer (lambda () t) (lambda (&rest args) (declare (ignore args)) (setf published t))))
      (wait-for (lambda () callback) :pump nil)
      (lem:delete-buffer buffer)
      (funcall callback)
      (ok (not published)) (ok (zerop ui::*maintenance-requests*)))
    (let ((callback nil) (published nil) (buffer (lem:make-buffer "failed job history dispatch")))
      (let ((ui::*maintenance-dispatch* (lambda (function) (setf callback function) (error "Injected dispatch failure"))))
        (ui::async-maintenance buffer (lambda () t) (lambda (&rest args) (declare (ignore args)) (setf published t))))
      (wait-for (lambda () (and callback (zerop ui::*maintenance-requests*))) :pump nil)
      (funcall callback)
      (ok (not published))
      (ui::async-maintenance buffer (lambda () t) (lambda (&rest args) (declare (ignore args)) (setf published t)))
      (ready buffer) (ok published) (ok (zerop ui::*maintenance-requests*)))))

(deftest maintenance-request-budget-refuses-before-starting-another-worker
  (with-ui (manager directory job)
    (let ((callbacks nil) (lock (bt2:make-lock)) (buffers nil) (extra-work nil))
      (unwind-protect
           (let ((ui::*maintenance-dispatch*
                   (lambda (function) (bt2:with-lock-held (lock) (push function callbacks)))))
             (dotimes (i 8)
               (let ((buffer (lem:make-buffer (format nil "bounded job worker ~d" i))))
                 (push buffer buffers)
                 (ui::async-maintenance buffer (lambda () t) (lambda (&rest args) (declare (ignore args))))))
             (ok (signals (ui::async-maintenance (lem:make-buffer "refused worker")
                                                 (lambda () (setf extra-work t))
                                                 (lambda (&rest args) (declare (ignore args))))))
             (ok (not extra-work))
             (wait-for (lambda () (bt2:with-lock-held (lock) (= 8 (length callbacks)))) :pump nil))
        (dolist (buffer buffers) (lem:delete-buffer buffer))
        (dolist (callback callbacks) (funcall callback)))
      (ok (zerop ui::*maintenance-requests*)))))
