;;;; Assertions run on the configured daemon's editor thread; no provider calls.
(in-package :lem-yath)

(defun proposal-test-check (condition description)
  (assert condition () "~a" description)
  (format t "PASS: ~a~%" description))

(defun proposal-test-ready-rewrite (name)
  (let ((source (make-buffer name)))
    (switch-to-buffer source)
    (insert-string (buffer-point source) "before OLD after")
    (clear-buffer-edit-history source)
    (with-point ((start (buffer-start-point source)) (end (buffer-start-point source)))
      (character-offset start 7)
      (character-offset end 10)
      (let* ((proposal (lem-buffer-proposals:capture-region start end))
             (state (make-llm-rewrite-state
                     :id (incf *llm-rewrite-sequence*) :proposal proposal
                     :source-buffer source :start (copy-point start :right-inserting)
                     :end (copy-point end :left-inserting) :original "OLD"
                     :response "NEW" :instruction "Test fixture" :backend :fixture
                     :model "no-provider")))
        (lem-buffer-proposals:stage-replacement proposal "NEW")
        (setf (llm-rewrite-state-overlay state)
              (make-overlay start end 'llm-rewrite-ready-attribute))
        (push state (buffer-value source *llm-rewrite-states-key*))
        (llm-rewrite-show-preview state)
        (values source state proposal)))))

(defun run-buffer-proposal-acceptance-tests ()
  (assert (null lem-user::*lem-yath-boot-error*))
  (multiple-value-bind (source state proposal)
      (proposal-test-ready-rewrite "proposal-normal")
    (declare (ignore proposal))
    (lem-yath-llm-rewrite-accept)
    (proposal-test-check (and (string= "before NEW after" (buffer-text source))
                              (llm-rewrite-state-discarded-p state)
                              (null (llm-rewrite-states source)))
                         "configured rewrite acceptance edits and clears the pending overlay")
    (buffer-undo (buffer-point source))
    (proposal-test-check (string= "before OLD after" (buffer-text source))
                         "one undo restores the captured unsaved source"))
  (multiple-value-bind (source state proposal)
      (proposal-test-ready-rewrite "proposal-stale")
    (with-point ((point (buffer-start-point source)))
      (character-offset point 8)
      (insert-string point "human"))
    (let ((human (buffer-text source)) (tick (buffer-modified-tick source)))
      (proposal-test-check
       (handler-case (progn (lem-yath-llm-rewrite-accept) nil)
         (editor-error () t))
       "configured acceptance refuses a rewrite after a human touches its region")
      (proposal-test-check
       (and (string= human (buffer-text source)) (= tick (buffer-modified-tick source))
            (eq :conflict (lem-buffer-proposals:proposal-state proposal))
            (not (llm-rewrite-state-discarded-p state))
            (search (lem-buffer-proposals:proposal-current-text proposal)
                    (buffer-text (current-buffer)))
            (search "Captured original" (buffer-text (current-buffer)))
            (search "Proposed replacement" (buffer-text (current-buffer))))
       "conflict review preserves human text, original, replacement and pending decision")
      (lem-buffer-proposals::proposal-review-reject)
      (proposal-test-check
       (and (string= human (buffer-text source)) (= tick (buffer-modified-tick source))
            (llm-rewrite-state-discarded-p state) (null (llm-rewrite-states source)))
       "rejecting from shared review clears the rewrite overlay without editing source")))
  (multiple-value-bind (source state proposal)
      (proposal-test-ready-rewrite "proposal-outside")
    (declare (ignore state))
    (buffer-disable-undo-boundary source)
    (insert-string (buffer-start-point source) "human ")
    (lem-yath-llm-rewrite-accept)
    (proposal-test-check (string= "human before NEW after" (buffer-text source))
                         "tracked outside-region human edits remain when accepting a rewrite")
    (buffer-undo (buffer-point source))
    (proposal-test-check (string= "human before OLD after" (buffer-text source))
                         "proposal undo preserves an earlier open human insertion command")
    (proposal-test-check (= 13 (getf (lem-buffer-proposals:proposal-source-location proposal)
                                    :column))
                         "stable source links retain the accepted tracked location"))
  (multiple-value-bind (source state proposal)
      (proposal-test-ready-rewrite "proposal-generation")
    (declare (ignore state))
    (lem-buffer-proposals:show-proposal proposal)
    (lem-buffer-proposals:stage-replacement proposal "NEXT")
    (proposal-test-check
     (handler-case (progn (lem-buffer-proposals::proposal-review-accept) nil)
       (editor-error () t))
     "an old review cannot approve a newer candidate")
    (proposal-test-check (string= "before OLD after" (buffer-text source))
                         "candidate version conflict has no source edit")
    (lem-buffer-proposals::proposal-review-accept)
    (proposal-test-check (and (string= "before NEXT after" (buffer-text source))
                              (null (llm-rewrite-states source)))
                         "explicit acceptance of refreshed review uses the new candidate"))
  (proposal-test-check
   (bt2:join-thread
    (bt2:make-thread
     (lambda ()
       (handler-case (progn (lem-buffer-proposals:list-proposals) nil)
         (error () t)))
     :name "proposal-wrong-thread"))
   "native agents must queue live-buffer operations onto the editor thread")
  t)
