;;;; Test fixtures only. Product systems and configured managers must already exist.
;;;; No Quicklisp/ASDF loads, credentials, network transport, or runtime replacements.
(defpackage :lem-native-agent-fixture
  (:use :cl)
  (:local-nicknames (:agent :lem-agent) (:ui :lem-agent/ui)
                    (:jobs :lem-toolkit/jobs) (:proposals :lem-buffer-proposals)))
(in-package :lem-native-agent-fixture)

(defvar *root* nil)
(defvar *python* nil)
(defvar *gates* (make-hash-table :test 'equal))
(defvar *gate-lock* (bt2:make-lock :name "native fixture gates"))
(defstruct gate (lock (bt2:make-lock)) (wake (bt2:make-condition-variable)) open)

(defun field (object name) (gethash name object))
(defun json (value) (with-output-to-string (out) (yason:encode value out)))
(defun session (id)
  (or (agent:find-session ui:*default-manager* id) (error "Unknown fixture session")))
(defun snapshot (id) (agent:session-snapshot (session id)))
(defun pending (id)
  (find "pending" (field (snapshot id) "decisions")
        :key (lambda (item) (field item "status")) :test #'equal))
(defun task-message (request)
  (loop for message across (reverse (field request "messages"))
        when (equal "user" (field message "role")) return (field message "content")))
(defun call-tool (id name arguments)
  (agent:json-object "tool_calls" (vector (agent:json-object "id" id "name" name "arguments" arguments))))

(defun gate-for (id)
  (bt2:with-lock-held (*gate-lock*)
    (or (gethash id *gates*) (setf (gethash id *gates*) (make-gate)))))
(defun release-stream (id)
  (let ((gate (gate-for id)))
    (bt2:with-lock-held ((gate-lock gate))
      (setf (gate-open gate) t) (bt2:condition-broadcast (gate-wake gate))))
  t)
(defun wait-stream (context)
  (let* ((id (agent:operation-session-id context)) (gate (gate-for id)))
    (agent:register-cancellation context (lambda () (release-stream id)))
    (bt2:with-lock-held ((gate-lock gate))
      (loop until (gate-open gate)
            do (unless (bt2:condition-wait (gate-wake gate) (gate-lock gate) :timeout 90)
                 (error "Native fixture stream deadline exceeded"))))
    (agent:check-operation context)))

(defun provider (request emit context)
  (let* ((messages (field request "messages")) (last (aref messages (1- (length messages))))
         (task (task-message request)))
    (cond
      ((uiop:string-prefix-p "stream:" task)
       (funcall emit (format nil "~a stream λ" (subseq task 7)))
       (wait-stream context)
       (funcall emit " completed")
       (agent:json-object))
      ((uiop:string-prefix-p "complete:" task)
       (agent:json-object "content" (subseq task 9)))
      ((uiop:string-prefix-p "process:" task)
       (if (equal "tool" (field last "role"))
           (agent:json-object "content" "process round completed")
           (let* ((kind (subseq task 8))
                  (long (member kind '("long" "crash") :test #'equal)))
             (call-tool "process" "run_process"
                        (agent:json-object
                         "argv" (vector *python* (concatenate 'string *root* (if long "long.py" "once.py"))
                                        (concatenate 'string *root* kind))
                         "timeout_ms" 60000 "output_limit" 512)))))
      ((uiop:string-prefix-p "edit:" task)
       (cond
         ((not (equal "tool" (field last "role")))
          (call-tool "inspect" "read_file" (agent:json-object "path" "source.txt")))
         ((equal "read_file" (field last "name"))
          (let ((inspection (field last "content")))
            (call-tool "stage" "propose_edit"
                       (agent:json-object "path" "source.txt" "revision" (field inspection "revision")
                                          "original" (field inspection "content") "replacement" (subseq task 5)))))
         (t (agent:json-object "content" "edit proposal staged"))))
      (t (error "Unknown native fixture task")))))

(defun install (root python)
  (assert ui:*default-manager* () "Configured native agent manager is missing")
  (assert (jobs:job-manager-ready-p jobs:*default-manager*) () "Configured shared job manager is missing")
  ;; Inspection only: registration belongs to configured startup, not the fixture.
  (dolist (name '("list_directory" "read_file" "propose_edit" "run_process"))
    (assert (gethash name (agent::manager-tools ui:*default-manager*)) ()
            "Configured native tool is missing: ~a" name))
  (setf *root* root *python* python)
  (agent:register-provider ui:*default-manager* "native-acceptance-fake" #'provider)
  t)

(defun new-session ()
  (agent:session-id (agent:create-session ui:*default-manager* :provider "native-acceptance-fake"
                                         :model "fixture-no-network" :root *root*)))

(defun show (id kind)
  (let* ((session (session id))
         (buffer (ecase kind
                   (:transcript (ui:show-session session))
                   (:decisions (ui:show-decisions session))
                   (:composer (ui:show-composer session)))))
    (lem:switch-to-buffer buffer)
    (lem:redraw-display :force t)
    (lem:buffer-name buffer)))

(defun point-at-decision (buffer-name id)
  (let* ((buffer (lem:get-buffer buffer-name))
         (offset (search (format nil "Decision ~a" id) (lem:buffer-text buffer))))
    (assert offset () "The decision is not yet rendered")
    (lem:switch-to-buffer buffer)
    (lem:move-to-position (lem:current-point) (1+ offset))
    (lem:redraw-display :force t)
    t))

(defun tool-results (id name)
  (coerce (loop for turn across (field (snapshot id) "turns")
                append (loop for message across (field turn "messages")
                             when (and (equal "tool" (field message "role"))
                                       (equal name (field message "name")))
                               collect (field message "content"))) 'vector))

(defun session-jobs (id)
  (let ((prefix (format nil "agent:~a:" id)))
    (coerce (loop for job in (jobs:list-jobs)
                  when (uiop:string-prefix-p prefix (jobs:job-owner job))
                    collect (jobs:job-snapshot job)) 'vector)))

(defun journal-directories ()
  (agent:json-object "agents" (uiop:native-namestring (agent::manager-directory ui:*default-manager*))
                     "jobs" (uiop:native-namestring (jobs::manager-directory jobs:*default-manager*))))

(defun source-buffer () (lem:get-file-buffer (concatenate 'string *root* "source.txt")))
(defun prepare-source ()
  ;; Administrative fixture setup of a private file; subsequent edits use a PTY.
  (let ((buffer (lem:find-file-buffer (concatenate 'string *root* "source.txt"))))
    (lem:clear-buffer-edit-history buffer)
    (lem:erase-buffer buffer)
    (lem:insert-string (lem:buffer-point buffer) "human unsaved original")
    (lem:buffer-name buffer)))
(defun show-source (&optional (offset 0))
  (lem:switch-to-buffer (source-buffer))
  (lem:move-to-position (lem:current-point) (1+ offset))
  (lem:redraw-display :force t)
  t)
(defun show-proposal (id)
  (proposals:show-proposal (proposals:find-proposal id))
  (lem:redraw-display :force t)
  t)
