(in-package :lem-agent)

(defun json-object (&rest fields) (apply #'store:object fields))
(defun field (object name &optional default) (gethash name object default))
(defun (setf field) (value object name &optional default)
  (declare (ignore default)) (setf (gethash name object) value))

(defun json-copy (value &optional (budget (* 2 1024 1024)))
  "Copy bounded JSON data without retaining an adapter's mutable graph."
  (let ((nodes 0) (characters 0) (ancestors (make-hash-table :test 'eq)))
    (labels ((copy-value (value depth)
               (when (or (> depth 24) (> (incf nodes) 20000))
                 (error "JSON structure exceeds the agent budget"))
               (cond
                 ((stringp value)
                  (when (> (incf characters (length value)) budget)
                    (error "JSON text exceeds the agent budget"))
                  (copy-seq value))
                 ((or (null value) (eq value t)
                      (member value '(yason:false yason:true yason:null))) value)
                 ((and (integerp value) (< (integer-length value) 128)) value)
                 ((and (floatp value) (= value value) (< (abs value) 1d100)) value)
                 ((or (hash-table-p value) (vectorp value) (consp value))
                  (when (gethash value ancestors) (error "Cyclic JSON data"))
                  (setf (gethash value ancestors) t)
                  (unwind-protect
                       (if (hash-table-p value)
                           (let ((result (make-hash-table :test 'equal)))
                             (when (> (hash-table-count value) 128)
                               (error "JSON object has too many fields"))
                             (maphash
                              (lambda (key item)
                                (unless (and (stringp key) (<= (length key) 128))
                                  (error "Invalid JSON object key"))
                                (setf (gethash (copy-seq key) result)
                                      (copy-value item (1+ depth)))) value)
                             result)
                           (let ((length (if (vectorp value) (length value)
                                             (or (list-length value)
                                                 (error "Cyclic JSON array")))))
                             (when (> length 4096) (error "JSON array is too long"))
                             (map 'vector (lambda (item) (copy-value item (1+ depth))) value)))
                    (remhash value ancestors)))
                 (t (error "Value is not bounded JSON data")))))
      (copy-value value 0))))

(defun array-value (value)
  (unless (or (null value) (listp value) (and (vectorp value) (not (stringp value))))
    (error "Expected a JSON array"))
  (coerce value 'vector))

(defun text-p (value maximum &optional (minimum 0))
  (and (stringp value) (<= minimum (length value) maximum)))

(defun encoded-size (value)
  (length (babel:string-to-octets
           (with-output-to-string (stream) (yason:encode value stream)) :encoding :utf-8)))

(defparameter *default-limits*
  '("rounds" 8 "tools" 16 "stream" 65536 "arguments" 16384 "result" 32768
    "history" 524288 "turns" 16 "queued" 8 "message" 65536 "workers" 8))

(defun make-limits (overrides)
  (let ((limits (apply #'json-object *default-limits*)))
    (when overrides
      (maphash (lambda (key value)
                 (unless (and (gethash key limits) (integerp value)
                              (<= 1 value (gethash key limits)))
                   (error "Invalid agent limit: ~a" key))
                 (setf (gethash key limits) value)) overrides))
    limits))

(defstruct (receipt (:constructor make-receipt ()))
  (id (store:new-id)) (lock (bt2:make-lock :name "agent receipt"))
  (ready (bt2:make-condition-variable)) done value error)

(defun finish-receipt (receipt value &optional error)
  (when receipt
    (bt2:with-lock-held ((receipt-lock receipt))
      (unless (receipt-done receipt)
        (setf (receipt-done receipt) t (receipt-value receipt) value
              (receipt-error receipt) error)
        (bt2:condition-broadcast (receipt-ready receipt))))))

(defun await-request (receipt &key (timeout 10))
  "Worker-only wait; return VALUE,T or NIL,NIL on timeout."
  (let ((deadline (+ (get-internal-real-time) (* timeout internal-time-units-per-second))))
    (bt2:with-lock-held ((receipt-lock receipt))
      (loop until (receipt-done receipt)
            for remaining = (/ (- deadline (get-internal-real-time)) internal-time-units-per-second)
            do (unless (plusp remaining) (return-from await-request (values nil nil)))
               (bt2:condition-wait (receipt-ready receipt) (receipt-lock receipt) :timeout remaining))
      (when (receipt-error receipt) (error (receipt-error receipt)))
      (values (receipt-value receipt) t))))

(defstruct tool name schema validate execute permission)
(defstruct (manager (:constructor %make-manager))
  directory lease closed close-thread (lock (bt2:make-lock :name "agent manager"))
  (providers (make-hash-table :test 'equal)) (tools (make-hash-table :test 'equal))
  (session-table (make-hash-table :test 'equal)))

(defstruct (session (:constructor %make-session))
  manager id record (ready (make-receipt))
  (lock (bt2:make-lock :name "agent session")) (wake (bt2:make-condition-variable))
  queue tail (queue-count 0) thread cached-snapshot (generation 0) operation
  (subscribers (make-hash-table :test 'equal)) (workers '())
  interrupt-pending close-pending closed poisoned
  ;; The remaining fields belong exclusively to the actor.
  calls (call-index 0) waiting-decision pending-tool)

(defstruct (operation (:constructor %make-operation))
  session session-id turn-id generation root kind finished
  (text (make-array 0 :element-type 'character :adjustable t :fill-pointer 0))
  (published 0) delta-pending failure cancellation-callbacks (cancellation-count 0)
  late-reported)

(define-condition operation-cancelled (error) ())
(define-condition agent-budget-exceeded (error)
  ((message :initarg :message :reader budget-message))
  (:report (lambda (condition stream) (write-string (budget-message condition) stream))))

(defun budget-error (message) (error 'agent-budget-exceeded :message message))

(sb-alien:define-alien-routine ("flock" %flock) sb-alien:int
  (fd sb-alien:int) (operation sb-alien:int))

(defun acquire-lease (directory)
  (store:ensure-private-directory directory)
  (let* ((path (merge-pathnames ".manager.lock" directory))
         ;; Linux O_CLOEXEC closes the descriptor atomically across exec, including
         ;; subprocess launches concurrent with manager initialization.
         (fd (sb-posix:open (namestring path)
                            (logior sb-posix:o-rdwr sb-posix:o-creat sb-posix:o-nofollow #o2000000)
                            #o600)))
    (handler-case
        (progn
          (store::check-private-file-stat (sb-posix:fstat fd) path)
          (unless (zerop (%flock fd 6)) (error "An agent manager already owns ~a" directory))
          fd)
      (error (condition) (sb-posix:close fd) (error condition)))))

(defun make-manager (&key directory)
  "Blocking startup API: acquire exclusive ownership before any journal access."
  (unless (and directory (uiop:absolute-pathname-p directory))
    (error "Agent manager needs an absolute private journal directory"))
  (let* ((directory (uiop:ensure-directory-pathname directory))
         (lease (acquire-lease directory)))
    (handler-case (%make-manager :directory directory :lease lease)
      (error (condition) (sb-posix:close lease) (error condition)))))

(defun check-manager-open (manager)
  ;; Caller holds MANAGER-LOCK, including registration/attachment during close.
  (when (manager-closed manager) (error "Agent manager is closed")))

(defun manager-open-p (manager)
  "Check manager ownership without filesystem I/O."
  (and manager
       (bt2:with-lock-held ((manager-lock manager))
         (not (manager-closed manager)))))

(defun register-provider (manager name function)
  (unless (and (text-p name 128 1) (functionp function)) (error "Invalid provider registration"))
  (bt2:with-lock-held ((manager-lock manager))
    (check-manager-open manager)
    (setf (gethash (copy-seq name) (manager-providers manager)) function))
  name)

(defun register-tool (manager name &key schema validate execute permission)
  (unless (and (text-p name 128 1) (hash-table-p schema)
               (functionp validate) (functionp execute)
               (or (null permission) (eq permission t) (functionp permission)))
    (error "Tools require a JSON schema, validator, and Lisp executor"))
  (let ((tool (make-tool :name (copy-seq name) :schema (json-copy schema 16384)
                         :validate validate :execute execute :permission permission)))
    (bt2:with-lock-held ((manager-lock manager))
      (check-manager-open manager)
      (setf (gethash (copy-seq name) (manager-tools manager)) tool)))
  name)

(defun manager-sessions (manager)
  (bt2:with-lock-held ((manager-lock manager))
    (loop for session being the hash-values of (manager-session-table manager) collect session)))

(defun find-session (manager id)
  (bt2:with-lock-held ((manager-lock manager)) (gethash id (manager-session-table manager))))

(defun session-snapshot (session)
  (bt2:with-lock-held ((session-lock session)) (json-copy (session-cached-snapshot session))))

(defun subscribe-session (session callback)
  (check-type callback function)
  (let ((id (store:new-id)))
    (bt2:with-lock-held ((session-lock session))
      (setf (gethash id (session-subscribers session)) callback))
    id))

(defun unsubscribe-session (session id)
  (bt2:with-lock-held ((session-lock session)) (remhash id (session-subscribers session))))

(defun append-field (object name value)
  (setf (field object name) (concatenate 'vector (array-value (field object name)) (vector value))))

(defun diagnostic (session message)
  (let ((items (append-field (session-record session) "diagnostics" message)))
    (when (> (length items) 32)
      (setf (field (session-record session) "diagnostics") (subseq items (- (length items) 32))))))

(defun publish (session &optional event)
  (let ((snapshot (json-copy (session-record session))) (callbacks nil))
    (bt2:with-lock-held ((session-lock session))
      (setf (session-cached-snapshot session) snapshot
            callbacks (loop for callback being the hash-values of (session-subscribers session)
                            collect callback)))
    (when event
      (setf (field event "session_id") (session-id session))
      (dolist (callback callbacks)
        (handler-case (funcall callback (json-copy event))
          (error () (diagnostic session "A view subscriber failed; session execution continued")))))))

(defun checkpoint (session &optional event)
  (trim-history session)
  (when (> (encoded-size (session-record session)) (* 2 1024 1024))
    (error "Agent journal exceeds its retention budget"))
  (handler-case
      (store::write-private-json (manager-directory (session-manager session))
                                (session-id session) (session-record session) :maximum-depth 24)
    (error (condition) (setf (session-poisoned session) t) (error condition)))
  (publish session event))

(defun enqueue-locked (session event)
  (let ((entry (list event)))
    (if (session-tail session) (setf (cdr (session-tail session)) entry)
        (setf (session-queue session) entry))
    (setf (session-tail session) entry)
    (incf (session-queue-count session))
    (bt2:condition-notify (session-wake session))))

(defun enqueue-command (session kind &rest arguments)
  (let ((receipt (make-receipt)))
    (bt2:with-lock-held ((session-lock session))
      (if (or (session-closed session) (>= (session-queue-count session) 128))
          (finish-receipt receipt nil (make-condition 'simple-error
                                                    :format-control "Session is closed or its input queue is full"))
          (enqueue-locked session (list* kind receipt arguments))))
    receipt))

(defun submit-message (session text)
  (let ((maximum (field (field (session-record session) "limits") "message")))
    (unless (text-p text maximum 1) (error "Agent message exceeds its size limit")))
  (enqueue-command session :submit (store:new-id) (copy-seq text)))

(defun resolve-decision (session id answer)
  (unless (and (text-p id 64 1) (text-p answer 65536)) (error "Invalid decision response"))
  (enqueue-command session :resolve (copy-seq id) (copy-seq answer)))

(defun resume-session (session)
  "Deliberately process retained queued messages; never replay the interrupted turn."
  (enqueue-command session :resume))

(defun interrupt-session (session)
  (bt2:with-lock-held ((session-lock session))
    (when (session-closed session)
      (let ((receipt (make-receipt)))
        (finish-receipt receipt nil) (return-from interrupt-session receipt)))
    (or (session-interrupt-pending session)
        (let ((receipt (make-receipt)))
          ;; Invalidation happens before returning to the UI, not when the actor
          ;; eventually reaches the control message.
          (incf (session-generation session))
          (setf (session-interrupt-pending session) receipt)
          (enqueue-locked session (list :interrupt receipt))
          receipt))))

(defun close-session (session)
  (bt2:with-lock-held ((session-lock session))
    (or (session-close-pending session)
        (let ((receipt (make-receipt)))
          (incf (session-generation session))
          (setf (session-close-pending session) receipt (session-closed session) t)
          (enqueue-locked session (list :close receipt))
          receipt))))

(defun operation-live-locked-p (context)
  (let ((session (operation-session context)))
    (and (= (operation-generation context) (session-generation session))
         (eq context (session-operation session)) (not (session-closed session)))))

(defun operation-live-p (context)
  (bt2:with-lock-held ((session-lock (operation-session context)))
    (operation-live-locked-p context)))

(defun check-operation (context)
  (unless (operation-live-p context) (error 'operation-cancelled))
  t)

(defun call-with-agent-warnings (session function)
  (let ((reported nil))
    (handler-bind
        ((warning
           (lambda (condition)
             (unless reported
               (setf reported t)
               (if (eq (bt2:current-thread) (session-thread session))
                   (diagnostic session "Agent code emitted a warning; execution continued")
                   (bt2:with-lock-held ((session-lock session))
                     (unless (session-closed session)
                       (enqueue-locked session (list :diagnostic nil "Agent code emitted a warning; execution continued"))))))
             ;; BT2 remembers any escaping condition and makes JOIN fail even
             ;; for warnings. Record a bounded diagnostic and take WARN's restart.
             (muffle-warning condition))))
      (funcall function))))

(defun run-cancellation (context callback)
  (let* ((session (operation-session context))
         (worker
           (bt2:make-thread
            (lambda ()
              (handler-case (call-with-agent-warnings session callback)
                (error ()
                  (bt2:with-lock-held ((session-lock session))
                    (unless (session-closed session)
                      (enqueue-locked session (list :diagnostic nil "A cancellation callback failed")))))))
            :name "agent cancellation")))
    (bt2:with-lock-held ((session-lock session)) (push (cons worker nil) (session-workers session)))
    worker))

(defun register-cancellation (context callback)
  (check-type callback function)
  (let ((cancel-now nil))
    (bt2:with-lock-held ((session-lock (operation-session context)))
      (when (>= (operation-cancellation-count context) 16)
        (budget-error "Operation cancellation callback budget exhausted"))
      (incf (operation-cancellation-count context))
      (if (operation-live-locked-p context)
          (push callback (operation-cancellation-callbacks context))
          (setf cancel-now t)))
    (when cancel-now (run-cancellation context callback)))
  callback)

(defun cancel-operation (session &optional expected)
  (let ((context nil) (callbacks nil))
    (bt2:with-lock-held ((session-lock session))
      (when (and expected (not (operation-live-locked-p expected)))
        (return-from cancel-operation nil))
      (setf context (session-operation session) (session-operation session) nil)
      (when context
        (setf callbacks (operation-cancellation-callbacks context)
              (operation-cancellation-callbacks context) nil)))
    (dolist (callback callbacks) (run-cancellation context callback))
    context))

(defun report-late-locked (context)
  (let ((session (operation-session context)))
    (unless (or (operation-late-reported context) (session-closed session))
      (setf (operation-late-reported context) t)
      (enqueue-locked session (list :diagnostic nil "Discarded output from an interrupted operation")))))

(defun emit-text (context fragment)
  (let ((session (operation-session context)))
    (bt2:with-lock-held ((session-lock session))
      (unless (operation-live-locked-p context)
        (report-late-locked context) (return-from emit-text nil))
      (unless (and (stringp fragment)
                   (<= (+ (length fragment) (length (operation-text context)))
                       (field (field (session-record session) "limits") "stream")))
        (setf (operation-failure context) "Provider stream retention budget exceeded")
        (error "Provider stream exceeds its retention budget"))
      (loop for character across fragment do (vector-push-extend character (operation-text context)))
      ;; Coalesce notification objects; a provider emitting tiny fragments cannot
      ;; make an unbounded event queue while storage or a view is slow.
      (unless (operation-delta-pending context)
        (setf (operation-delta-pending context) t)
        (enqueue-locked session (list :delta nil context)))
      t)))

(defun operation-result (context kind value)
  (let ((session (operation-session context)))
    (bt2:with-lock-held ((session-lock session))
      ;; The adapter has returned before its result is queued. Its final thread
      ;; epilogue must not consume capacity needed by the next tool/provider.
      (setf (operation-finished context) t)
      (if (operation-live-locked-p context)
          (enqueue-locked session (if (operation-failure context)
                                     (list :operation-failed nil context (operation-failure context))
                                     (list kind nil context value)))
          (report-late-locked context)))))

(defun current-turn (session)
  (let ((record (session-record session)))
    (find (field record "active_turn") (array-value (field record "turns"))
          :key (lambda (turn) (field turn "id")) :test #'equal)))

(defun limit (session name) (field (field (session-record session) "limits") name))

(defgeneric operation-error-summary (condition)
  (:documentation "Return a bounded, credential-free diagnostic for a failed adapter.
Methods must perform no I/O and must not expose request bodies, headers, stderr,
or arbitrary condition arguments. The default reports only the condition type.")
  (:method ((condition t)) (format nil "~a" (type-of condition))))

(defun bounded-operation-error-summary (condition)
  (let ((summary (ignore-errors (operation-error-summary condition))))
    (if (and (stringp summary) (<= 1 (length summary) 512))
        summary
        (format nil "~a" (type-of condition)))))

(defun launch-operation (session kind function)
  (let* ((turn (current-turn session))
         (context (%make-operation :session session :session-id (session-id session)
                                   :turn-id (copy-seq (field turn "id"))
                                   :root (copy-seq (field (session-record session) "root"))
                                   :generation (field (session-record session) "generation") :kind kind)))
    (bt2:with-lock-held ((session-lock session))
      (unless (= (operation-generation context) (session-generation session))
        (return-from launch-operation nil))
      (setf (session-workers session)
            (remove-if-not (lambda (entry)
                             (and (bt2:thread-alive-p (car entry))
                                  (or (null (cdr entry)) (not (operation-finished (cdr entry))))))
                           (session-workers session)))
      (when (>= (length (session-workers session)) (limit session "workers"))
        (budget-error "Previous uncooperative operations still occupy the worker budget"))
      (setf (session-operation session) context))
    (let ((worker
            (bt2:make-thread
             (lambda ()
               (handler-case
                   (progn
                     (check-operation context)
                     (let ((result (json-copy (call-with-agent-warnings session (lambda () (funcall function context))))))
                       (operation-result context (if (eq kind :provider) :provider-done :tool-done) result)))
                 (operation-cancelled () (operation-result context :operation-failed "Operation interrupted"))
                 (error (condition)
                   ;; Adapter errors may contain credentials. Only explicit safe
                   ;; methods may supply more than the default condition type.
                   (operation-result context :operation-failed
                                     (format nil "~a failed (~a)" kind
                                             (bounded-operation-error-summary condition))))))
             :name (format nil "agent ~a" kind))))
      (bt2:with-lock-held ((session-lock session)) (push (cons worker context) (session-workers session))))
    context))

(defun trim-history (session)
  (let* ((record (session-record session)) (turns (array-value (field record "turns"))))
    (loop while (and (plusp (length turns))
                     (not (equal (field (aref turns 0) "id") (field record "active_turn")))
                     (or (> (length turns) (limit session "turns"))
                         (> (encoded-size turns) (limit session "history"))))
          do (setf turns (subseq turns 1)) (incf (field record "omitted_turns")))
    (setf (field record "turns") turns)
    ;; Decisions are retained with their complete turns; an omitted ID can never
    ;; be resolved again because it is no longer a pending decision.
    (setf (field record "decisions")
          (remove-if-not
           (lambda (decision)
             (find (field decision "turn_id") turns :key (lambda (turn) (field turn "id"))
                   :test #'equal))
           (array-value (field record "decisions"))))))

(defun append-message (session message)
  (let* ((turn (current-turn session))
         (messages (concatenate 'vector (array-value (field turn "messages")) (vector message))))
    (when (> (encoded-size messages) (limit session "history"))
      (budget-error "Current turn exceeded the history budget"))
    (setf (field turn "messages") messages)))

(defun finish-orphan-calls (turn reason)
  (let ((calls nil) (results (make-hash-table :test 'equal)))
    (loop for message across (array-value (field turn "messages"))
          do (when (equal "assistant" (field message "role"))
               (loop for call across (array-value (field message "tool_calls")) do (push call calls)))
             (when (equal "tool" (field message "role"))
               (setf (gethash (field message "tool_call_id") results) t)))
    (dolist (call (nreverse calls))
      (unless (gethash (field call "id") results)
        (append-field turn "messages"
                      (json-object "role" "tool" "tool_call_id" (field call "id")
                                   "name" (field call "name")
                                   "content" (json-object "error" reason "outcome"
                                                          (if (find (field call "id") (field turn "started_tools") :test #'equal)
                                                              "unknown" "not-started"))))))))

(defun end-active-turn (session status reason)
  (let* ((record (session-record session)) (turn (current-turn session)))
    (when turn
      (finish-orphan-calls turn reason)
      (setf (field turn "status") status)
      (loop for decision across (array-value (field record "decisions"))
            when (and (equal (field decision "turn_id") (field turn "id"))
                      (equal (field decision "status") "pending"))
              do (setf (field decision "status") "cancelled" (field decision "reason") reason)))
    (setf (field record "active_turn") nil (field record "status") status
          (field record "stream") "" (session-calls session) nil
          (session-waiting-decision session) nil (session-pending-tool session) nil)))

(defun preserve-interrupted-stream (session context)
  (let ((turn (current-turn session))
        (text (if context (coerce (operation-text context) 'simple-string)
                  (field (session-record session) "stream"))))
    (when (and turn (text-p text (limit session "stream") 1))
      (append-field turn "messages" (json-object "role" "assistant" "content" text
                                                 "tool_calls" #() "interrupted" t)))))

(defun stop-active (session status reason)
  (preserve-interrupted-stream session (cancel-operation session))
  (end-active-turn session status reason)
  (setf (field (session-record session) "generation") (session-generation session))
  (checkpoint session (json-object "type" status "reason" reason)))

(defun fail-session (session reason)
  (bt2:with-lock-held ((session-lock session)) (incf (session-generation session)))
  (preserve-interrupted-stream session (cancel-operation session))
  (end-active-turn session "failed" reason)
  (diagnostic session reason)
  (setf (field (session-record session) "generation") (session-generation session))
  (if (session-poisoned session)
      (progn
        (setf (field (session-record session) "durability") "failed")
        (publish session (json-object "type" "failed" "reason" "Journal durability failed; reload before continuing")))
      (checkpoint session (json-object "type" "failed" "reason" reason))))

(defun provider-request (session)
  (let ((messages '()) (schemas '()) (record (session-record session)))
    (when (plusp (field record "omitted_turns"))
      (push (json-object "role" "system" "content"
                         (format nil "~d complete earlier turns omitted by the history budget."
                                 (field record "omitted_turns"))) messages))
    (loop for turn across (array-value (field record "turns"))
          do (loop for message across (array-value (field turn "messages")) do (push message messages)))
    (bt2:with-lock-held ((manager-lock (session-manager session)))
      (maphash (lambda (name tool)
                 (push (json-object "name" name "schema" (tool-schema tool)) schemas))
               (manager-tools (session-manager session))))
    (json-copy (json-object "model" (field record "model")
                            "messages" (coerce (nreverse messages) 'vector)
                            "tools" (coerce (nreverse schemas) 'vector)))))

(defun begin-provider-round (session)
  (let* ((turn (current-turn session)) (manager (session-manager session))
         (provider (bt2:with-lock-held ((manager-lock manager))
                     (gethash (field (session-record session) "provider") (manager-providers manager)))))
    (unless provider (error "No adapter is registered for this session's provider"))
    (when (>= (field turn "rounds") (limit session "rounds")) (budget-error "Agent round budget exhausted"))
    (incf (field turn "rounds"))
    (setf (field (session-record session) "status") "running"
          (field (session-record session) "stream") "")
    (checkpoint session (json-object "type" "round_started" "turn_id" (field turn "id")))
    (let ((request (provider-request session)))
      (launch-operation session :provider
                        (lambda (context) (funcall provider request
                                                   (lambda (fragment) (emit-text context fragment)) context))))))

(defun start-next-turn (session)
  (let* ((record (session-record session)) (queue (array-value (field record "queue"))))
    (when (and (null (current-turn session)) (plusp (length queue))
               (= (field record "generation") (session-generation session))
               (equal (field record "status") "idle"))
      (let* ((message (aref queue 0))
             (turn (json-object "id" (store:new-id) "status" "running" "rounds" 0 "tools" 0
                                "call_ids" #() "messages"
                                (vector (json-object "role" "user" "content" (field message "text"))))))
        (let ((generation
                (bt2:with-lock-held ((session-lock session))
                  (unless (= (field record "generation") (session-generation session))
                    (return-from start-next-turn nil))
                  (incf (session-generation session)))))
          (setf (field record "generation") generation
                (field record "status") "running"
                (field record "queue") (subseq queue 1)
                (field record "active_turn") (field turn "id"))
          (append-field record "turns" turn)
          (checkpoint session (json-object "type" "turn_started" "turn_id" (field turn "id")
                                           "message_id" (field message "id")))
          (begin-provider-round session))))))

(defun finish-turn (session)
  (end-active-turn session "completed" "Turn completed")
  (setf (field (session-record session) "status") "idle")
  (checkpoint session (json-object "type" "turn_completed"))
  (start-next-turn session))

(defun normalized-call (session value)
  (let ((failure nil) (id nil) (name nil) (arguments nil) (turn (current-turn session)))
    (if (hash-table-p value)
        (setf id (field value "id") name (field value "name") arguments (field value "arguments"))
        (setf failure "Malformed tool call"))
    (unless (and (text-p id 128 1)
                 (not (find id (array-value (field turn "call_ids")) :test #'equal)))
      (setf id (store:new-id) failure "Missing or duplicate tool call identifier"))
    (unless (text-p name 128 1) (setf name "invalid" failure "Invalid tool name"))
    (unless (and (hash-table-p arguments) (<= (encoded-size arguments) (limit session "arguments")))
      (setf arguments (json-object) failure "Tool arguments must be a bounded JSON object"))
    (append-field turn "call_ids" id)
    (json-object "id" id "name" name "arguments" arguments "validation_error" failure)))

(defun create-decision (session kind question &key choices call)
  (unless (and (text-p question 8192 1)
               (every (lambda (choice) (text-p choice 4096 1)) (array-value choices))
               (<= (length (array-value choices)) 32))
    (error "Malformed clarification or permission question"))
  (let ((decision (json-object "id" (store:new-id) "turn_id" (field (current-turn session) "id")
                               "generation" (field (session-record session) "generation") "kind" kind
                               "status" "pending" "question" question "choices" (array-value choices)
                               "tool" (and call (field call "name"))
                               "call_id" (and call (field call "id"))
                               "arguments" (and call (field call "arguments")))))
    (when (> (encoded-size decision) 32768) (budget-error "Decision record exceeds its size budget"))
    (append-field (session-record session) "decisions" decision)
    (setf (session-waiting-decision session) (field decision "id")
          (field (session-record session) "status") "waiting")
    (checkpoint session (json-object "type" "decision_requested" "decision" decision))
    decision))

(defun tool-result (session result)
  (let ((call (aref (session-calls session) (session-call-index session))))
    (when (> (encoded-size result) (limit session "result"))
      (setf result (json-object "error" "Tool output omitted: result retention budget exceeded")))
    (append-message session (json-object "role" "tool" "tool_call_id" (field call "id")
                                         "name" (field call "name") "content" result))
    (checkpoint session (json-object "type" "tool_completed" "call_id" (field call "id") "result" result))
    (incf (session-call-index session))
    (setf (session-pending-tool session) nil)
    (advance-tools session)))

(defun execute-pending-tool (session)
  (let* ((call (aref (session-calls session) (session-call-index session)))
         (tool (session-pending-tool session))
         (arguments (json-copy (field call "arguments"))))
    (setf (field (session-record session) "status") "running")
    (append-field (current-turn session) "started_tools" (field call "id"))
    (checkpoint session (json-object "type" "tool_started" "call_id" (field call "id")
                                     "name" (field call "name")))
    (launch-operation session :tool (lambda (context) (funcall (tool-execute tool) arguments context)))))

(defun advance-tools (session)
  (if (>= (session-call-index session) (length (session-calls session)))
      (progn (setf (session-calls session) nil) (begin-provider-round session))
      (let* ((call (aref (session-calls session) (session-call-index session)))
             (tool (bt2:with-lock-held ((manager-lock (session-manager session)))
                     (gethash (field call "name") (manager-tools (session-manager session))))))
        (cond
          ((field call "validation_error")
           (tool-result session (json-object "error" (field call "validation_error"))))
          ((null tool) (tool-result session (json-object "error" "Unknown registered tool")))
          ((not (handler-case (funcall (tool-validate tool) (json-copy (field call "arguments")))
                  (error () nil)))
           (tool-result session (json-object "error" "Tool argument validation failed")))
          (t
           (setf (session-pending-tool session) tool)
           (let ((permission (tool-permission tool)))
             (if permission
                 (create-decision session "permission"
                                  (if (functionp permission) (funcall permission (json-copy (field call "arguments")))
                                      (format nil "Allow ~a with the recorded arguments?" (field call "name")))
                                  :choices #("allow" "deny") :call call)
                 (execute-pending-tool session))))))))

(defun handle-provider-result (session context result)
  (unless (hash-table-p result) (error "Provider response must be a JSON object"))
  (let* ((stream (coerce (operation-text context) 'simple-string))
         (content (field result "content" stream))
         (calls (array-value (field result "tool_calls")))
         (clarification (field result "clarification")))
    (unless (text-p content (limit session "stream")) (error "Provider response content exceeds budget"))
    (when (and (plusp (length stream)) (not (equal stream content)))
      (error "Final provider content disagrees with its stream"))
    (when (> (+ (field (current-turn session) "tools") (length calls)) (limit session "tools"))
      (budget-error "Agent tool-call budget exhausted"))
    (when (and clarification (plusp (length calls)))
      (error "Provider cannot mix clarification and tool calls"))
    (let ((normalized (map 'vector (lambda (call) (normalized-call session call)) calls)))
      (append-message session (json-object "role" "assistant" "content" content "tool_calls" normalized))
      (setf (field (session-record session) "stream") "")
      (incf (field (current-turn session) "tools") (length calls))
      (checkpoint session (json-object "type" "assistant_completed" "text" content))
      (cond
        (clarification
         (unless (hash-table-p clarification) (error "Malformed clarification"))
         (create-decision session "clarification" (field clarification "question")
                          :choices (field clarification "choices")))
        ((plusp (length normalized))
         (setf (session-calls session) normalized (session-call-index session) 0)
         (advance-tools session))
        (t (finish-turn session))))))

(define-condition request-rejected (error)
  ((message :initarg :message :reader rejection-message))
  (:report (lambda (condition stream) (write-string (rejection-message condition) stream))))

(defun reject (message) (error 'request-rejected :message message))

(defun handle-resolution (session receipt id answer)
  (let* ((record (session-record session))
         (decision (find id (array-value (field record "decisions"))
                         :key (lambda (decision) (field decision "id")) :test #'equal)))
    (unless (and decision (equal (field decision "status") "pending")
                 (= (field decision "generation") (session-generation session))
                 (equal id (session-waiting-decision session)))
      (finish-receipt receipt nil) (return-from handle-resolution))
    (let ((choices (array-value (field decision "choices"))))
      (when (and (plusp (length choices)) (not (find answer choices :test #'equal)))
        (reject "Answer is not one of this decision's choices")))
    (setf (field decision "status") "resolved" (field decision "answer") answer)
    ;; This write must succeed before an approval or clarification can advance
    ;; the loop. On uncertain durability the actor is poisoned, never retried.
    (checkpoint session (json-object "type" "decision_resolved" "decision" decision))
    (finish-receipt receipt t)
    (setf (session-waiting-decision session) nil)
    (if (equal (field decision "kind") "permission")
        (if (equal answer "allow") (execute-pending-tool session)
            (tool-result session (json-object "error" "Permission denied")))
        (progn
          (append-message session (json-object "role" "user" "content" answer))
          (begin-provider-round session)))))

(defun handle-delta (session context)
  (let ((fragment nil) (text nil))
    (bt2:with-lock-held ((session-lock session))
      (unless (operation-live-locked-p context) (return-from handle-delta))
      (setf fragment (subseq (operation-text context) (operation-published context))
            text (coerce (operation-text context) 'simple-string)
            (operation-published context) (length text)
            (operation-delta-pending context) nil))
    (setf (field (session-record session) "stream") text)
    ;; Stream fragments are live view state; final/error/interrupt checkpoints
    ;; persist them. Permission and tool boundaries always use durable writes.
    (publish session (json-object "type" "assistant_text_delta" "text" fragment))))

(defun take-operation (session context)
  (bt2:with-lock-held ((session-lock session))
    (when (operation-live-locked-p context)
      (setf (session-operation session) nil)
      t)))

(defun process-event (session event)
  (destructuring-bind (kind receipt &rest arguments) event
    (when (and (session-poisoned session) (member kind '(:submit :resolve :resume)))
      (reject "Journal durability failed; reload this session before continuing"))
    (case kind
      (:initialize (checkpoint session (json-object "type" "session_ready"))
                   (finish-receipt receipt (session-id session)))
      (:submit
       (destructuring-bind (id text) arguments
         (when (equal (field (session-record session) "status") "closed")
           (reject "Session is closed"))
         (when (>= (length (array-value (field (session-record session) "queue"))) (limit session "queued"))
           (reject "Session follow-up queue is full"))
         (append-field (session-record session) "queue" (json-object "id" id "text" text))
         (when (member (field (session-record session) "status") '("failed" "interrupted") :test #'equal)
           (setf (field (session-record session) "status") "idle"))
         (checkpoint session (json-object "type" "message_queued" "message_id" id))
         (finish-receipt receipt id)
         (start-next-turn session)))
      (:resolve (apply #'handle-resolution session receipt arguments))
      (:resume
       (when (equal (field (session-record session) "status") "closed") (reject "Session is closed"))
       (unless (current-turn session)
         (setf (field (session-record session) "status") "idle")
         (checkpoint session (json-object "type" "session_resumed"))
         (start-next-turn session))
       (finish-receipt receipt t))
      (:interrupt
       (unless (equal (field (session-record session) "status") "closed")
         (stop-active session "interrupted" "user-interrupted"))
       (bt2:with-lock-held ((session-lock session)) (setf (session-interrupt-pending session) nil))
       (finish-receipt receipt t))
      (:close (stop-active session "closed" "session-closed") (finish-receipt receipt t))
      (:diagnostic (diagnostic session (first arguments)) (checkpoint session))
      (:delta (handle-delta session (first arguments)))
      (:provider-done
       (destructuring-bind (context result) arguments
         (when (take-operation session context) (handle-provider-result session context result))))
      (:tool-done
       (destructuring-bind (context result) arguments
         (when (take-operation session context) (tool-result session result))))
      (:operation-failed
       (destructuring-bind (context reason) arguments
         ;; Keep the failed context available until its registered resource
         ;; cleanup has been scheduled. A successful return relinquishes it;
         ;; an error or exhausted stream budget must cancel owned requests/jobs.
         (when (cancel-operation session context)
           (if (eq (operation-kind context) :tool)
               (tool-result session (json-object "error" reason))
               (fail-session session reason)))))
      (t (error "Unknown internal session event")))))

(defun actor-loop (session)
  (loop
    (let ((event
            (bt2:with-lock-held ((session-lock session))
              (loop while (null (session-queue session))
                    do (bt2:condition-wait (session-wake session) (session-lock session)))
              (prog1 (pop (session-queue session))
                (decf (session-queue-count session))
                (unless (session-queue session) (setf (session-tail session) nil))))))
      (handler-case (process-event session event)
        (request-rejected (condition) (finish-receipt (second event) nil condition))
        (error (condition)
          (finish-receipt (second event) nil condition)
          (handler-case (fail-session session (if (typep condition 'agent-budget-exceeded)
                                                 (budget-message condition)
                                                 (format nil "Session stopped (~a)" (type-of condition))))
            (error ()
              (setf (session-poisoned session) t)
              (publish session (json-object "type" "failed" "reason" "Journal could not be updated"))))))
      (when (eq (first event) :close)
        (bt2:with-lock-held ((session-lock session))
          (dolist (pending (session-queue session))
            (finish-receipt (second pending) nil (make-condition 'request-rejected :message "Session closed")))
          (setf (session-queue session) nil (session-tail session) nil (session-queue-count session) 0))
        (return)))))

(defun attach-session (manager record)
  (let ((session (%make-session :manager manager :id (field record "id") :record record
                                :generation (field record "generation")
                                :cached-snapshot (json-copy record))))
    (bt2:with-lock-held ((manager-lock manager))
      (check-manager-open manager)
      (when (gethash (session-id session) (manager-session-table manager))
        (error "Session identifier is already loaded"))
      (bt2:with-lock-held ((session-lock session))
        (enqueue-locked session (list :initialize (session-ready session))))
      (setf (session-thread session)
            (bt2:make-thread (lambda () (call-with-agent-warnings session (lambda () (actor-loop session))))
                             :name "agent session actor")
            (gethash (session-id session) (manager-session-table manager)) session))
    session))

(defun create-session (manager &key provider model root limits)
  (unless (and (text-p provider 128 1) (text-p model 256 1)
               (text-p (and root (uiop:native-namestring root)) 8192 1)
               (uiop:absolute-pathname-p root))
    (error "Session requires a provider name, model name, and absolute project root"))
  (attach-session manager
                  (json-object "version" 1 "id" (store:new-id) "provider" (copy-seq provider)
                               "model" (copy-seq model) "root" (uiop:native-namestring root)
                               "status" "idle" "generation" 0 "limits" (make-limits limits)
                               "turns" #() "queue" #() "decisions" #() "diagnostics" #()
                               "active_turn" nil "stream" "" "omitted_turns" 0)))

(defun valid-id-p (id)
  (and (text-p id 32 32) (every (lambda (character) (find character "0123456789abcdef")) id)))

(defun journal-array (object name maximum)
  (let ((items (array-value (field object name))))
    (when (> (length items) maximum) (error "Journal array exceeds its schema budget"))
    (setf (field object name) items)))

(defun remember-journal-id (table id &optional (external nil))
  (unless (and (if external (text-p id 128 1) (valid-id-p id)) (not (gethash id table)))
    (error "Invalid or duplicate journal identifier"))
  (setf (gethash id table) t))

(defun validate-restored-turn (turn active-id limits)
  (unless (and (hash-table-p turn) (valid-id-p (field turn "id"))
               (typep (field turn "rounds") '(integer 0))
               (<= (field turn "rounds") (field limits "rounds"))
               (typep (field turn "tools") '(integer 0))
               (<= (field turn "tools") (field limits "tools"))
               (member (field turn "status") '("running" "completed" "interrupted" "failed" "closed") :test #'equal)
               (eq (equal (field turn "id") active-id) (equal (field turn "status") "running")))
    (error "Invalid turn journal schema"))
  (let ((calls (make-hash-table :test 'equal)) (results (make-hash-table :test 'equal))
        (declared (make-hash-table :test 'equal)) (started (make-hash-table :test 'equal)))
    (loop for id across (journal-array turn "call_ids" (field limits "tools"))
          do (remember-journal-id declared id t))
    (loop for message across (journal-array turn "messages" 128)
          do (unless (and (hash-table-p message)
                          (member (field message "role") '("user" "assistant" "tool") :test #'equal))
               (error "Invalid journal message"))
             (cond
               ((equal "assistant" (field message "role"))
                (unless (text-p (field message "content") (field limits "stream"))
                  (error "Invalid assistant journal text"))
                (loop for call across (journal-array message "tool_calls" (field limits "tools"))
                      do (unless (and (hash-table-p call) (text-p (field call "name") 128 1)
                                      (hash-table-p (field call "arguments"))
                                      (<= (encoded-size (field call "arguments")) (field limits "arguments"))
                                      (gethash (field call "id") declared)
                                      (or (null (field call "validation_error"))
                                          (text-p (field call "validation_error") 256 1)))
                           (error "Invalid journal tool call"))
                         (remember-journal-id calls (field call "id") t)
                         (setf (gethash (field call "id") calls) (field call "name"))))
               ((equal "tool" (field message "role"))
                (let ((id (field message "tool_call_id")))
                  (unless (and (gethash id calls) (equal (field message "name") (gethash id calls)))
                    (error "Tool result does not match an earlier call"))
                  (remember-journal-id results id t)))
               ((not (text-p (field message "content") 65536))
                (error "Invalid user journal text"))))
    (loop for id across (journal-array turn "started_tools" (field limits "tools"))
          do (unless (gethash id calls) (error "Unknown started tool"))
             (remember-journal-id started id t))
    (unless (or (equal (field turn "id") active-id)
                (= (hash-table-count calls) (hash-table-count results)))
      (error "Finished journal turn has an unmatched tool call"))))

(defun validate-restored-record (id object)
  (let* ((record (json-copy object)) (turns (make-hash-table :test 'equal))
         (decisions (make-hash-table :test 'equal)) (queued (make-hash-table :test 'equal))
         (pending 0))
    (unless (and (hash-table-p record) (eql 1 (field record "version"))
                 (valid-id-p id) (equal id (field record "id"))
                 (text-p (field record "provider") 128 1) (text-p (field record "model") 256 1)
                 (text-p (field record "root") 8192 1) (uiop:absolute-pathname-p (field record "root"))
                 (typep (field record "generation") '(integer 0))
                 (typep (field record "omitted_turns") '(integer 0))
                 (member (field record "status") '("idle" "running" "waiting" "interrupted" "failed" "closed") :test #'equal)
                 (hash-table-p (field record "limits")))
      (error "Invalid agent session journal schema"))
    (setf (field record "limits") (make-limits (field record "limits")))
    (let ((limits (field record "limits")) (active (field record "active_turn")))
      (unless (and (or (null active) (valid-id-p active))
                   (eq (not (null active))
                       (not (null (member (field record "status") '("running" "waiting") :test #'equal))))
                   (text-p (field record "stream") (field limits "stream")))
        (error "Inconsistent journal lifecycle"))
      (loop for turn across (journal-array record "turns" (field limits "turns"))
            do (validate-restored-turn turn active limits)
               (remember-journal-id turns (field turn "id"))
               (setf (gethash (field turn "id") turns) turn))
      (when (and active (or (not (gethash active turns))
                            (not (equal active (field (aref (field record "turns")
                                                           (1- (length (field record "turns")))) "id")))))
        (error "Active journal turn is missing or out of order"))
      (loop for decision across (journal-array record "decisions" (* (field limits "turns")
                                                                      (+ (field limits "tools") (field limits "rounds"))))
            do (unless (and (hash-table-p decision) (gethash (field decision "turn_id") turns)
                            (typep (field decision "generation") '(integer 0))
                            (<= (field decision "generation") (field record "generation"))
                            (member (field decision "kind") '("permission" "clarification") :test #'equal)
                            (member (field decision "status") '("pending" "resolved" "cancelled") :test #'equal)
                            (text-p (field decision "question") 8192 1)
                            (every (lambda (choice) (text-p choice 4096 1)) (journal-array decision "choices" 32)))
                 (error "Invalid journal decision"))
               (remember-journal-id decisions (field decision "id"))
               (if (equal (field decision "kind") "permission")
                   (let ((call
                           (loop for message across (field (gethash (field decision "turn_id") turns) "messages")
                                 thereis (find (field decision "call_id") (field message "tool_calls")
                                               :key (lambda (call) (field call "id")) :test #'equal))))
                     (unless (and call (equalp (field decision "choices") #("allow" "deny"))
                                  (equal (field decision "tool") (field call "name"))
                                  (equalp (field decision "arguments") (field call "arguments")))
                       (error "Permission journal decision does not match its concrete tool call")))
                   (unless (and (null (field decision "tool")) (null (field decision "arguments"))
                                (null (field decision "call_id")))
                     (error "Clarification journal decision contains tool authority")))
               (cond
                 ((equal (field decision "status") "pending")
                  (unless (and (= (incf pending) 1) (equal (field decision "turn_id") active)
                               (= (field decision "generation") (field record "generation"))
                               (equal (field record "status") "waiting") (null (field decision "answer")))
                    (error "Pending decision does not match the active turn")))
                 ((equal (field decision "status") "resolved")
                  (unless (and (text-p (field decision "answer") 65536)
                               (or (zerop (length (field decision "choices")))
                                   (find (field decision "answer") (field decision "choices") :test #'equal)))
                    (error "Invalid resolved journal decision")))
                 ((not (text-p (field decision "reason") 512 1))
                  (error "Cancelled journal decision has no reason"))))
      (loop for message across (journal-array record "queue" (field limits "queued"))
            do (unless (and (hash-table-p message) (text-p (field message "text") (field limits "message") 1))
                 (error "Invalid queued message"))
               (remember-journal-id queued (field message "id")))
      (unless (every (lambda (text) (text-p text 512 1)) (journal-array record "diagnostics" 32))
        (error "Invalid journal diagnostic")))
    record))

(defun restore-sessions (manager)
  "Blocking worker API. Load journals; never restart their prior operations."
  (bt2:with-lock-held ((manager-lock manager)) (check-manager-open manager))
  (multiple-value-bind (records errors)
      (store::list-private-json (manager-directory manager) :maximum-depth 24)
    (let ((sessions '()) (failures errors))
      (dolist (entry records)
        (handler-case
            (let* ((record (validate-restored-record (car entry) (cdr entry)))
                   (prior-active (field record "active_turn")))
              (when (find-session manager (car entry)) (error "Session is already loaded"))
              (when (or prior-active (member (field record "status") '("running" "waiting") :test #'equal))
                (loop for turn across (field record "turns")
                      when (equal (field turn "id") prior-active)
                        do (finish-orphan-calls turn "daemon-interrupted; external outcome unknown; not replayed")
                           (setf (field turn "status") "interrupted"))
                (loop for decision across (field record "decisions")
                      when (equal (field decision "status") "pending")
                        do (setf (field decision "status") "cancelled" (field decision "reason") "daemon-interrupted"))
                (setf (field record "status") "interrupted" (field record "active_turn") nil))
              (incf (field record "generation"))
              (setf (field record "stream") "")
              (push (attach-session manager record) sessions))
          (error (condition) (push (cons (car entry) (format nil "Invalid agent journal (~a)" (type-of condition))) failures))))
      (values (nreverse sessions) failures))))

(defun close-manager (manager &key (wait nil))
  "Close sessions asynchronously. WAIT is a blocking supervisor API.
The directory lease survives until all journal-writing actors have stopped."
  (let ((thread nil) (receipts nil))
    (bt2:with-lock-held ((manager-lock manager))
      (setf (manager-closed manager) t)
      (let ((sessions (loop for session being the hash-values of (manager-session-table manager)
                            collect session)))
        (setf receipts (mapcar #'close-session sessions))
        (unless (manager-close-thread manager)
          (setf (manager-close-thread manager)
                (bt2:make-thread
                 (lambda ()
                   ;; Never release ownership while an actor can still write,
                   ;; even if its close receipt reports a durability failure.
                   (dolist (session sessions) (bt2:join-thread (session-thread session)))
                   (bt2:with-lock-held ((manager-lock manager))
                     (when (manager-lease manager)
                       (sb-posix:close (manager-lease manager))
                       (setf (manager-lease manager) nil))))
                 :name "agent manager close")))
        (setf thread (manager-close-thread manager))))
    (when wait (bt2:join-thread thread))
    receipts))
