(defpackage :lem-agent/openrouter
  (:use :cl)
  (:local-nicknames (:agent :lem-agent) (:jobs :lem-toolkit/jobs)
                    (:store :lem-daemon/recovery-store))
  (:export :make-provider :transport-error :transport-error-kind :transport-error-status))
(in-package :lem-agent/openrouter)

(defconstant +maximum-line-bytes+ 65536)
(defconstant +maximum-event-bytes+ 65536)
(defconstant +maximum-response-bytes+ (* 1024 1024))
(defconstant +maximum-request-bytes+ (* 480 1024))
(defconstant +maximum-content-characters+ 65536)
(defconstant +maximum-argument-characters+ 16384)
(defconstant +maximum-calls+ 16)
(defparameter +endpoint+ "https://openrouter.ai/api/v1/chat/completions")

(define-condition transport-error (error)
  ((kind :initarg :kind :reader transport-error-kind)
   (status :initarg :status :initform nil :reader transport-error-status))
  (:report (lambda (condition stream)
             ;; Never print provider text, request data, headers, or curl stderr.
             (format stream "OpenRouter transport failed: ~a~@[ (~d)~]"
                     (transport-error-kind condition) (transport-error-status condition)))))
(defun fail (kind &optional status) (error 'transport-error :kind kind :status status))
(defun field (object name &optional default) (gethash name object default))
(defun object (&rest fields) (apply #'agent:json-object fields))
(defun json-text (value) (with-output-to-string (stream) (yason:encode value stream)))
(defun array-items (value)
  (unless (or (null value) (listp value) (and (vectorp value) (not (stringp value))))
    (fail :invalid-json-array))
  (coerce value 'vector))
(defun bounded-text-p (value maximum &optional (minimum 0))
  (and (stringp value) (<= minimum (length value) maximum)))
(defun name-p (name)
  (and (bounded-text-p name 64 1)
       (every (lambda (c) (find c "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-")) name)))

(defun parse-json (text)
  (handler-case
      (progn
        (store::check-json-depth text 16)
        (with-input-from-string (stream text)
          (let ((value (yason:parse stream :object-as :hash-table)))
            (loop for c = (read-char stream nil) while c
                  unless (find c '(#\Space #\Tab #\Return #\Newline)) do (fail :trailing-json-data))
            (agent:json-copy value))))
    (transport-error (condition) (error condition))
    (error () (fail :malformed-json))))

(defun wire-call (call)
  (unless (and (hash-table-p call) (bounded-text-p (field call "id") 128 1)
               (name-p (field call "name")) (hash-table-p (field call "arguments")))
    (fail :invalid-request-tool-call))
  (object "id" (field call "id") "type" "function"
          "function" (object "name" (field call "name") "arguments" (json-text (field call "arguments")))))

(defun wire-message (message)
  (unless (hash-table-p message) (fail :invalid-request-message))
  (let ((role (field message "role")) (content (field message "content")))
    (cond
      ((equal role "tool")
       (unless (bounded-text-p (field message "tool_call_id") 128 1) (fail :invalid-request-tool-result))
       (object "role" role "tool_call_id" (field message "tool_call_id")
               "content" (if (stringp content) content (json-text content))))
      ((member role '("user" "system" "assistant") :test #'equal)
       (unless (stringp content) (fail :invalid-request-content))
       (let ((result (object "role" role "content" content)))
         (when (equal role "assistant")
           (let ((calls (array-items (field message "tool_calls"))))
             (when (plusp (length calls)) (setf (gethash "tool_calls" result) (map 'vector #'wire-call calls)))))
         result))
      (t (fail :invalid-request-role)))))

(defun request-body (request max-tokens)
  (let* ((request (agent:json-copy request)) (tools (array-items (field request "tools")))
         (body (object "model" (field request "model") "stream" t "max_tokens" max-tokens
                       "messages" (map 'vector #'wire-message (array-items (field request "messages"))))))
    (unless (bounded-text-p (field request "model") 256 1) (fail :invalid-model))
    (when (plusp (length tools))
      (setf (gethash "tools" body)
            (map 'vector (lambda (tool)
                           (unless (and (hash-table-p tool) (name-p (field tool "name"))
                                        (hash-table-p (field tool "schema")))
                             (fail :invalid-tool-definition))
                           (object "type" "function" "function"
                                   (object "name" (field tool "name") "parameters" (field tool "schema")))) tools)
            (gethash "tool_choice" body) "auto"))
    (let ((text (json-text body)))
      (when (> (length (babel:string-to-octets text :encoding :utf-8)) +maximum-request-bytes+)
        (fail :request-budget))
      text)))

(defun config-quote (text)
  (with-output-to-string (stream)
    (loop for c across text
          do (case c
               (#\\ (write-string "\\\\" stream)) (#\" (write-string "\\\"" stream))
               (#\Newline (write-string "\\n" stream)) (#\Return (write-string "\\r" stream))
               (#\Tab (write-string "\\t" stream)) (otherwise (write-char c stream))))))

(defun private-config (endpoint key body ca-bundle)
  (unless (and (bounded-text-p key 4096 1)
               (every (lambda (c) (<= 33 (char-code c) 126)) key))
    (fail :missing-or-invalid-openrouter-key))
  (let ((config
          (with-output-to-string (stream)
            (flet ((option (name value) (format stream "~a = \"~a\"~%" name (config-quote value))))
              (option "url" endpoint)
              (option "header" (concatenate 'string "Authorization: Bearer " key))
              (option "header" "Content-Type: application/json")
              (option "header" "Accept: text/event-stream")
              (option "header" "Expect:")
              (when ca-bundle (option "cacert" ca-bundle))
              (option "data-binary" body)))))
    (when (> (length (babel:string-to-octets config :encoding :utf-8)) (* 1024 1024))
      (fail :private-input-budget))
    config))

(defun loopback-endpoint-p (endpoint)
  (let ((prefix "http://127.0.0.1:"))
    (and (bounded-text-p endpoint 256 (1+ (length prefix)))
         (string= prefix endpoint :end2 (length prefix))
         (let ((slash (position #\/ endpoint :start (length prefix))))
           (and slash (< (length prefix) slash)
                (every #'digit-char-p (subseq endpoint (length prefix) slash))
                (<= 1 (parse-integer endpoint :start (length prefix) :end slash) 65535)
                (every (lambda (c) (find c "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/_-"))
                       (subseq endpoint slash)))))))

(defstruct call (id "") (name "") (arguments (make-array 0 :element-type 'character :adjustable t :fill-pointer 0)))
(defstruct parser emit
  (mode :status) status content-type (header-bytes 0) (total-bytes 0) skip-lf first-body-line
  (line (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
  (data (make-array 0 :element-type 'character :adjustable t :fill-pointer 0)) (data-bytes 0) data-p
  (content (make-array 0 :element-type 'character :adjustable t :fill-pointer 0))
  (calls (make-hash-table)) finish done)

(defun append-text (target fragment maximum)
  (unless (and (stringp fragment) (<= (+ (length target) (length fragment)) maximum)) (fail :fragment-budget))
  (loop for c across fragment do (vector-push-extend c target)) target)
(defun append-name (original fragment maximum)
  (unless (and (stringp fragment) (<= (+ (length original) (length fragment)) maximum)) (fail :invalid-tool-fragment))
  (concatenate 'string original fragment))

(defun tool-fragment (parser fragment)
  (unless (hash-table-p fragment) (fail :invalid-tool-fragment))
  (let ((index (field fragment "index")) (type (field fragment "type")) (function (field fragment "function")))
    (unless (and (typep index `(integer 0 ,(1- +maximum-calls+)))
                 (or (null type) (equal type "function")) (or (null function) (hash-table-p function)))
      (fail :invalid-tool-fragment))
    (let ((call (or (gethash index (parser-calls parser))
                    (setf (gethash index (parser-calls parser)) (make-call)))))
      (when (field fragment "id") (setf (call-id call) (append-name (call-id call) (field fragment "id") 128)))
      (when function
        (when (field function "name") (setf (call-name call) (append-name (call-name call) (field function "name") 64)))
        (when (field function "arguments")
          (append-text (call-arguments call) (field function "arguments") +maximum-argument-characters+))))))

(defun apply-choice (parser choice usage-p)
  (unless (and (hash-table-p choice) (eql 0 (field choice "index"))) (fail :invalid-choice))
  (let* ((delta (field choice "delta")) (reason (field choice "finish_reason"))
         (content (and (hash-table-p delta) (field delta "content")))
         (tools (and (hash-table-p delta) (array-items (field delta "tool_calls")))))
    (unless (and (hash-table-p delta) (or (null content) (stringp content))
                 (or (null (field delta "role")) (equal (field delta "role") "assistant")))
      (fail :invalid-delta))
    (when (or (field delta "function_call") (field delta "refusal")) (fail :unsupported-delta))
    (when (parser-finish parser)
      ;; OpenRouter's final accounting frame repeats the terminal reason.
      (unless (and usage-p (or (null content) (zerop (length content))) (zerop (length tools))
                   (or (null reason) (equal reason (parser-finish parser))))
        (fail :data-after-finish))
      (return-from apply-choice))
    (when content
      (append-text (parser-content parser) content +maximum-content-characters+)
      (unless (zerop (length content)) (funcall (parser-emit parser) (copy-seq content))))
    (loop for fragment across tools do (tool-fragment parser fragment))
    (when reason
      (unless (member reason '("stop" "tool_calls") :test #'equal) (fail :incomplete-generation))
      (setf (parser-finish parser) reason))))

(defun dispatch-event (parser)
  (when (parser-data-p parser)
    (when (parser-done parser) (fail :data-after-done))
    (let ((text (coerce (parser-data parser) 'simple-string)))
      (if (equal text "[DONE]")
          (progn (unless (parser-finish parser) (fail :missing-finish)) (setf (parser-done parser) t))
          (let ((event (parse-json text)))
            (unless (hash-table-p event) (fail :invalid-event))
            (when (field event "error") (fail :provider-error))
            (let ((choices (array-items (field event "choices"))) (usage (field event "usage")))
              (unless (or (= 1 (length choices)) (and (zerop (length choices)) (hash-table-p usage)))
                (fail :invalid-choices))
              (loop for choice across choices do (apply-choice parser choice (hash-table-p usage)))))))
    (setf (fill-pointer (parser-data parser)) 0 (parser-data-bytes parser) 0 (parser-data-p parser) nil)))

(defun body-line (parser line)
  (when (parser-first-body-line parser)
    (setf (parser-first-body-line parser) nil)
    (when (and (plusp (length line)) (char= (char line 0) (code-char #xfeff))) (setf line (subseq line 1))))
  (cond
    ((zerop (length line)) (dispatch-event parser))
    ((char= (char line 0) #\:) nil)
    (t
     (let* ((colon (position #\: line)) (name (subseq line 0 colon))
            (value (if colon (subseq line (1+ colon)) "")))
       (when (and (plusp (length value)) (char= (char value 0) #\Space)) (setf value (subseq value 1)))
       (when (equal name "data")
         (when (parser-data-p parser) (vector-push-extend #\Newline (parser-data parser)))
         (incf (parser-data-bytes parser) (1+ (length (babel:string-to-octets value :encoding :utf-8))))
         (when (> (parser-data-bytes parser) +maximum-event-bytes+) (fail :event-budget))
         (append-text (parser-data parser) value +maximum-event-bytes+)
         (setf (parser-data-p parser) t))))))

(defun consume-line (parser)
  (let ((line (handler-case (babel:octets-to-string (parser-line parser) :encoding :utf-8 :errorp t)
                (error () (fail :invalid-utf8)))))
    (setf (fill-pointer (parser-line parser)) 0)
    (case (parser-mode parser)
      (:status
       (unless (and (>= (length line) 12) (string= "HTTP/1." line :end2 7)
                    (find (char line 7) "01")
                    (char= #\Space (char line 8)) (every #'digit-char-p (subseq line 9 12))
                    (or (= 12 (length line)) (char= #\Space (char line 12))))
         (fail :invalid-http-status))
       (setf (parser-status parser) (parse-integer line :start 9 :end 12) (parser-mode parser) :headers)
       (unless (or (<= 200 (parser-status parser) 299) (member (parser-status parser) '(100 103)))
         (fail :http-status (parser-status parser))))
      (:headers
       (if (zerop (length line))
           (if (< (parser-status parser) 200)
               (setf (parser-mode parser) :status (parser-content-type parser) nil)
               (progn
                 (unless (equal (parser-content-type parser) "text/event-stream") (fail :unexpected-content-type))
                 (setf (parser-mode parser) :sse (parser-first-body-line parser) t)))
           (let ((colon (position #\: line)))
             (unless colon (fail :invalid-http-header))
             (when (string-equal "content-type" line :end2 colon)
               (when (parser-content-type parser) (fail :duplicate-content-type))
               (setf (parser-content-type parser)
                     (string-downcase (string-trim '(#\Space #\Tab)
                                                   (subseq line (1+ colon) (position #\; line :start (1+ colon))))))))))
      (:sse (body-line parser line)))))

(defun feed (parser bytes)
  (incf (parser-total-bytes parser) (length bytes))
  (when (> (parser-total-bytes parser) +maximum-response-bytes+) (fail :response-budget))
  (loop for byte across bytes
        do (unless (eq (parser-mode parser) :sse)
             (when (> (incf (parser-header-bytes parser)) 16384) (fail :header-budget)))
           (cond
             ((and (parser-skip-lf parser) (= byte 10)) (setf (parser-skip-lf parser) nil))
             ((member byte '(10 13))
              (consume-line parser) (setf (parser-skip-lf parser) (= byte 13)))
             (t (setf (parser-skip-lf parser) nil)
                (when (>= (length (parser-line parser)) +maximum-line-bytes+) (fail :line-budget))
                (vector-push-extend byte (parser-line parser))))))

(defun finish-parser (parser)
  (unless (and (eq (parser-mode parser) :sse) (parser-done parser) (parser-finish parser)
               (zerop (length (parser-line parser))) (not (parser-data-p parser)))
    (fail :truncated-stream))
  (let ((count (hash-table-count (parser-calls parser))) (ids (make-hash-table :test 'equal)))
    (unless (if (equal (parser-finish parser) "tool_calls") (plusp count) (zerop count))
      (fail :inconsistent-tool-finish))
    (object "content" (coerce (parser-content parser) 'simple-string)
            "tool_calls"
            (coerce
             (loop for index below count for call = (gethash index (parser-calls parser))
                   collect (progn
                             (unless (and call (bounded-text-p (call-id call) 128 1) (name-p (call-name call))
                                          (not (gethash (call-id call) ids))) (fail :incomplete-tool-call))
                             (setf (gethash (call-id call) ids) t)
                             (let ((arguments (parse-json (coerce (call-arguments call) 'simple-string))))
                               (unless (hash-table-p arguments) (fail :invalid-tool-arguments))
                               (object "id" (call-id call) "name" (call-name call) "arguments" arguments)))) 'vector))))

(defun make-provider (&key job-manager curl-program
                          (api-key-provider (lambda () (uiop:getenvp "OPENROUTER_API_KEY")))
                          (timeout 120) (max-tokens 4096) ca-bundle test-endpoint)
  "Return one-round provider function. Setup may stat pinned executable/CA paths.
TEST-ENDPOINT permits only an explicitly selected numeric loopback HTTP fixture."
  (unless (and (jobs:job-manager-ready-p job-manager) (functionp api-key-provider)
               curl-program (uiop:absolute-pathname-p curl-program) (probe-file curl-program)
               (realp timeout) (<= 0.05 timeout 3600) (typep max-tokens '(integer 1 32768))
               (or (null ca-bundle) (and (uiop:absolute-pathname-p ca-bundle) (probe-file ca-bundle)))
               (or (null test-endpoint) (loopback-endpoint-p test-endpoint)))
    (fail :invalid-provider-configuration))
  (let ((curl-program (namestring (truename curl-program)))
        (ca-bundle (when ca-bundle (namestring (truename ca-bundle))))
        (endpoint (copy-seq (or test-endpoint +endpoint+))))
    (lambda (request emit-text context)
      (agent:check-operation context)
      (let* ((parser (make-parser :emit (lambda (text) (agent:check-operation context) (funcall emit-text text))))
             (failure nil) (job nil) (complete nil)
             (config (private-config endpoint (funcall api-key-provider) (request-body request max-tokens) ca-bundle)))
        (unwind-protect
             (progn
               (agent:check-operation context)
               (setf job
                     (jobs:start-job
                      (list curl-program "--disable" "--silent" "--fail" "--no-buffer" "--http1.1"
                            "--include" "--suppress-connect-headers" "--request" "POST"
                            "--proto" (if test-endpoint "=http" "=https")
                            "--connect-timeout" (format nil "~,3f" (min 15 timeout))
                            "--max-time" (format nil "~,3f" timeout) "--config" "-")
                      :manager job-manager :owner (format nil "agent:~a:openrouter" (agent:operation-session-id context))
                      :directory (agent:operation-root context) :timeout timeout :output-limit 1
                      :environment '("LC_ALL=C.UTF-8") :input config
                      :on-output
                      (lambda (job channel bytes)
                        (declare (ignore job))
                        (handler-case
                            (progn (agent:check-operation context) (when (eq channel :stdout) (feed parser bytes)))
                          (agent:operation-cancelled (condition) (setf failure condition) (error condition))
                          (transport-error (condition) (setf failure condition) (error condition))
                          (error () (setf failure (make-condition 'transport-error :kind :output-consumer)) (error failure))))))
               (agent:register-cancellation context (lambda () (jobs:cancel-job job)))
               (let ((result (jobs:wait-job job :timeout (+ timeout 10))))
                 (agent:check-operation context)
                 (when failure (error failure))
                 (unless result (fail :job-wait-timeout))
                 (unless (and (equal "exited" (field result "state")) (eql 0 (field result "exit-code"))
                              (null (field result "journal-error")))
                   (fail :managed-request (field result "exit-code")))
                 (let ((value (finish-parser parser))) (setf complete t) value)))
          (setf config nil)
          (when (and job (not complete)) (jobs:cancel-job job)))))))
