(defpackage :lem-buffer-proposals/tests
  (:use :cl :rove)
  (:local-nicknames (:proposal :lem-buffer-proposals)))
(in-package :lem-buffer-proposals/tests)

(defmacro with-source ((buffer text) &body body)
  `(let ((lem-core::*frames* nil)
         (lem-core::*display-frame-map* (make-hash-table)))
     (lem:with-current-buffers ()
       (let ((lem/buffer/internal::*current-buffer* (lem:primordial-buffer)))
         (lem-fake-interface:with-fake-interface ()
           (let ((proposal::*proposals* (make-hash-table :test #'equal)))
             (let ((,buffer (lem:make-buffer "proposal-test-source")))
               (lem:switch-to-buffer ,buffer)
               (lem:insert-string (lem:buffer-point ,buffer) ,text)
               (lem:clear-buffer-edit-history ,buffer)
               (unwind-protect (progn ,@body)
                 (dolist (item (proposal:list-proposals))
                   (unless (proposal::terminal-proposal-p item)
                     (proposal:reject-proposal item))
                   (proposal:forget-proposal item))))))))))

(defun capture (buffer start end)
  (lem:with-point ((left (lem:buffer-start-point buffer))
                   (right (lem:buffer-start-point buffer)))
    (lem:character-offset left start)
    (lem:character-offset right end)
    (proposal:capture-region left right)))

(defun edit (buffer start end text)
  (lem:with-point ((left (lem:buffer-start-point buffer) :right-inserting)
                   (right (lem:buffer-start-point buffer) :left-inserting))
    (lem:character-offset left start)
    (lem:character-offset right end)
    (lem:delete-between-points left right)
    (lem:insert-string left text)))

(deftest staged-unsaved-source
  (with-source (buffer "before OLD after")
    (let* ((tick (lem:buffer-modified-tick buffer))
           (item (capture buffer 7 10)))
      (proposal:stage-replacement item "NEW")
      (ok (string= "OLD" (proposal:proposal-original item)))
      (ok (string= "before OLD after" (lem:buffer-text buffer)))
      (ok (= tick (lem:buffer-modified-tick buffer)) "staging does not edit unsaved source")
      (ok (= tick (proposal:proposal-revision item)))
      (ok (eq item (proposal:find-proposal (proposal:proposal-id item))))
      (let ((copy (proposal:proposal-original item)))
        (setf (char copy 0) #\X)
        (ok (string= "OLD" (proposal:proposal-original item)) "snapshot text cannot be mutated through its reader"))
      (proposal:reject-proposal item)
      (ok (eq :rejected (proposal:proposal-state item)))
      (ok (= tick (lem:buffer-modified-tick buffer)) "rejection has no source edit or undo entry"))))

(deftest outside-edits-and-separate-undo
  (with-source (buffer "before OLD after")
    (let ((item (capture buffer 7 10)))
      (proposal:stage-replacement item "NEW")
      (lem:buffer-disable-undo-boundary buffer)
      (edit buffer 0 0 "human ")
      (edit buffer 22 22 "!")
      (ok (proposal:proposal-valid-p item) "accounted outside edits preserve the captured region")
      (ok (= 13 (getf (proposal:proposal-source-location item) :column)))
      (proposal:apply-proposal item)
      (ok (string= "human before NEW after!" (lem:buffer-text buffer)))
      (ng (lem/buffer/internal::buffer-enable-undo-boundary-p buffer)
          "the open insertion mode's boundary policy is restored")
      (lem:buffer-undo (lem:buffer-point buffer))
      (ok (string= "human before OLD after!" (lem:buffer-text buffer))
          "one undo removes the accepted proposal and retains prior human edits")
      (lem:buffer-undo (lem:buffer-point buffer))
      (ok (string= "before OLD after" (lem:buffer-text buffer)))
      (lem:buffer-redo (lem:buffer-point buffer))
      (lem:buffer-redo (lem:buffer-point buffer))
      (ok (string= "human before NEW after!" (lem:buffer-text buffer))))))

(deftest touching-edit-conflicts
  (dolist (range '((8 9 "human") (7 7 "left") (10 10 "right")))
    (with-source (buffer "before OLD after")
      (let ((item (capture buffer 7 10)))
        (proposal:stage-replacement item "NEW")
        (apply #'edit buffer range)
        (let ((human (lem:buffer-text buffer)) (tick (lem:buffer-modified-tick buffer)))
          (ok (signals (proposal:apply-proposal item) 'proposal:proposal-conflict))
          (ok (string= human (lem:buffer-text buffer)))
          (ok (= tick (lem:buffer-modified-tick buffer)))
          (ok (eq :conflict (proposal:proposal-state item))))))))

(deftest changed-then-undone-is-a-conflict
  (with-source (buffer "before OLD after")
    (let ((item (capture buffer 7 10)))
      (proposal:stage-replacement item "NEW")
      (edit buffer 7 10 "human")
      (lem:buffer-undo-boundary buffer)
      (lem:buffer-undo (lem:buffer-point buffer))
      (ok (string= "before OLD after" (lem:buffer-text buffer)))
      (ok (signals (proposal:apply-proposal item) 'proposal:proposal-conflict)
          "restoring the old text does not erase its intervening revision history"))))

(deftest missed-hooks-conflict
  (with-source (buffer "before OLD after")
    (let ((item (capture buffer 7 10)))
      (proposal:stage-replacement item "NEW")
      (let ((lem/buffer/internal::*inhibit-modification-hooks* t))
        (edit buffer 0 0 "unobserved "))
      (ok (string= "OLD" (proposal:proposal-current-text item)))
      (ok (signals (proposal:apply-proposal item) 'proposal:proposal-conflict)
          "matching content alone cannot excuse an unobserved revision"))))

(deftest competing-proposals
  (with-source (buffer "before OLD after")
    (let ((first (capture buffer 7 10)) (second (capture buffer 7 10)))
      (proposal:stage-replacement first "FIRST")
      (proposal:stage-replacement second "SECOND")
      (proposal:apply-proposal first)
      (ok (signals (proposal:apply-proposal second) 'proposal:proposal-conflict))
      (ok (string= "before FIRST after" (lem:buffer-text buffer)))
      (ok (signals (proposal:apply-proposal first) 'proposal:proposal-conflict)
          "an accepted proposal cannot be applied twice"))))

(deftest reviewed-version-is-explicit
  (with-source (buffer "OLD")
    (let ((item (capture buffer 0 3)))
      (proposal:stage-replacement item "FIRST")
      (let ((generation (proposal:proposal-generation item)))
        (proposal:stage-replacement item "SECOND")
        (ok (signals (proposal:apply-proposal item :expected-generation generation)
                     'proposal:proposal-conflict))
        (ok (eq :pending (proposal:proposal-state item)))
        (ok (string= "OLD" (lem:buffer-text buffer))))
      (proposal:apply-proposal item :expected-generation (proposal:proposal-generation item)
                                   :expected-revision (proposal:proposal-revision item))
      (ok (string= "SECOND" (lem:buffer-text buffer))))))

(deftest disjoint-proposals-and-empty-region
  (with-source (buffer "ONE middle TWO")
    (let ((first (capture buffer 0 3)) (second (capture buffer 11 14)))
      (proposal:stage-replacement first "first")
      (proposal:stage-replacement second "second")
      (proposal:apply-proposal first)
      (proposal:apply-proposal second)
      (ok (string= "first middle second" (lem:buffer-text buffer))
          "disjoint proposals track changes from other accepted proposals")
      (lem:buffer-undo (lem:buffer-point buffer))
      (ok (string= "first middle TWO" (lem:buffer-text buffer)))
      (lem:buffer-undo (lem:buffer-point buffer))
      (ok (string= "ONE middle TWO" (lem:buffer-text buffer)))))
  (with-source (buffer "left right")
    (let ((item (capture buffer 5 5)))
      (proposal:stage-replacement item "new ")
      (proposal:apply-proposal item)
      (ok (string= "left new right" (lem:buffer-text buffer)))
      (lem:buffer-undo (lem:buffer-point buffer))
      (ok (string= "left right" (lem:buffer-text buffer)))))
  (with-source (buffer "left right")
    (let ((item (capture buffer 5 5)))
      (proposal:stage-replacement item "new ")
      (edit buffer 5 5 "human ")
      (ok (signals (proposal:apply-proposal item) 'proposal:proposal-conflict))
      (ok (string= "left human right" (lem:buffer-text buffer))))))

(deftest aggregate-capacity-and-display-bound
  (with-source (buffer "OLD")
    (let ((proposal::*maximum-retained-characters* 6))
      (let ((item (capture buffer 0 3)))
        (proposal:stage-replacement item "NEW")
        (ok (signals (proposal:stage-replacement item "NEXT") 'proposal:proposal-error))
        (ok (= 1 (proposal:proposal-generation item)))
        (ok (string= "NEW" (proposal:proposal-replacement item)))
        (proposal:reject-proposal item)))
    (let* ((item (capture buffer 0 3))
           (text (make-string 4000 :initial-element #\x))
           (proposal::*review-section-limit* 8))
      (proposal:stage-replacement item text)
      (let ((review (proposal:proposal-review-buffer item)))
        (ok (< (length (lem:buffer-text review)) 1000))
        (ok (search "Display truncated" (lem:buffer-text review)))
        (ok (string= text (proposal:proposal-replacement item))
            "display limits do not truncate the staged candidate")))))

(deftest source-identity-and-read-only
  (with-source (buffer "OLD")
    (let ((item (capture buffer 0 3)))
      (proposal:stage-replacement item "NEW")
      (setf (lem:buffer-read-only-p buffer) t)
      (ok (signals (proposal:apply-proposal item) 'proposal:proposal-error))
      (ok (string= "OLD" (lem:buffer-text buffer)))
      (setf (lem:buffer-read-only-p buffer) nil)
      (lem:delete-buffer buffer)
      (let ((replacement (lem:make-buffer "proposal-test-source")))
        (lem:insert-string (lem:buffer-point replacement) "OLD")
        (ok (signals (proposal:apply-proposal item) 'proposal:proposal-conflict))
        (ok (string= "OLD" (lem:buffer-text replacement)))
        (ok (null (proposal:proposal-source-buffer item)) "deleted sources are not retained or redirected by name")))))

(deftest filename-reassociation-conflicts
  (dolist (names '((nil "/tmp/proposal-other.txt")
                   ("/tmp/proposal-original.txt" nil)
                   ("/tmp/proposal-original.txt" "/tmp/proposal-other.txt")))
    (with-source (buffer "OLD")
      (when (first names) (setf (lem:buffer-filename buffer) (first names)))
      (let ((item (capture buffer 0 3)) (tick (lem:buffer-modified-tick buffer)))
        (proposal:stage-replacement item "NEW")
        (if (second names)
            (setf (lem:buffer-filename buffer) (second names))
            ;; The public filename setter accepts only pathnames; model an
            ;; explicit association removal without visiting or deleting files.
            (setf (lem/buffer/internal::buffer-%filename buffer) nil))
        (ok (= tick (lem:buffer-modified-tick buffer)) "file association can change without a text edit")
        (ok (signals (proposal:apply-proposal item) 'proposal:proposal-conflict))
        (ok (string= "OLD" (lem:buffer-text buffer)))
        (multiple-value-bind (valid reason) (proposal:proposal-valid-p item)
          (ok (not valid)) (ok (eq :source-file-changed reason)))))))

(deftest failed-edit-rolls-back
  (with-source (buffer "before OLD after")
    (let ((item (capture buffer 7 10)))
      (proposal:stage-replacement item "NEW")
      (lem:move-to-position (lem:buffer-point buffer) 9)
      (let ((hook (lambda (start end old-length)
                    (declare (ignore old-length))
                    (when (lem:point< start end) (error "simulated failing edit hook")))))
        (unwind-protect
             (progn
               (lem:add-hook (lem:variable-value 'lem:after-change-functions :buffer buffer) hook)
               (ok (signals (proposal:apply-proposal item) 'error)))
          (lem:remove-hook (lem:variable-value 'lem:after-change-functions :buffer buffer) hook)))
      (ok (string= "before OLD after" (lem:buffer-text buffer)) "an edit hook failure restores the exact source")
      (ok (= 9 (lem:position-at-point (lem:buffer-point buffer))) "failed replacement preserves the original point")
      (ok (proposal:proposal-valid-p item))
      (proposal:apply-proposal item)
      (lem:buffer-undo (lem:buffer-point buffer))
      (ok (string= "before OLD after" (lem:buffer-text buffer)) "a retry remains one undo unit"))))

(deftest bounded-registry-and-review
  (with-source (buffer "before OLD after")
    (let ((proposal::*maximum-proposals* 2)
          (proposal::*maximum-text-characters* 8)
          (proposal::*maximum-retained-characters* 16))
      (let* ((first (capture buffer 7 10)) (first-id (proposal:proposal-id first))
             (second (capture buffer 7 10)))
        (proposal:stage-replacement first "NEW")
        (ok (signals (capture buffer 7 10) 'proposal:proposal-error)
            "capacity pressure never discards pending decisions")
        (ok (signals (proposal:stage-replacement first "too large") 'proposal:proposal-error))
        (ok (string= "NEW" (proposal:proposal-replacement first)))
        (proposal:reject-proposal first)
        (let ((third (capture buffer 7 10)))
          (ng (proposal:find-proposal first-id))
          (ng (string= first-id (proposal:proposal-id third)))
          (ok (eq second (proposal:find-proposal (proposal:proposal-id second)))))))
    (let ((item (capture buffer 7 10)))
      (proposal:stage-replacement item "NEW")
      (edit buffer 8 9 "human")
      (let ((human (lem:buffer-text buffer))
            (review (proposal:proposal-review-buffer item)))
        (ok (lem:buffer-read-only-p review))
        (ok (search "OLD" (lem:buffer-text review)))
        (ok (search "OhumanD" (lem:buffer-text review)))
        (ok (search "NEW" (lem:buffer-text review)))
        (ok (search (proposal:proposal-id item) (lem:buffer-text review)))
        (ok (eq review (proposal:proposal-review-buffer item)) "one stable review buffer per proposal")
        (lem:switch-to-buffer review)
        (proposal:visit-proposal-source item)
        (ok (eq buffer (lem:current-buffer)))
        (ok (string= human (lem:buffer-text buffer)) "conflict review and source navigation preserve human edits")))))

(deftest proposal-browser-preserves-human-source-and-undo
  (with-source (buffer "before OLD after")
    (edit buffer 0 0 "human ")
    (let ((item (capture buffer 13 16)))
      (proposal:stage-replacement item "NEW")
      (let* ((tick (lem:buffer-modified-tick buffer))
             (listing (proposal:buffer-proposal-list)))
        (ok (eq listing (lem:current-buffer)))
        (ok (lem:buffer-read-only-p listing))
        (ok (search (proposal:proposal-id item) (lem:buffer-text listing)))
        (ok (search "pending" (lem:buffer-text listing)))
        (ok (search "proposal-test-source:1:13" (lem:buffer-text listing)))
        (ok (= tick (lem:buffer-modified-tick buffer)))
        (proposal::proposal-list-open-selected)
        (ok (eq item (proposal::reviewed-proposal)))
        (ok (= tick (lem:buffer-modified-tick buffer)) "list/open never edits the live source")
        (proposal::proposal-review-accept)
        (ok (string= "human before NEW after" (lem:buffer-text buffer)))
        (lem:buffer-undo (lem:buffer-point buffer))
        (ok (string= "human before OLD after" (lem:buffer-text buffer))
            "one undo removes acceptance while preserving prior human text")))))

(deftest proposal-browser-stale-review-and-source-conflict
  (with-source (buffer "before OLD after")
    (let ((item (capture buffer 7 10)))
      (proposal:stage-replacement item "FIRST")
      (proposal:buffer-proposal-list)
      (proposal::proposal-list-open-selected)
      (proposal:stage-replacement item "SECOND")
      (ok (signals (proposal::proposal-review-accept) 'lem:editor-error))
      (ok (string= "before OLD after" (lem:buffer-text buffer)))
      (ok (eq :pending (proposal:proposal-state item)))
      (edit buffer 7 10 "human")
      (let ((human (lem:buffer-text buffer)))
        (ok (signals (proposal::proposal-review-accept) 'lem:editor-error))
        (ok (string= human (lem:buffer-text buffer)))
        (ok (eq :conflict (proposal:proposal-state item)))))))

(deftest proposal-browser-close-reopen-and-deleted-source
  (with-source (buffer "OLD")
    (let ((item (capture buffer 0 3)))
      (proposal:stage-replacement item "NEW")
      (let ((listing (proposal:buffer-proposal-list)))
        (lem:delete-buffer listing)
        (ok (eq :pending (proposal:proposal-state item)))
        (ok (not (eq listing (proposal:buffer-proposal-list)))))
      (lem:switch-to-buffer buffer)
      (proposal:buffer-proposal-open (proposal:proposal-id item))
      (let ((review (lem:current-buffer)))
        (lem:delete-buffer review)
        (ok (eq :pending (proposal:proposal-state item)))
        (proposal:buffer-proposal-open (proposal:proposal-id item))
        (ok (not (eq review (lem:current-buffer)))))
      (lem:delete-buffer buffer)
      (let ((listing (proposal:buffer-proposal-list)))
        (ok (search "[source closed]" (lem:buffer-text listing)))
        (proposal::proposal-list-open-selected)
        (ok (eq item (proposal::reviewed-proposal)))
        (ok (search "source-deleted" (lem:buffer-text (lem:current-buffer))))
        (ok (signals (proposal::proposal-review-source) 'lem:editor-error))))))

(deftest proposal-browser-forgotten-row-keeps-exact-identity
  (with-source (buffer "OLD")
    (let* ((first (capture buffer 0 3))
           (first-id (proposal:proposal-id first))
           (second (capture buffer 0 3)))
      (proposal:stage-replacement first "FIRST")
      (proposal:stage-replacement second "SECOND")
      (let* ((listing (proposal:buffer-proposal-list))
             (button (lem/button:button-at (lem:current-point))))
        (proposal:reject-proposal first)
        (proposal:forget-proposal first)
        (ok (signals (proposal::proposal-list-open-selected) 'lem:editor-error))
        (ok (signals (lem/button:button-action button) 'lem:editor-error)
            "mouse callbacks also retain exact object identity")
        (ok (signals (proposal:buffer-proposal-open first-id) 'lem:editor-error))
        (ok (eq listing (lem:current-buffer)))
        (ok (string= "OLD" (lem:buffer-text buffer)))
        (proposal::proposal-list-refresh)
        (proposal::proposal-list-open-selected)
        (ok (eq second (proposal::reviewed-proposal)))))))

(deftest proposal-browser-bounded-single-line-labels
  (with-source (buffer "OLD")
    (lem:rename-buffer (concatenate 'string (format nil "source~%injected ")
                                    (make-string 1000 :initial-element #\x)))
    (let ((item (capture buffer 0 3)))
      (proposal:stage-replacement item "NEW")
      (let* ((listing (proposal:buffer-proposal-list))
             (text (lem:buffer-text listing)))
        (ok (< (length text) 600))
        (ok (search "source?injected" text))
        (lem:buffer-start (lem:current-point))
        (ok (signals (proposal::proposal-list-open-selected) 'lem:editor-error))
        (lem:buffer-end (lem:current-point))
        (ok (signals (proposal::proposal-list-open-selected) 'lem:editor-error)
            "blank lines never select the preceding row")))))
