(defpackage #:lem-structured-notes/lem-notes-adapter-tests
  (:use #:cl #:rove)
  (:local-nicknames (#:notes #:lem-structured-notes) (#:adapter #:lem-structured-notes/lem-adapter)
                    (#:proposal #:lem-buffer-proposals) (#:disk #:lem-daemon/recovery-store)))
(in-package #:lem-structured-notes/lem-notes-adapter-tests)

(defmacro with-notes ((directory workspace public) &body body)
  `(let* ((,directory (merge-pathnames (format nil "lem-notes-adapter-~a/" (disk:new-id)) (uiop:temporary-directory)))
          (lem-core::*frames* nil) (lem-core::*display-frame-map* (make-hash-table))
          (adapter::*lem-notes-workspace-context* nil)
          (proposal::*proposals* (make-hash-table :test #'equal))
          (lem:*before-find-file-hook* nil) (lem:*find-file-hook* nil))
     (ensure-directories-exist (merge-pathnames "work/roam/journal/" ,directory))
     (ensure-directories-exist (merge-pathnames "public/roam/" ,directory))
     (unwind-protect
          (lem:with-current-buffers ()
            (let ((lem/buffer/internal::*current-buffer* (lem:primordial-buffer)))
              (lem-fake-interface:with-fake-interface ()
                (let* ((context (adapter:configure-lem-notes-workspaces
                                 :work-root (merge-pathnames "work/" ,directory)
                                 :public-root (merge-pathnames "public/" ,directory)))
                       (,workspace (adapter:lem-notes-workspace-context-workspace context))
                       (,public (adapter:lem-notes-workspace-context-public-workspace context)))
                  (declare (ignorable ,workspace ,public))
                  (unwind-protect (locally ,@body)
                    (dolist (item (proposal:list-proposals))
                      (unless (proposal::terminal-proposal-p item) (proposal:reject-proposal item))
                      (proposal:forget-proposal item)))))))
       (uiop:delete-directory-tree ,directory :validate t))))

(defun source-text ()
  (format nil "---~%lem:~%  profile: lsm/1~%  document-id: fixture~%---~%~%# Heading λ~%~%Body stays exact.~%"))
(defun fixture-buffer (workspace &optional (source (source-text)) (name "identity.md"))
  (let ((buffer (lem:find-file-buffer (merge-pathnames name (notes:notes-workspace-roam-root workspace)))))
    (lem:insert-string (lem:buffer-start-point buffer) source)
    (lem:clear-buffer-edit-history buffer)
    (lem:move-to-position (lem:buffer-point buffer) (1+ (search "# Heading" source)))
    buffer))
(defun id-plan (snapshot)
  (nth-value 1 (notes:plan-lsm-node-id snapshot
                                     (notes:semantic-node-id (first (notes:semantic-document-nodes
                                                                    (notes:source-snapshot-document snapshot))))
                                     :proposed-id "node:fixture")))
(defun write-source (path text)
  (with-open-file (stream path :direction :output :if-exists :supersede :external-format :utf-8)
    (write-string text stream)))
(defun error-code (function)
  (handler-case (progn (funcall function) nil)
    (adapter:notes-adapter-error (condition) (adapter:notes-adapter-error-code condition))))

(deftest explicit-pinned-roots-and-safe-local-targets
  (with-notes (directory workspace public)
    (let ((pinned (adapter:lem-current-notes-workspaces)))
      (ok (eq pinned (adapter:configure-lem-notes-workspaces :work-root (merge-pathnames "work/" directory)
                                                           :public-root (merge-pathnames "public/" directory))))
      (ok (eq :conflicting-workspaces
              (error-code (lambda () (adapter:configure-lem-notes-workspaces :work-root (merge-pathnames "public/" directory))))))
      (ok (eq :unavailable-workspace
              (error-code (lambda () (adapter:configure-lem-notes-workspaces :work-root (merge-pathnames "missing/" directory))))))
      (ok (eq pinned (adapter:lem-current-notes-workspaces)))
      (let ((adapter::*lem-notes-workspace-context* nil))
        (ok (eq :unavailable-workspace (error-code #'adapter:lem-current-notes-workspaces)))
        (ok (signals (adapter:configure-lem-notes-workspaces :work-root "relative")))))
    (ok (signals (adapter:lem-open-lsm-daily-note (notes:resolve-notes-workspace (merge-pathnames "work/" directory))
                                                "2026-09-13" :switch-p nil))
        "an arbitrary workspace object cannot bypass configured authority")
    (dolist (tail '("../escape.md" "roam/../../escape.md" "roam//empty.md" "roam/./dot.md"))
      (ok (signals (adapter::target-info (concatenate 'string (namestring (notes:notes-workspace-root workspace)) tail)))))
    (let ((link (merge-pathnames "link.md" (notes:notes-workspace-roam-root workspace)))
          (fifo (merge-pathnames "fifo.md" (notes:notes-workspace-roam-root workspace))))
      (sb-posix:symlink "/dev/null" (namestring link))
      (sb-posix:mkfifo (namestring fifo) #o600)
      (ok (eq :unsafe-target (error-code (lambda () (adapter::target-info link)))))
      (ok (eq :unsafe-target (error-code (lambda () (adapter::target-info fifo))))))
    (sb-posix:rmdir (namestring (notes:notes-workspace-journal-root workspace)))
    (ok (eq :unavailable-parent
            (error-code (lambda () (adapter:lem-append-lsm-journal-entry workspace 3998246400 :timezone 0 :switch-p nil)))))
    (ng (probe-file (notes:notes-workspace-journal-root workspace)) "an unsaved command creates no directories")))

(deftest fresh-live-plan-is-one-independent-undo-unit
  (with-notes (directory workspace public)
    (declare (ignore directory))
    (let ((buffer (fixture-buffer workspace)))
      (lem:buffer-disable-undo-boundary buffer)
      (lem:insert-string (lem:buffer-end-point buffer) "Prior human text λ")
      (let ((before (lem:buffer-text buffer)) (tick (lem:buffer-modified-tick buffer)))
        (multiple-value-bind (snapshot context) (adapter:lem-current-lsm-snapshot buffer)
          (let ((plan (id-plan snapshot)))
            (multiple-value-bind (item focus) (adapter:lem-stage-lsm-edit-plan context plan snapshot)
              (ok (equal before (lem:buffer-text buffer)))
              (ok (= tick (lem:buffer-modified-tick buffer)))
              (ok (equal before (proposal:proposal-original item)))
              (proposal:apply-proposal item)
              (ok (search "id: \"node:fixture\"" (lem:buffer-text buffer)))
              (ok (= focus (1+ (search "# Heading" (lem:buffer-text buffer)))))
              (lem:buffer-undo (lem:buffer-point buffer))
              (ok (equal before (lem:buffer-text buffer)) "one undo retains the preceding human insertion")
              (ng (lem/buffer/internal::buffer-enable-undo-boundary-p buffer)))))))))

(deftest planning-time-provenance-refuses-aba-and-replaced-source
  (with-notes (directory workspace public)
    (declare (ignore directory))
    (let ((buffer (fixture-buffer workspace)))
      (multiple-value-bind (snapshot context) (adapter:lem-current-lsm-snapshot buffer)
        (let ((plan (id-plan snapshot)) (original (lem:buffer-text buffer))
              (filename (lem:buffer-filename buffer)) (name (lem:buffer-name buffer)))
          (lem:insert-string (lem:buffer-end-point buffer) "intervening")
          (lem:buffer-undo-boundary buffer)
          (lem:buffer-undo (lem:buffer-point buffer))
          (ok (equal original (lem:buffer-text buffer)))
          (ok (eq :stale-source (error-code (lambda () (adapter:lem-stage-lsm-edit-plan context plan snapshot)))))
          (let ((fresh (adapter:lem-current-lsm-snapshot buffer)))
            (ng (equal (notes:source-snapshot-revision snapshot) (notes:source-snapshot-revision fresh))))
          (lem:delete-buffer buffer)
          (let ((replacement (lem:find-file-buffer filename)))
            (lem:insert-string (lem:buffer-point replacement) original)
            (ok (equal name (lem:buffer-name replacement)))
            (ok (eq :stale-source (error-code (lambda () (adapter:lem-apply-lsm-edit-plan context plan snapshot)))))
            (ok (equal original (lem:buffer-text replacement)))))))))

(deftest document-plans-also-require-planning-time-provenance
  (with-notes (directory workspace public)
    (declare (ignore directory))
    (let* ((buffer (adapter:lem-open-lsm-daily-note workspace "2026-09-13" :switch-p nil))
           (context (adapter:lem-capture-notes-source buffer))
           (plan (notes:plan-lsm-daily-note workspace "2026-09-13" :current-source (adapter:lem-notes-source-base context)))
           (before (lem:buffer-text buffer)))
      (lem:insert-string (lem:buffer-end-point buffer) "changed")
      (lem:buffer-undo-boundary buffer) (lem:buffer-undo (lem:buffer-point buffer))
      (ok (equal before (lem:buffer-text buffer)))
      (ok (eq :stale-source (error-code (lambda () (adapter:lem-apply-notes-document-plan context plan)))))
      (ok (eq :missing-provenance (error-code (lambda () (adapter:lem-stage-notes-document-plan nil plan))))))))

(deftest read-only-and-failing-hooks-preserve-original-data
  (with-notes (directory workspace public)
    (declare (ignore directory))
    (let* ((buffer (fixture-buffer workspace)) (before (lem:buffer-text buffer))
           (point (lem:position-at-point (lem:buffer-point buffer))))
      (multiple-value-bind (snapshot context) (adapter:lem-current-lsm-snapshot buffer)
        (let ((plan (id-plan snapshot)))
          (setf (lem:buffer-read-only-p buffer) t)
          (ok (eq :read-only-source (error-code (lambda () (adapter:lem-apply-lsm-edit-plan context plan snapshot)))))
          (ok (equal before (lem:buffer-text buffer)))
          (setf (lem:buffer-read-only-p buffer) nil)
          (let ((hook (lambda (start end old-length)
                        (declare (ignore old-length))
                        (when (lem:point< start end) (error "fixture edit hook failure")))))
            (unwind-protect
                 (progn
                   (lem:add-hook (lem:variable-value 'lem:after-change-functions :buffer buffer) hook)
                   (ok (signals (adapter:lem-apply-lsm-edit-plan context plan snapshot))))
              (lem:remove-hook (lem:variable-value 'lem:after-change-functions :buffer buffer) hook)))
          (ok (equal before (lem:buffer-text buffer)))
          (ok (= point (lem:position-at-point (lem:buffer-point buffer))))
          (ok (null (proposal:list-proposals)) "failed direct application releases its private proposal"))))))

(deftest capacity-failure-leaves-no-new-note-or-partial-edit
  (with-notes (directory workspace public)
    (declare (ignore directory))
    (let* ((buffer (fixture-buffer workspace)) (before (lem:buffer-text buffer))
           (proposal::*maximum-proposals* 1)
           (held (proposal:capture-region (lem:buffer-start-point buffer) (lem:buffer-end-point buffer))))
      (proposal:stage-replacement held "held candidate")
      (multiple-value-bind (snapshot context) (adapter:lem-current-lsm-snapshot buffer)
        (ok (signals (adapter:lem-apply-lsm-edit-plan context (id-plan snapshot) snapshot))))
      (ok (equal before (lem:buffer-text buffer)))
      (let ((buffers (copy-list (lem:buffer-list)))
            (target (notes:notes-workspace-daily-path workspace "2026-09-13")))
        (ok (signals (adapter:lem-open-lsm-daily-note workspace "2026-09-13" :switch-p nil)))
        (ok (equal buffers (lem:buffer-list)) "failed creation never publishes the private buffer")
        (ng (lem:get-file-buffer target)) (ng (probe-file target))
        (ok (= 1 (length (proposal:list-proposals))))))))

(deftest daily-journal-and-capture-stay-unsaved
  (with-notes (directory workspace public)
    (let* ((date "2026-09-13") (time (encode-universal-time 0 0 12 13 9 2026 0))
           (org (merge-pathnames "work/roam/unchanged.org" directory))
           (daily (adapter:lem-open-lsm-daily-note workspace date :switch-p nil))
           (daily-source (lem:buffer-text daily)) (daily-tick (lem:buffer-modified-tick daily)))
      (write-source org "* Org remains authoritative")
      (ok (lem:buffer-modified-p daily)) (ng (probe-file (lem:buffer-filename daily)))
      (ok (eq daily (adapter:lem-open-lsm-daily-note workspace date :switch-p nil)))
      (ok (equal daily-source (lem:buffer-text daily)))
      (ok (= daily-tick (lem:buffer-modified-tick daily)))
      (ok (= (lem:position-at-point (lem:buffer-point daily)) (1+ (search "# 2026-09-13" daily-source))))
      (let* ((journal (adapter:lem-append-lsm-journal-entry workspace time :timezone 0 :switch-p nil))
             (first (lem:buffer-text journal)))
        (adapter:lem-append-lsm-journal-entry workspace (+ time 60) :timezone 0 :switch-p nil)
        (ok (> (length (lem:buffer-text journal)) (length first)))
        (lem:buffer-undo (lem:buffer-point journal))
        (ok (equal first (lem:buffer-text journal)))
        (ng (probe-file (lem:buffer-filename journal))))
      (dolist (key '("i" "t" "r" "p"))
        (let* ((buffer (adapter:lem-capture-lsm-note workspace key "Captured λ" time :timezone 0
                                                   :public-workspace public :body-source "body kept exact" :switch-p nil))
               (snapshot (adapter:lem-current-lsm-snapshot buffer)))
          (ok (search "Captured λ" (lem:buffer-text buffer)))
          (ok (search "body kept exact" (lem:buffer-text buffer)))
          (ok (eq :lsm (notes:semantic-document-format (notes:source-snapshot-document snapshot))))
          (ng (probe-file (lem:buffer-filename buffer)))))
      (ok (signals (adapter:lem-capture-lsm-note workspace "p" "No inferred public root" time :switch-p nil)))
      (ok (equal "* Org remains authoritative" (uiop:read-file-string org))))))

(deftest live-unsaved-text-and-id-command-preserve-disk
  (with-notes (directory workspace public)
    (declare (ignore directory))
    (let ((path (merge-pathnames "identity.md" (notes:notes-workspace-roam-root workspace))))
      (write-source path (source-text))
      (let* ((buffer (lem:find-file-buffer path)) (disk-source (uiop:read-file-string path)))
        (lem:move-to-position (lem:buffer-point buffer) (1+ (search "# Heading" disk-source)))
        (lem:insert-string (lem:buffer-end-point buffer) "human unsaved suffix")
        (let ((before (lem:buffer-text buffer)))
          (ok (equal "node:fixture" (adapter:lem-assign-current-lsm-node-id buffer "node:fixture")))
          (ok (search "human unsaved suffix" (lem:buffer-text buffer)))
          (ok (equal disk-source (uiop:read-file-string path)))
          (let ((tick (lem:buffer-modified-tick buffer)))
            (ok (equal "node:fixture" (adapter:lem-assign-current-lsm-node-id buffer "another-id")))
            (ok (= tick (lem:buffer-modified-tick buffer)) "existing IDs are reused without another edit"))
          (lem:buffer-undo (lem:buffer-point buffer))
          (ok (equal before (lem:buffer-text buffer))))))))

(deftest recovered-text-is-inert-and-closed-review-retains-proposal
  (with-notes (directory workspace public)
    (let* ((buffer (fixture-buffer workspace)) (visits 0)
           (lem:*before-find-file-hook* (list (lambda (&rest ignored) (declare (ignore ignored)) (incf visits))))
           (lem:*find-file-hook* (list (lambda (&rest ignored) (declare (ignore ignored)) (incf visits)))))
      (multiple-value-bind (snapshot context) (adapter:lem-current-lsm-snapshot buffer)
        (let* ((item (adapter:lem-stage-lsm-edit-plan context (id-plan snapshot) snapshot))
               (id (proposal:proposal-id item)))
          (proposal:show-proposal item)
          (lem:delete-buffer (proposal:proposal-review-buffer item))
          (ok (eq item (proposal:find-proposal id)))
          (ok (eq :pending (proposal:proposal-state item)))
          (ok (proposal:show-proposal item))))
      (let* ((store (merge-pathnames "recovery/" directory)) (id (disk:new-id))
             (record (disk:object "version" 1 "id" id "name" "notes fixture"
                                   "filename" (lem:buffer-filename buffer) "text" (lem:buffer-text buffer)
                                   "point" 0 "created" 1 "baseline" "unknown")))
        (disk:ensure-private-directory store)
        (disk:write-private-json store id record)
        (let ((restored (lem-daemon/recovery:restore-checkpoint id :directory store)))
          (ng (lem:buffer-filename restored))
          (ok (equal (lem:buffer-text buffer) (lem:buffer-text restored)))
          (ok (eq :unavailable-buffer (error-code (lambda () (adapter:lem-current-lsm-snapshot restored)))))))
      (ok (zerop visits) "snapshot, staging, review and recovery invoke no file hooks"))))

(deftest deferred-review-refuses-a-reassociated-source
  (with-notes (directory workspace public)
    (let* ((buffer (fixture-buffer workspace)) (before (lem:buffer-text buffer)))
      (multiple-value-bind (snapshot context) (adapter:lem-current-lsm-snapshot buffer)
        (let ((item (adapter:lem-stage-lsm-edit-plan context (id-plan snapshot) snapshot)))
          (setf (lem:buffer-filename buffer) (namestring (merge-pathnames "outside-work.md" directory)))
          (ok (signals (proposal:apply-proposal item) 'proposal:proposal-conflict))
          (ok (eq :source-file-changed (nth-value 1 (proposal:proposal-valid-p item))))
          (ok (equal before (lem:buffer-text buffer)))
          (ng (probe-file (lem:buffer-filename buffer))))))))

(deftest org-and-ordinary-markdown-are-not-converted
  (with-notes (directory workspace public)
    (declare (ignore directory))
    (dolist (fixture '(("ordinary.md" "# Ordinary Markdown") ("original.org" "* Original Org")))
      (destructuring-bind (name text) fixture
        (let ((buffer (lem:find-file-buffer (merge-pathnames name (notes:notes-workspace-roam-root workspace)))))
          (lem:insert-string (lem:buffer-point buffer) text)
          (ok (signals (adapter:lem-current-lsm-snapshot buffer)))
          (ok (equal text (lem:buffer-text buffer)))
          (ng (probe-file (lem:buffer-filename buffer))))))))
