(defpackage :lem-agent/tests
  (:use :cl :rove)
  (:local-nicknames (:agent :lem-agent) (:store :lem-daemon/recovery-store)))
(in-package :lem-agent/tests)

(defun field (object key) (gethash key object))
(defun array-items (value) (coerce value 'list))

(defun await (receipt)
  (multiple-value-bind (value done) (agent:await-request receipt :timeout 8)
    (unless done (error "Agent receipt timed out")) value))

(defun wait-for (predicate)
  (loop repeat 400 when (funcall predicate) return t do (sleep 0.01)
        finally (error "Agent state did not reach the expected condition")))

(defun state (session) (field (agent:session-snapshot session) "status"))
(defun idle (session &optional (turn-count 1))
  (wait-for (lambda ()
              (let ((snapshot (agent:session-snapshot session)))
                (and (equal (field snapshot "status") "idle")
                     (null (field snapshot "active_turn"))
                     (>= (length (field snapshot "turns")) turn-count)
                     (zerop (length (field snapshot "queue"))))))))

(defun decision (session)
  (let ((pending nil))
    (wait-for (lambda ()
                (setf pending (find "pending" (array-items (field (agent:session-snapshot session) "decisions"))
                                    :key (lambda (decision) (field decision "status")) :test #'equal))))
    pending))

(defstruct gate (lock (bt2:make-lock)) (ready (bt2:make-condition-variable)) open)
(defun open-gate (gate)
  (bt2:with-lock-held ((gate-lock gate))
    (setf (gate-open gate) t) (bt2:condition-broadcast (gate-ready gate))))
(defun wait-gate (gate)
  (bt2:with-lock-held ((gate-lock gate))
    (loop until (gate-open gate)
          do (unless (bt2:condition-wait (gate-ready gate) (gate-lock gate) :timeout 8)
               (error "Fake operation gate timed out")))))

(defmacro with-manager ((manager directory) &body body)
  `(let* ((,directory (merge-pathnames (format nil "lem-agent-~a/" (store:new-id))
                                     (uiop:temporary-directory)))
          (,manager (agent:make-manager :directory ,directory)))
     (unwind-protect (progn ,@body)
       (agent:close-manager ,manager :wait t)
       (when (uiop:directory-exists-p ,directory)
         (uiop:delete-directory-tree ,directory :validate t)))))

(defun new-session (manager directory &key limits (provider "fake"))
  (let ((session (agent:create-session manager :provider provider :model "fake-model"
                                              :root directory :limits limits)))
    (await (agent:session-ready session)) session))

(defun request-messages (request) (array-items (field request "messages")))
(defun tool-call (name &optional (arguments (agent:json-object)) (id "call-1"))
  (agent:json-object "id" id "name" name "arguments" arguments))
(defun tool-provider (calls)
  (lambda (request emit context)
    (declare (ignore emit context))
    (if (equal "tool" (field (car (last (request-messages request))) "role"))
        (agent:json-object "content" "tools completed")
        (agent:json-object "tool_calls" calls))))

(defun register-review-fixture (manager executor &optional (arguments (agent:json-object "path" "a.txt" "revision" "old-token"
                                                                                    "original" "before" "replacement" "after")))
  (agent:register-provider manager "fake" (tool-provider (vector (tool-call "propose_edit" arguments))))
  (agent:register-tool manager "propose_edit" :schema (agent:json-object) :validate (constantly t)
                       :retain-for-review t :execute executor))

(defun settle (session)
  (wait-for (lambda () (let ((snapshot (agent:session-snapshot session)))
                        (and (member (field snapshot "status") '("idle" "failed") :test #'equal)
                             (zerop (length (field snapshot "queue"))))))))

(deftest durable-submission-identity-survives-trimming-and-restart
  (with-manager (manager directory)
    (let ((requests 0) (identity (store:new-id)))
      (agent:register-provider manager "fake" (lambda (&rest ignored)
                                               (declare (ignore ignored)) (incf requests)
                                               (agent:json-object "content" "done")))
      (let* ((session (new-session manager directory :limits (agent:json-object "turns" 1)))
             (id (agent:session-id session))
             (result (await (agent:submit-message session "exact λ input" :submission-id identity))))
        (idle session)
        (dotimes (index 3) (await (agent:submit-message session (format nil "later ~d" index))) (idle session))
        (ok (= 3 (field (agent:session-snapshot session) "omitted_turns")))
        (ok (equal result (field (agent:find-submission session identity) "result")))
        (let ((before requests))
          (ok (equal result (await (agent:submit-message session "exact λ input" :submission-id identity))))
          (ok (= before requests) "duplicate identity cannot enqueue a second turn after history trimming")
          (ok (signals (await (agent:submit-message session "different" :submission-id identity))))
          (ok (= before requests)))
        (agent:close-manager manager :wait t)
        (setf manager (agent:make-manager :directory directory))
        (multiple-value-bind (sessions errors) (agent:restore-sessions manager)
          (ok (null errors)) (setf session (first sessions)) (await (agent:session-ready session)))
        (ok (equal id (agent:session-id session)))
        (ok (equal result (field (agent:find-submission session identity) "result")))
        (ok (equal result (await (agent:submit-message session "exact λ input" :submission-id identity))))
        (ok (await (agent:acknowledge-submission session identity)))
        (ng (agent:find-submission session identity))
        (ng (await (agent:acknowledge-submission session identity)))
        (ok (zerop (length (field (store:read-private-json directory id :maximum-depth 24) "submissions"))))))))

(deftest submission-capacity-preserves-pending-decisions
  (with-manager (manager directory)
    (agent:register-provider manager "fake" (constantly (agent:json-object "content" "done")))
    (let ((session (new-session manager directory)) (identities nil))
      (dotimes (index 32)
        (let ((id (store:new-id)))
          (push id identities)
          (await (agent:submit-message session (format nil "fill ~d" index) :submission-id id))
          (idle session)))
      (let ((snapshot (agent:session-snapshot session)))
        (ok (signals (await (agent:submit-message session "overflow" :submission-id (store:new-id)))))
        (ok (equalp snapshot (agent:session-snapshot session)) "quota rejection changes neither input nor lifecycle"))
      (agent:register-provider manager "fake"
                               (constantly (agent:json-object "clarification"
                                                              (agent:json-object "question" "Choose" "choices" #("one" "two")))))
      (await (agent:submit-message session "ask"))
      (let* ((pending (decision session)) (id (field pending "id")) (submission-id (store:new-id)))
        (ok (signals (await (agent:resolve-decision session id "one" :submission-id submission-id))))
        (ok (equalp pending (decision session)) "receipt capacity is checked before resolving a decision")
        (await (agent:acknowledge-submission session (first identities)))
        (agent:register-provider manager "fake" (constantly (agent:json-object "content" "done")))
        (ok (await (agent:resolve-decision session id "one" :submission-id submission-id)))
        (idle session)
        (ok (await (agent:resolve-decision session id "one" :submission-id submission-id)))
        (ok (signals (await (agent:resolve-decision session id "two" :submission-id submission-id))))
        (ok (signals (await (agent:submit-message session "one" :submission-id submission-id))))
        (ok (eq t (field (agent:find-submission session submission-id) "result")))
        (ok (agent::validate-restored-record (agent:session-id session)
                                           (store:read-private-json directory (agent:session-id session) :maximum-depth 24)))
        (agent:close-manager manager :wait t)
        (setf manager (agent:make-manager :directory directory))
        (multiple-value-bind (sessions errors) (agent:restore-sessions manager)
          (ok (null errors)) (setf session (first sessions)) (await (agent:session-ready session)))
        (ok (eq t (field (agent:find-submission session submission-id) "result")))
        (ok (eq t (await (agent:resolve-decision session id "one" :submission-id submission-id)))
            "restored clarification receipts preserve the public true result without replay")
        (dolist (invalid (list yason:false nil #()))
          (let* ((record (agent:session-snapshot session))
                 (item (find submission-id (gethash "submissions" record)
                             :key (lambda (item) (gethash "id" item)) :test #'equal)))
            (setf (gethash "result" item) invalid)
            (ok (signals (agent::validate-restored-record (agent:session-id session) record)))))
        (dolist (field '("kind" "digest" "decision_id" "result"))
          (let* ((record (agent:session-snapshot session))
                 (item (find submission-id (gethash "submissions" record)
                             :key (lambda (item) (gethash "id" item)) :test #'equal)))
            (setf (gethash field item) "invalid")
            (ok (signals (agent::validate-restored-record (agent:session-id session) record)))))))))

(deftest submission-write-failure-does-not-publish-acceptance
  (with-manager (manager directory)
    (let* ((session (new-session manager directory)) (id (store:new-id))
           (write (symbol-function 'store:write-private-json)))
      (unwind-protect
           (progn
             (setf (symbol-function 'store:write-private-json)
                   (lambda (directory identifier record &rest options)
                     (when (and (equal identifier (agent:session-id session))
                                (plusp (length (field record "submissions"))))
                       (error "injected journal failure"))
                     (apply write directory identifier record options)))
             (ok (signals (await (agent:submit-message session "retained draft" :submission-id id))))
             (ok (signals (agent:find-submission session id)) "uncertain in-memory publication cannot prove acceptance")
             (ok (signals (await (agent:submit-message session "retained draft" :submission-id id))))
             (ok (zerop (length (field (store:read-private-json directory (agent:session-id session) :maximum-depth 24)
                                      "submissions")))))
        (setf (symbol-function 'store:write-private-json) write)))))

(deftest retained-review-durable-before-effect-and-independent-of-history
  (with-manager (manager directory)
    (let ((durable nil)
          (result (agent:json-object "proposal_id" "historical-proposal"
                                     "needs_activation" yason:false "reviewed" yason:true
                                     "optional" nil "empty" #()
                                     "nested" (vector nil yason:false #()))))
      (register-review-fixture
       manager (lambda (arguments context)
                 (let* ((disk (store:read-private-json directory (agent:operation-session-id context) :maximum-depth 24))
                        (review (first (array-items (field disk "retained_reviews")))))
                   (setf durable (and (equalp arguments (field review "arguments"))
                                      (equal "executing" (field review "status"))
                                      (= 0 (field review "generation")))))
                 result))
      (let ((session (new-session manager directory :limits (agent:json-object "turns" 1))))
        (await (agent:submit-message session "stage")) (idle session)
        (ok durable "the complete candidate is fsynced before the executor runs")
        (let* ((review (first (agent:list-retained-reviews session))) (id (field review "id")))
          (ok (equal "returned" (field review "status"))) (ok (= 1 (field review "generation")))
          (setf (gethash "original" (field review "arguments")) "tampered")
          (ok (equal "before" (field (field (agent:find-retained-review session id) "arguments") "original")))
          (agent:register-provider manager "fake" (constantly (agent:json-object "content" "ordinary turn")))
          (dotimes (index 20)
            (await (agent:submit-message session (format nil "ordinary ~d" index))) (idle session))
          (ok (>= (field (agent:session-snapshot session) "omitted_turns") 20))
          (ok (agent:find-retained-review session id) "turn eviction cannot evict a retained candidate")
          (agent:close-manager manager :wait t)
          (let ((reopened (agent:make-manager :directory directory)))
            (unwind-protect
                 (multiple-value-bind (sessions errors) (agent:restore-sessions reopened)
                   (ok (null errors))
                   (let ((restored (first sessions)))
                     (await (agent:session-ready restored))
                     (ok (equalp result (field (agent:find-retained-review restored id) "result"))
                         "a completed candidate restores exact JSON values after its originating turn is gone")))
              (agent:close-manager reopened :wait t))))))))

(deftest retained-review-quota-and-explicit-discard
  (with-manager (manager directory)
    (let ((executions 0))
      (ok (signals (agent:register-tool manager "invalid" :schema (agent:json-object) :validate (constantly t)
                                        :execute (constantly nil) :retain-for-review :yes)))
      (register-review-fixture manager (lambda (arguments context)
                                        (declare (ignore arguments context)) (incf executions) "candidate"))
      (let ((session (new-session manager directory :limits (agent:json-object "turns" 1))))
        (dotimes (index 16)
          (await (agent:submit-message session (format nil "stage ~d" index))) (idle session))
        (await (agent:submit-message session "full")) (settle session)
        (ok (equal "failed" (state session)))
        (ok (= 16 executions (length (agent:list-retained-reviews session)))
            "full retention fails before the next executor, preserving every older candidate")
        (let* ((review (first (agent:list-retained-reviews session))) (id (field review "id")))
          (ok (signals (await (agent:discard-retained-review session id :expected-generation 0))))
          (ok (await (agent:discard-retained-review session id :expected-generation 1)))
          (ok (null (await (agent:discard-retained-review session id :expected-generation 1))))
          (ok (null (agent:find-retained-review session id)))
          (await (agent:submit-message session "capacity released")) (idle session)
          (ok (= 17 executions))
          (ok (not (find id (agent:list-retained-reviews session) :key (lambda (entry) (field entry "id")) :test #'equal))))))))

(deftest retained-review-byte-reservation-and-result-shape
  (with-manager (manager directory)
    (let ((executions 0))
      (register-review-fixture manager (lambda (arguments context)
                                        (declare (ignore arguments context)) (incf executions)
                                        (make-string 30000 :initial-element #\x))
                               (agent:json-object "large" (make-string 12000 :initial-element #\a)))
      (let ((session (new-session manager directory :limits (agent:json-object "turns" 1))))
        (loop repeat 16 do (await (agent:submit-message session "large candidate")) (settle session)
              when (equal "failed" (state session)) return nil)
        (ok (< 1 executions 16) "aggregate quota reserves the result before the count quota is reached")
        (ok (= executions (length (agent:list-retained-reviews session))))
        (ok (<= (agent::encoded-size (field (agent:session-snapshot session) "retained_reviews")) (* 512 1024))))))
  (with-manager (manager directory)
    (register-review-fixture manager (lambda (arguments context)
                                      (declare (ignore arguments context)) (make-array 2000 :initial-element 0)))
    (let ((session (new-session manager directory)))
      (await (agent:submit-message session "large shape")) (idle session)
      (let ((review (first (agent:list-retained-reviews session))))
        (ok (equal "unknown" (field review "status")))
        (ok (search "omitted" (field (field review "result") "error")))
        (ok (equal "after" (field (field review "arguments") "replacement"))
            "an excessive result shape cannot discard the original candidate")))))

(deftest retained-review-combined-json-budget-prevents-execution
  (with-manager (manager directory)
    (let ((executions 0) (bulk 0))
      (agent:register-provider manager "fake"
                               (tool-provider (vector (tool-call "bulk" (agent:json-object) "bulk-1")
                                                      (tool-call "bulk" (agent:json-object) "bulk-2")
                                                      (tool-call "retained" (agent:json-object) "candidate"))))
      (agent:register-tool manager "bulk" :schema (agent:json-object) :validate (constantly t)
                           :execute (lambda (arguments context)
                                      (declare (ignore arguments context)) (incf bulk)
                                      (map 'vector (lambda (ignored) (declare (ignore ignored))
                                                     (make-array 970 :initial-element 0)) (make-array 10))))
      (agent:register-tool manager "retained" :schema (agent:json-object) :validate (constantly t)
                           :retain-for-review t :execute (lambda (arguments context)
                                                         (declare (ignore arguments context)) (incf executions)))
      (let ((session (new-session manager directory)))
        (await (agent:submit-message session "reserve combined graph"))
        (wait-for (lambda () (equal "failed" (state session))))
        (ok (and (= 2 bulk) (zerop executions))
            "JSON node reservation prevents execution before result copies could exceed the journal budget")
        (let ((disk (store:read-private-json directory (agent:session-id session) :maximum-depth 24)))
          (ok (<= (agent::json-shape (agent:json-copy disk)) 20000))
          (ok (agent::validate-restored-record (agent:session-id session) disk)))))))

(deftest retained-review-reserves-current-turn-budget
  (dolist (result-limit '(32768 256))
    (with-manager (manager directory)
      (let ((executions 0))
        (register-review-fixture manager (lambda (arguments context)
                                          (declare (ignore arguments context)) (incf executions) "candidate"))
        (let ((session (new-session manager directory :limits (agent:json-object "history" 4096 "result" result-limit))))
          (await (agent:submit-message session "bounded turn")) (settle session)
          (ok (= executions (if (= result-limit 256) 1 0))
              "the current turn reserves the permitted result size before its executor")
          (ok (equal (state session) (if (= result-limit 256) "idle" "failed"))))))))

(deftest retained-review-failed-result-append-remains-recoverable
  (with-manager (manager directory)
    (let ((original (symbol-function 'agent::append-message)))
      (register-review-fixture manager (lambda (arguments context) (declare (ignore arguments context)) "candidate"))
      (let ((session (new-session manager directory)))
        (unwind-protect
             (progn
               (setf (symbol-function 'agent::append-message)
                     (lambda (target message)
                       (when (and (eq target session) (equal "tool" (field message "role")))
                         (error "Injected result append failure"))
                       (funcall original target message)))
               (await (agent:submit-message session "result failure"))
               (wait-for (lambda () (equal "failed" (state session))))
               (ok (equal "unknown" (field (first (agent:list-retained-reviews session)) "status")))
               (ok (agent::validate-restored-record
                    (agent:session-id session) (store:read-private-json directory (agent:session-id session) :maximum-depth 24))
                   "failed transcript insertion cannot leave a conflicting returned archive record"))
          (setf (symbol-function 'agent::append-message) original))))))

(deftest retained-review-write-failure-never-launches
  (dolist (after-rename '(nil t))
    (with-manager (manager directory)
      (let ((executions 0) (injected nil) (original (symbol-function 'store:write-private-json)))
        (register-review-fixture manager (lambda (arguments context)
                                          (declare (ignore arguments context)) (incf executions)))
        (let ((session (new-session manager directory)))
          (unwind-protect
               (progn
                 (setf (symbol-function 'store:write-private-json)
                       (lambda (path id record &rest options)
                         (if (and (equal id (agent:session-id session))
                                  (plusp (length (field record "retained_reviews"))))
                             (progn (setf injected t)
                                    (when after-rename (apply original path id record options))
                                    (error "Injected review checkpoint failure"))
                             (apply original path id record options))))
                 (await (agent:submit-message session "no durable retention"))
                 (wait-for (lambda () (equal "failed" (state session))))
                 (ok (and injected (zerop executions)) "failed or uncertain retention never launches the executor"))
            (setf (symbol-function 'store:write-private-json) original))
          (agent:close-manager manager :wait t)
          (let ((reopened (agent:make-manager :directory directory)))
            (unwind-protect
                 (multiple-value-bind (sessions errors) (agent:restore-sessions reopened)
                   (ok (null errors))
                   (let ((restored (first sessions)))
                     (await (agent:session-ready restored))
                     (ok (every (lambda (review) (equal "unknown" (field review "status")))
                                (agent:list-retained-reviews restored)))
                     (ok (zerop executions))))
              (agent:close-manager reopened :wait t))))))))

(deftest retained-review-shutdown-discards-late-results
  (with-manager (manager directory)
    (let ((gate (make-gate)) (entered nil) (cancelled nil) (reopened nil))
      (register-review-fixture manager (lambda (arguments context)
                                        (declare (ignore arguments))
                                        (agent:register-cancellation context (lambda () (setf cancelled t)))
                                        (setf entered t) (wait-gate gate)
                                        (agent:json-object "proposal_id" "late")))
      (let ((session (new-session manager directory)))
        (unwind-protect
             (progn
               (await (agent:submit-message session "uncooperative")) (wait-for (lambda () entered))
               (let* ((review (first (agent:list-retained-reviews session))) (id (field review "id")))
                 (ok (signals (await (agent:discard-retained-review session id :expected-generation 0))))
                 (agent:close-manager manager :wait t) (wait-for (lambda () cancelled))
                 (setf reopened (agent:make-manager :directory directory))
                 (multiple-value-bind (sessions errors) (agent:restore-sessions reopened)
                   (ok (null errors))
                   (let ((restored (first sessions)))
                     (await (agent:session-ready restored))
                     (let ((before (agent:find-retained-review restored id)))
                       (ok (and (equal "unknown" (field before "status")) (= 1 (field before "generation"))))
                       (open-gate gate)
                       (dolist (entry (agent::session-workers session)) (bt2:join-thread (car entry)))
                       (ok (equalp before (agent:find-retained-review restored id))
                           "an old worker cannot update the new owner's archive")
                       (ok (await (agent:discard-retained-review restored id :expected-generation 1))))))))
          (open-gate gate)
          (when reopened (agent:close-manager reopened :wait t)))))))

(deftest retained-review-result-space-survives-queued-escaping
  (with-manager (manager directory)
    (let ((gate (make-gate)) (entered nil))
      (register-review-fixture manager (lambda (arguments context)
                                        (declare (ignore arguments context)) (setf entered t) (wait-gate gate)
                                        (make-string 5000 :initial-element #\Null)))
      (let ((session (new-session manager directory :limits (agent:json-object "turns" 1))))
        (unwind-protect
             (progn
               (await (agent:submit-message session "large queued input")) (wait-for (lambda () entered))
               (let ((accepted 0) (rejected 0))
                 (dotimes (index 8)
                   (declare (ignore index))
                   (handler-case (progn (await (agent:submit-message session (make-string 65536 :initial-element #\Null)))
                                        (incf accepted))
                     (agent::request-rejected () (incf rejected))))
                 (ok (and (plusp accepted) (plusp rejected)))
                 (ok (equal "running" (state session))
                     "encoded-byte admission rejects excessive follow-ups without interrupting the retained tool")
                 (ok (not (agent::session-poisoned session)))
                 ;; Follow-ups should be ordinary completed messages, not another retained tool.
                 (agent:register-provider manager "fake" (constantly (agent:json-object "content" "done")))
                 (open-gate gate) (idle session)
                 (let ((review (first (agent:list-retained-reviews session))))
                   (ok (equal "returned" (field review "status")))
                   (ok (= 5000 (length (field review "result"))))
                   (ok (agent::validate-restored-record
                        (agent:session-id session)
                        (store:read-private-json directory (agent:session-id session) :maximum-depth 24))))))
          (open-gate gate))))))

(deftest retained-review-failed-discard-and-closed-record-cleanup
  (with-manager (manager directory)
    (register-review-fixture manager (lambda (arguments context) (declare (ignore arguments context)) "candidate"))
    (let ((session (new-session manager directory)) (original (symbol-function 'store:write-private-json)))
      (await (agent:submit-message session "candidate")) (idle session)
      (let* ((review (first (agent:list-retained-reviews session))) (id (field review "id")))
        (unwind-protect
             (progn
               (setf (symbol-function 'store:write-private-json)
                     (lambda (path key record &rest options)
                       (if (equal key (agent:session-id session)) (error "Injected discard write failure")
                           (apply original path key record options))))
               (ok (signals (await (agent:discard-retained-review session id :expected-generation 1))))
               (wait-for (lambda () (agent::session-poisoned session)))
               (ok (agent:find-retained-review session id) "a failed discard keeps the historical live copy"))
          (setf (symbol-function 'store:write-private-json) original))
        (await (agent:close-session session))
        (ok (signals (await (agent:discard-retained-review session id :expected-generation 1))))
        (agent:close-manager manager :wait t)
        (let ((reopened (agent:make-manager :directory directory)))
          (unwind-protect
               (multiple-value-bind (sessions errors) (agent:restore-sessions reopened)
                 (ok (null errors))
                 (let ((restored (first sessions)))
                   (await (agent:session-ready restored))
                   (ok (equal "closed" (state restored)))
                   (ok (await (agent:discard-retained-review restored id :expected-generation 1)))
                   (ok (equal "closed" (state restored)) "archive cleanup cannot reopen a permanently closed session")))
            (agent:close-manager reopened :wait t)))))))

(deftest invalid-retained-reviews-and-empty-schema-default
  (with-manager (manager directory)
    (register-review-fixture manager (lambda (arguments context) (declare (ignore arguments context)) "candidate"))
    (let ((session (new-session manager directory)))
      (await (agent:submit-message session "candidate")) (idle session)
      (let ((baseline (store:read-private-json directory (agent:session-id session) :maximum-depth 24)))
        (dolist (mutate
                  (list (lambda (record) (setf (gethash "retained_reviews" record) "invalid"))
                        (lambda (record) (setf (gethash "retained_reviews" record)
                                              (concatenate 'vector (field record "retained_reviews") (field record "retained_reviews"))))
                        (lambda (record) (setf (gethash "generation" (aref (field record "retained_reviews") 0)) 0))
                        (lambda (record) (setf (gethash "status" (aref (field record "retained_reviews") 0)) "approved"))
                        (lambda (record) (setf (gethash "arguments" (aref (field record "retained_reviews") 0)) (agent:json-object "forged" t)))
                        (lambda (record) (setf (gethash "result" (aref (field record "retained_reviews") 0)) (make-array 300 :initial-element 0)))
                        (lambda (record) (setf (gethash "extra" (aref (field record "retained_reviews") 0)) t))
                        (lambda (record)
                          (setf (gethash "queue" record)
                                (map 'vector (lambda (ignored) (declare (ignore ignored))
                                               (agent:json-object "id" (store:new-id) "text"
                                                                 (make-string 65536 :initial-element #\Null)))
                                     (make-array 8))))))
          (with-manager (restored copy-directory)
            (let* ((record (agent:json-copy baseline)) (id (agent:session-id session)))
              (funcall mutate record)
              (let* ((path (store:write-private-json copy-directory id record :maximum-depth 24))
                     (before (uiop:read-file-string path)))
                (multiple-value-bind (sessions errors) (agent:restore-sessions restored)
                  (ok (and (null sessions) (= 1 (length errors)))))
                (ok (equal before (uiop:read-file-string path)) "invalid archives remain byte-for-byte untouched")))))
        (with-manager (restored copy-directory)
          (remhash "retained_reviews" baseline)
          (store:write-private-json copy-directory (agent:session-id session) baseline :maximum-depth 24)
          (multiple-value-bind (sessions errors) (agent:restore-sessions restored)
            (ok (null errors))
            (await (agent:session-ready (first sessions)))
            (ok (null (agent:list-retained-reviews (first sessions)))
                "a journal without the new field normalizes to an empty archive")))))))

(deftest independent-sessions-streams-and-views
  (with-manager (manager directory)
    (let ((slow-gate (make-gate)) (entered nil) (seen nil))
      (agent:register-provider
       manager "slow"
       (lambda (request emit context)
         (declare (ignore request))
         (agent:register-cancellation context (lambda () (open-gate slow-gate)))
         (setf entered t) (wait-gate slow-gate)
         (funcall emit "hel") (funcall emit "lo λ") (agent:json-object)))
      (agent:register-provider manager "fake"
                               (lambda (request emit context)
                                 (declare (ignore request context))
                                 (warn "Nonfatal provider warning")
                                 (funcall emit "fast") (agent:json-object)))
      (let ((slow (new-session manager directory :provider "slow"))
            (fast (new-session manager directory)))
        (unwind-protect
             (progn
               (let ((view (agent:subscribe-session slow (lambda (event) (push event seen)))))
                 (await (agent:submit-message slow "wait"))
                 (wait-for (lambda () entered))
                 (agent:unsubscribe-session slow view))
               (agent:subscribe-session fast (lambda (event) (declare (ignore event))
                                              (warn "Nonfatal view warning") (error "broken view")))
               (await (agent:submit-message fast "go")) (idle fast)
               (ok (equal "running" (state slow)) "a blocked provider does not stall another session")
               (let* ((snapshot (agent:session-snapshot fast))
                      (message (aref (field (aref (field snapshot "turns") 0) "messages") 0)))
                 (setf (gethash "content" message) "tampered"))
               (ok (equal "go" (field (aref (field (aref (field (agent:session-snapshot fast) "turns") 0)
                                                       "messages") 0) "content"))
                   "snapshots do not share nested mutable objects")
               (open-gate slow-gate) (idle slow)
               (ok (equal "hello λ" (field (aref (field (aref (field (agent:session-snapshot slow) "turns") 0)
                                                            "messages") 1) "content"))
                   "fragmented streaming completes after the view has closed")
               (ok (plusp (length (field (agent:session-snapshot fast) "diagnostics")))
                   "subscriber exceptions are isolated and recorded")
               (ok (null (find-package :lem-core)) "the core has no editor or extension dependency"))
          (open-gate slow-gate))))))

(deftest submission-real-process-crash-boundaries
  (dolist (phase '("submission-before" "submission-after"))
    (let* ((directory (merge-pathnames (format nil "lem-submission-crash-~a/" (store:new-id)) (uiop:temporary-directory)))
           (ready (merge-pathnames "ready.txt" directory)) (log (merge-pathnames "worker.log" directory))
           (process nil))
      (unwind-protect
           (progn
             (store:ensure-private-directory directory)
             (setf process
                   (sb-ext:run-program
                    (namestring sb-ext:*runtime-pathname*)
                    (list "--noinform" "--no-sysinit" "--no-userinit" "--script"
                          (namestring (asdf:system-relative-pathname "lem-agent" "tests/crash-worker.lisp"))
                          (namestring (asdf:system-source-directory "lem")) (namestring directory) phase)
                    :search nil :wait nil :input nil :output log :error :output))
             (loop repeat 1500 until (probe-file ready)
                   do (unless (sb-ext:process-alive-p process)
                        (error "Submission crash worker exited early: ~a" (uiop:read-file-string log)))
                      (sleep 0.01)
                   finally (unless (probe-file ready) (error "Submission crash worker did not reach boundary")))
             (ok (signals (agent:make-manager :directory directory)) "a live original host excludes recovery")
             (sb-ext:process-kill process sb-posix:sigkill) (sb-ext:process-wait process)
             (let ((manager (agent:make-manager :directory directory)) (requests 0))
               (unwind-protect
                    (progn
                      (agent:register-provider manager "fake" (lambda (&rest ignored) (declare (ignore ignored)) (incf requests)))
                      (multiple-value-bind (sessions errors) (agent:restore-sessions manager)
                        (ok (null errors))
                        (let ((session (first sessions)))
                          (await (agent:session-ready session))
                          (ok (eq (not (null (agent:find-submission session "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")))
                                  (equal phase "submission-after"))
                              "the same session checkpoint distinguishes durable acceptance before UI cleanup")
                          (ok (= (if (equal phase "submission-after") 1 0)
                                 (length (field (agent:session-snapshot session) "queue"))))
                          (ok (zerop requests) "restoration never replays the accepted or unaccepted submission"))))
                 (agent:close-manager manager :wait t))))
        (when process
          (when (sb-ext:process-alive-p process) (sb-ext:process-kill process sb-posix:sigkill))
          (sb-ext:process-wait process) (sb-ext:process-close process))
        (when (uiop:directory-exists-p directory) (uiop:delete-directory-tree directory :validate t))))))

(deftest retained-review-real-process-crash-boundaries
  (dolist (phase '("review-before" "review-after" "review-returned"))
    (let* ((directory (merge-pathnames (format nil "lem-agent-review-crash-~a/" (store:new-id)) (uiop:temporary-directory)))
           (ready (merge-pathnames "ready.txt" directory)) (log (merge-pathnames "worker.log" directory))
           (effect (merge-pathnames "effect.txt" directory)) (process nil))
      (unwind-protect
           (progn
             (store:ensure-private-directory directory)
             (setf process
                   (sb-ext:run-program
                    (namestring sb-ext:*runtime-pathname*)
                    (list "--noinform" "--no-sysinit" "--no-userinit" "--script"
                          (namestring (asdf:system-relative-pathname "lem-agent" "tests/crash-worker.lisp"))
                          (namestring (asdf:system-source-directory "lem")) (namestring directory) phase)
                    :search nil :wait nil :input nil :output log :error :output))
             (loop repeat 1500 until (probe-file ready)
                   do (unless (sb-ext:process-alive-p process)
                        (error "Review crash worker exited early: ~a" (uiop:read-file-string log)))
                      (sleep 0.01)
                   finally (unless (probe-file ready) (error "Review crash worker did not reach its boundary")))
             (ok (signals (agent:make-manager :directory directory)) "the original actor owns the journal lease")
             (sb-ext:process-kill process sb-posix:sigkill) (sb-ext:process-wait process)
             (let ((manager (agent:make-manager :directory directory)) (requests 0))
               (unwind-protect
                    (progn
                      (agent:register-provider manager "fake" (lambda (&rest ignored) (declare (ignore ignored)) (incf requests)))
                      (multiple-value-bind (sessions errors) (agent:restore-sessions manager)
                        (ok (null errors))
                        (let ((session (first sessions)))
                          (await (agent:session-ready session))
                          (let ((review (first (agent:list-retained-reviews session))))
                            (ok (equal "new" (field (field review "arguments") "replacement")))
                            (ok (equal (field review "status")
                                       (if (equal phase "review-returned") "returned" "unknown")))
                            (ok (= 1 (field review "generation")))
                            (ok (if (equal phase "review-returned")
                                    (equal "recorded-proposal" (field (field review "result") "proposal_id"))
                                    (equal "unknown" (field (field review "result") "outcome"))))
                            (ok (zerop requests) "recovery does not replay either a pre-execution intent or a possibly completed effect")
                            (ok (if (equal phase "review-before") (null (probe-file effect))
                                    (equal '("effect") (uiop:read-file-lines effect))))))))
                 (agent:close-manager manager :wait t))))
        (when process
          (when (sb-ext:process-alive-p process) (sb-ext:process-kill process sb-posix:sigkill))
          (sb-ext:process-wait process) (sb-ext:process-close process))
        (when (uiop:directory-exists-p directory) (uiop:delete-directory-tree directory :validate t))))))

(deftest approval-is-durable-and-resolves-once
  (with-manager (manager directory)
    (let ((executions 0) (durable-before-action nil) (results '()) (lock (bt2:make-lock)))
      (agent:register-provider manager "fake" (tool-provider (vector (tool-call "change" (agent:json-object "n" 3)))))
      (agent:register-tool
       manager "change" :schema (agent:json-object "type" "object")
       :validate (lambda (arguments) (= 3 (field arguments "n"))) :permission t
       :execute
       (lambda (arguments context)
         (declare (ignore arguments))
         (let* ((record (store:read-private-json directory (agent:operation-session-id context) :maximum-depth 24))
                (decision (first (array-items (field record "decisions"))))
                (turn (first (array-items (field record "turns")))))
           (setf durable-before-action (and (equal "resolved" (field decision "status"))
                                           (equal "allow" (field decision "answer"))
                                           (equal '("call-1") (array-items (field turn "started_tools"))))))
         (incf executions) (agent:json-object "changed" t)))
      (let* ((session (new-session manager directory)) (request (agent:submit-message session "change it")))
        (await request)
        (let* ((pending (decision session)) (id (field pending "id"))
               (disk (store:read-private-json directory (agent:session-id session) :maximum-depth 24)))
          (ok (equal id (field (first (array-items (field disk "decisions"))) "id"))
              "pending permission has a durable stable identifier")
          (ok (zerop executions) "a pending decision is not approval")
          (let ((threads
                  (loop repeat 12 collect
                        (bt2:make-thread
                         (lambda ()
                           (let ((result (await (agent:resolve-decision session id "allow"))))
                             (bt2:with-lock-held (lock) (push result results))))))))
            (dolist (thread threads) (bt2:join-thread thread)))
          (idle session)
          (ok (= 1 (count t results)) "concurrent resolutions have exactly one winner")
          (ok (= 1 executions) "one approval dispatches the tool once")
          (ok durable-before-action "resolution and execution intent reach disk before the tool runs")
          (ok (null (await (agent:resolve-decision session id "deny")))))))))

(deftest malformed-unknown-and-failing-tools
  (with-manager (manager directory)
    (let ((executions 0))
      (agent:register-provider
       manager "fake"
       (tool-provider (vector (tool-call "missing" (agent:json-object) "unknown")
                              (tool-call "safe" "not parsed JSON" "malformed")
                              (tool-call "safe" (agent:json-object "n" -1) "invalid")
                              (tool-call "throws" (agent:json-object) "throws")
                              (tool-call "safe" (agent:json-object "n" 4) "valid"))))
      (agent:register-tool manager "safe" :schema (agent:json-object "type" "object")
                           :validate (lambda (arguments) (and (integerp (field arguments "n"))
                                                              (plusp (field arguments "n"))))
                           :execute (lambda (arguments context)
                                      (declare (ignore arguments context)) (incf executions) "safe result"))
      (agent:register-tool manager "throws" :schema (agent:json-object)
                           :validate (constantly t) :execute (lambda (arguments context)
                                                              (declare (ignore arguments context))
                                                              (error "API_TOKEN=must-not-be-journaled")))
      (let ((session (new-session manager directory)))
        (await (agent:submit-message session "exercise tools")) (idle session)
        (let* ((messages (field (aref (field (agent:session-snapshot session) "turns") 0) "messages"))
               (results (remove-if-not (lambda (message) (equal "tool" (field message "role")))
                                       (array-items messages))))
          (ok (= 1 executions) "only a registered tool with valid arguments executes")
          (ok (= 5 (length results)) "every requested call gets one success or failure result")
          (ok (= 4 (count-if (lambda (message) (hash-table-p (field message "content"))) results))))
        (ok (not (search "must-not-be-journaled"
                         (uiop:read-file-string (merge-pathnames (format nil "~a.json" (agent:session-id session)) directory))))
            "arbitrary provider/tool error arguments are not copied into the journal")))))

(deftest clarification-denial-and-follow-up-queue
  (with-manager (manager directory)
    (let ((calls 0) (executions 0))
      (agent:register-provider
       manager "fake"
       (lambda (request emit context)
         (declare (ignore request emit context))
         (case (incf calls)
           (1 (agent:json-object "clarification" (agent:json-object "question" "Choose" "choices" #("one" "two"))))
           (2 (agent:json-object "tool_calls" (vector (tool-call "write"))))
           (otherwise (agent:json-object "content" "done")))))
      (agent:register-tool manager "write" :schema (agent:json-object) :validate (constantly t)
                           :permission t :execute (lambda (arguments context)
                                                    (declare (ignore arguments context)) (incf executions)))
      (let ((session (new-session manager directory :limits (agent:json-object "queued" 1))))
        (await (agent:submit-message session "first"))
        (let ((id (field (decision session) "id")))
          (await (agent:submit-message session "follow up"))
          (ok (signals (await (agent:submit-message session "overflow"))))
          (ok (signals (await (agent:resolve-decision session id "invalid"))))
          (ok (equal "waiting" (state session)) "invalid answers preserve the pending decision")
          (await (agent:resolve-decision session id "two")))
        (await (agent:resolve-decision session (field (decision session) "id") "deny"))
        (idle session 2)
        (ok (zerop executions) "denial never invokes the tool")
        (ok (= 4 calls) "follow-up starts only after the current turn's tool round completes")))))

(deftest interrupt-and-late-registration
  (with-manager (manager directory)
    (let ((gate (make-gate)) (entered nil) (saved-emit nil) (saved-context nil)
          (cancelled nil) (registered-after nil))
      (agent:register-provider
       manager "fake"
       (lambda (request emit context)
         (declare (ignore request))
         (setf saved-emit emit saved-context context entered t)
         (agent:register-cancellation context (lambda () (setf cancelled t)))
         (wait-gate gate)
         (funcall emit "late mutation") (agent:json-object "content" "late mutation")))
      (let ((session (new-session manager directory)))
        (unwind-protect
             (progn
               (await (agent:submit-message session "slow")) (wait-for (lambda () entered))
               (await (agent:interrupt-session session))
               (wait-for (lambda () cancelled))
               (ok (null (agent:operation-live-p saved-context)))
               (ok (signals (agent:check-operation saved-context)))
               (agent:register-cancellation saved-context (lambda () (setf registered-after t)))
               (wait-for (lambda () registered-after))
               (ok (null (funcall saved-emit "must be ignored")))
               (open-gate gate)
               (wait-for (lambda () (plusp (length (field (agent:session-snapshot session) "diagnostics")))))
               (ok (equal "interrupted" (state session)) "an uncooperative late return cannot finish the interrupted turn")
               (ok (equal "" (field (agent:session-snapshot session) "stream"))))
          (open-gate gate))))))

(deftest stream-and-round-budgets
  (with-manager (manager directory)
    (agent:register-provider manager "overflow"
                             (lambda (request emit context)
                               (declare (ignore request context))
                               ;; Catching the callback error cannot bypass the core limit.
                               (ignore-errors (funcall emit (make-string 100 :initial-element #\x)))
                               (agent:json-object)))
    (let ((session (new-session manager directory :provider "overflow" :limits (agent:json-object "stream" 16))))
      (await (agent:submit-message session "stream"))
      (wait-for (lambda () (equal "failed" (state session))))
      (ok (<= (length (field (agent:session-snapshot session) "stream")) 16)))
    (let ((executions 0) (rounds 0))
      (agent:register-provider manager "fake"
                               (lambda (request emit context)
                                 (declare (ignore request emit context))
                                 (agent:json-object "tool_calls" (vector (tool-call "loop" (agent:json-object)
                                                                                 (format nil "call-~d" (incf rounds)))))))
      (agent:register-tool manager "loop" :schema (agent:json-object) :validate (constantly t)
                           :execute (lambda (arguments context) (declare (ignore arguments context)) (incf executions)))
      (let ((session (new-session manager directory :limits (agent:json-object "rounds" 2))))
        (await (agent:submit-message session "loop"))
        (wait-for (lambda () (equal "failed" (state session))))
        (ok (= executions rounds 2) "the Lisp turn loop enforces its round budget before another request")))))

(deftest restart-preserves-decisions-without-replaying-tools
  (dolist (phase '(:permission :running-tool))
    (with-manager (manager directory)
      (let ((gate (make-gate)) (executions 0) (entered nil))
        (agent:register-provider manager "fake" (tool-provider (vector (tool-call "effect"))))
        (agent:register-tool
         manager "effect" :schema (agent:json-object) :validate (constantly t) :permission t
         :execute (lambda (arguments context)
                    (declare (ignore arguments))
                    (agent:register-cancellation context (lambda () (open-gate gate)))
                    (incf executions) (setf entered t) (wait-gate gate) "completed"))
        (let ((session (new-session manager directory)))
          (unwind-protect
               (progn
                 (await (agent:submit-message session "effect"))
                 (let ((id (field (decision session) "id")))
                   (await (agent:submit-message session "deliberate follow-up"))
                   (when (eq phase :running-tool)
                     (await (agent:resolve-decision session id "allow"))
                     (wait-for (lambda () entered)))
                   ;; Copy the actual durable crash boundary into a fresh manager
                   ;; namespace; the old process stack is deliberately unavailable.
                   (let ((record (store:read-private-json directory (agent:session-id session) :maximum-depth 24)))
                     (with-manager (restored-manager restored-directory)
                       (let ((requests 0))
                         (agent:register-provider
                          restored-manager "fake"
                          (lambda (request emit context)
                            (declare (ignore emit context))
                            (incf requests)
                            (let ((calls 0) (results 0))
                              (dolist (message (request-messages request))
                                (incf calls (length (field message "tool_calls")))
                                (when (equal "tool" (field message "role")) (incf results)))
                              (unless (= calls results) (error "Unpaired call in restored context")))
                            (agent:json-object "content" "fresh work")))
                         (store:write-private-json restored-directory (agent:session-id session) record :maximum-depth 24)
                         (multiple-value-bind (sessions failures) (agent:restore-sessions restored-manager)
                           (ok (null failures))
                           (let* ((restored (first sessions))
                                  (ready (await (agent:session-ready restored)))
                                  (snapshot (agent:session-snapshot restored))
                                  (decision (aref (field snapshot "decisions") 0)))
                             (declare (ignore ready))
                             (ok (equal "interrupted" (field snapshot "status")))
                             (ok (equal id (field decision "id")) "decision identity survives restart")
                             (if (eq phase :permission)
                                 (ok (and (equal "cancelled" (field decision "status"))
                                          (equal "daemon-interrupted" (field decision "reason"))))
                                 (ok (equal "resolved" (field decision "status"))))
                             (ok (null (await (agent:resolve-decision restored id "allow"))))
                             (ok (zerop requests) "recovery never starts queued work or replays an uncertain action")
                             (await (agent:resume-session restored)) (idle restored 2)
                             (ok (= 1 requests) "explicit resume runs only the retained follow-up")
                             (ok (= executions (if (eq phase :permission) 0 1)))
                             (ok (equal "interrupted" (field (aref (field (agent:session-snapshot restored) "turns") 0)
                                                               "status"))))))))))
            (open-gate gate)))))))

(deftest durability-failure-never-performs-approved-action
  (dolist (after-write '(nil t))
    (with-manager (manager directory)
      (let ((executions 0) (injected nil) (original (symbol-function 'store:write-private-json)))
        (agent:register-provider manager "fake" (tool-provider (vector (tool-call "effect"))))
        (agent:register-tool manager "effect" :schema (agent:json-object) :validate (constantly t)
                             :permission t :execute (lambda (arguments context)
                                                      (declare (ignore arguments context)) (incf executions)))
        (let ((session (new-session manager directory)))
          (await (agent:submit-message session "effect"))
          (let ((id (field (decision session) "id")))
            (unwind-protect
                 (progn
                   (setf (symbol-function 'store:write-private-json)
                         (lambda (path record-id record &rest options)
                           (let ((decision (first (array-items (field record "decisions")))))
                             (if (and (not injected) decision (equal "resolved" (field decision "status")))
                                 (progn
                                   (setf injected t)
                                   (when after-write (apply original path record-id record options))
                                   (error "Injected journal publication/fsync failure"))
                                 (apply original path record-id record options)))))
                   (ok (signals (await (agent:resolve-decision session id "allow")))))
              (setf (symbol-function 'store:write-private-json) original))
            (wait-for (lambda () (equal "failed" (state session))))
            (ok injected)
            (ok (zerop executions) "failure before or after journal publication prevents dependent execution")
            (ok (signals (await (agent:submit-message session "must not continue"))))
            (ok (equal "failed" (field (agent:session-snapshot session) "durability")))))))))

(deftest history-retains-complete-tool-pairs
  (with-manager (manager directory)
    (agent:register-provider manager "fake" (tool-provider (vector (tool-call "read"))))
    (agent:register-tool manager "read" :schema (agent:json-object) :validate (constantly t)
                         :execute (lambda (arguments context) (declare (ignore arguments context)) "context"))
    (let ((session (new-session manager directory :limits (agent:json-object "turns" 2))))
      (dotimes (index 4)
        (await (agent:submit-message session (format nil "message ~d" index)))
        (idle session (min 2 (1+ index))))
      (let ((snapshot (agent:session-snapshot session)))
        (ok (= 2 (length (field snapshot "turns")) (field snapshot "omitted_turns")))
        (loop for turn across (field snapshot "turns")
              do (let ((calls 0) (results 0))
                   (loop for message across (field turn "messages")
                         do (incf calls (length (field message "tool_calls")))
                            (when (equal "tool" (field message "role")) (incf results)))
                   (ok (= calls results 1) "retention drops whole turns, never half of a tool exchange")))))))

(deftest concurrent-session-initialization
  (with-manager (manager directory)
    (agent:register-provider manager "fake" (lambda (request emit context)
                                              (declare (ignore request emit context))
                                              (agent:json-object "content" "ready")))
    (let ((sessions (loop repeat 8 collect (agent:create-session manager :provider "fake"
                                                               :model "fake-model" :root directory))))
      (dolist (session sessions) (await (agent:session-ready session)))
      (let ((receipts (mapcar (lambda (session) (agent:submit-message session "start")) sessions)))
        (mapc #'await receipts))
      (dolist (session sessions) (idle session))
      (ok (= 8 (length (agent:manager-sessions manager)))
          "concurrent actors initialize distinct records in one leased private directory"))))

(deftest interrupt-during-approval-publication
  (with-manager (manager directory)
    (let ((executions 0) (publishing nil) (gate (make-gate))
          (original (symbol-function 'store:write-private-json)))
      (agent:register-provider manager "fake" (tool-provider (vector (tool-call "effect"))))
      (agent:register-tool manager "effect" :schema (agent:json-object) :validate (constantly t)
                           :permission t :execute (lambda (arguments context)
                                                    (declare (ignore arguments context)) (incf executions)))
      (let ((session (new-session manager directory)))
        (await (agent:submit-message session "effect"))
        (let ((id (field (decision session) "id")))
          (unwind-protect
               (progn
                 (setf (symbol-function 'store:write-private-json)
                       (lambda (path record-id record &rest options)
                         (let ((decision (first (array-items (field record "decisions")))))
                           (when (and (not publishing) decision (equal "resolved" (field decision "status")))
                             (setf publishing t) (wait-gate gate))
                           (apply original path record-id record options))))
                 (let ((resolution (agent:resolve-decision session id "allow")))
                   (wait-for (lambda () publishing))
                   (let ((interrupt (agent:interrupt-session session)))
                     (open-gate gate) (await resolution) (await interrupt)))
                 (ok (zerop executions) "interrupt invalidates work even while its approval fsync is in progress")
                 (ok (equal "interrupted" (state session))))
            (open-gate gate) (setf (symbol-function 'store:write-private-json) original)))))))

(deftest tool-cancellation-does-not-block-the-actor
  (with-manager (manager directory)
    (let ((tool-gate (make-gate)) (cancel-gate (make-gate)) (entered nil) (cancelled nil))
      (agent:register-provider manager "fake" (tool-provider (vector (tool-call "slow"))))
      (agent:register-tool
       manager "slow" :schema (agent:json-object) :validate (constantly t)
       :execute (lambda (arguments context)
                  (declare (ignore arguments))
                  (agent:register-cancellation context (lambda () (setf cancelled t) (wait-gate cancel-gate)))
                  (setf entered t) (wait-gate tool-gate) "late tool output"))
      (let ((session (new-session manager directory)))
        (unwind-protect
             (progn
               (await (agent:submit-message session "slow tool")) (wait-for (lambda () entered))
               (await (agent:interrupt-session session)) (wait-for (lambda () cancelled))
               (agent:register-provider manager "fake" (lambda (request emit context)
                                                         (declare (ignore request emit context))
                                                         (agent:json-object "content" "new turn")))
               (await (agent:submit-message session "continue")) (idle session 2)
               (ok (not (gate-open cancel-gate)) "a blocked cancellation callback cannot block a subsequent turn")
               (open-gate tool-gate) (open-gate cancel-gate)
               (wait-for (lambda () (plusp (length (field (agent:session-snapshot session) "diagnostics")))))
               (let* ((turn (aref (field (agent:session-snapshot session) "turns") 0))
                      (result (car (last (array-items (field turn "messages"))))))
                 (ok (equal "unknown" (field (field result "content") "outcome"))
                     "a late tool return cannot replace its interrupted/uncertain result")))
          (open-gate tool-gate) (open-gate cancel-gate))))))

(deftest failed-operations-cancel-owned-resources
  (dolist (phase '(:provider :tool :stream))
    (with-manager (manager directory)
      (let ((cancelled nil))
        (agent:register-provider
         manager "fake"
         (if (eq phase :tool)
             (tool-provider (vector (tool-call "failure")))
             (lambda (request emit context)
               (declare (ignore request))
               (agent:register-cancellation context (lambda () (setf cancelled t)))
               (if (eq phase :stream)
                   (progn (ignore-errors (funcall emit (make-string 100))) (agent:json-object))
                   (error "Provider failed after starting an owned resource")))))
        (agent:register-tool
         manager "failure" :schema (agent:json-object) :validate (constantly :valid)
         :execute (lambda (arguments context)
                    (declare (ignore arguments))
                    (agent:register-cancellation context (lambda () (setf cancelled t)))
                    (error "Tool failed after starting an owned resource")))
        (let ((session (new-session manager directory :limits (agent:json-object "stream" 32))))
          (await (agent:submit-message session "exercise failure"))
          (wait-for (lambda () cancelled))
          (if (eq phase :tool) (idle session)
              (wait-for (lambda () (equal "failed" (state session)))))
          (ok cancelled "failure and exhausted streaming run registered cancellation"))))))

(deftest manager-lease-survives-asynchronous-close
  (with-manager (manager directory)
    (let ((publishing nil) (gate (make-gate)) (original (symbol-function 'store:write-private-json)))
      (agent:register-provider manager "fake" (constantly (agent:json-object "content" "ready")))
      (let ((session (new-session manager directory)))
        (ok (signals (agent:make-manager :directory directory)) "a second manager cannot acquire this journal namespace")
        (ok (= 1 (logand 1 (sb-posix:fcntl (agent::manager-lease manager) sb-posix:f-getfd)))
            "the manager lease does not leak through subprocess exec")
        (unwind-protect
             (progn
               (setf (symbol-function 'store:write-private-json)
                     (lambda (path id record &rest options)
                       (when (and (not publishing) (equal id (agent:session-id session)))
                         (setf publishing t) (wait-gate gate))
                       (apply original path id record options)))
               (agent:close-manager manager)
               (wait-for (lambda () publishing))
               (ok (signals (agent:make-manager :directory directory))
                   "asynchronous close keeps ownership until the final actor write ends")
               (ok (signals (agent:create-session manager :provider "fake" :model "fake" :root directory)))
               (open-gate gate)
               (agent:close-manager manager :wait t))
          (open-gate gate) (setf (symbol-function 'store:write-private-json) original))
        (let ((reopened (agent:make-manager :directory directory)))
          (unwind-protect
               (multiple-value-bind (sessions errors) (agent:restore-sessions reopened)
                 (ok (null errors))
                 (let ((restored (first sessions)))
                   (await (agent:session-ready restored))
                   (ok (equal "idle" (state restored)) "host shutdown preserves an idle session")
                   (await (agent:resume-session restored))
                   (ok (equal "idle" (state restored)) "a restored session remains usable")))
            (agent:close-manager reopened :wait t)))))))

(deftest graceful-shutdown-preserves-session-lifecycle
  (dolist (phase '(:idle :queued :permission :running-tool :closed))
    (with-manager (manager directory)
      (let ((gate (make-gate)) (entered nil) (cancelled nil) (executions 0)
            (context nil) (reopened nil))
        (agent:register-provider manager "fake" (tool-provider (vector (tool-call "effect"))))
        (agent:register-tool
         manager "effect" :schema (agent:json-object) :validate (constantly t) :permission t
         :execute (lambda (arguments operation)
                    (declare (ignore arguments))
                    (setf context operation)
                    (agent:register-cancellation operation (lambda () (setf cancelled t)))
                    (incf executions) (setf entered t)
                    ;; Deliberately ignore cancellation until the fixture releases us.
                    (wait-gate gate) (agent:json-object "late" t)))
        (let ((session (new-session manager directory)))
          (unwind-protect
               (progn
                 (when (member phase '(:queued :permission :running-tool))
                   (await (agent:submit-message session "effect"))
                   (let ((pending (decision session)))
                     (await (agent:submit-message session "retained follow-up"))
                     (case phase
                       (:queued (await (agent:interrupt-session session)))
                       (:running-tool
                        (await (agent:resolve-decision session (field pending "id") "allow"))
                        (wait-for (lambda () entered))))))
                 (when (eq phase :closed) (await (agent:close-session session)))
                 (agent:close-manager manager :wait t)
                 (ok (not (bt2:thread-alive-p (agent::session-thread session)))
                     "host shutdown stops every journal actor")
                 (when context
                   (wait-for (lambda () cancelled))
                   (ok (not (agent:operation-live-p context)))
                   (ok (some (lambda (entry) (bt2:thread-alive-p (car entry)))
                             (agent::session-workers session))
                       "an uncooperative tool cannot hold the manager lease"))
                 (ok (signals (await (agent:submit-message session "obsolete handle"))))
                 (unless (eq phase :closed)
                   (ok (signals (await (agent:close-session session)))
                       "permanent closure cannot be enqueued after host suspension"))
                 (setf reopened (agent:make-manager :directory directory))
                 (let ((requests 0))
                   (agent:register-provider reopened "fake"
                                            (lambda (request emit operation)
                                              (declare (ignore request emit operation))
                                              (incf requests) (agent:json-object "content" "fresh")))
                   (multiple-value-bind (sessions errors) (agent:restore-sessions reopened)
                     (ok (null errors))
                     (let* ((restored (first sessions))
                            (ready (await (agent:session-ready restored)))
                            (snapshot (agent:session-snapshot restored)))
                       (declare (ignore ready))
                       (ok (equal (field snapshot "status")
                                  (case phase (:idle "idle") (:closed "closed") (t "interrupted"))))
                       (ok (zerop requests) "restoration never invokes a provider or replays work")
                       (when (member phase '(:queued :permission :running-tool))
                         (let* ((pending (aref (field snapshot "decisions") 0))
                                (messages (field (aref (field snapshot "turns") 0) "messages"))
                                (result (field (aref messages (1- (length messages))) "content")))
                           (ok (equal "retained follow-up" (field (aref (field snapshot "queue") 0) "text")))
                           (ok (equal (field result "outcome")
                                      (if (eq phase :running-tool) "unknown" "not-started")))
                           (ok (equal (field pending "status")
                                      (if (eq phase :running-tool) "resolved" "cancelled")))
                           (when (eq phase :permission)
                             (ok (equal "host-shutdown" (field pending "reason"))))
                           (ok (null (await (agent:resolve-decision restored (field pending "id") "allow"))))))
                       ;; Return the old worker while the new actor owns the same
                       ;; journal. Neither late results nor diagnostics may write.
                       (let* ((path (merge-pathnames (format nil "~a.json" (agent:session-id session)) directory))
                              (before (uiop:read-file-string path)))
                         (open-gate gate)
                         (dolist (entry (agent::session-workers session)) (bt2:join-thread (car entry)))
                         (ok (equal before (uiop:read-file-string path))
                             "old workers cannot alter journals owned by the restored manager"))
                       (if (eq phase :closed)
                           (progn
                             (await (agent:interrupt-session restored))
                             (ok (equal "closed" (state restored)))
                             (ok (signals (await (agent:resume-session restored))))
                             (ok (signals (await (agent:submit-message restored "reopen")))))
                           (progn
                             (await (agent:resume-session restored))
                             (if (eq phase :idle)
                                 (progn (await (agent:submit-message restored "new turn")) (idle restored))
                                 (idle restored 2))
                             (ok (= 1 requests) "explicit continuation runs exactly one fresh turn")
                             (ok (= executions (if (eq phase :running-tool) 1 0)))))))))
            (open-gate gate)
            (when reopened (agent:close-manager reopened :wait t))))))))

(deftest shutdown-retains-accepted-mailbox-messages
  (with-manager (manager directory)
    (let ((gate (make-gate)) (publishing nil) (requests 0) (reopened nil))
      (agent:register-provider manager "fake"
                               (lambda (request emit context)
                                 (declare (ignore request emit context))
                                 (incf requests) (agent:json-object "content" "fresh")))
      (let ((session (new-session manager directory)))
        (agent:subscribe-session
         session (lambda (event)
                   (when (and (not publishing) (equal "message_queued" (field event "type")))
                     (setf publishing t) (wait-gate gate))))
        (unwind-protect
             (let ((first (agent:submit-message session "first queued")))
               (wait-for (lambda () publishing))
               ;; INTERRUPT synchronizes the persisted generation before SUBMIT
               ;; is drained. The closed-host guard must still prevent a turn.
               (let* ((interrupt (agent:interrupt-session session))
                      (second (agent:submit-message session "second queued"))
                      (receipts (agent:close-manager manager)))
                 (ok (signals (agent:make-manager :directory directory)))
                 (open-gate gate)
                 (mapc #'await (append (list first interrupt second) receipts))
                 (agent:close-manager manager :wait t))
               (ok (zerop requests))
               (let ((snapshot (agent:session-snapshot session)))
                 (ok (zerop (length (field snapshot "turns"))) "shutdown does not consume accepted follow-ups")
                 (ok (= 2 (length (field snapshot "queue")))))
               (setf reopened (agent:make-manager :directory directory))
               (multiple-value-bind (sessions errors) (agent:restore-sessions reopened)
                 (ok (null errors))
                 (let ((restored (first sessions)))
                   (await (agent:session-ready restored))
                   (ok (equal '("first queued" "second queued")
                              (map 'list (lambda (message) (field message "text"))
                                   (field (agent:session-snapshot restored) "queue"))))
                   (ok (zerop requests)))))
          (open-gate gate)
          (when reopened (agent:close-manager reopened :wait t)))))))

(deftest shutdown-does-not-wait-for-provider-or-cancellation-workers
  (with-manager (manager directory)
    (let ((gate (make-gate)) (entered nil) (cleanup-entered nil) (context nil) (emit nil))
      (agent:register-provider
       manager "fake"
       (lambda (request callback operation)
         (declare (ignore request))
         (setf context operation emit callback)
         (agent:register-cancellation operation (lambda () (setf cleanup-entered t) (wait-gate gate)))
         (setf entered t) (wait-gate gate)
         (funcall callback "late") (agent:json-object "content" "late")))
      (let ((session (new-session manager directory)))
        (unwind-protect
             (progn
               (await (agent:submit-message session "blocked provider"))
               (wait-for (lambda () entered))
               (agent:close-manager manager :wait t)
               (wait-for (lambda () cleanup-entered))
               (ok (not (agent:operation-live-p context)))
               (ok (null (funcall emit "late")))
               (ok (equal "interrupted" (state session)))
               (let ((reopened (agent:make-manager :directory directory)))
                 (agent:close-manager reopened :wait t))
               (ok (>= (count-if (lambda (entry) (bt2:thread-alive-p (car entry)))
                                 (agent::session-workers session)) 2)
                   "both uncooperative workers remain outside journal ownership"))
          (open-gate gate)
          (dolist (entry (agent::session-workers session)) (bt2:join-thread (car entry))))))))

(deftest shutdown-write-failure-keeps-lease-until-actor-stops
  (with-manager (manager directory)
    (agent:register-provider manager "fake" (tool-provider (vector (tool-call "effect"))))
    (agent:register-tool manager "effect" :schema (agent:json-object) :validate (constantly t)
                         :permission t :execute (lambda (arguments context)
                                                  (declare (ignore arguments context))
                                                  (error "Unapproved tool must not run")))
    (let* ((session (new-session manager directory)) (gate (make-gate)) (writing nil)
           (original (symbol-function 'store:write-private-json)) (reopened nil))
      (await (agent:submit-message session "effect")) (decision session)
      (await (agent:submit-message session "retained follow-up"))
      (unwind-protect
           (progn
             (setf (symbol-function 'store:write-private-json)
                   (lambda (path id record &rest options)
                     (if (equal id (agent:session-id session))
                         (progn (setf writing t) (wait-gate gate) (error "Injected final checkpoint failure"))
                         (apply original path id record options))))
             (let ((receipts (agent:close-manager manager)))
               (wait-for (lambda () writing))
               (ok (signals (agent:make-manager :directory directory)))
               (open-gate gate)
               (ok (signals (await (first receipts))) "the shutdown receipt reports failed durability")
               (agent:close-manager manager :wait t))
             (ok (not (bt2:thread-alive-p (agent::session-thread session)))
                 "a failed final checkpoint still stops the actor before releasing ownership")
             (setf (symbol-function 'store:write-private-json) original
                   reopened (agent:make-manager :directory directory))
             (multiple-value-bind (sessions errors) (agent:restore-sessions reopened)
               (ok (null errors))
               (let ((restored (first sessions)))
                 (await (agent:session-ready restored))
                 (let ((snapshot (agent:session-snapshot restored)))
                   (ok (equal "interrupted" (field snapshot "status")))
                   (ok (equal "daemon-interrupted" (field (aref (field snapshot "decisions") 0) "reason"))
                       "the last durable active record follows crash recovery when shutdown could not persist")
                   (ok (= 1 (length (field snapshot "queue"))))))))
        (open-gate gate)
        (setf (symbol-function 'store:write-private-json) original)
        (when reopened (agent:close-manager reopened :wait t))))))

(deftest invalid-journals-are-never-rewritten
  (with-manager (manager directory)
    (agent:register-provider manager "fake" (tool-provider (vector (tool-call "effect"))))
    (agent:register-tool manager "effect" :schema (agent:json-object) :validate (constantly t)
                         :permission t :execute (lambda (arguments context) (declare (ignore arguments context)) "effect"))
    (let ((session (new-session manager directory)))
      (await (agent:submit-message session "effect")) (decision session)
      (let ((baseline (store:read-private-json directory (agent:session-id session) :maximum-depth 24)))
        (dolist (mutate
                  (list
                   (lambda (record) (setf (gethash "active_turn" record) (store:new-id)))
                   (lambda (record) (setf (gethash "status" record) "idle"))
                   (lambda (record) (setf (gethash "turn_id" (aref (field record "decisions") 0)) (store:new-id)))
                   (lambda (record) (setf (gethash "status" (aref (field record "decisions") 0)) "resolved"
                                         (gethash "answer" (aref (field record "decisions") 0)) "maybe"))
                   (lambda (record) (setf (gethash "choices" (aref (field record "decisions") 0)) #("allow")))
                   (lambda (record) (setf (gethash "arguments" (aref (field record "decisions") 0))
                                         (agent:json-object "forged" t)))
                   (lambda (record) (setf (gethash "call_id" (aref (field record "decisions") 0)) "missing"))
                   (lambda (record) (setf (gethash "turns" record) (vector (aref (field record "turns") 0)
                                                                         (agent:json-copy (aref (field record "turns") 0)))))
                   (lambda (record)
                     (let* ((turn (aref (field record "turns") 0)) (messages (field turn "messages")))
                       (setf (gethash "messages" turn)
                             (concatenate 'vector messages
                                          (vector (agent:json-object "role" "tool" "tool_call_id" "missing"
                                                                    "name" "effect" "content" "forged"))))))))
          (with-manager (restored directory-copy)
            (let* ((record (agent:json-copy baseline)) (id (agent:session-id session)))
              (funcall mutate record)
              (let* ((path (store:write-private-json directory-copy id record :maximum-depth 24))
                     (before (uiop:read-file-string path)))
                (multiple-value-bind (sessions errors) (agent:restore-sessions restored)
                  (ok (and (null sessions) (= 1 (length errors))) "inconsistent durable state is rejected")
                  (ok (equal before (uiop:read-file-string path)) "rejected journal bytes remain intact"))))))))))

(deftest killed-runtime-releases-lease-and-never-replays
  (dolist (phase '("permission" "tool"))
    (let* ((directory (merge-pathnames (format nil "lem-agent-crash-~a/" (store:new-id)) (uiop:temporary-directory)))
           (ready (merge-pathnames "ready.txt" directory))
           (effect (merge-pathnames "effect.txt" directory))
           (log (merge-pathnames "worker.log" directory))
           (process nil))
      (unwind-protect
           (progn
             (store:ensure-private-directory directory)
             (setf process
                   (sb-ext:run-program
                    (namestring sb-ext:*runtime-pathname*)
                    (list "--noinform" "--no-sysinit" "--no-userinit" "--script"
                          (namestring (asdf:system-relative-pathname "lem-agent" "tests/crash-worker.lisp"))
                          (namestring (asdf:system-source-directory "lem")) (namestring directory) phase)
                    :search nil :wait nil :input nil :output log :error :output))
             (loop repeat 1500 until (probe-file ready)
                   do (unless (sb-ext:process-alive-p process)
                        (error "Crash fixture exited early: ~a" (uiop:read-file-string log)))
                      (sleep 0.01)
                   finally (unless (probe-file ready) (error "Crash fixture did not reach its durable boundary")))
             (ok (signals (agent:make-manager :directory directory)) "a live separate Lisp process owns the journal lease")
             (sb-ext:process-kill process sb-posix:sigkill)
             (sb-ext:process-wait process)
             (let ((manager (agent:make-manager :directory directory)) (requests 0) (executions 0))
               (unwind-protect
                    (progn
                      (agent:register-provider manager "fake"
                                               (lambda (request emit context)
                                                 (declare (ignore request emit context))
                                                 (incf requests) (agent:json-object "content" "fresh continuation")))
                      (agent:register-tool manager "effect" :schema (agent:json-object) :validate (constantly t)
                                           :permission t :execute (lambda (arguments context)
                                                                    (declare (ignore arguments context)) (incf executions)))
                      (multiple-value-bind (sessions errors) (agent:restore-sessions manager)
                        (ok (null errors))
                        (let ((session (first sessions)))
                          (await (agent:session-ready session))
                          (ok (equal "interrupted" (state session)) "SIGKILL recovers the active turn as interrupted")
                          (ok (and (zerop requests) (zerop executions)) "recovery invokes neither provider nor uncertain tool")
                          (let* ((snapshot (agent:session-snapshot session))
                                 (decision (aref (field snapshot "decisions") 0))
                                 (messages (field (aref (field snapshot "turns") 0) "messages"))
                                 (result (aref messages (1- (length messages)))))
                            (ok (equal (field decision "status") (if (equal phase "permission") "cancelled" "resolved")))
                            (ok (equal (field (field result "content") "outcome")
                                       (if (equal phase "permission") "not-started" "unknown"))
                                "recovery distinguishes unapproved work from a durably started uncertain effect")
                            (ok (null (await (agent:resolve-decision session (field decision "id") "allow")))))
                          (await (agent:submit-message session "continue deliberately")) (idle session 2)
                          (ok (and (= requests 1) (zerop executions)) "deliberate continuation starts a fresh provider request")
                          (ok (if (equal phase "tool") (equal (uiop:read-file-lines effect) '("effect"))
                                  (not (probe-file effect)))
                              "the interrupted external effect is not replayed"))))
                 (agent:close-manager manager :wait t))))
        (when process
          (when (sb-ext:process-alive-p process) (sb-ext:process-kill process sb-posix:sigkill))
          (sb-ext:process-wait process) (sb-ext:process-close process))
        (when (uiop:directory-exists-p directory) (uiop:delete-directory-tree directory :validate t))))))

(deftest failed-manager-initialization-releases-ownership
  (let ((directory (merge-pathnames (format nil "lem-agent-open-~a/" (store:new-id)) (uiop:temporary-directory)))
        (original (symbol-function 'agent::%make-manager)) (manager nil))
    (unwind-protect
         (progn
           (unwind-protect
                (progn
                  (setf (symbol-function 'agent::%make-manager)
                        (lambda (&rest arguments) (declare (ignore arguments)) (error "Injected manager initialization failure")))
                  (ok (signals (agent:make-manager :directory directory))))
             (setf (symbol-function 'agent::%make-manager) original))
           (setf manager (agent:make-manager :directory directory))
           (ok manager "failed initialization releases the lease acquired before manager construction"))
      (when manager (agent:close-manager manager :wait t))
      (when (uiop:directory-exists-p directory) (uiop:delete-directory-tree directory :validate t)))))

(deftest worker-budget-counts-uncooperative-operations
  (with-manager (manager directory)
    (let ((gate (make-gate)) (entered nil) (returned nil) (executions 0))
      (agent:register-provider manager "fake"
                               (lambda (request emit context)
                                 (declare (ignore request emit context))
                                 (setf entered t) (wait-gate gate) (setf returned t)
                                 (agent:json-object "content" "late")))
      (let ((session (new-session manager directory :limits (agent:json-object "workers" 1))))
        (unwind-protect
             (progn
               (await (agent:submit-message session "blocked")) (wait-for (lambda () entered))
               (await (agent:interrupt-session session))
               (agent:register-provider manager "fake" (tool-provider (vector (tool-call "read"))))
               (agent:register-tool manager "read" :schema (agent:json-object) :validate (constantly t)
                                    :execute (lambda (arguments context) (declare (ignore arguments context)) (incf executions)))
               (await (agent:submit-message session "budget blocked"))
               (wait-for (lambda () (equal "failed" (state session))))
               (ok (zerop executions) "an uncooperative old worker prevents unbounded replacement workers")
               (open-gate gate) (wait-for (lambda () returned))
               (wait-for (lambda () (some (lambda (message) (search "Discarded" message))
                                          (array-items (field (agent:session-snapshot session) "diagnostics")))))
               (dotimes (index 4)
                 (await (agent:submit-message session (format nil "fresh work ~d" index)))
                 (idle session (+ 3 index)))
               (ok (= 4 executions) "one active worker slot supports successive provider and tool rounds"))
          (open-gate gate))))))


(define-condition safe-summary-fixture (error)
  ((summary :initarg :summary :reader fixture-summary))
  (:report (lambda (condition stream)
             (declare (ignore condition))
             (write-string "private-adapter-error-argument" stream))))
(defmethod agent:operation-error-summary ((condition safe-summary-fixture))
  (let ((summary (fixture-summary condition)))
    (if (eq summary :broken) (error "private-adapter-error-argument") summary)))

(deftest durable-adapter-error-summaries
  (with-manager (manager directory)
    (dolist (case (list (cons (make-condition 'simple-error
                                            :format-control "private-adapter-error-argument")
                             "SIMPLE-ERROR")
                       (cons (make-condition 'safe-summary-fixture :summary "HTTP authentication 401")
                             "HTTP authentication 401")
                       (cons (make-condition 'safe-summary-fixture :summary (make-string 513 :initial-element #\x))
                             "SAFE-SUMMARY-FIXTURE")
                       (cons (make-condition 'safe-summary-fixture :summary :broken)
                             "SAFE-SUMMARY-FIXTURE")))
      (let ((condition (car case)))
        (agent:register-provider manager "fake"
                                 (lambda (request emit context)
                                   (declare (ignore request emit context))
                                   (error condition)))
        (let ((session (new-session manager directory)))
          (await (agent:submit-message session "exercise safe failure"))
          (wait-for (lambda () (equal "failed" (state session))))
          (let* ((record (store:read-private-json directory (agent:session-id session) :maximum-depth 24))
                 (text (with-output-to-string (stream) (yason:encode record stream))))
            (ok (search (cdr case) text) "durable history contains the safe category or fallback type")
            (ok (not (search "private-adapter-error-argument" text))
                "arbitrary printed adapter arguments never enter the journal")))))))
