(defpackage :lem-agent/drafts/tests
  (:use :cl :rove)
  (:local-nicknames (:agent :lem-agent) (:drafts :lem-agent/drafts) (:disk :lem-daemon/recovery-store)))
(in-package :lem-agent/drafts/tests)
(defun field (object name) (gethash name object))
(defun await (receipt)
  (multiple-value-bind (value done) (agent:await-request receipt :timeout 8)
    (unless done (error "Draft request timed out")) value))
(defun wait-for (predicate)
  (loop repeat 800 when (funcall predicate) return t do (sleep 0.005)
        finally (error "Draft fixture state did not arrive")))
(defmacro with-store ((store manager directory) &body body)
  `(let* ((,directory (merge-pathnames (format nil "lem-drafts-~a/" (disk:new-id)) (uiop:temporary-directory)))
          (,manager (agent:make-manager :directory (merge-pathnames "sessions/" ,directory)))
          (,store (drafts:open-store :directory (merge-pathnames "drafts/" ,directory) :manager ,manager))
          (*claims* (make-hash-table :test 'equal)))
     (unwind-protect (progn ,@body)
       (drafts:close-store ,store :wait t)
       (agent:close-manager ,manager :wait t)
       (uiop:delete-directory-tree ,directory :validate t))))
(defun session (manager directory)
  (let ((session (agent:create-session manager :root directory :provider "fake" :model "fake")))
    (await (agent:session-ready session)) session))
(defvar *claims* nil)
(defun owner-for (store record)
  (let ((key (list store (field record "id"))))
    (or (gethash key *claims*)
        (setf (gethash key *claims*)
              (drafts:claim-draft store record :new (null (drafts:find-draft store (field record "id"))))))))
(defun queue-record (store record)
  (drafts:queue-snapshot store record :owner (owner-for store record)))
(defun submit-record (store record session)
  (drafts:submit-draft store record session :owner (owner-for store record)))
(defun discard-record (store id &rest args)
  (let ((key (list store id)))
    (drafts:release-draft store id (gethash key *claims*))
    (remhash key *claims*))
  (apply #'drafts:discard-draft store id args))

(defun save-record (store record)
  (queue-record store record)
  (wait-for (lambda () (let ((saved (drafts:find-draft store (field record "id"))))
                        (and saved (= (field saved "revision") (field record "revision"))
                             (equal (field saved "text") (field record "text")))))))

(deftest drafts-real-process-crash-reconciliation
  (dolist (phase '("before" "after" "marker"))
    (let* ((directory (merge-pathnames (format nil "lem-draft-crash-~a/" (disk:new-id)) (uiop:temporary-directory)))
           (ready (merge-pathnames "ready.txt" directory)) (log (merge-pathnames "worker.log" directory)) (process nil))
      (unwind-protect
           (progn
             (disk:ensure-private-directory directory)
             (setf process
                   (sb-ext:run-program
                    (namestring sb-ext:*runtime-pathname*)
                    (list "--noinform" "--no-sysinit" "--no-userinit" "--script"
                          (namestring (asdf:system-relative-pathname "lem-agent" "tests/draft-crash-worker.lisp"))
                          (namestring (asdf:system-source-directory "lem")) (namestring directory) phase)
                    :search nil :wait nil :input nil :output log :error :output))
             (loop repeat 1500 until (probe-file ready)
                   do (unless (sb-ext:process-alive-p process)
                        (error "Draft worker exited early: ~a" (uiop:read-file-string log)))
                      (sleep 0.01)
                   finally (unless (probe-file ready) (error "Draft worker did not reach boundary")))
             (sb-ext:process-kill process sb-posix:sigkill) (sb-ext:process-wait process)
             (let* ((manager (agent:make-manager :directory (merge-pathnames "sessions/" directory)))
                    (store nil) (requests 0))
               (unwind-protect
                    (progn
                      (agent:register-provider manager "fake" (lambda (&rest ignored) (declare (ignore ignored)) (incf requests)))
                      (multiple-value-bind (sessions errors) (agent:restore-sessions manager)
                        (declare (ignore sessions)) (ok (null errors)))
                      (setf store (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager))
                      (let* ((id (string-trim '(#\Newline) (uiop:read-file-string ready)))
                             (record (drafts:find-draft store id)))
                        (ok (equal "newer draft awaiting human" (field record "text")))
                        (ok (= 3 (field record "point")))
                        (ok (equal "crash retained draft λ" (field (field record "attempt") "text"))
                            "the original submitted text survives independently of newer draft edits")
                        (ok (equal (if (equal phase "before") "rejected" "accepted") (field (field record "attempt") "status")))
                        (ok (zerop requests) "neither recovery nor receipt reconciliation submits text")
                        (ok (zerop (length (field (agent:session-snapshot (agent:find-session manager (field record "session_id")))
                                                  "submissions"))) "accepted state reaches drafts before acknowledgement")))
                 (when store (drafts:close-store store :wait t))
                 (agent:close-manager manager :wait t))))
        (when process
          (when (sb-ext:process-alive-p process) (sb-ext:process-kill process sb-posix:sigkill))
          (sb-ext:process-wait process) (sb-ext:process-close process))
        (when (uiop:directory-exists-p directory) (uiop:delete-directory-tree directory :validate t))))))

(deftest closing-store-excludes-late-submission-workers
  (with-store (store manager directory)
    (let* ((session (session manager directory)) (record (drafts:new-record session "late input" 2 1))
           (submit (symbol-function 'agent:submit-message)) (entered nil) (release nil) (receipt nil))
      (agent:register-provider manager "fake" (constantly (agent:json-object "content" "done")))
      (unwind-protect
           (progn
             (setf (symbol-function 'agent:submit-message)
                   (lambda (&rest args)
                     (setf entered t)
                     (loop until release do (sleep 0.005))
                     (apply submit args)))
             (setf receipt (submit-record store record session))
             (wait-for (lambda () entered))
             (drafts:close-store store)
             (ok (signals (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager)))
             (ok (signals (submit-record store record session)))
             (setf release t)
             (drafts:close-store store :wait t)
             (ok (await receipt))
             (ok (equal "accepted" (field (field (drafts:find-draft store (field record "id")) "attempt") "status")))
             (setf store (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager))
             (ok (drafts:store-open-p store)))
        (setf release t (symbol-function 'agent:submit-message) submit)))))

(deftest exact-draft-metadata-survives-session-disappearance
  (with-store (store manager directory)
    (let* ((session (session manager directory))
           (record (drafts:new-record session "unsent λ\nsecond line" 4 17))
           (id (field record "id")))
      (save-record store record)
      (ok (equalp record (drafts:find-draft store id)))
      (drafts:close-store store :wait t) (agent:close-manager manager :wait t)
      (disk:discard-record (merge-pathnames "sessions/" directory) (agent:session-id session))
      (setf manager (agent:make-manager :directory (merge-pathnames "sessions/" directory)))
      (agent:restore-sessions manager)
      (setf store (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager))
      (ok (equalp record (drafts:find-draft store id)) "text, point and original session identity survive an absent session")
      (ok (signals (submit-record store record session)))
      (ok (await (discard-record store id :expected-revision 17)))
      (ng (drafts:find-draft store id)))))

(deftest clarification-json-metadata-survives-durable-roundtrip
  (with-store (store manager directory)
    (let ((calls 0) (session (session manager directory)))
      (agent:register-provider
       manager "fake"
       (lambda (&rest ignored)
         (declare (ignore ignored))
         (if (= 1 (incf calls))
             (agent:json-object "clarification" (agent:json-object "question" "Describe the next step" "choices" #()))
             (agent:json-object "content" "done"))))
      (await (agent:submit-message session "ask"))
      (wait-for (lambda () (equal "waiting" (field (agent:session-snapshot session) "status"))))
      (let* ((decision (aref (field (agent:session-snapshot session) "decisions") 0))
             (record (drafts:new-record session "human answer" 5 1))
             (id (field record "id")))
        (setf (gethash "decision" record) decision)
        (save-record store record)
        (drafts:close-store store :wait t)
        (let ((yason:*parse-json-booleans-as-symbols* nil)
              (yason:*parse-json-arrays-as-vectors* nil)
              (yason:*parse-json-null-as-keyword* t))
          (setf store (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager)))
        (let ((restored (drafts:find-draft store id)))
          (ok (equalp record restored) "exact pending decision, empty choices and null authority survive disk")
          (ok (= 1 calls) "restoring clarification text never answers the decision")
          (ok (await (submit-record store restored session))))
        (wait-for (lambda () (equal "idle" (field (agent:session-snapshot session) "status"))))
        (drafts:close-store store :wait t)
        (let ((yason:*parse-json-booleans-as-symbols* nil)
              (yason:*parse-json-arrays-as-vectors* nil)
              (yason:*parse-json-null-as-keyword* t))
          (setf store (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager)))
        (let* ((restored (drafts:find-draft store id)) (attempt (field restored "attempt")))
          (ok (equalp decision (field restored "decision")))
          (ok (equal "accepted" (field attempt "status")))
          (ok (eq t (field attempt "result")) "the accepted decision retains the core's true receipt API")
          (ok (signals (await (submit-record store restored session))))
          (ok (= 2 calls) "restoration and duplicate submission cannot repeat an accepted answer")
          (setf (gethash "result" attempt) yason:false)
          (ok (signals (drafts::validate-record restored)) "false cannot masquerade as acceptance"))))))

(deftest clarification-receipt-reconciles-before-view-cleanup
  (dolist (boundary '(:before-marker :after-marker))
    (with-store (store manager directory)
      (let ((calls 0) (session (session manager directory)))
        (agent:register-provider
         manager "fake"
         (lambda (&rest ignored)
           (declare (ignore ignored))
           (if (= 1 (incf calls))
               (agent:json-object "clarification" (agent:json-object "question" "Describe the next step" "choices" #()))
               (agent:json-object "content" "done"))))
        (await (agent:submit-message session "ask"))
        (wait-for (lambda () (equal "waiting" (field (agent:session-snapshot session) "status"))))
        (let* ((decision (aref (field (agent:session-snapshot session) "decisions") 0))
               (record (drafts:new-record session "original answer" 8 1))
               (id (field record "id")) (write (symbol-function 'disk:write-private-json))
               (acknowledge (symbol-function 'agent:acknowledge-submission)))
          (setf (gethash "decision" record) decision)
          (unwind-protect
               (progn
                 (if (eq boundary :before-marker)
                     (setf (symbol-function 'disk:write-private-json)
                           (lambda (path target value &rest args)
                             (when (and (equal (uiop:ensure-directory-pathname path) (merge-pathnames "drafts/" directory))
                                        (field value "attempt")
                                        (equal "accepted" (field (field value "attempt") "status")))
                               (error "injected failure before accepted marker"))
                             (apply write path target value args)))
                     (setf (symbol-function 'agent:acknowledge-submission)
                           (lambda (&rest ignored) (declare (ignore ignored))
                             (error "injected failure after accepted marker"))))
                 (if (eq boundary :before-marker)
                     (ok (signals (await (submit-record store record session))))
                     (ok (await (submit-record store record session)))))
            (setf (symbol-function 'disk:write-private-json) write
                  (symbol-function 'agent:acknowledge-submission) acknowledge))
          (wait-for (lambda () (equal "idle" (field (agent:session-snapshot session) "status"))))
          (let ((attempt-id (field (field (drafts:find-draft store id) "attempt") "id")))
            (ok (eq t (field (agent:find-submission session attempt-id) "result")))
            (drafts:close-store store :wait t) (agent:close-manager manager :wait t)
            (setf manager (agent:make-manager :directory (merge-pathnames "sessions/" directory)))
            (agent:register-provider manager "fake" (lambda (&rest ignored) (declare (ignore ignored)) (incf calls)))
            (multiple-value-bind (sessions errors) (agent:restore-sessions manager)
              (declare (ignore sessions)) (ok (null errors)))
            (setf store (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager))
            (let* ((restored (drafts:find-draft store id)) (attempt (field restored "attempt"))
                   (restored-session (agent:find-session manager (field restored "session_id"))))
              (ok (equalp decision (field restored "decision")))
              (ok (equal attempt-id (field attempt "id")))
              (ok (equal "accepted" (field attempt "status")))
              (ok (eq t (field attempt "result")))
              (ok (equal "original answer" (field attempt "text")))
              (ng (agent:find-submission restored-session attempt-id) "the draft marker is durable before receipt acknowledgement")
              (ok (= 2 calls) "restart does not replay an already accepted clarification answer"))))))))

(deftest delayed-submission-preserves-newer-queued-snapshot
  (with-store (store manager directory)
    (let* ((session (session manager directory)) (record (drafts:new-record session "submitted" 0 1))
           (blocker (drafts:new-record session "block writer" 0 0))
           (write (symbol-function 'drafts::write-record)) (entered nil) (release nil) (receipt nil))
      (agent:register-provider manager "fake" (constantly (agent:json-object "content" "done")))
      (save-record store record)
      (unwind-protect
           (progn
             (setf (symbol-function 'drafts::write-record)
                   (lambda (store snapshot)
                     (when (equal (field snapshot "id") (field blocker "id"))
                       (setf entered t) (loop until release do (sleep 0.005)))
                     (funcall write store snapshot)))
             (queue-record store blocker) (wait-for (lambda () entered))
             (let ((newer (agent:json-copy record)))
               (setf (gethash "revision" newer) 2 (gethash "text" newer) "newer pending text")
               (queue-record store newer)
               (setf receipt (submit-record store record session))
               (bt2:with-lock-held ((drafts::draft-store-lock store))
                 (ok (equal "newer pending text"
                            (field (gethash (field record "id") (drafts::draft-store-pending store)) "text"))))
               (setf release t)
               (ok (await receipt))
               (drafts:close-store store :wait t)
               (let ((saved (drafts:find-draft store (field record "id"))))
                 (ok (equal "newer pending text" (field saved "text")))
                 (ok (= 1 (field (field saved "attempt") "revision")))
                 (ok (= 2 (field saved "revision"))))))
        (setf release t (symbol-function 'drafts::write-record) write)))))

(deftest discard-retires-publication-claims-before-unlink
  (with-store (store manager directory)
    (let* ((session (session manager directory)) (record (drafts:new-record session "accepted text" 0 1))
           (id (field record "id")) (discard (symbol-function 'disk:discard-record))
           (entered nil) (release nil) (receipt nil) (old-owner nil))
      (agent:register-provider manager "fake" (constantly (agent:json-object "content" "done")))
      (ok (await (submit-record store record session)))
      (setf old-owner (owner-for store record))
      (ok (signals (await (drafts:discard-draft store id :expected-revision 1))) "a live editor claim prevents discard")
      (unwind-protect
           (progn
             (setf (symbol-function 'disk:discard-record)
                   (lambda (directory target)
                     (when (equal target id) (setf entered t) (loop until release do (sleep 0.005)))
                     (funcall discard directory target)))
             (setf receipt (discard-record store id :expected-revision 1))
             (wait-for (lambda () entered))
             (ok (signals (drafts:claim-draft store (drafts:find-draft store id))))
             (ok (signals (drafts:queue-snapshot store record :owner old-owner)))
             (setf release t) (ok (await receipt))
             (ng (drafts:find-draft store id))
             (ok (signals (drafts:claim-draft store record)))
             (ok (signals (drafts:queue-snapshot store record :owner old-owner))))
        (setf release t (symbol-function 'disk:discard-record) discard)))))

(deftest failed-discard-fsync-does-not-acknowledge-absence
  (with-store (store manager directory)
    (let* ((session (session manager directory)) (record (drafts:new-record session "evidence" 0 0))
           (id (field record "id")) (sync (symbol-function 'disk::fsync-directory)))
      (save-record store record)
      (unwind-protect
           (progn
             (setf (symbol-function 'disk::fsync-directory)
                   (lambda (path)
                     (if (equal (uiop:ensure-directory-pathname path) (merge-pathnames "drafts/" directory))
                         (error "injected unlink fsync failure") (funcall sync path))))
             (ok (signals (await (discard-record store id :expected-revision 0))))
             (ok (drafts:find-draft store id) "uncertain deletion retains the cached evidence")
             (ok (drafts:store-error store))
             (ok (signals (drafts:discard-draft store id :expected-revision 0)))
             (ng (probe-file (disk::record-path (merge-pathnames "drafts/" directory) id)) "unlink happened, but cannot be called durable"))
        (setf (symbol-function 'disk::fsync-directory) sync)))))

(deftest submission-thread-creation-failure-wakes-shutdown
  (with-store (store manager directory)
    (let* ((session (session manager directory)) (record (drafts:new-record session "unsubmitted" 0 0))
           (make-thread (symbol-function 'bt2:make-thread)) (entered nil) (release nil)
           (failed nil) (closed nil) (submitter nil) (closer nil) (owner nil))
      (save-record store record)
      (setf owner (owner-for store record))
      (unwind-protect
           (progn
             (sb-ext:without-package-locks
               (setf (symbol-function 'bt2:make-thread)
                     (lambda (function &rest args)
                       (when (equal "agent durable draft submission" (getf args :name))
                         (setf entered t) (loop until release do (sleep 0.005))
                         (error "injected thread creation failure"))
                       (apply make-thread function args))))
             (setf submitter (funcall make-thread
                                     (lambda () (handler-case (drafts:submit-draft store record session :owner owner)
                                                  (error () (setf failed t)))) :name "draft test caller"))
             (wait-for (lambda () entered))
             (setf closer (funcall make-thread (lambda () (drafts:close-store store :wait t) (setf closed t))
                                   :name "draft test shutdown"))
             (wait-for (lambda () (drafts::draft-store-closing store)))
             (ng closed "shutdown retains the lease while thread admission is unresolved")
             (setf release t)
             (wait-for (lambda () (and failed closed)))
             (ok (drafts::draft-store-closed store) "failed admission wakes the waiting store writer"))
        (setf release t)
        (sb-ext:without-package-locks (setf (symbol-function 'bt2:make-thread) make-thread))
        (when submitter (bt2:join-thread submitter)) (when closer (bt2:join-thread closer))))))

(deftest orphaned-unknown-draft-needs-explicit-uncertainty-discard
  (with-store (store manager directory)
    (let* ((session (session manager directory)) (record (drafts:new-record session "uncertain evidence" 0 3))
           (id (field record "id")))
      (save-record store record)
      (setf (gethash "attempt" record)
            (agent:json-object "id" (disk:new-id) "kind" "message" "decision_id" nil
                               "revision" 3 "digest" (disk:text-digest (field record "text"))
                               "text" (field record "text")
                               "status" "unknown" "result" nil))
      (drafts::write-record store record)
      (drafts:close-store store :wait t) (agent:close-manager manager :wait t)
      (disk:discard-record (merge-pathnames "sessions/" directory) (agent:session-id session))
      (setf manager (agent:make-manager :directory (merge-pathnames "sessions/" directory)))
      (agent:restore-sessions manager)
      (setf store (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager))
      (ok (equal "unknown" (field (field (drafts:find-draft store id) "attempt") "status")))
      (ok (signals (await (drafts:discard-draft store id :expected-revision 3))))
      (ok (await (drafts:discard-draft store id :expected-revision 3 :acknowledge-uncertainty t)))
      (ng (drafts:find-draft store id)))))

(deftest drafts-acceptance-marker-precedes-receipt-acknowledgement
  (with-store (store manager directory)
    (let ((calls 0) (acknowledged-after-marker nil)
          (acknowledge (symbol-function 'agent:acknowledge-submission)))
      (agent:register-provider manager "fake" (lambda (&rest ignored) (declare (ignore ignored))
                                               (incf calls) (agent:json-object "content" "done")))
      (let* ((session (session manager directory)) (record (drafts:new-record session "exact input" 2 4))
             (id (field record "id")))
        (unwind-protect
             (progn
               (setf (symbol-function 'agent:acknowledge-submission)
                     (lambda (session submission-id)
                       (let ((record (disk:read-private-json (merge-pathnames "drafts/" directory) id :maximum-depth 16)))
                         (setf acknowledged-after-marker
                               (and (equal submission-id (field (field record "attempt") "id"))
                                    (equal "accepted" (field (field record "attempt") "status")))))
                       (funcall acknowledge session submission-id)))
               (ok (await (submit-record store record session)))
               (ok acknowledged-after-marker "accepted marker is fsynced before the core receipt may be forgotten")
               (ok (equal "exact input" (field (drafts:find-draft store id) "text")))
               (ok (signals (await (submit-record store record session))))
               (ok (= 1 calls) "the accepted revision cannot be submitted again")
               (ok (drafts:store-open-p store) "a semantic rejection does not poison storage")
               (let ((newer (agent:json-copy record)))
                 (setf (gethash "revision" newer) 5 (gethash "text" newer) "newer input")
                 (save-record store newer)
                 (ok (equal "accepted" (field (field (drafts:find-draft store id) "attempt") "status")))
                 (ok (await (submit-record store newer session)))))
          (setf (symbol-function 'agent:acknowledge-submission) acknowledge))))))

(deftest draft-capacity-and-private-file-boundaries
  (with-store (store manager directory)
    (let ((session (session manager directory)) (records nil))
      (dotimes (index 32)
        (let ((record (drafts:new-record session (format nil "draft ~d" index) 0 0)))
          (push record records) (queue-record store record)))
      (ok (signals (queue-record store (drafts:new-record session "overflow" 0 0))))
      (wait-for (lambda () (= 32 (length (drafts:list-drafts store)))))
      (let ((record (first records)))
        (ok (signals (await (discard-record store (field record "id") :expected-revision 99))))
        (ok (= 32 (length (drafts:list-drafts store))))
        (ok (await (discard-record store (field record "id") :expected-revision 0))))
      (ok (drafts:store-open-p store))
      (let ((record (drafts:new-record session (make-string 65537 :initial-element #\x) 0 0)))
        (ok (signals (queue-record store record))))
      (drafts:close-store store :wait t)
      (let* ((id (disk:new-id)) (path (disk::record-path (merge-pathnames "drafts/" directory) id)))
        (sb-posix:symlink "/dev/null" (namestring path))
        (ok (signals (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager)))
        (sb-posix:unlink (namestring path))
        (sb-posix:mkfifo (namestring path) #o600)
        (ok (signals (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager)))
        (sb-posix:unlink (namestring path))
        (with-open-file (out path :direction :output :element-type '(unsigned-byte 8))
          (write-sequence (make-array (1+ drafts::+maximum-record-bytes+) :element-type '(unsigned-byte 8) :initial-element 32) out))
        (sb-posix:chmod (namestring path) #o600)
        (ok (signals (drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager)))
        (sb-posix:unlink (namestring path))))))

(deftest storage-failure-prevents-core-submission
  (with-store (store manager directory)
    (let* ((session (session manager directory)) (record (drafts:new-record session "must remain" 3 1))
           (write (symbol-function 'disk:write-private-json)) (calls 0))
      (agent:register-provider manager "fake" (lambda (&rest ignored) (declare (ignore ignored)) (incf calls)))
      (unwind-protect
           (progn
             (setf (symbol-function 'disk:write-private-json)
                   (lambda (path id value &rest args)
                     (when (equal (uiop:ensure-directory-pathname path) (merge-pathnames "drafts/" directory))
                       (error "injected checkpoint failure"))
                     (apply write path id value args)))
             (ok (signals (await (submit-record store record session))))
             (ok (zerop calls)) (ok (drafts:store-error store))
             (ng (drafts:store-open-p store)))
        (setf (symbol-function 'disk:write-private-json) write)))))
