(require :asdf)
(load (uiop:getenv "LEM_QUICKLISP_SETUP"))
(defparameter *source-root* (pathname (first (uiop:command-line-arguments))))
(asdf:initialize-source-registry `(:source-registry (:tree ,*source-root*) :ignore-inherited-configuration))
(setf asdf:*system-definition-search-functions*
      (cons 'asdf/system-registry:sysdef-source-registry-search
            (remove 'asdf/system-registry:sysdef-source-registry-search asdf:*system-definition-search-functions*)))
(ql:quickload "lem-agent/drafts" :silent t)
(unless (uiop:subpathp (truename (asdf:system-source-directory "lem-agent")) (truename *source-root*))
  (error "Draft crash worker resolved source outside the tested checkout"))

(destructuring-bind (root directory phase) (uiop:command-line-arguments)
  (declare (ignore root))
  (let* ((directory (pathname directory))
         (manager (lem-agent:make-manager :directory (merge-pathnames "sessions/" directory)))
         (store (lem-agent/drafts:open-store :directory (merge-pathnames "drafts/" directory) :manager manager))
         (session (lem-agent:create-session manager :root directory :provider "fake" :model "fake")))
    (lem-agent:await-request (lem-agent:session-ready session))
    (lem-agent:register-provider manager "fake" (constantly (lem-agent:json-object "content" "done")))
    (let* ((record (lem-agent/drafts:new-record session "crash retained draft λ" 7 11))
           (owner (lem-agent/drafts:claim-draft store record :new t)))
      (labels ((stop-at-boundary ()
                 (let ((newer (lem-agent:json-copy record)))
                   (setf (gethash "text" newer) "newer draft awaiting human"
                         (gethash "point" newer) 3 (gethash "revision" newer) 12)
                   (lem-agent/drafts:queue-snapshot store newer :owner owner)
                   (loop until (= 12 (gethash "revision" (lem-agent/drafts:find-draft store (gethash "id" record))))
                         do (sleep 0.005)))
                 (with-open-file (out (merge-pathnames "ready.txt" directory) :direction :output :if-exists :error)
                   (write-line (gethash "id" record) out) (finish-output out)
                   (sb-posix:fsync (sb-sys:fd-stream-fd out)))
                 (loop (sleep 1))))
        (cond
          ((equal phase "before")
           (let ((submit (symbol-function 'lem-agent:submit-message)))
             (setf (symbol-function 'lem-agent:submit-message)
                   (lambda (&rest args) (stop-at-boundary) (apply submit args)))))
          ((equal phase "after")
           (let ((enqueue (symbol-function 'lem-agent/drafts::enqueue)))
             (setf (symbol-function 'lem-agent/drafts::enqueue)
                   (lambda (store command &rest args)
                     (when (eq :finish (first command)) (stop-at-boundary))
                     (apply enqueue store command args)))))
          ((equal phase "marker")
           (let ((acknowledge (symbol-function 'lem-agent:acknowledge-submission)))
             (setf (symbol-function 'lem-agent:acknowledge-submission)
                   (lambda (&rest args) (stop-at-boundary) (apply acknowledge args))))))
        (lem-agent/drafts:submit-draft store record session :owner owner)
        (loop (sleep 1))))))
