(defpackage :lem-agent/editor-tools-tests
  (:use :cl :rove)
  (:local-nicknames (:agent :lem-agent) (:tools :lem-agent/editor-tools)
                    (:proposals :lem-buffer-proposals)))
(in-package :lem-agent/editor-tools-tests)

(defvar *manager*) (defvar *session*) (defvar *tools*) (defvar *root*)
(defun object (&rest fields) (apply #'agent:json-object fields))
(defun field (value name) (gethash name value))

(defun context (&optional (session *session*))
  (let ((operation (agent::%make-operation :session session :session-id (agent:session-id session)
                                          :root (namestring *root*) :generation (agent::session-generation session))))
    (setf (agent::session-operation session) operation) operation))

(defun invoke (name arguments &optional (operation (context)))
  (let ((tool (gethash name (agent::manager-tools *manager*))))
    (assert tool)
    (funcall (agent::tool-validate tool) arguments)
    (funcall (agent::tool-execute tool) arguments operation)))

(defun write-text (name text)
  (let ((path (merge-pathnames (sb-ext:parse-native-namestring name) *root*)))
    (ensure-directories-exist path)
    (with-open-file (out path :direction :output :if-exists :supersede :external-format :utf-8)
      (write-string text out)) path))

(defun proposal-arguments (inspection replacement)
  (object "path" (field inspection "path") "revision" (field inspection "revision")
          "original" (field inspection "content") "replacement" replacement))

(defmacro with-fixture (() &body body)
  `(let* ((*root* (merge-pathnames (format nil "lem-agent-files-~a/" (lem-daemon/recovery-store:new-id))
                                  (uiop:temporary-directory)))
          (*manager* (agent::%make-manager))
          (*session* (agent::%make-session :manager *manager* :id "file-session"))
          (*tools* (tools:install-editor-tools *manager* :dispatch #'funcall))
          (lem-core::*frames* nil) (lem-core::*display-frame-map* (make-hash-table)))
     (ensure-directories-exist *root*)
     (unwind-protect
          (lem:with-current-buffers ()
            (let ((lem/buffer/internal::*current-buffer* (lem:primordial-buffer)))
              (lem-fake-interface:with-fake-interface ()
                (let ((proposals::*proposals* (make-hash-table :test #'equal)))
                  (unwind-protect (progn ,@body)
                    (dolist (proposal (proposals:list-proposals))
                      (unless (proposals::terminal-proposal-p proposal) (proposals:reject-proposal proposal))
                      (proposals:forget-proposal proposal)))))))
       (uiop:delete-directory-tree *root* :validate t))))

(deftest descriptor-scoped-file-inspection
  (with-fixture ()
    (write-text "literal[*]; name.txt" "literal λ text")
    (let ((read (invoke "read_file" (object "path" "literal[*]; name.txt"))))
      (ok (equal "literal λ text" (field read "content")))
      (ok (equal "disk" (field read "source"))))
    (let ((buffer (lem:find-file-buffer (merge-pathnames (sb-ext:parse-native-namestring "literal[*]; name.txt") *root*))))
      (lem:erase-buffer buffer) (lem:insert-string (lem:buffer-point buffer) "human literal")
      (let ((read (invoke "read_file" (object "path" "literal[*]; name.txt"))))
        (ok (equal "buffer" (field read "source")))
        (ok (equal "human literal" (field read "content")))))
    (dolist (path '("../outside" "/etc/passwd" "a/../b" "a//b" "a/./b"))
      (ok (signals (invoke "read_file" (object "path" path))) "path traversal is rejected"))
    (sb-posix:symlink "/etc" (namestring (merge-pathnames "link" *root*)))
    (sb-posix:symlink "literal[*]; name.txt" (namestring (merge-pathnames "leaf-link" *root*)))
    (sb-posix:mkfifo (namestring (merge-pathnames "fifo" *root*)) #o600)
    (dolist (path '("link/passwd" "leaf-link" "fifo"))
      (ok (signals (invoke "read_file" (object "path" path))) "symlink/FIFO cannot become file input"))
    (let ((listing (invoke "list_directory" (object "path" ""))))
      (ok (= 4 (length (field listing "entries")))))
    (ok (signals (invoke "read_file" (object "path" "literal[*]; name.txt" "eval" "oops"))))
    (ok (signals (invoke "read_file" (object "path" "literal[*]; name.txt" "limit" 4097))))))

(deftest worker-snapshot-publishes-reviewable-file-buffer
  (with-fixture ()
    (let* ((path (write-text "plain.txt" "before text"))
           (inspection (invoke "read_file" (object "path" "plain.txt" "offset" 7)))
           (result (invoke "propose_edit" (proposal-arguments inspection "proposal")))
           (proposal (proposals:find-proposal (field result "proposal_id")))
           (buffer (proposals:proposal-source-buffer proposal)))
      (ok (equal "before text" (lem:buffer-text buffer)) "staging preserves the imported baseline")
      (ok (not (lem:buffer-modified-p buffer)))
      (ok (= (file-write-date path) (lem:buffer-last-write-date buffer)))
      (ok (equal "before text" (uiop:read-file-string path)))
      (ok (eq yason:true (field result "needs_activation")))
      (ok (signals (invoke "propose_edit" (proposal-arguments inspection "second"))))
      (let ((view (proposals:proposal-review-buffer proposal)))
        (lem:delete-buffer view)
        (ok (eq :pending (proposals:proposal-state proposal)) "closing review preserves pending proposal"))
      (proposals:apply-proposal proposal :expected-revision (field result "revision")
                                         :expected-generation (field result "generation"))
      (ok (equal "before proposal" (lem:buffer-text buffer)))
      (ok (equal "before text" (uiop:read-file-string path)) "human acceptance still does not save")
      (lem:switch-to-buffer buffer)
      (let* ((called nil)
            (lem:*find-file-hook* (list (cons (lambda (visited) (assert (eq buffer visited))
                                                       (setf called t)) 0))))
        (tools:agent-activate-file-buffer)
        (ok called "human activation performs ordinary file setup explicitly")))))

(deftest live-unsaved-buffer-wins-and-aba-conflicts
  (with-fixture ()
    (let* ((path (write-text "live.txt" "disk text"))
           (buffer (lem:find-file-buffer path)))
      (lem:erase-buffer buffer) (lem:insert-string (lem:buffer-point buffer) "human unsaved")
      ;; Invalid UTF-8 on disk must not replace/refuse the usable live document.
      (with-open-file (out path :direction :output :if-exists :supersede :element-type '(unsigned-byte 8))
        (write-byte 255 out))
      (let* ((inspection (invoke "read_file" (object "path" "live.txt")))
             (result (invoke "propose_edit" (proposal-arguments inspection "candidate"))))
        (ok (equal "buffer" (field inspection "source")))
        (ok (equal "human unsaved" (field inspection "content")))
        (ok (equal "human unsaved" (lem:buffer-text buffer)))
        (ok (proposals:find-proposal (field result "proposal_id"))))
      (let ((inspection (invoke "read_file" (object "path" "live.txt"))))
        (lem:insert-string (lem:buffer-end-point buffer) "!")
        (lem:with-point ((point (lem:buffer-end-point buffer)))
          (lem:character-offset point -1) (lem:delete-character point 1))
        (ok (equal "human unsaved" (lem:buffer-text buffer)))
        (ok (signals (invoke "propose_edit" (proposal-arguments inspection "stale")))
            "editing and restoring identical text invalidates the inspected buffer revision")))))

(deftest imported-utf8-line-ending-metadata
  (with-fixture ()
    (write-text "crlf.txt" (format nil "first~c~csecond λ~c~c" #\Return #\Newline #\Return #\Newline))
    (let* ((inspection (invoke "read_file" (object "path" "crlf.txt")))
           (result (invoke "propose_edit" (proposal-arguments inspection "replacement")))
           (buffer (proposals:proposal-source-buffer (proposals:find-proposal (field result "proposal_id")))))
      (ok (equal (format nil "first~%second λ~%") (field inspection "content")))
      (ok (eq :crlf (lem:encoding-end-of-line (lem:buffer-encoding buffer))))
      (ok (not (lem:buffer-modified-p buffer))))))

(deftest failed-stage-keeps-private-buffer-unpublished
  (with-fixture ()
    (let* ((first (invoke "read_file" (object "path" "first.txt")))
           (existing (invoke "propose_edit" (proposal-arguments first "pending")))
           (inspection (invoke "read_file" (object "path" "second.txt"))))
      (let ((proposals::*maximum-proposals* 1))
        (ok (signals (invoke "propose_edit" (proposal-arguments inspection "too many")))))
      (ok (null (lem:get-file-buffer (merge-pathnames "second.txt" *root*))))
      (ok (= 1 (length (proposals:list-proposals))))
      (ok (eq :pending (proposals:proposal-state (proposals:find-proposal (field existing "proposal_id")))))
      (ok (not (probe-file (merge-pathnames "second.txt" *root*))))
      (ok (field (invoke "propose_edit" (proposal-arguments inspection "retry")) "proposal_id")
          "failed private preparation preserves the inspection token for retry"))))

(deftest editor-publication-defers-file-probes-and-hooks
  (with-fixture ()
    (write-text "deferred.txt" "baseline")
    (let ((probe (symbol-function 'uiop:directory-exists-p))
          (lem:*before-find-file-hook* (list (cons (lambda (&rest arguments)
                                                   (declare (ignore arguments))
                                                   (error "Unexpected before-file hook")) 0)))
          (lem:*find-file-hook* (list (cons (lambda (&rest arguments)
                                            (declare (ignore arguments))
                                            (error "Unexpected file hook")) 0))))
      (setf (tools::editor-tools-dispatch *tools*)
            (lambda (callback)
              (unwind-protect
                   (progn
                     (setf (symbol-function 'uiop:directory-exists-p)
                           (lambda (&rest arguments)
                             (declare (ignore arguments))
                             (error "Filesystem probe on editor callback")))
                     (funcall callback))
                (setf (symbol-function 'uiop:directory-exists-p) probe))))
      (let* ((inspection (invoke "read_file" (object "path" "deferred.txt")))
             (result (invoke "propose_edit" (proposal-arguments inspection "candidate"))))
        (ok (field result "proposal_id"))
        (ok (equal "baseline" (lem:buffer-text (lem:get-file-buffer (merge-pathnames "deferred.txt" *root*)))))))))

(deftest source-identity-and-disk-changes-conflict
  (with-fixture ()
    (let* ((path (write-text "changed.txt" "first"))
           (inspection (invoke "read_file" (object "path" "changed.txt"))))
      (write-text "changed.txt" "other")
      (write-text "changed.txt" "first")
      (ok (signals (invoke "propose_edit" (proposal-arguments inspection "stale")))
          "nanosecond file metadata catches disk write/restore ABA")
      (let* ((buffer (lem:find-file-buffer path))
             (inspection (invoke "read_file" (object "path" "changed.txt"))))
        (lem:delete-buffer buffer)
        (lem:find-file-buffer path)
        (ok (signals (invoke "propose_edit" (proposal-arguments inspection "stale")))
            "recreated same-name buffers do not inherit an inspection identity")))))

(deftest prospective-file-and-session-scoped-tokens
  (with-fixture ()
    (let* ((inspection (invoke "read_file" (object "path" "new.txt")))
           (other (agent::%make-session :manager *manager* :id "another-session")))
      (ok (equal "new-file" (field inspection "source")))
      (ok (signals (invoke "propose_edit" (proposal-arguments inspection "new text") (context other))))
      (let* ((result (invoke "propose_edit" (proposal-arguments inspection "new text")))
             (proposal (proposals:find-proposal (field result "proposal_id")))
             (buffer (proposals:proposal-source-buffer proposal)))
        (ok (equal "" (lem:buffer-text buffer)))
        (ok (lem:buffer-modified-p buffer) "a new prospective file remains unsaved")
        (ok (not (probe-file (merge-pathnames "new.txt" *root*))))))))

(deftest bounded-revisions-and-file-size
  (with-fixture ()
    (write-text "small.txt" "small")
    (let ((first (invoke "read_file" (object "path" "small.txt"))))
      (dotimes (index 129) (declare (ignore index)) (invoke "read_file" (object "path" "small.txt")))
      (ok (<= (hash-table-count (tools::editor-tools-inspections *tools*)) 128))
      (ok (signals (invoke "propose_edit" (proposal-arguments first "expired")))) )
    (write-text "large.txt" (make-string (1+ tools::+maximum-file-bytes+) :initial-element #\a))
    (ok (signals (invoke "read_file" (object "path" "large.txt"))))))

(deftest cancelled-queued-editor-stage-is-inert
  (with-fixture ()
    (let* ((inspection (invoke "read_file" (object "path" "cancelled.txt")))
           (arguments (proposal-arguments inspection "must never appear"))
           (operation (context)) (queued nil) (failure nil)
           (lock (bt2:make-lock)) (worker nil)
           (manager *manager*))
      (setf (tools::editor-tools-dispatch *tools*)
            (lambda (callback) (bt2:with-lock-held (lock) (setf queued callback))))
      (setf worker
            (bt2:make-thread
             (lambda ()
               (handler-case
                   (let ((*manager* manager)) (invoke "propose_edit" arguments operation))
                 (error (condition) (setf failure condition)))) :name "queued agent file test"))
      (loop repeat 300 until (bt2:with-lock-held (lock) queued) do (sleep 0.01)
            finally (unless queued (error "Editor callback was not queued")))
      (agent:interrupt-session *session*)
      (funcall queued)
      (bt2:join-thread worker)
      (ok (typep failure 'agent:operation-cancelled))
      (ok (null (lem:get-file-buffer (merge-pathnames "cancelled.txt" *root*))))
      (ok (null (proposals:list-proposals)))
      (ok (not (probe-file (merge-pathnames "cancelled.txt" *root*)))))))

(deftest timed-out-editor-callback-cannot-publish-later
  (with-fixture ()
    (let ((callback nil) (called nil))
      (setf (tools::editor-tools-dispatch *tools*) (lambda (function) (setf callback function)))
      (ok (signals (tools::call-on-editor *tools* (context) (lambda () (setf called t)) :timeout 0.01)))
      (ok (and callback (not called)))
      (funcall callback)
      (ok (not called) "a late callback remains inert after the worker's wait expires")
      (ok (zerop (tools::editor-tools-pending *tools*))))))

(deftest failing-dispatch-releases-once-and-invalidates-queued-callback
  (with-fixture ()
    (let ((callback nil) (called nil))
      (setf (tools::editor-tools-dispatch *tools*)
            (lambda (function) (setf callback function) (error "dispatch failed")))
      (ok (signals (tools::call-on-editor *tools* (context) (lambda () (setf called t)))))
      (ok (zerop (tools::editor-tools-pending *tools*)))
      (funcall callback)
      (ok (not called))
      (ok (zerop (tools::editor-tools-pending *tools*))))))
