(defpackage :lem-agent/edit-recovery-tests
  (:use :cl :rove)
  (:local-nicknames (:agent :lem-agent) (:recovery :lem-agent/edit-recovery)
                    (:ui :lem-agent/ui) (:proposals :lem-buffer-proposals)
                    (:store :lem-daemon/recovery-store)))
(in-package :lem-agent/edit-recovery-tests)

(defun object (&rest fields) (apply #'agent:json-object fields))
(defun field (value key) (gethash key value))
(defun await (receipt)
  (multiple-value-bind (value done) (agent:await-request receipt :timeout 8)
    (unless done (error "Test receipt timed out")) value))
(defun pump () (lem-core::receive-event 0))
(defun wait-for (predicate)
  (loop repeat 1000 do (pump)
        when (funcall predicate) return t do (sleep 0.005)
        finally (error "Recovery test state did not arrive")))
(defun state (session) (field (agent:session-snapshot session) "status"))
(defun idle (session) (wait-for (lambda () (equal "idle" (state session)))))

(defmacro with-fixture ((manager directory) &body body)
  `(let ((lem-core::*frames* nil) (lem-core::*display-frame-map* (make-hash-table)))
     (lem:with-current-buffers ()
       (let ((lem/buffer/internal::*current-buffer* (lem:primordial-buffer)))
         (lem-fake-interface:with-fake-interface ()
           (let* ((,directory (merge-pathnames (format nil "edit-recovery-~a/" (store:new-id))
                                               (uiop:temporary-directory)))
                  (,manager (agent:make-manager :directory ,directory))
                  (ui:*default-manager* ,manager)
                  (proposals::*proposals* (make-hash-table :test #'equal)))
             ;; Only fixtures replace prompt/file entry points, restoring them
             ;; before this dynamically scoped package unlock ends.
             (unwind-protect (sb-ext:with-unlocked-packages (:lem-core :lem/buffer/file :lem/buffer/internal) ,@body)
               (loop for buffer being the hash-keys of ui::*views* collect buffer into buffers
                     finally (mapc #'ui::retire-view buffers))
               (agent:close-manager ,manager :wait t)
               (wait-for (lambda () (and (zerop recovery::*pending-discards*) (zerop ui::*pending-requests*))))
               (dolist (proposal (proposals:list-proposals))
                 (unless (proposals::terminal-proposal-p proposal) (proposals:reject-proposal proposal))
                 (proposals:forget-proposal proposal))
               (uiop:delete-directory-tree ,directory :validate t))))))))

(defun history (manager directory original replacement &key execute)
  (let ((provider (store:new-id))
        (arguments (object "path" "historical-name-only.txt" "revision" "obsolete-inspection-token"
                           "original" original "replacement" replacement)))
    (agent:register-provider
     manager provider
     (lambda (request emit context)
       (declare (ignore emit context))
       (let* ((messages (field request "messages")) (last (aref messages (1- (length messages)))))
         (if (equal "tool" (field last "role")) (object "content" "recorded")
             (object "tool_calls" (vector (object "id" "fixture-edit" "name" "propose_edit"
                                                   "arguments" arguments)))))))
    (agent:register-tool manager "propose_edit" :schema (object "type" "object")
                         :validate (constantly t) :retain-for-review t
                         :execute (or execute (lambda (arguments context)
                                                (declare (ignore arguments context))
                                                (object "proposal_id" "historical-proposal-is-not-live"
                                                        "state" "applied"))))
    (let ((session (agent:create-session manager :provider provider :model "fixture" :root directory)))
      (await (agent:session-ready session))
      (await (agent:submit-message session "remember candidate"))
      (wait-for (lambda () (let ((record (first (agent:list-retained-reviews session))))
                            (and record (not (equal "executing" (field record "status")))))))
      (idle session)
      (values session (first (agent:list-retained-reviews session))))))

(defun source (text &optional (name "explicit human source"))
  (let ((buffer (lem:make-buffer name)))
    (lem:switch-to-buffer buffer)
    (lem:insert-string (lem:buffer-point buffer) text)
    (lem:clear-buffer-edit-history buffer)
    buffer))
(defun select-region (buffer start end)
  (lem:switch-to-buffer buffer)
  (lem:move-to-position (lem:buffer-point buffer) (1+ start))
  (lem:with-point ((mark (lem:buffer-start-point buffer)))
    (lem:move-to-position mark (1+ end))
    (lem:set-cursor-mark (lem:buffer-point buffer) mark)))
(defun edit (buffer start end text)
  (lem:with-point ((left (lem:buffer-start-point buffer) :right-inserting)
                   (right (lem:buffer-start-point buffer) :left-inserting))
    (lem:move-to-position left (1+ start)) (lem:move-to-position right (1+ end))
    (lem:delete-between-points left right) (lem:insert-string left text)))
(defun point-at-record (buffer id)
  (lem:move-to-position (lem:buffer-point buffer)
                       (1+ (or (search id (lem:buffer-text buffer)) (error "History row missing")))))

(deftest historical-inspection-is-read-only-and-not-a-file-visit
  (with-fixture (manager directory)
    (multiple-value-bind (session record) (history manager directory "OLD λ" "NEW λ")
      (let* ((buffer (source "unrelated unsaved text")) (hooks 0)
             (lem:*find-file-hook* (list (cons (lambda (buffer) (declare (ignore buffer)) (incf hooks)) 0)))
             (old-find (symbol-function 'lem:find-file-buffer))
             (old-get (symbol-function 'lem:get-file-buffer)))
        (unwind-protect
             (progn
               (setf (symbol-function 'lem:find-file-buffer) (lambda (&rest arguments) (declare (ignore arguments)) (error "Unexpected visit"))
                     (symbol-function 'lem:get-file-buffer) (lambda (&rest arguments) (declare (ignore arguments)) (error "Unexpected filename lookup")))
               (let ((list (recovery:show-retained-reviews session))
                     (detail (recovery:show-retained-review session (field record "id"))))
                 (ok (and (lem:buffer-read-only-p list) (lem:buffer-read-only-p detail)))
                 (ok (eq buffer (lem:current-buffer)) "opening historical views does not select them")
                 (dolist (text '("Current applicability and prior application are UNKNOWN" "Original (JSON string)" "Replacement (JSON string)"
                                 "obsolete-inspection-token" "historical-proposal-is-not-live" "applied" "OLD λ" "NEW λ"))
                   (ok (search text (lem:buffer-text detail))))
                 (ok (zerop hooks))
                 (ok (equal "unrelated unsaved text" (lem:buffer-text buffer)))
                 (ok (null (proposals:list-proposals)) "inspection never creates a live proposal")
                 (lem:delete-buffer detail)
                 (ok (agent:find-retained-review session (field record "id")) "closing a view preserves history")))
          (setf (symbol-function 'lem:find-file-buffer) old-find
                (symbol-function 'lem:get-file-buffer) old-get))))))

(deftest exact-selected-duplicate-and-separate-human-acceptance
  (with-fixture (manager directory)
    (multiple-value-bind (session record) (history manager directory "OLD" "NEW")
      (let ((buffer (source "OLD / OLD")))
        (select-region buffer 6 9)
        (let* ((selection (recovery:capture-selection))
               (proposal (recovery:restage-selection selection session record)))
          (ok (eq :pending (proposals:proposal-state proposal)))
          (ok (not (equal (proposals:proposal-id proposal) (field (field record "result") "proposal_id"))))
          (ok (equal "OLD / OLD" (lem:buffer-text buffer)) "restage never applies either duplicate")
          (ok (= 1 (length (proposals:list-proposals))) "the pre-prompt fresh capture becomes the pending proposal")
          (ok (signals (recovery:restage-selection selection session record)) "a capture cannot be reused")
          (proposals:apply-proposal proposal)
          (ok (equal "OLD / NEW" (lem:buffer-text buffer)) "only the human-selected second match changes")
          (lem:buffer-undo (lem:buffer-point buffer))
          (ok (equal "OLD / OLD" (lem:buffer-text buffer)))
          (ok (equal "applied" (field (field record "result") "state")) "a historical applied result did not authorize this acceptance"))))))

(deftest explicit-empty-insertion-and-original-mismatch
  (with-fixture (manager directory)
    (multiple-value-bind (session record) (history manager directory "" "INSERT")
      (let ((buffer (source "ab")))
        (ok (signals (recovery:capture-selection)) "an insertion still requires an explicit mark")
        (select-region buffer 1 1)
        (let ((proposal (recovery:restage-selection (recovery:capture-selection) session record)))
          (ok (equal "ab" (lem:buffer-text buffer)))
          (proposals:apply-proposal proposal)
          (ok (equal "aINSERTb" (lem:buffer-text buffer))))))
    (multiple-value-bind (session record) (history manager directory "OLD" "NEW")
      (let ((buffer (source "different text" "mismatch source")))
        (select-region buffer 0 3)
        (let ((count (length (proposals:list-proposals))))
          (ok (signals (recovery:restage-selection (recovery:capture-selection) session record)))
          (ok (= count (length (proposals:list-proposals))))
          (ok (equal "different text" (lem:buffer-text buffer))))))))

(deftest changes-undo-aba-buffer-replacement-and-candidate-generation
  (with-fixture (manager directory)
    (multiple-value-bind (session record) (history manager directory "OLD" "NEW")
      (dolist (change '(:text :undo :replacement :generation :outside))
        (let ((buffer (source "OLD tail" (string change))))
          (select-region buffer 0 3)
          (let ((selection (recovery:capture-selection)))
            (ecase change
              (:text (edit buffer 1 2 "human"))
              (:undo (lem:buffer-undo-boundary buffer) (edit buffer 1 1 "human")
                     (lem:buffer-undo-boundary buffer) (lem:buffer-undo (lem:buffer-point buffer))
                     (ok (equal "OLD tail" (lem:buffer-text buffer)) "actual undo restores identical text before validation"))
              (:replacement (let ((name (lem:buffer-name buffer)))
                              (lem:delete-buffer buffer) (source "OLD tail" name)))
              (:generation (proposals:stage-replacement (recovery::selection-proposal selection) "other candidate"))
              (:outside (edit buffer 8 8 "!")))
            (ok (signals (recovery:restage-selection selection session record)) (string change))
            (ok (null (proposals:list-proposals)) "refusal cleans the temporary capture")))))))

(deftest capture-precedes-prompts-and-cancellation-cleans-up
  (with-fixture (manager directory)
    (multiple-value-bind (session record) (history manager directory "OLD" "NEW")
      (let ((buffer (source "OLD")) (old-prompt (symbol-function 'lem:prompt-for-string)) (calls 0))
        (select-region buffer 0 3)
        (unwind-protect
             (progn
               (setf (symbol-function 'lem:prompt-for-string)
                     (lambda (&rest arguments)
                       (declare (ignore arguments))
                       (incf calls)
                       (ok (= 1 (length (proposals:list-proposals))) "the tracked capture exists before either prompt")
                       (if (= calls 1) (agent:session-id session)
                           (progn (edit buffer 1 1 "X") (field record "id")))))
               (ok (signals (recovery:agent-restage-retained-review)))
               (ok (= 2 calls)) (ok (null (proposals:list-proposals)))
               (select-region buffer 0 3)
               (setf (symbol-function 'lem:prompt-for-string) (lambda (&rest arguments) (declare (ignore arguments)) (error "Fixture cancelled prompt")))
               (ok (signals (recovery:agent-restage-retained-review)))
               (ok (null (proposals:list-proposals))))
          (setf (symbol-function 'lem:prompt-for-string) old-prompt))))))

(deftest stale-records-and-display-bounds-disable-actions
  (with-fixture (manager directory)
    (multiple-value-bind (session record) (history manager directory "OLD" "NEW")
      (let ((buffer (source "OLD")) (bad (agent:json-copy record)))
        (setf (gethash "replacement" (field bad "arguments")) "tampered")
        (select-region buffer 0 3)
        (ok (signals (recovery:restage-selection (recovery:capture-selection) session bad)))
        (remhash "original" (field bad "arguments"))
        (select-region buffer 0 3)
        (ok (signals (recovery:restage-selection (recovery:capture-selection) session bad)))
        (let* ((recovery::*render-limit* 120)
               (view (recovery:show-retained-review session (field record "id"))))
          (ok (< (length (lem:buffer-text view)) 180))
          (ok (search "all actions disabled" (lem:buffer-text view)))
          (ok (signals (recovery:discard-displayed-review view))))
        (let ((view (recovery:show-retained-review session (field record "id"))))
          (point-at-record view (field record "id"))
          (setf (gethash "generation" (recovery::displayed-record view)) 0)
          (recovery:discard-displayed-review view)
          (wait-for (lambda () (zerop recovery::*pending-discards*)))
          (ok (search "Discard failed" (lem:buffer-value view 'recovery::discard-status)))
          (ok (agent:find-retained-review session (field record "id")) "a stale discard generation preserves history"))
        (select-region buffer 0 3)
        (let ((selection (recovery:capture-selection)))
          (await (agent:discard-retained-review session (field record "id") :expected-generation (field record "generation")))
          (ok (signals (recovery:restage-selection selection session record))))
        (ok (null (proposals:list-proposals)))
        (ok (equal "OLD" (lem:buffer-text buffer)))))))

(deftest unknown-outcome-and-result-enrichment-do-not-rebind-history
  (with-fixture (manager directory)
    (multiple-value-bind (session record)
        (history manager directory "OLD" "NEW"
                 :execute (lambda (arguments context) (declare (ignore arguments context))
                            (object "large" (make-string 40000 :initial-element #\x))))
      (ok (equal "unknown" (field record "status")))
      (let ((buffer (source "OLD")) (earlier (agent:json-copy record))
            (view (recovery:show-retained-review session (field record "id"))))
        (ok (search "Historical status: unknown" (lem:buffer-text view)))
        (ok (search "Current applicability and prior application are UNKNOWN" (lem:buffer-text view)))
        (setf (gethash "generation" earlier) 0 (gethash "status" earlier) "executing"
              (gethash "result" earlier) nil)
        (select-region buffer 0 3)
        (let ((proposal (recovery:restage-selection (recovery:capture-selection) session earlier)))
          (ok (eq :pending (proposals:proposal-state proposal))
              "only immutable origin/arguments determine whether this is still the chosen candidate")
          (ok (equal "OLD" (lem:buffer-text buffer))))))))

(deftest concurrent-discard-during-staging-abandons-unapplied-proposal
  (with-fixture (manager directory)
    (multiple-value-bind (session record) (history manager directory "OLD" "NEW")
      (let ((buffer (source "OLD")) (old-stage (symbol-function 'proposals:stage-replacement)))
        (select-region buffer 0 3)
        (unwind-protect
             (progn
               (setf (symbol-function 'proposals:stage-replacement)
                     (lambda (proposal replacement)
                       (funcall old-stage proposal replacement)
                       ;; Administrative fixture synchronization only: product
                       ;; code never awaits an actor receipt on the editor.
                       (await (agent:discard-retained-review session (field record "id")
                                                             :expected-generation (field record "generation")))
                       proposal))
               (ok (signals (recovery:restage-selection (recovery:capture-selection) session record)))
               (ok (null (proposals:list-proposals)))
               (ok (equal "OLD" (lem:buffer-text buffer))))
          (setf (symbol-function 'proposals:stage-replacement) old-stage))))))

(deftest metadata-discard-is-asynchronous-and-late-view-callback-is-harmless
  (with-fixture (manager directory)
    (multiple-value-bind (session record) (history manager directory "OLD" "NEW")
      (let* ((source (source "OLD")) (view (recovery:show-retained-review session (field record "id")))
             (old-await (symbol-function 'agent:await-request)) (editor (bt2:current-thread)) (waits 0))
        (select-region source 0 3)
        (let ((proposal (recovery:restage-selection (recovery:capture-selection) session record)))
          (point-at-record view (field record "id"))
          (unwind-protect
               (progn
                 (setf (symbol-function 'agent:await-request)
                       (lambda (&rest arguments)
                         (assert (not (eq editor (bt2:current-thread))))
                         (incf waits) (apply old-await arguments)))
                 (recovery:discard-displayed-review view)
                 (let ((name (lem:buffer-name view)))
                   (lem:delete-buffer view)
                   (let ((replacement (lem:make-buffer name)))
                     (lem:insert-string (lem:buffer-point replacement) "replacement view owns this name")
                     (wait-for (lambda () (zerop recovery::*pending-discards*)))
                     (ok (equal "replacement view owns this name" (lem:buffer-text replacement)))))
                 (ok (plusp waits))
                 (ok (null (agent:find-retained-review session (field record "id"))))
                 (ok (eq :pending (proposals:proposal-state proposal)) "discard does not revoke a published new proposal")
                 (ok (equal "OLD" (lem:buffer-text source)))
                 (ok (eq source (lem:current-buffer)) "receipt completion never steals focus"))
            (setf (symbol-function 'agent:await-request) old-await)))))))

(deftest historical-capacity-discard-and-live-proposal-capacity
  (with-fixture (manager directory)
    (let ((executions 0))
      (multiple-value-bind (session record)
          (history manager directory "OLD" "NEW"
                   :execute (lambda (arguments context) (declare (ignore arguments context))
                              (incf executions) (object "status" "staged")))
        (dotimes (i 15)
          (await (agent:submit-message session "another candidate"))
          (wait-for (lambda () (= (+ 2 i) (length (agent:list-retained-reviews session)))))
          (idle session))
        (ok (= 16 (length (agent:list-retained-reviews session))))
        (await (agent:submit-message session "capacity overflow"))
        (wait-for (lambda () (equal "failed" (state session))))
        (ok (= 16 executions) "retention capacity refuses before executor")
        (let ((view (recovery:show-retained-review session (field record "id"))))
          (point-at-record view (field record "id"))
          (recovery:discard-displayed-review view)
          (wait-for (lambda () (zerop recovery::*pending-discards*)))
          (ok (search "Metadata discarded" (lem:buffer-value view 'recovery::discard-status))))
        (ok (= 15 (length (agent:list-retained-reviews session))))
        (await (agent:submit-message session "deliberate new work")) (await (agent:resume-session session))
        (wait-for (lambda () (= 16 (length (agent:list-retained-reviews session))))) (idle session)
        (ok (= 17 executions))
        (let ((buffer (source "OLD")) (proposals::*maximum-proposals* 1))
          (select-region buffer 0 3)
          (let ((selection (recovery:capture-selection)))
            (ok (signals (recovery:capture-selection)) "existing pending captures are never evicted")
            (recovery:release-selection selection))
          (ok (null (proposals:list-proposals)))
          (select-region buffer 0 3)
          (let ((selection (recovery:capture-selection)) (proposals::*maximum-retained-characters* 4))
            (ok (signals (recovery:restage-selection selection session (first (agent:list-retained-reviews session)))))
            (ok (null (proposals:list-proposals)) "failed stage admission forgets the temporary capture")))))))

(deftest deliberate-transcript-return-from-composer-and-new-review
  (with-fixture (manager directory)
    (multiple-value-bind (session record) (history manager directory "OLD" "NEW")
      (let ((composer (ui:show-composer session)))
        (lem:switch-to-buffer composer)
        (recovery:agent-show-session)
        (ok (eq session (lem:buffer-value (lem:current-buffer) 'ui::agent-session)))
        (ok (not (eq composer (lem:current-buffer)))))
      (let ((buffer (source "OLD")) (old-prompt (symbol-function 'lem:prompt-for-string)) (calls 0))
        (select-region buffer 0 3)
        (unwind-protect
             (progn
               (setf (symbol-function 'lem:prompt-for-string)
                     (lambda (&rest arguments) (declare (ignore arguments))
                       (if (= 1 (incf calls)) (agent:session-id session) (field record "id"))))
               (recovery:agent-restage-retained-review)
               (ok (eq 'proposals::proposal-review-mode (lem:buffer-major-mode (lem:current-buffer))))
               (ok (equal "OLD" (lem:buffer-text buffer)))
               (recovery:agent-show-session)
               (ok (eq session (lem:buffer-value (lem:current-buffer) 'ui::agent-session))))
          (setf (symbol-function 'lem:prompt-for-string) old-prompt))))))
