(eval-when (:compile-toplevel :load-toplevel :execute) (require :sb-bsd-sockets))
(defpackage :lem-agent/openrouter-tests
  (:use :cl :rove)
  (:local-nicknames (:agent :lem-agent) (:router :lem-agent/openrouter)
                    (:jobs :lem-toolkit/jobs) (:store :lem-daemon/recovery-store)))
(in-package :lem-agent/openrouter-tests)

(defun object (&rest fields) (apply #'agent:json-object fields))
(defun field (object name) (gethash name object))
(defun bytes (text) (babel:string-to-octets text :encoding :utf-8))
(defun await (receipt)
  (multiple-value-bind (value done) (agent:await-request receipt :timeout 10)
    (unless done (error "Agent request timed out")) value))
(defun wait-for (predicate)
  (loop repeat 1500 when (funcall predicate) return t do (sleep 0.01)
        finally (error "Expected transport condition was not reached")))
(defun state (session) (field (agent:session-snapshot session) "status"))
(defun event (value) (format nil "data: ~a~%~%" (if (stringp value) value (router::json-text value))))
(defun chunk (content &key tools finish usage)
  (let ((value (object "choices" (vector (object "index" 0 "delta"
                                                (object "role" "assistant" "content" content "tool_calls" tools)
                                                "finish_reason" finish)))))
    (when usage (setf (gethash "usage" value) (object "total_tokens" 4))) value))
(defun tool-fragment (index &key id name arguments)
  (object "index" index "id" id "type" "function" "function" (object "name" name "arguments" arguments)))
(defun response-head (&optional (status 200) (content-type "text/event-stream"))
  (format nil "HTTP/1.1 ~d Fixture~c~cContent-Type: ~a~c~cConnection: close~c~c~c~c"
          status #\Return #\Newline content-type #\Return #\Newline #\Return #\Newline #\Return #\Newline))
(defun success-body (&optional (content "hello λ"))
  (concatenate 'string (event (chunk content :finish "stop"))
               (event (chunk "" :finish "stop" :usage t)) (event "[DONE]")))
(defun parse-wire (wire &key (single-byte t))
  (let* ((seen nil) (parser (router::make-parser :emit (lambda (text) (push text seen))))
         (bytes (if (stringp wire) (bytes wire) wire)))
    (if single-byte (loop for byte across bytes do (router::feed parser (vector byte)))
        (router::feed parser bytes))
    (values (router::finish-parser parser) (nreverse seen))))
(defun failure-kind (function)
  (handler-case (progn (funcall function) nil)
    (router:transport-error (condition) (router:transport-error-kind condition))))

(deftest incremental-sse-and-tool-assembly
  (multiple-value-bind (result seen)
      (parse-wire (concatenate 'string (response-head) ": keepalive" (string #\Newline)
                               (success-body)))
    (ok (equal "hello λ" (field result "content")))
    (ok (equal '("hello λ") seen) "single-byte UTF-8 input streams one complete text delta"))
  (let* ((first (chunk "" :tools (vector (tool-fragment 0 :id "a" :name "re" :arguments "{\"x\":")
                                         (tool-fragment 1 :id "b" :name "list" :arguments "{}"))))
         (second (chunk nil :tools (vector (tool-fragment 0 :name "ad" :arguments "\"λ\"}")) :finish "tool_calls"))
         (result (parse-wire (concatenate 'string (response-head) (event first) (event second)
                                          (event (chunk "" :finish "tool_calls" :usage t)) (event "[DONE]")))))
    (ok (= 2 (length (field result "tool_calls"))))
    (ok (equal "read" (field (aref (field result "tool_calls") 0) "name")))
    (ok (equal "λ" (field (field (aref (field result "tool_calls") 0) "arguments") "x")))
    (ok (hash-table-p (field (aref (field result "tool_calls") 1) "arguments"))))
  (let* ((json (router::json-text (chunk "multiline" :finish "stop")))
         (comma (position #\, json))
         (body (format nil "data: ~a~%data: ~a~%~%~a" (subseq json 0 (1+ comma)) (subseq json (1+ comma)) (event "[DONE]"))))
    (ok (equal "multiline" (field (parse-wire (concatenate 'string (response-head) body)) "content"))
        "SSE multiline data fields are joined before JSON parsing")))

(deftest protocol-rejects-incomplete-and-malformed-results
  (dolist (case
            (list (cons :missing-finish (event "[DONE]"))
                  (cons :truncated-stream (event (chunk "partial" :finish "stop")))
                  (cons :incomplete-generation (event (chunk "partial" :finish "length")))
                  (cons :provider-error (event (object "error" (object "message" "credential echo must not be logged"))))
                  (cons :malformed-json (event "{broken"))
                  (cons :data-after-finish (concatenate 'string (event (chunk "done" :finish "stop")) (event (chunk "late"))))
                  (cons :data-after-done (concatenate 'string (success-body) (event (chunk "late"))))
                  (cons :inconsistent-tool-finish (concatenate 'string (event (chunk "" :finish "tool_calls")) (event "[DONE]")))
                  (cons :incomplete-tool-call (concatenate 'string
                                                         (event (chunk "" :tools (vector (tool-fragment 1 :id "x" :name "read" :arguments "{}"))
                                                                       :finish "tool_calls")) (event "[DONE]")))
                  (cons :invalid-tool-arguments (concatenate 'string
                                                            (event (chunk "" :tools (vector (tool-fragment 0 :id "x" :name "read" :arguments "[]"))
                                                                          :finish "tool_calls")) (event "[DONE]")))))
    (ok (eq (car case) (failure-kind (lambda () (parse-wire (concatenate 'string (response-head) (cdr case))))))
        (format nil "reject ~a" (car case))))
  (ok (eq :http-status (failure-kind (lambda () (parse-wire (response-head 401 "application/json"))))))
  (ok (eq :invalid-utf8 (failure-kind (lambda () (parse-wire (concatenate 'vector (bytes (response-head)) #(255 10)))))))
  (ok (eq :trailing-json-data (failure-kind (lambda () (router::parse-json "{} trailing")))))
  (ok (eq :malformed-json (failure-kind (lambda () (router::parse-json (concatenate 'string (make-string 30 :initial-element #\[)
                                                                                 "0" (make-string 30 :initial-element #\]))))))))

(deftest bounded-wire-before-unbounded-allocation
  (let ((parser (router::make-parser :emit (constantly nil))))
    (router::feed parser (bytes (response-head)))
    (ok (eq :line-budget (failure-kind (lambda () (dotimes (i 17) (router::feed parser (make-array 4096 :initial-element 65))))))))
  (let ((parser (router::make-parser :emit (constantly nil))))
    (router::feed parser (bytes (response-head)))
    (ok (eq :event-budget
            (failure-kind (lambda ()
                            (dotimes (i 2)
                              (router::feed parser (bytes (format nil "data: ~a~%" (make-string 40000 :initial-element #\x))))))))))
  (let ((parser (router::make-parser :emit (constantly nil))))
    (router::feed parser (bytes (response-head)))
    (ok (eq :response-budget
            (failure-kind (lambda ()
                            (dotimes (i 1024) (router::feed parser (bytes (format nil ": ~a~%" (make-string 2048 :initial-element #\x)))))))))))

(define-condition fixture-stop (error) ())
(defstruct fixture listener thread endpoint requests error)
(defun read-fixture-line (stream)
  (let ((line (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (loop for byte = (read-byte stream nil) do (unless byte (error "Fixture request closed early"))
          until (= byte 10)
          do (when (>= (length line) 16384) (error "Fixture header too long"))
             (unless (= byte 13) (vector-push-extend byte line)))
    (babel:octets-to-string line :encoding :utf-8)))
(defun read-fixture-request (stream)
  (let ((headers (make-hash-table :test 'equalp)) (start (read-fixture-line stream)))
    (loop for line = (read-fixture-line stream) until (zerop (length line))
          for colon = (position #\: line)
          do (unless colon (error "Fixture malformed header"))
             (setf (gethash (subseq line 0 colon) headers) (string-trim '(#\Space) (subseq line (1+ colon)))))
    (let* ((length (parse-integer (gethash "content-length" headers)))
           (body (make-array length :element-type '(unsigned-byte 8))))
      (unless (<= 0 length (* 1024 1024)) (error "Fixture request too large"))
      (loop for index below length do (setf (aref body index) (read-byte stream)))
      (object "start" start "headers" headers "body" (babel:octets-to-string body :encoding :utf-8)))))
(defun start-fixture (respond &optional (requests 1))
  (let* ((socket (make-instance 'sb-bsd-sockets:inet-socket :type :stream :protocol :tcp))
         (fixture (make-fixture :listener socket)))
    (sb-bsd-sockets:socket-bind socket #(127 0 0 1) 0)
    (sb-bsd-sockets:socket-listen socket 4)
    (setf (fixture-endpoint fixture) (format nil "http://127.0.0.1:~d/chat" (nth-value 1 (sb-bsd-sockets:socket-name socket))))
    (setf (fixture-thread fixture)
          (sb-thread:make-thread
           (lambda ()
             (handler-case
                 (dotimes (index requests)
                   (let ((peer (sb-bsd-sockets:socket-accept socket)))
                     (unwind-protect
                          (with-open-stream (stream (sb-bsd-sockets:socket-make-stream peer :input t :output t
                                                                                       :element-type '(unsigned-byte 8) :buffering :none))
                            (let ((request (read-fixture-request stream)))
                              (push request (fixture-requests fixture))
                              (funcall respond stream request index)))
                       (ignore-errors (sb-bsd-sockets:socket-close peer)))))
               (fixture-stop ()) (error (condition) (setf (fixture-error fixture) condition))))
           :name "OpenRouter HTTP fixture")) fixture))
(defun stop-fixture (fixture)
  (when (sb-thread:thread-alive-p (fixture-thread fixture))
    (sb-thread:interrupt-thread (fixture-thread fixture) (lambda () (error 'fixture-stop))))
  (sb-thread:join-thread (fixture-thread fixture))
  (sb-bsd-sockets:socket-close (fixture-listener fixture)))
(defun send-wire (stream wire)
  (write-sequence (if (stringp wire) (bytes wire) wire) stream) (finish-output stream))
(defmacro with-transport ((manager job-manager directory fixture responder &key (requests 1)) &body body)
  `(let* ((,directory (merge-pathnames (format nil "lem-openrouter-~a/" (store:new-id)) (uiop:temporary-directory)))
          (,job-manager (jobs:open-job-manager :directory (merge-pathnames "jobs/" ,directory)))
          (,manager (agent:make-manager :directory (merge-pathnames "agents/" ,directory)))
          (,fixture (start-fixture ,responder ,requests)))
     (unwind-protect (progn ,@body)
       (agent:close-manager ,manager :wait t) (jobs:close-job-manager ,job-manager)
       (stop-fixture ,fixture) (uiop:delete-directory-tree ,directory :validate t))))
(defun install-provider (manager job-manager fixture &key (timeout 3) (key "fake-openrouter-key") on-error)
  (let ((provider (router:make-provider :job-manager job-manager :curl-program (uiop:getenv "LEM_TEST_CURL")
                                       :api-key-provider (lambda () key) :timeout timeout
                                       :test-endpoint (fixture-endpoint fixture))))
    (agent:register-provider manager "openrouter"
                             (lambda (request emit context)
                               (handler-case (funcall provider request emit context)
                                 (router:transport-error (condition)
                                   (when on-error (funcall on-error condition))
                                   (error condition)))))))
(defun new-session (manager directory)
  (let ((session (agent:create-session manager :provider "openrouter" :model "fake/model" :root directory)))
    (await (agent:session-ready session)) session))

(deftest actual-curl-private-input-and-native-tool-round
  (let ((executions 0) (key "fake-quote-\"backslash-\\-token"))
    (with-transport (manager job-manager directory fixture
                            (lambda (stream request index)
                              (declare (ignore request))
                              (send-wire stream (concatenate 'string (response-head)
                                                            (if (zerop index)
                                                                (concatenate 'string
                                                                             (event (chunk "" :tools (vector (tool-fragment 0 :id "call-1" :name "read" :arguments "{\"x\":3}"))
                                                                                           :finish "tool_calls")) (event "[DONE]"))
                                                                (success-body "finished λ"))))) :requests 2)
      (install-provider manager job-manager fixture :key key)
      (agent:register-tool manager "read" :schema (object "type" "object")
                           :validate (lambda (arguments) (eql 3 (field arguments "x")))
                           :execute (lambda (arguments context) (declare (ignore arguments context)) (incf executions) (object "value" 4)))
      (let ((session (new-session manager directory)))
        (await (agent:submit-message session "private-request-body"))
        (wait-for (lambda ()
                    (let ((snapshot (agent:session-snapshot session)))
                      (and (equal "idle" (field snapshot "status"))
                           (= 1 (length (field snapshot "turns")))
                           (equal "completed" (field (aref (field snapshot "turns") 0) "status"))))))
        (ok (= 1 executions) "the Lisp core executes the tool between two native transport requests")
        (ok (null (find-package :lem-core)) "the native transport has no editor dependency")
        (ok (= 2 (length (fixture-requests fixture))))
        (ok (null (fixture-error fixture)) "the local HTTP server completed both exchanges cleanly")
        (dolist (request (fixture-requests fixture))
          (ok (equal (concatenate 'string "Bearer " key) (gethash "authorization" (field request "headers"))))
          (let ((body (router::parse-json (field request "body"))))
            (ok (field body "stream"))
            (ok (equal "function" (field (aref (field body "tools") 0) "type")))))
        (let* ((second (router::parse-json (field (first (fixture-requests fixture)) "body")))
               (messages (field second "messages")) (tool (aref messages (1- (length messages)))))
          (ok (equal "tool" (field tool "role")))
          (ok (equal "call-1" (field tool "tool_call_id")))
          (ok (= 4 (field (router::parse-json (field tool "content")) "value"))))
        (dolist (job (jobs:list-jobs job-manager))
          (let* ((snapshot (jobs:job-snapshot job))
                 (journal (uiop:read-file-string (merge-pathnames (format nil "jobs/~a.json" (jobs:job-id job)) directory))))
            (ok (equal "--disable" (aref (field snapshot "argv") 1)))
            (ok (and (not (search key journal)) (not (search "private-request-body" journal)))
                "credentials and request body never enter managed job argv or journals")
            (ok (every (lambda (needle)
                         (not (search (ironclad:byte-array-to-hex-string (bytes needle)) journal)))
                       '("fake-quote-" "private-request-body"))
                "private request data is also absent from raw hexadecimal job output")
            (ok (<= (field snapshot "stdout-retained-bytes") 1))))))))

(deftest actual-http-failures-and-cancellation
  (dolist (mode '(:unauthorized :truncated :provider-error :hang :noisy :invalid-length))
    (let ((failure nil))
    (with-transport (manager job-manager directory fixture
                            (lambda (stream request index)
                              (declare (ignore request index))
                              (case mode
                                (:unauthorized (send-wire stream (concatenate 'string (response-head 401 "application/json") "{}")))
                                (:truncated (send-wire stream (concatenate 'string (response-head) (event (chunk "partial")))))
                                (:provider-error (send-wire stream (concatenate 'string (response-head) (event (object "error" (object "message" "fixture failure"))))))
                                (:hang (send-wire stream (response-head)) (read-byte stream nil))
                                (:invalid-length
                                 (send-wire stream
                                            (format nil "HTTP/1.1 200 OK~c~cContent-Type: text/event-stream~c~cContent-Length: 99999~c~c~c~c~a"
                                                    #\Return #\Newline #\Return #\Newline #\Return #\Newline #\Return #\Newline
                                                    (success-body))))
                                (:noisy (send-wire stream (response-head))
                                        (loop repeat 50 do (send-wire stream (make-array 4096 :initial-element 65)))))))
      (install-provider manager job-manager fixture :timeout (if (eq mode :hang) 0.3 3)
                        :on-error (lambda (condition) (setf failure (router:transport-error-kind condition))))
      (let ((session (new-session manager directory)))
        (await (agent:submit-message session "exercise failure"))
        (wait-for (lambda () (equal "failed" (state session))))
        (ok (not (equal "idle" (state session))) (format nil "HTTP fixture ~a is an explicit failure" mode))
        (when (eq mode :unauthorized)
          (let* ((record (store:read-private-json (merge-pathnames "agents/" directory)
                                                 (agent:session-id session) :maximum-depth 24))
                 (diagnostics (field record "diagnostics")))
            (ok (some (lambda (text) (and (search "HTTP-STATUS" text) (search "401" text)))
                      diagnostics)
                "the durable session explains authentication failure using safe status fields")))
        (ok (fixture-requests fixture) "the failure follows a request to the actual local HTTP fixture")
        (ok (eq failure (ecase mode
                          (:unauthorized :http-status) (:truncated :truncated-stream)
                          (:provider-error :provider-error) (:hang :managed-request)
                          (:noisy :line-budget) (:invalid-length :managed-request)))
            (format nil "~a reports its precise transport failure" mode))
        (ok (every (lambda (job) (jobs:job-result job)) (jobs:list-jobs job-manager))
            "the managed request is terminal before the provider reports failure")))))
  (with-transport (manager job-manager directory fixture
                          (lambda (stream request index) (declare (ignore request index))
                            (send-wire stream (response-head)) (read-byte stream nil)))
    (install-provider manager job-manager fixture :timeout 10)
    (let ((session (new-session manager directory)))
      (await (agent:submit-message session "interrupt"))
      (wait-for (lambda () (fixture-requests fixture)))
      (await (agent:interrupt-session session))
      (wait-for (lambda () (every (lambda (job) (jobs:job-result job)) (jobs:list-jobs job-manager))))
      (ok (equal "interrupted" (state session)))
      (ok (equal "cancelled" (field (jobs:job-result (first (jobs:list-jobs job-manager))) "state"))))))

(deftest explicit-credential-and-endpoint-boundaries
  (with-transport (manager job-manager directory fixture
                          (lambda (stream request index) (declare (ignore request index))
                            (send-wire stream (concatenate 'string (response-head) (success-body)))))
    (dolist (endpoint '("http://openrouter.ai/api/v1/chat/completions" "https://example.com/chat"
                        "http://127.0.0.1.evil:80/chat" "http://127.0.0.1:80/chat?redirect=elsewhere"))
      (ok (eq :invalid-provider-configuration
              (failure-kind (lambda ()
                              (router:make-provider :job-manager job-manager :curl-program (uiop:getenv "LEM_TEST_CURL")
                                                    :test-endpoint endpoint))))
          "the fixture escape hatch cannot send provider credentials to another host"))
    (let ((original (symbol-function 'uiop:getenvp)) (lookups nil))
      (unwind-protect
           (progn
             (setf (symbol-function 'uiop:getenvp)
                   (lambda (name)
                     (cond ((equal name "OPENROUTER_API_KEY") (push name lookups) nil)
                           ((equal name "OPENAI_API_KEY") (push name lookups) "wrong-provider-fixture-key")
                           (t (funcall original name)))))
             (agent:register-provider manager "openrouter"
                                      (router:make-provider :job-manager job-manager :curl-program (uiop:getenv "LEM_TEST_CURL")
                                                            :test-endpoint (fixture-endpoint fixture)))
             (let ((session (new-session manager directory)))
               (await (agent:submit-message session "missing credential"))
               (wait-for (lambda () (equal "failed" (state session))))
               (ok (equal '("OPENROUTER_API_KEY") lookups) "the default credential lookup never falls back to another provider")
               (ok (null (jobs:list-jobs job-manager)) "a missing matching credential starts no external request")))
        (setf (symbol-function 'uiop:getenvp) original)))
    (install-provider manager job-manager fixture :key (format nil "bad~cInjected: header" #\Newline))
    (let ((session (new-session manager directory)))
      (await (agent:submit-message session "invalid credential"))
      (wait-for (lambda () (equal "failed" (state session))))
      (ok (null (jobs:list-jobs job-manager)) "a credential containing a newline is rejected before curl starts"))))

(deftest throwing-stream-consumer-terminates-the-managed-request
  (with-transport (manager job-manager directory fixture
                          (lambda (stream request index) (declare (ignore request index))
                            (send-wire stream (concatenate 'string (response-head) (event (chunk "first delta"))))
                            (read-byte stream nil)))
    (let ((provider (router:make-provider :job-manager job-manager :curl-program (uiop:getenv "LEM_TEST_CURL")
                                         :api-key-provider (constantly "fake-key") :timeout 5
                                         :test-endpoint (fixture-endpoint fixture)))
          (failure nil))
      (agent:register-provider manager "openrouter"
                               (lambda (request emit context)
                                 (declare (ignore emit))
                                 (handler-case
                                     (funcall provider request (lambda (text) (declare (ignore text))
                                                                 (error "fake-secret-in-consumer-error")) context)
                                   (router:transport-error (condition)
                                     (setf failure (router:transport-error-kind condition)) (error condition)))))
      (let ((session (new-session manager directory)))
        (await (agent:submit-message session "break consumer"))
        (wait-for (lambda () (equal "failed" (state session))))
        (ok (eq failure :output-consumer))
        (let* ((job (first (jobs:list-jobs job-manager)))
               (result (jobs:job-result job))
               (journal (uiop:read-file-string (merge-pathnames (format nil "jobs/~a.json" (jobs:job-id job)) directory))))
          (ok (equal "failed" (field result "state")))
          (ok (not (search "fake-secret-in-consumer-error" journal))
              "consumer failure closes the guardian boundary without journaling arbitrary error arguments"))))))

(deftest unavailable-project-does-not-disable-http-transport
  (dolist (mode '(:missing :renamed))
    (let ((tool-roots nil))
      (with-transport (manager job-manager directory fixture
                              (lambda (stream request index)
                                (declare (ignore request))
                                (send-wire
                                 stream
                                 (concatenate
                                  'string (response-head)
                                  (if (zerop index)
                                      (concatenate
                                       'string
                                       (event (chunk "" :tools
                                                     (vector (tool-fragment 0 :id "root-call" :name "inspect_root"
                                                                             :arguments "{}"))
                                                     :finish "tool_calls"))
                                       (event "[DONE]"))
                                      (success-body "Project recovery remains available"))))) :requests 2)
        (install-provider manager job-manager fixture)
        (agent:register-tool manager "inspect_root" :schema (object "type" "object")
                             :validate #'hash-table-p
                             :execute (lambda (arguments context)
                                        (declare (ignore arguments))
                                        (push (agent:operation-root context) tool-roots)
                                        (object "root" (agent:operation-root context))))
        (let ((root (merge-pathnames "project/" directory)))
          (when (eq mode :renamed) (ensure-directories-exist root))
          (let ((session (new-session manager root)))
            (when (eq mode :renamed)
              (rename-file root (merge-pathnames "renamed-project/" directory)))
            (ok (not (probe-file root)) "the original project path is unavailable before the request")
            (await (agent:submit-message session "Help recover the unavailable project"))
            (wait-for
             (lambda ()
               (let ((snapshot (agent:session-snapshot session)))
                 (and (equal "idle" (field snapshot "status"))
                      (= 1 (length (field snapshot "turns")))
                      (equal "completed" (field (aref (field snapshot "turns") 0) "status"))))))
            (ok (= 2 (length (fixture-requests fixture)))
                (format nil "~a project still permits both actual HTTP provider rounds" mode))
            (ok (null (fixture-error fixture)))
            (ok (equal (list (namestring root)) tool-roots)
                "tool contexts retain the original root rather than the HTTP process cwd")
            (ok (equal (namestring root) (field (agent:session-snapshot session) "root")))
            (ok (every (lambda (job) (equal "/" (jobs:job-directory job))) (jobs:list-jobs job-manager))
                "only the HTTP process cwd is neutral")))))))
