(defpackage :lem-agent/ui/tests
  (:use :cl :rove)
  (:local-nicknames (:agent :lem-agent) (:ui :lem-agent/ui)
                    (:store :lem-daemon/recovery-store)))
(in-package :lem-agent/ui/tests)

(defun field (object name) (gethash name object))
(defun await (receipt)
  (multiple-value-bind (value done) (agent:await-request receipt :timeout 8)
    (unless done (error "Test receipt timed out")) value))
(defun pump () (lem-core::receive-event 0))
(defun wait-for (predicate &key (pump t))
  (loop repeat 800 do (when pump (pump))
        when (funcall predicate) return t do (sleep 0.005)
        finally (error "Expected UI state did not arrive")))
(defun contains (buffer text) (search text (lem:buffer-text buffer)))
(defun state (session) (field (agent:session-snapshot session) "status"))
(defun idle (session)
  (wait-for (lambda () (equal "idle" (state session)))))
(defun pending (session)
  (find "pending" (field (agent:session-snapshot session) "decisions")
        :key (lambda (item) (field item "status")) :test #'equal))
(defun ready-input (buffer)
  (wait-for (lambda () (not (or (lem:buffer-value buffer 'ui::pending-request)
                               (lem:buffer-value buffer 'ui::lifecycle-request))))))
(defun new-session (manager directory &optional (provider "fake"))
  (let ((session (agent:create-session manager :provider provider :model "fixture-model" :root directory)))
    (await (agent:session-ready session)) session))
(defstruct gate (lock (bt2:make-lock)) (wake (bt2:make-condition-variable)) open)
(defun release (gate)
  (bt2:with-lock-held ((gate-lock gate))
    (setf (gate-open gate) t) (bt2:condition-broadcast (gate-wake gate))))
(defun block-on (gate)
  (bt2:with-lock-held ((gate-lock gate))
    (loop until (gate-open gate)
          do (unless (bt2:condition-wait (gate-wake gate) (gate-lock gate) :timeout 8)
               (error "Fixture gate timed out")))))

(defmacro with-ui ((manager directory) &body body)
  `(let ((lem-core::*frames* nil)
         (lem-core::*display-frame-map* (make-hash-table)))
     (lem:with-current-buffers ()
       (let ((lem/buffer/internal::*current-buffer* (lem:primordial-buffer)))
         (lem-fake-interface:with-fake-interface ()
           (let* ((,directory (merge-pathnames (format nil "agent-ui-~a/" (store:new-id))
                                              (uiop:temporary-directory)))
                  (,manager (agent:make-manager :directory ,directory)))
             (unwind-protect (progn ,@body)
               (loop for buffer being the hash-keys of ui::*views* collect buffer into buffers
                     finally (mapc #'ui::retire-view buffers))
               (agent:close-manager ,manager :wait t)
               (wait-for (lambda () (zerop ui::*pending-requests*)))
               (uiop:delete-directory-tree ,directory :validate t))))))))

(defun complete-provider (request emit context)
  (declare (ignore request context))
  (funcall emit "fast response") (agent:json-object))

(defun tool-provider (request emit context)
  (declare (ignore emit context))
  (if (equal "tool" (field (aref (field request "messages")
                                 (1- (length (field request "messages")))) "role"))
      (agent:json-object "content" "tool finished")
      (agent:json-object "tool_calls"
                        (vector (agent:json-object "id" "fixture-call" "name" "run_process"
                                                   "arguments" (agent:json-object "argv" #("fixture" "exact arg")))))))

(defun point-at-decision (buffer id)
  (lem:switch-to-buffer buffer)
  (lem:move-to-position (lem:current-point) (1+ (or (contains buffer (format nil "Decision ~a" id))
                                                   (error "Decision not rendered")))))

(deftest independent-streaming-and-disposable-views
  (with-ui (manager directory)
    (let ((gate (make-gate)) (entered nil))
      (agent:register-provider manager "fake" #'complete-provider)
      (agent:register-provider
       manager "slow" (lambda (request emit context)
                        (declare (ignore request context))
                        (funcall emit "stream λ") (setf entered t) (block-on gate)
                        (dotimes (i 1000) (funcall emit "."))
                        (funcall emit "slow completed") (agent:json-object)))
      (let* ((slow (new-session manager directory "slow"))
             (fast (new-session manager directory))
             (original-buffer (lem:current-buffer))
             (slow-view (ui:show-session slow)) (fast-view (ui:show-session fast)))
        (unwind-protect
             (progn
               (ok (eq original-buffer (lem:current-buffer)) "show-session never selects a buffer")
               (await (agent:submit-message slow "slow"))
               (await (agent:submit-message fast "fast"))
               (wait-for (lambda () entered) :pump nil)
               (wait-for (lambda () (and (ui::view-queued (gethash slow-view ui::*views*))
                                        (ui::view-queued (gethash fast-view ui::*views*)))) :pump nil)
               (ok (<= (lem-core::event-queue-length) 2) "one queued redraw per view before editor consumption")
               (wait-for (lambda () (contains slow-view "stream λ")))
               (wait-for (lambda () (contains fast-view "fast response")))
               (ok (equal "running" (state slow)))
               (ok (lem:buffer-read-only-p slow-view))
               (ok (eq original-buffer (lem:current-buffer)) "worker updates do not steal focus")
               (ui::request-refresh (gethash slow-view ui::*views*))
               (wait-for (lambda () (ui::view-queued (gethash slow-view ui::*views*))) :pump nil)
               (let ((old-name (lem:buffer-name slow-view)))
                 (lem:delete-buffer slow-view)
                 (let ((replacement (lem:make-buffer old-name)))
                   (lem:insert-string (lem:buffer-point replacement) "replacement owns this name")
                   (pump)
                   (ok (equal "replacement owns this name" (lem:buffer-text replacement))
                       "a queued callback cannot mutate a new buffer with the same name")))
               (ok (equal "running" (state slow)) "closing a view does not interrupt work")
               (let ((reopened (ui:show-session slow)))
                 (release gate)
                 (wait-for (lambda () (contains reopened "slow completed")))
                 (ok (eq original-buffer (lem:current-buffer)))))
          (release gate))))))

(deftest concrete-decisions-race-once-and-survive-view-closure
  (with-ui (manager directory)
    (let ((executions 0))
      (agent:register-provider manager "fake" #'tool-provider)
      (agent:register-tool manager "run_process" :schema (agent:json-object "type" "object")
                           :validate (constantly t) :permission t
                           :execute (lambda (args context) (declare (ignore args context))
                                      (incf executions) (agent:json-object "exit" 0)))
      (let* ((session (new-session manager directory))
             (first (ui:show-decisions session)) (second (ui:show-decisions session)))
        (await (agent:submit-message session "run fixture"))
        (wait-for (lambda () (pending session)))
        (let ((id (field (pending session) "id")))
          (wait-for (lambda () (and (contains first id) (contains second id))))
          (ok (contains first "run_process")) (ok (contains first "exact arg"))
          (lem:switch-to-buffer first) (lem:buffer-start (lem:current-point))
          (ok (signals (ui:agent-allow) 'lem:editor-error) "no action without the concrete record under point")
          (lem:delete-buffer first)
          (ok (equal id (field (pending session) "id")) "killing the view does not answer a question")
          (setf first (ui:show-decisions session))
          (wait-for (lambda () (contains first id)))
          (point-at-decision first id) (ui:agent-allow)
          (point-at-decision second id) (ui:agent-allow)
          (ready-input first) (ready-input second)
          (wait-for (lambda () (= executions 1)))
          (ok (= 1 (count-if (lambda (buffer) (search "Approval accepted" (ui:composer-status buffer)))
                             (list first second)))
              "exactly one competing view gets durable acceptance")
          (ok (= 1 (count-if (lambda (buffer) (search "not accepted" (ui:composer-status buffer)))
                             (list first second))))
          (idle session)))
      (let ((session (new-session manager directory)))
        (await (agent:submit-message session "deny fixture"))
        (wait-for (lambda () (pending session)))
        (let* ((view (ui:show-decisions session)) (id (field (pending session) "id")))
          (wait-for (lambda () (contains view id)))
          (point-at-decision view id) (ui:agent-deny) (ready-input view)
          (idle session) (ok (= executions 1) "denial never executes the tool"))))))

(deftest draft-revision-and-durable-receipts
  (with-ui (manager directory)
    (agent:register-provider manager "fake" #'complete-provider)
    (let* ((session (new-session manager directory)) (composer (ui:show-composer session))
           (gate (make-gate)) (publishing nil)
           (original-write (symbol-function 'store:write-private-json))
           (original-await (symbol-function 'agent:await-request))
           (editor (bt2:current-thread)) (waited-on-editor nil))
      (unwind-protect
           (progn
             (setf (symbol-function 'store:write-private-json)
                   (lambda (directory id value &rest args)
                     (when (and (equal id (agent:session-id session))
                                (plusp (length (field value "queue"))) (not publishing))
                       (setf publishing t) (block-on gate))
                     (apply original-write directory id value args))
                   (symbol-function 'agent:await-request)
                   (lambda (&rest args)
                     (when (eq editor (bt2:current-thread)) (setf waited-on-editor t))
                     (apply original-await args)))
             (lem:insert-string (lem:buffer-point composer) "original")
             (ui:submit-composer composer)
             (wait-for (lambda () publishing))
             (ok (equal "original" (lem:buffer-text composer)) "draft stays until the journal write completes")
             (lem:insert-string (lem:buffer-point composer) " + newer typing")
             (release gate) (ready-input composer)
             (ok (equal "original + newer typing" (lem:buffer-text composer)))
             (ok (search "newer draft preserved" (ui:composer-status composer)))
             (ng waited-on-editor "receipt waits never run on the editor thread"))
        (release gate)
        (setf (symbol-function 'store:write-private-json) original-write
              (symbol-function 'agent:await-request) original-await))
      (ui:submit-composer composer) (ready-input composer)
      (ok (equal "" (lem:buffer-text composer)) "unchanged draft clears after durable acceptance")
      (await (agent:close-session session))
      (lem:insert-string (lem:buffer-point composer) "keep rejected draft")
      (ui:submit-composer composer) (ready-input composer)
      (ok (equal "keep rejected draft" (lem:buffer-text composer)))
      (ok (search "failed" (ui:composer-status composer))))))

(deftest clarification-is-editable-and-deliberate
  (with-ui (manager directory)
    (agent:register-provider
     manager "fake" (lambda (request emit context)
                      (declare (ignore emit context))
                      (if (= 1 (length (field request "messages")))
                          (agent:json-object "clarification"
                                            (agent:json-object "question" "Choose a branch" "choices" #("left" "right")))
                          (agent:json-object "content" "answer received"))))
    (let ((session (new-session manager directory)))
      (await (agent:submit-message session "ask me"))
      (wait-for (lambda () (pending session)))
      (let* ((decision (pending session)) (view (ui:show-decisions session))
             (answer (ui:show-composer session :decision decision)))
        (wait-for (lambda () (contains view "Choose a branch")))
        (ok (contains view "right"))
        (point-at-decision view (field decision "id"))
        (ok (signals (ui:agent-allow) 'lem:editor-error) "permission keys cannot answer a clarification")
        (lem:delete-buffer view)
        (lem:insert-string (lem:buffer-point answer) "wrong")
        (ok (pending session) "typing and view closure do not submit an answer")
        (ui:submit-composer answer) (ready-input answer)
        (ok (equal "wrong" (lem:buffer-text answer)))
        (ok (pending session) "invalid choices retain the pending question")
        (lem:erase-buffer answer) (lem:insert-string (lem:buffer-point answer) "left")
        (ui:submit-composer answer) (ready-input answer)
        (ok (equal "" (lem:buffer-text answer)))
        (let ((reopened (ui:show-session session)))
          (wait-for (lambda () (contains reopened "answer received"))))))))

(deftest explicit-interrupt-resume-and-late-operation-callbacks
  (with-ui (manager directory)
    (let ((gate (make-gate)) (entered nil) (finished nil) (calls 0) old-context)
      (agent:register-provider
       manager "fake" (lambda (request emit context)
                        (declare (ignore request))
                        (if (= 1 (incf calls))
                            (progn (setf old-context context entered t) (block-on gate) (setf finished t)
                                   (funcall emit "forbidden late text")
                                   (agent:json-object "content" "forbidden late response"))
                            (agent:json-object "content" "resumed follow-up"))))
      (let* ((session (new-session manager directory)) (view (ui:show-session session)))
        (unwind-protect
             (progn
               (await (agent:submit-message session "first"))
               (wait-for (lambda () entered))
               (await (agent:submit-message session "queued next"))
               (lem:switch-to-buffer view) (ui:agent-interrupt)
               (ng (agent:operation-live-p old-context)
                   "interrupt invalidates the generation before the editor command returns")
               (ready-input view)
               (wait-for (lambda () (contains view "interrupted")))
               (ok (contains view "queued next"))
               (ok (= calls 1) "interrupt does not automatically resume queued work")
               (ui:agent-resume) (ready-input view)
               (wait-for (lambda () (contains view "resumed follow-up")))
               (release gate) (wait-for (lambda () finished))
               (ui:agent-refresh) (pump)
               (ng (contains view "forbidden late") "interrupted generation cannot change the transcript")
               (ui:agent-close-session) (ready-input view)
               (wait-for (lambda () (contains view "Status: closed"))))
          (release gate))))))

(deftest bounded-render-and-session-list
  (with-ui (manager directory)
    (agent:register-provider manager "fake"
                             (lambda (request emit context) (declare (ignore request emit context))
                               (agent:json-object "content" (make-string 65536 :initial-element #\x))))
    (let* ((session (new-session manager directory)) (view (ui:show-session session))
           (listing (ui:show-session-list manager)))
      (await (agent:submit-message session "large response"))
      (wait-for (lambda () (contains view "Display truncated")))
      (ok (< (length (lem:buffer-text view)) 65600))
      (wait-for (lambda () (contains listing (agent:session-id session))))
      (lem:switch-to-buffer listing)
      (lem:move-to-position (lem:current-point) (1+ (contains listing (agent:session-id session))))
      (ui:agent-open-session)
      (ok (eq session (lem:buffer-value (lem:current-buffer) 'ui::agent-session))))))

(deftest unknown-tool-outcome-is-visible
  (with-ui (manager directory)
    (let ((gate (make-gate)) (entered nil))
      (agent:register-provider manager "fake" #'tool-provider)
      (agent:register-tool manager "run_process" :schema (agent:json-object "type" "object")
                           :validate (constantly t)
                           :execute (lambda (args context) (declare (ignore args context))
                                      (setf entered t) (block-on gate) (agent:json-object "effect" "late")))
      (let* ((session (new-session manager directory)) (view (ui:show-session session)))
        (unwind-protect
             (progn
               (await (agent:submit-message session "tool effect"))
               (wait-for (lambda () entered))
               (lem:switch-to-buffer view) (ui:agent-interrupt) (ready-input view)
               (wait-for (lambda () (contains view "unknown")))
               (ok (contains view "run_process"))
               (ok (contains view "not replayed")))
          (release gate))))))

(deftest partial-decision-blocks-are-not-actionable
  (with-ui (manager directory)
    (agent:register-provider manager "fake" #'tool-provider)
    (agent:register-tool manager "run_process" :schema (agent:json-object "type" "object")
                         :validate (constantly t) :permission t :execute (constantly nil))
    (let ((session (new-session manager directory)))
      (await (agent:submit-message session "inspect"))
      (wait-for (lambda () (pending session)))
      ;; Exercise the worker formatter with a deliberately tiny display budget.
      (let ((view (ui::make-view nil session nil :decisions)))
        (multiple-value-bind (full spans) (ui::format-view view)
          (declare (ignore full))
          (let ((ui::*render-limit* (- (second (first spans)) 1)))
            (multiple-value-bind (partial targets) (ui::format-view view)
              (ok (search "Display truncated" partial))
              (ok (null targets) "incomplete arguments never acquire an approval target"))))))))

(deftest pending-composer-can-interrupt-and-be-killed
  (with-ui (manager directory)
    (let ((tool-gate (make-gate)) (write-gate (make-gate)) context publishing
          (original-write (symbol-function 'store:write-private-json)))
      (agent:register-provider
       manager "fake" (lambda (request emit operation)
                        (declare (ignore request emit))
                        (setf context operation) (block-on tool-gate) (agent:json-object)))
      (let* ((session (new-session manager directory)) (composer (ui:show-composer session)))
        (unwind-protect
             (progn
               (await (agent:submit-message session "start"))
               (wait-for (lambda () context))
               (setf (symbol-function 'store:write-private-json)
                     (lambda (directory id value &rest args)
                       (when (and (equal id (agent:session-id session))
                                  (plusp (length (field value "queue"))) (not publishing))
                         (setf publishing t) (block-on write-gate))
                       (apply original-write directory id value args)))
               (lem:insert-string (lem:buffer-point composer) "retained follow-up")
               (ui:submit-composer composer)
               (wait-for (lambda () publishing))
               (lem:switch-to-buffer composer) (ui:agent-interrupt)
               (ng (agent:operation-live-p context)
                   "a pending composer receipt does not prevent immediate interruption")
               (let ((name (lem:buffer-name composer)))
                 (lem:delete-buffer composer)
                 (let ((replacement (lem:make-buffer name)))
                   (lem:insert-string (lem:buffer-point replacement) "new draft buffer")
                   (release write-gate)
                   (wait-for (lambda () (zerop ui::*pending-requests*)))
                   (ok (equal "new draft buffer" (lem:buffer-text replacement))
                       "late message and interruption receipts cannot clear a replacement composer")))
               (ok (equal "interrupted" (state session)))
               (ok (= 1 (length (field (agent:session-snapshot session) "queue")))
                   "accepted follow-up remains queued after its composer closes"))
          (release write-gate) (release tool-gate)
          (setf (symbol-function 'store:write-private-json) original-write))))))
