(defpackage :lem-daemon/tests/recovery
  (:use :cl :rove)
  (:local-nicknames (:recovery :lem-daemon/recovery)
                    (:store :lem-daemon/recovery-store)))
(in-package :lem-daemon/tests/recovery)

(defclass recovery-test-timer-manager (lem/common/timer:timer-manager) ())
(defmethod lem/common/timer:send-timer-notification ((manager recovery-test-timer-manager) function)
  (declare (ignore manager function)))

(defmacro with-test-frame (() &body body)
  `(let ((lem/common/timer::*timer-manager* (make-instance 'recovery-test-timer-manager)))
     (lem:with-implementation (make-instance 'lem-daemon:daemon-implementation)
       (lem:setup-first-frame)
       ,@body)))

(defmacro with-recovery-directory ((directory) &body body)
  `(let ((,directory (merge-pathnames (format nil "lem-recovery-~a/" (store:new-id))
                                     (uiop:temporary-directory))))
     (unwind-protect (progn ,@body)
       (recovery:disable)
       (when (probe-file ,directory)
         (uiop:delete-directory-tree ,directory :validate t)))))

(defun record (id &optional (text "unsaved λ 界"))
  (store:object "version" 1 "id" id "name" "scratch" "filename" nil
                "baseline" "unknown" "created" (get-universal-time)
                "point" 0 "text" text))

(defun write-text (path text)
  (with-open-file (stream path :direction :output :if-exists :supersede
                               :external-format :utf-8)
    (write-string text stream)))

(deftest private-atomic-records
  (with-recovery-directory (directory)
    (let* ((id (store:new-id)) (path (store:write-record directory (record id))))
      (ok (equal "unsaved λ 界" (store:field (store:read-record directory id) "text")))
      (ok (= #o600 (logand #o777 (sb-posix:stat-mode (sb-posix:stat (namestring path))))))
      (ok (= #o700 (logand #o777 (sb-posix:stat-mode (sb-posix:stat (namestring directory))))))
      (store:write-record directory (record id "newer"))
      (ok (equal "newer" (store:field (store:read-record directory id) "text"))))
    (ok (signals (store:write-record directory (record "../../wrong")))))
  (with-recovery-directory (directory)
    (ensure-directories-exist directory)
    (sb-posix:chmod (namestring directory) #o755)
    (ok (signals (store:write-record directory (record (store:new-id)))))))

(deftest malformed-and-symlink-records
  (with-recovery-directory (directory)
    (let* ((id (store:new-id)) (path (store:write-record directory (record id))))
      (write-text path "{\"version\":1,\"text\":\"#.(error :read-eval)\"}")
      (ok (signals (store:read-record directory id)) "schema rejects a malformed record")
      (multiple-value-bind (records failures) (store:list-records directory)
        (ok (null records)) (ok (= 1 (length failures))))
      (delete-file path)
      (sb-posix:symlink "/etc/passwd" (namestring path))
      (ok (signals (store:read-record directory id)) "record symlinks are rejected")
      (ok (signals (store:write-record directory (record id))) "replace rejects a symlink target")
      (ok (signals (store:discard-record directory id)))
      (delete-file path)
      (write-text path "{\"a\":[[[[[]]]]]}")
      (sb-posix:chmod (namestring path) #o600)
      (ok (signals (store:read-record directory id)) "excessive JSON nesting is rejected"))))

(deftest recover-file-and-scratch-with-conflict
  (with-test-frame ()
    (with-recovery-directory (directory)
      (store::ensure-private-directory directory)
      (let* ((path (merge-pathnames "example.txt" directory))
             (scratch (lem:make-buffer "recovery scratch"))
             (file nil) (restored nil))
        (unwind-protect
             (progn
               (write-text path "original")
               (recovery:enable :directory directory)
               (setf file (lem:find-file-buffer path))
               (lem:insert-string (lem:buffer-end-point file) " unsaved")
               (lem:insert-string (lem:buffer-point scratch) "scratch λ")
               (let* ((ids (recovery:checkpoint-now))
                      (file-id (lem:buffer-value file 'recovery::recovery-id))
                      (scratch-id (lem:buffer-value scratch 'recovery::recovery-id)))
                 (ok (and (member file-id ids :test #'equal) (member scratch-id ids :test #'equal)))
                 (ok (equal "original" (uiop:read-file-string path)))
                 (write-text path "external change")
                 (multiple-value-bind (buffer status) (recovery:restore-checkpoint file-id)
                   (push buffer restored)
                   (ok (eq status :conflict) "external disk changes are surfaced")
                   (ok (equal "original unsaved" (lem:buffer-text buffer)))
                   (ok (null (lem:buffer-filename buffer)) "recovery cannot silently overwrite original")
                   (ok (lem:buffer-modified-p buffer))
                   (ok (equal (namestring path) (getf (recovery:buffer-recovery-origin buffer) :filename))))
                 (multiple-value-bind (buffer status) (recovery:restore-checkpoint scratch-id)
                   (push buffer restored)
                   (ok (eq status :scratch))
                   (ok (equal "scratch λ" (lem:buffer-text buffer))))
                 (ok (equal "original unsaved" (lem:buffer-text file)) "the live file buffer stays intact")
                 (ok (equal "external change" (uiop:read-file-string path)))
                 (ok (store:read-record directory file-id) "restore retains its source checkpoint")))
          (recovery:disable)
          (dolist (buffer (append restored (list file scratch)))
            (when buffer (lem:delete-buffer buffer))))))))

(deftest save-after-background-checkpoint
  (with-test-frame ()
    (with-recovery-directory (directory)
      (store::ensure-private-directory directory)
      (let* ((path (merge-pathnames "save.txt" directory)) (buffer nil))
        (unwind-protect
             (progn
               (write-text path "base")
               (recovery:enable :directory directory)
               (setf buffer (lem:find-file-buffer path))
               (lem:insert-string (lem:buffer-end-point buffer) " edit")
               (recovery::checkpoint-periodically)
               (lem:write-to-file buffer path)
               (ok (null (store:list-records directory)) "save waits for old writer, then removes its checkpoint")
               (ok (equal "base edit" (uiop:read-file-string path))))
          (when buffer (lem:delete-buffer buffer)))))))

(deftest recovery-copies-are-independent-and-empty-text-survives
  (with-test-frame ()
    (with-recovery-directory (directory)
      (let* ((id (store:new-id)) (buffers nil))
        (store:write-record directory (record id ""))
        (recovery:enable :directory directory)
        (unwind-protect
             (progn
               (dotimes (i 2)
                 (declare (ignore i))
                 (push (recovery:restore-checkpoint id) buffers))
               (ok (every #'lem:buffer-modified-p buffers) "empty restored text remains unsaved")
               (ok (every (lambda (buffer) (equal "" (lem:buffer-text buffer))) buffers))
               (lem:insert-string (lem:buffer-point (first buffers)) "first copy")
               (lem:insert-string (lem:buffer-point (second buffers)) "second copy")
               (recovery:checkpoint-now)
               (let ((records (store:list-records directory)))
                 (ok (find "first copy" records :key (lambda (r) (store:field r "text")) :test #'equal))
                 (ok (find "second copy" records :key (lambda (r) (store:field r "text")) :test #'equal))
                 (ok (equal "" (store:field (store:read-record directory id) "text"))
                     "editing copies leaves the original checkpoint available")))
          (dolist (buffer buffers) (lem:delete-buffer buffer)))))))

(deftest checkpoint-failure-does-not-block-other-buffers
  (with-test-frame ()
    (with-recovery-directory (directory)
      (recovery:enable :directory directory)
      (let ((oversized (lem:make-buffer "oversized recovery input"))
            (ordinary (lem:make-buffer "ordinary recovery input")))
        (unwind-protect
             (progn
               (lem:insert-string (lem:buffer-point oversized)
                                  (make-string (1+ store:+maximum-text-length+) :initial-element #\x))
               (lem:insert-string (lem:buffer-point ordinary) "keep this")
               (recovery::checkpoint-periodically)
               (recovery::finish-writer :wait t)
               (ok recovery:*last-error* "unsupported size is reported")
               (ok (find "keep this" (store:list-records directory)
                         :key (lambda (r) (store:field r "text")) :test #'equal)
                   "another buffer still reaches durable storage")
               (ok (numberp (gethash (lem:buffer-value ordinary 'recovery::recovery-id)
                                    recovery::*written-ticks*))
                   "successful snapshots advance even when another buffer fails"))
          (lem:delete-buffer oversized)
          (lem:delete-buffer ordinary))))))

(deftest bounded-json-and-disk-baselines
  (with-recovery-directory (directory)
    (let* ((id (store:new-id)) (path (store:write-record directory (record id))))
      (write-text path (format nil "{\"version\":~a}" (make-string 1000 :initial-element #\9)))
      (ok (signals (store:read-record directory id)) "numeric parser work is bounded")
      (store:write-record directory (record id))
      (with-open-file (stream path :direction :output :if-exists :append)
        (write-string "{}" stream))
      (ok (signals (store:read-record directory id)) "trailing JSON is rejected"))
    (let ((path (merge-pathnames "same-size.txt" directory)))
      (write-text path "before")
      (let ((baseline (store:file-baseline path))
            (mtime (sb-posix:stat-mtime (sb-posix:stat (namestring path)))))
        (write-text path "after!")
        (sb-posix:utime (namestring path) mtime mtime)
        (ok (not (equal baseline (store:file-baseline path)))
            "same size and timestamp cannot conceal a content change")))))

(deftest shared-writable-ancestor-is-rejected
  (with-recovery-directory (directory)
    (ensure-directories-exist directory)
    (sb-posix:chmod (namestring directory) #o777)
    (ok (signals (store:write-record (merge-pathnames "nested/" directory)
                                     (record (store:new-id))))
        "another user's ability to replace a parent prevents snapshot publication")
    (ok (not (probe-file (merge-pathnames "nested/" directory))))))
