(defpackage :lem-daemon/tests/recovery
  (:use :cl :rove)
  (:local-nicknames (:recovery :lem-daemon/recovery)
                    (:store :lem-daemon/recovery-store)))
(in-package :lem-daemon/tests/recovery)

(defclass recovery-test-timer-manager (lem/common/timer:timer-manager) ())
(defmethod lem/common/timer:send-timer-notification ((manager recovery-test-timer-manager) function)
  (declare (ignore manager function)))

(defmacro with-test-frame (() &body body)
  `(let ((lem/common/timer::*timer-manager* (make-instance 'recovery-test-timer-manager)))
     (lem:with-implementation (make-instance 'lem-daemon:daemon-implementation)
       (lem:setup-first-frame)
       ,@body)))

(defmacro with-recovery-directory ((directory) &body body)
  `(let ((,directory (merge-pathnames (format nil "lem-recovery-~a/" (store:new-id))
                                     (uiop:temporary-directory))))
     (unwind-protect (progn ,@body)
       (recovery:disable)
       (when (probe-file ,directory)
         (uiop:delete-directory-tree ,directory :validate t)))))

(defun record (id &optional (text "unsaved λ 界"))
  (store:object "version" 1 "id" id "name" "scratch" "filename" nil
                "baseline" "unknown" "created" (get-universal-time)
                "point" 0 "text" text))

(defun write-text (path text)
  (with-open-file (stream path :direction :output :if-exists :supersede
                               :external-format :utf-8)
    (write-string text stream)))

(deftest private-atomic-records
  (with-recovery-directory (directory)
    (let* ((id (store:new-id)) (path (store:write-record directory (record id))))
      (ok (equal "unsaved λ 界" (store:field (store:read-record directory id) "text")))
      (ok (= #o600 (logand #o777 (sb-posix:stat-mode (sb-posix:stat (namestring path))))))
      (ok (= #o700 (logand #o777 (sb-posix:stat-mode (sb-posix:stat (namestring directory))))))
      (store:write-record directory (record id "newer"))
      (ok (equal "newer" (store:field (store:read-record directory id) "text"))))
    (ok (signals (store:write-record directory (record "../../wrong")))))
  (with-recovery-directory (directory)
    (ensure-directories-exist directory)
    (sb-posix:chmod (namestring directory) #o755)
    (ok (signals (store:write-record directory (record (store:new-id)))))))

(deftest malformed-and-symlink-records
  (with-recovery-directory (directory)
    (let* ((id (store:new-id)) (path (store:write-record directory (record id))))
      (write-text path "{\"version\":1,\"text\":\"#.(error :read-eval)\"}")
      (ok (signals (store:read-record directory id)) "schema rejects a malformed record")
      (multiple-value-bind (records failures) (store:list-records directory)
        (ok (null records)) (ok (= 1 (length failures))))
      (delete-file path)
      (sb-posix:symlink "/etc/passwd" (namestring path))
      (ok (signals (store:read-record directory id)) "record symlinks are rejected")
      (ok (signals (store:write-record directory (record id))) "replace rejects a symlink target")
      (ok (signals (store:discard-record directory id)))
      (delete-file path)
      (write-text path "{\"a\":[[[[[]]]]]}")
      (sb-posix:chmod (namestring path) #o600)
      (ok (signals (store:read-record directory id)) "excessive JSON nesting is rejected"))))

(deftest bounded-private-json-for-other-schemas
  (with-recovery-directory (directory)
    (let* ((id (store:new-id))
           (value (loop with value = "leaf" repeat 24 do (setf value (vector value)) finally (return value))))
      (ok (signals (store:write-private-json directory id value)) "default nesting bound applies before publication")
      (ok (not (probe-file directory)) "invalid values do not create storage")
      (store:write-private-json directory id value :maximum-depth 24)
      (ok (signals (store:read-private-json directory id)) "reader independently enforces its bound")
      (ok (store:read-private-json directory id :maximum-depth 24))
      (multiple-value-bind (records failures) (store:list-private-json directory :maximum-depth 24)
        (ok (equal id (caar records))) (ok (null failures)))
      (multiple-value-bind (records failures) (store:list-private-json directory)
        (ok (null records)) (ok (= 1 (length failures))))
      (let ((cycle (list 1)))
        (setf (cdr cycle) cycle)
        (ok (signals (store:write-private-json directory id cycle)) "circular lists are not object graphs to serialize"))
      (ok (signals (store:write-private-json directory id (store:object "self" (make-pathname :name "not-json")))))
      (ok (signals (store:write-private-json directory id (expt 10 65))) "large numeric atoms are bounded before parsing")
      (ok (signals (store:write-private-json directory id sb-ext:double-float-positive-infinity)))
      (store:write-private-json directory id (store:object "nested" (vector "safe")))
      (ok (equal "safe" (elt (store:field (store:read-private-json directory id) "nested") 0))))))

(deftest private-json-preserves-literal-types
  (with-recovery-directory (directory)
    (let* ((id (store:new-id))
           (original (store:object "false" yason:false "true" yason:true "null" nil
                                   "empty" #() "nested" (vector #() nil yason:false yason:true)))
           (path (store:write-private-json directory id original))
           (fingerprint (store:file-baseline path)))
      ;; A caller's parser preferences cannot change the journal's values.
      (let ((yason:*parse-json-booleans-as-symbols* nil)
            (yason:*parse-json-arrays-as-vectors* nil)
            (yason:*parse-json-null-as-keyword* t))
        (ok (equalp original (store:read-private-json directory id))
            "false, true, null and empty arrays survive a durable JSON round trip distinctly")
        (multiple-value-bind (inspected sha diagnostic) (store:inspect-private-json directory id)
          (ok (equalp original inspected))
          (ok (equal fingerprint sha))
          (ok (null diagnostic)))))))

(deftest inspecting-missing-records-does-not-create-storage
  (with-recovery-directory (directory)
    (ok (signals (store:read-private-json directory (store:new-id))))
    (ok (not (probe-file directory)) "direct inspection never creates an absent namespace")
    (multiple-value-bind (records failures) (store:list-private-json directory)
      (ok (null records)) (ok (null failures)))
    (ok (not (probe-file directory)) "listing an absent namespace is read-only")
    (ok (zerop (store:map-private-json directory (lambda (&rest ignored) (declare (ignore ignored))
                                                 (error "Missing directory cannot invoke a callback")))))
    (ok (signals (store:discard-record directory (store:new-id))))
    (ok (not (probe-file directory)) "cleanup cannot recreate a missing journal namespace")
    (store:ensure-private-directory directory)
    (let ((missing (merge-pathnames "missing/nested/" directory)))
      (ok (signals (store:read-record missing (store:new-id))))
      (ok (not (probe-file (merge-pathnames "missing/" directory)))
          "failed text export does not create parent directories"))))

(deftest streaming-private-json-name-inventory
  (with-recovery-directory (directory)
    (store:ensure-private-directory directory)
    (let ((id (store:new-id)) (names nil)
          (literal "not[*]?;a.json") (reads 0) (original (symbol-function 'store:read-private-json)))
      (store:write-private-json directory id (store:object "payload" "not read by the inventory"))
      (dolist (name (list literal ".json" "ignored.tmp" ".manager.lock"))
        (write-text (sb-ext:parse-native-namestring (concatenate 'string (uiop:native-namestring directory) name)) "malformed"))
      (let ((link-id (store:new-id)))
        (sb-posix:symlink "/does/not/exist" (uiop:native-namestring (store::record-path directory link-id)))
        (unwind-protect
             (progn
               (setf (symbol-function 'store:read-private-json)
                     (lambda (&rest ignored) (declare (ignore ignored)) (incf reads) (error "Unexpected payload read")))
               (ok (= 4 (store:map-private-json
                         directory (lambda (stem path)
                                     (push stem names)
                                     (when (equal stem "not[*]?;a")
                                       (ok (equal (concatenate 'string (uiop:native-namestring directory) literal)
                                                  (uiop:native-namestring path)))
                                       (ok (not (wild-pathname-p path)))
                                       (ok (equal "malformed" (uiop:read-file-string path))))))))
               (ok (zerop reads))
               (ok (and (member id names :test #'equal) (member link-id names :test #'equal)
                        (member "" names :test #'equal)))
               (ok (= 4 (length names)) "malformed and symlink JSON entries count without materializing their records"))
          (setf (symbol-function 'store:read-private-json) original))))))

(deftest streaming-private-json-closes-after-callback-error
  (with-recovery-directory (directory)
    (store:write-private-json directory (store:new-id) (store:object))
    (flet ((descriptor-count () (length (uiop:directory-files #P"/proc/self/fd/"))))
      (let ((before (descriptor-count)))
        (dotimes (i 8)
          (ok (signals (store:map-private-json directory
                                               (lambda (id path) (declare (ignore id path))
                                                 (error "Injected callback failure"))))))
        (ok (= before (descriptor-count)) "a failing consumer cannot retain a directory descriptor")))))

(deftest exact-private-json-inspection
  (with-recovery-directory (directory)
    (let* ((id (store:new-id)) (path (store:write-private-json directory id (store:object "safe" 1))))
      (multiple-value-bind (value fingerprint diagnostic) (store:inspect-private-json directory id)
        (ok (= 1 (store:field value "safe")))
        (ok (equal fingerprint (store:file-baseline path)))
        (ok (null diagnostic)))
      (dolist (text (list "{private-untrusted-secret" "{} trailing" "[[[[]]]]"))
        (write-text path text)
        (multiple-value-bind (value fingerprint diagnostic)
            (store:inspect-private-json directory id :maximum-depth 2)
          (ok (null value)) (ok (equal fingerprint (store:file-baseline path)))
          (ok (stringp diagnostic))
          (ok (not (search "private-untrusted-secret" diagnostic)))))
      (with-open-file (out path :direction :output :if-exists :supersede :element-type '(unsigned-byte 8))
        (write-byte #xff out))
      (multiple-value-bind (value fingerprint diagnostic) (store:inspect-private-json directory id)
        (ok (null value)) (ok (equal fingerprint (store:file-baseline path))) (ok diagnostic))
      (sb-posix:truncate (uiop:native-namestring path) (1+ store:+maximum-record-bytes+))
      (ok (signals (store:inspect-private-json directory id)) "oversized payload has no cleanup fingerprint")
      (delete-file path)
      (sb-posix:symlink "/does/not/exist" (uiop:native-namestring path))
      (ok (signals (store:inspect-private-json directory id)) "symlink cannot receive a cleanup fingerprint")
      (delete-file path)
      (sb-posix:mkfifo (uiop:native-namestring path) #o600)
      (ok (signals (store:inspect-private-json directory id)) "FIFO rejected without blocking")
      (delete-file path)
      (ok (signals (store:inspect-private-json directory id))))))

(deftest recover-file-and-scratch-with-conflict
  (with-test-frame ()
    (with-recovery-directory (directory)
      (store::ensure-private-directory directory)
      (let* ((path (merge-pathnames "example.txt" directory))
             (scratch (lem:make-buffer "recovery scratch"))
             (file nil) (restored nil))
        (unwind-protect
             (progn
               (write-text path "original")
               (recovery:enable :directory directory)
               (setf file (lem:find-file-buffer path))
               (lem:insert-string (lem:buffer-end-point file) " unsaved")
               (lem:insert-string (lem:buffer-point scratch) "scratch λ")
               (let* ((ids (recovery:checkpoint-now))
                      (file-id (lem:buffer-value file 'recovery::recovery-id))
                      (scratch-id (lem:buffer-value scratch 'recovery::recovery-id)))
                 (ok (and (member file-id ids :test #'equal) (member scratch-id ids :test #'equal)))
                 (ok (equal "original" (uiop:read-file-string path)))
                 (write-text path "external change")
                 (multiple-value-bind (buffer status) (recovery:restore-checkpoint file-id)
                   (push buffer restored)
                   (ok (eq status :conflict) "external disk changes are surfaced")
                   (ok (equal "original unsaved" (lem:buffer-text buffer)))
                   (ok (null (lem:buffer-filename buffer)) "recovery cannot silently overwrite original")
                   (ok (lem:buffer-modified-p buffer))
                   (ok (equal (namestring path) (getf (recovery:buffer-recovery-origin buffer) :filename))))
                 (multiple-value-bind (buffer status) (recovery:restore-checkpoint scratch-id)
                   (push buffer restored)
                   (ok (eq status :scratch))
                   (ok (equal "scratch λ" (lem:buffer-text buffer))))
                 (ok (equal "original unsaved" (lem:buffer-text file)) "the live file buffer stays intact")
                 (ok (equal "external change" (uiop:read-file-string path)))
                 (ok (store:read-record directory file-id) "restore retains its source checkpoint")))
          (recovery:disable)
          (dolist (buffer (append restored (list file scratch)))
            (when buffer (lem:delete-buffer buffer))))))))

(deftest save-after-background-checkpoint
  (with-test-frame ()
    (with-recovery-directory (directory)
      (store::ensure-private-directory directory)
      (let* ((path (merge-pathnames "save.txt" directory)) (buffer nil))
        (unwind-protect
             (progn
               (write-text path "base")
               (recovery:enable :directory directory)
               (setf buffer (lem:find-file-buffer path))
               (lem:insert-string (lem:buffer-end-point buffer) " edit")
               (recovery::checkpoint-periodically)
               (lem:write-to-file buffer path)
               (ok (null (store:list-records directory)) "save waits for old writer, then removes its checkpoint")
               (ok (equal "base edit" (uiop:read-file-string path))))
          (when buffer (lem:delete-buffer buffer)))))))

(deftest recovery-copies-are-independent-and-empty-text-survives
  (with-test-frame ()
    (with-recovery-directory (directory)
      (let* ((id (store:new-id)) (buffers nil))
        (store:write-record directory (record id ""))
        (recovery:enable :directory directory)
        (unwind-protect
             (progn
               (dotimes (i 2)
                 (declare (ignore i))
                 (push (recovery:restore-checkpoint id) buffers))
               (ok (every #'lem:buffer-modified-p buffers) "empty restored text remains unsaved")
               (ok (every (lambda (buffer) (equal "" (lem:buffer-text buffer))) buffers))
               (lem:insert-string (lem:buffer-point (first buffers)) "first copy")
               (lem:insert-string (lem:buffer-point (second buffers)) "second copy")
               (recovery:checkpoint-now)
               (let ((records (store:list-records directory)))
                 (ok (find "first copy" records :key (lambda (r) (store:field r "text")) :test #'equal))
                 (ok (find "second copy" records :key (lambda (r) (store:field r "text")) :test #'equal))
                 (ok (equal "" (store:field (store:read-record directory id) "text"))
                     "editing copies leaves the original checkpoint available")))
          (dolist (buffer buffers) (lem:delete-buffer buffer)))))))

(deftest checkpoint-failure-does-not-block-other-buffers
  (with-test-frame ()
    (with-recovery-directory (directory)
      (recovery:enable :directory directory)
      (let ((oversized (lem:make-buffer "oversized recovery input"))
            (ordinary (lem:make-buffer "ordinary recovery input")))
        (unwind-protect
             (progn
               (lem:insert-string (lem:buffer-point oversized)
                                  (make-string (1+ store:+maximum-text-length+) :initial-element #\x))
               (lem:insert-string (lem:buffer-point ordinary) "keep this")
               (recovery::checkpoint-periodically)
               (recovery::finish-writer :wait t)
               (ok recovery:*last-error* "unsupported size is reported")
               (ok (find "keep this" (store:list-records directory)
                         :key (lambda (r) (store:field r "text")) :test #'equal)
                   "another buffer still reaches durable storage")
               (ok (numberp (gethash (lem:buffer-value ordinary 'recovery::recovery-id)
                                    recovery::*written-ticks*))
                   "successful snapshots advance even when another buffer fails"))
          (lem:delete-buffer oversized)
          (lem:delete-buffer ordinary))))))

(deftest bounded-json-and-disk-baselines
  (with-recovery-directory (directory)
    (let* ((id (store:new-id)) (path (store:write-record directory (record id))))
      (write-text path (format nil "{\"version\":~a}" (make-string 1000 :initial-element #\9)))
      (ok (signals (store:read-record directory id)) "numeric parser work is bounded")
      (store:write-record directory (record id))
      (with-open-file (stream path :direction :output :if-exists :append)
        (write-string "{}" stream))
      (ok (signals (store:read-record directory id)) "trailing JSON is rejected"))
    (let ((path (merge-pathnames "same-size.txt" directory)))
      (write-text path "before")
      (let ((baseline (store:file-baseline path))
            (mtime (sb-posix:stat-mtime (sb-posix:stat (namestring path)))))
        (write-text path "after!")
        (sb-posix:utime (namestring path) mtime mtime)
        (ok (not (equal baseline (store:file-baseline path)))
            "same size and timestamp cannot conceal a content change")))))

(deftest shared-writable-ancestor-is-rejected
  (with-recovery-directory (directory)
    (ensure-directories-exist directory)
    (sb-posix:chmod (namestring directory) #o777)
    (ok (signals (store:write-record (merge-pathnames "nested/" directory)
                                     (record (store:new-id))))
        "another user's ability to replace a parent prevents snapshot publication")
    (ok (not (probe-file (merge-pathnames "nested/" directory))))))
